// autogenerated by GenomeCompiler.js on 4/26/2021, 5:40:02 PM
// Gene key abbreviations
const spfbdp = 'surface.primary.fuel.bed.dead.particle.class'
const spfblp = 'surface.primary.fuel.bed.live.particle.class'
const ssfbdp = 'surface.secondary.fuel.bed.dead.particle.class'
const ssfblp = 'surface.secondary.fuel.bed.live.particle.class'
const ccfbdp = 'crown.canopy.fuel.bed.dead.particle.class'
const ccfblp = 'crown.canopy.fuel.bed.live.particle.class'
const spfbd = 'surface.primary.fuel.bed.dead'
const spfbl = 'surface.primary.fuel.bed.live'
const spff = 'surface.primary.fuel.fire'
const ssfbd = 'surface.secondary.fuel.bed.dead'
const ssfbl = 'surface.secondary.fuel.bed.live'
const ssff = 'surface.secondary.fuel.fire'
const ccfbd = 'crown.canopy.fuel.bed.dead'
const ccfbl = 'crown.canopy.fuel.bed.live'
const ccff = 'crown.canopy.fuel.fire'
const spfb = 'surface.primary.fuel.bed'
const ssfb = 'surface.secondary.fuel.bed'
const ccfb = 'crown.canopy.fuel.bed'
const cfa = 'crown.fire.active'
const cff = 'crown.fire.final'
const cfi = 'crown.fire.initiation'
const spf = 'surface.primary.fuel'
const ssf = 'surface.secondary.fuel'
const mbd = 'model.behave.derived'
const mbp = 'model.behave.parms'
const mcd = 'model.chaparral.derived'
const mcp = 'model.chaparral.parms'
const mpd = 'model.palmettoGallberry.derived'
const mpp = 'model.palmettoGallberry.parms'
const mwd = 'model.westernAspen.derived'
const mwp = 'model.westernAspen.parms'
const sfe = 'surface.fire.ellipse'
const swf = 'surface.weighted.fire'
const spotb = 'spotting.burningPile'
const spotc = 'spotting.crownFire'
const spots = 'spotting.surfaceFire'
const spott = 'spotting.torchingTrees'
const savr = 'surfaceAreaToVolumeRatio'
const emc = 'effective.mineralContent'
const tmc = 'total.mineralContent'
const heat = 'heatOfCombustion'
const ef = 'effectiveFuel'
const sa = 'surfaceArea'
const sc = 'sizeClass'
const wf = 'weightingFactor'
const qig = 'heatOfPreignition'
const waf = 'windSpeedAdjustmentFactor'
const load = 'ovendryLoad'
const mois = 'moistureContent'
const fli = 'firelineIntensity'
const fl = 'flameLength'
const lwr = 'lengthToWidthRatio'
const ros = 'spreadRate'
const rxi = 'reactionIntensity'
const sh = 'scorchHeight'
const hpua = 'heatPerUnitArea'
const phiew = 'phiEffectiveWind'
const taur = 'flameResidenceTime'
const ews = 'effectiveWindSpeed'
const dens = 'fiberDensity'
const ehn = 'heatingNumber'

export const CompiledGenome = {
// Array of literals used by Gene updater config conditions and method parameters
literalArgsArray: [
8000, // 0
'lengthToWidthRatio', // 1
'flameLength', // 2
'firelineIntensity', // 3
'headingFromUpslope', // 4
'upslope', // 5
'sourceFromNorth', // 6
'effectiveWindSpeed', // 7
1, // 8
'category', // 9
'fosberg', // 10
'liveCategory', // 11
'degrees', // 12
'map', // 13
'humidity', // 14
'wetBulb', // 15
0, // 16
'at10m', // 17
'at20ft', // 18
'atMidflame', // 19
32, // 20
46, // 21
30, // 22
8300, // 23
640, // 24
350, // 25
0.01, // 26
0.015, // 27
0.0555, // 28
0.055, // 29
0.03, // 30
'dead', // 31
109, // 32
127, // 33
140, // 34
5, // 35
61, // 36
2000, // 37
27, // 38
10500, // 39
2800, // 40
'live', // 41
9550, // 42
2200, // 43
0.035, // 44
0.3, // 45
0.4, // 46
0.25, // 47
'input', // 48
'applied', // 49
'catalog', // 50
'behave', // 51
'chaparral', // 52
'palmettoGallberry', // 53
'westernAspen', // 54
'none', // 55
'estimated', // 56
'chamise', // 57
'aspenShrub', // 58
'expected', // 59
'harmonic', // 60
'linkedToSurfaceFire', // 61
'fromHead', // 62
'fromUpslope', // 63
'fromNorth', // 64
'linkedToCrownFire', // 65
'standAlone', // 66
0.138, // 67
0.092, // 68
0.23, // 69
1500, // 70
],
// Simple array of updater method <file>.<function> names
methodRefsArray: [
'Dag.module', // 0
'Dag.config', // 1
'Dag.input', // 2
'IgnitionProbability.firebrand', // 3
'IgnitionProbability.lightningStrike', // 4
'Canopy.crownFill', // 5
'Canopy.crownLength', // 6
'Canopy.crownRatio', // 7
'Canopy.heatPerUnitArea', // 8
'Dag.fixed', // 9
'Canopy.sheltersFuelFromWind', // 10
'Canopy.fuelLoad', // 11
'Canopy.windSpeedAdjustmentFactor', // 12
'Spotting.appliedDownWindCoverHeight', // 13
'TreeMortality.barkThickness', // 14
'SurfaceFire.effectiveWindSpeedFromLwr', // 15
'SurfaceFire.firelineIntensityFromFlameLength', // 16
'SurfaceFire.flameLength', // 17
'Compass.diff', // 18
'Compass.sum', // 19
'SurfaceFire.lengthToWidthRatio', // 20
'Calc.divide', // 21
'Calc.multiply', // 22
'Compass.slopeRatioMap', // 23
'Compass.slopeDegreesMap', // 24
'FuelMoisture.fosbergReference', // 25
'FuelMoisture.fosbergCorrection', // 26
'FuelMoisture.fosbergDead1h', // 27
'FuelMoisture.fosbergDead10h', // 28
'FuelMoisture.fosbergDead100h', // 29
'Dag.bind', // 30
'Compass.opposite', // 31
'Compass.slopeDegrees', // 32
'Compass.slopeRatio', // 33
'TemperatureHumidity.reaDewPoint', // 34
'TemperatureHumidity.dewPoint', // 35
'IgnitionProbability.fuelTemperature', // 36
'TemperatureHumidity.relativeHumidity', // 37
'TemperatureHumidity.wetBulbDepression', // 38
'Wind.speedAt10m', // 39
'Wind.speedAt20ft', // 40
'Wind.speedAt20ftFromMidflame', // 41
'Wind.speedAtMidflame', // 42
'FuelParticle.selectByDomain', // 43
'FuelParticle.effectiveHeatingNumber', // 44
'FuelParticle.effectiveFuelLoad', // 45
'FuelParticle.heatOfPreignition', // 46
'FuelParticle.netOvendryLoad', // 47
'FuelParticle.sizeClass', // 48
'FuelParticle.sizeClassWeightingFactor', // 49
'FuelParticle.surfaceArea', // 50
'FuelParticle.surfaceAreaWeightingFactor', // 51
'FuelParticle.volume', // 52
'FuelParticle.effectiveFuelWaterLoad', // 53
'Calc.sum', // 54
'FuelBed.mineralDamping', // 55
'FuelBed.moistureDamping', // 56
'Calc.sumOfProducts', // 57
'FuelBed.extinctionMoistureContentFactor', // 58
'FuelBed.reactionIntensityDry', // 59
'FuelBed.sizeClassWeightingFactorArray', // 60
'FuelBed.extinctionMoistureContent', // 61
'FuelBed.heatSink', // 62
'FuelBed.noWindNoSlopeSpreadRate', // 63
'FuelBed.openWindSpeedAdjustmentFactor', // 64
'FuelBed.packingRatio', // 65
'FuelBed.optimumPackingRatio', // 66
'FuelBed.propagatingFluxRatio', // 67
'FuelBed.reactionVelocityExponent', // 68
'FuelBed.reactionVelocityMaximum', // 69
'FuelBed.reactionVelocityOptimum', // 70
'FuelBed.savr15', // 71
'SurfaceFire.maximumDirectionSlopeSpreadRate', // 72
'SurfaceFire.maximumDirectionWindSpreadRate', // 73
'SurfaceFire.maximumDirectionXComponent', // 74
'SurfaceFire.maximumDirectionYComponent', // 75
'SurfaceFire.maximumDirectionSpreadRate', // 76
'Calc.greaterThan', // 77
'SurfaceFire.effectiveWindSpeedLimit', // 78
'SurfaceFire.phiEwFromEws', // 79
'SurfaceFire.maximumSpreadRate', // 80
'FuelBed.slopeK', // 81
'SurfaceFire.phiSlope', // 82
'SurfaceFire.effectiveWindSpeed', // 83
'SurfaceFire.phiEffectiveWind', // 84
'SurfaceFire.phiEffectiveWindInferred', // 85
'SurfaceFire.spreadRateWithCrossSlopeWind', // 86
'Math.min', // 87
'SurfaceFire.spreadRateWithRosLimitApplied', // 88
'FuelBed.windSpeedAdjustmentFactor', // 89
'FuelBed.windB', // 90
'FuelBed.windC', // 91
'FuelBed.windE', // 92
'FuelBed.windK', // 93
'FuelBed.windI', // 94
'SurfaceFire.phiWind', // 95
'SurfaceFire.firelineIntensity', // 96
'FuelBed.taur', // 97
'SurfaceFire.spreadDirectionFromUpslope', // 98
'FuelBed.heatPerUnitArea', // 99
'SurfaceFire.scorchHeight', // 100
'FuelCatalog.domain', // 101
'BehaveFuel.curedHerbFraction', // 102
'FuelCatalog.behaveDepth', // 103
'FuelCatalog.behaveDeadMext', // 104
'FuelCatalog.behaveTotalHerbLoad', // 105
'FuelCatalog.behaveDead1Load', // 106
'FuelCatalog.behaveDead10Load', // 107
'FuelCatalog.behaveDead100Load', // 108
'FuelCatalog.behaveLiveStemLoad', // 109
'FuelCatalog.behaveDead1Savr', // 110
'FuelCatalog.behaveLiveHerbSavr', // 111
'FuelCatalog.behaveLiveStemSavr', // 112
'FuelCatalog.behaveDeadHeat', // 113
'FuelCatalog.behaveLiveHeat', // 114
'BehaveFuel.deadHerbLoad', // 115
'BehaveFuel.liveHerbLoad', // 116
'FuelCatalog.chaparralFuelType', // 117
'FuelCatalog.chaparralDeadFraction', // 118
'FuelCatalog.chaparralDepth', // 119
'FuelCatalog.chaparralTotalLoad', // 120
'ChaparralFuel.age', // 121
'ChaparralFuel.deadFractionAverageMortality', // 122
'ChaparralFuel.deadFractionSevereMortality', // 123
'ChaparralFuel.fuelDepth', // 124
'ChaparralFuel.totalLoad', // 125
'ChaparralFuel.deadLoad', // 126
'ChaparralFuel.deadClass1Load', // 127
'ChaparralFuel.deadClass2Load', // 128
'ChaparralFuel.deadClass3Load', // 129
'ChaparralFuel.deadClass4Load', // 130
'ChaparralFuel.liveLoad', // 131
'ChaparralFuel.liveClass1Load', // 132
'ChaparralFuel.liveClass2Load', // 133
'ChaparralFuel.liveClass3Load', // 134
'ChaparralFuel.liveClass4Load', // 135
'ChaparralFuel.liveClass5Load', // 136
'FuelCatalog.palmettoGallberryAge', // 137
'FuelCatalog.palmettoGallberryBasalArea', // 138
'FuelCatalog.palmettoGallberryCover', // 139
'FuelCatalog.palmettoGallberryHeight', // 140
'PalmettoGallberryFuel.fuelDepth', // 141
'PalmettoGallberryFuel.deadFineLoad', // 142
'PalmettoGallberryFuel.deadSmallLoad', // 143
'PalmettoGallberryFuel.deadFoliageLoad', // 144
'PalmettoGallberryFuel.deadLitterLoad', // 145
'PalmettoGallberryFuel.liveFineLoad', // 146
'PalmettoGallberryFuel.liveSmallLoad', // 147
'PalmettoGallberryFuel.liveFoliageLoad', // 148
'FuelCatalog.westernAspenFuelType', // 149
'FuelCatalog.westernAspenCuringLevel', // 150
'WesternAspenFuel.depth', // 151
'WesternAspenFuel.deadFineLoad', // 152
'WesternAspenFuel.deadSmallLoad', // 153
'WesternAspenFuel.deadFineSavr', // 154
'WesternAspenFuel.liveHerbLoad', // 155
'WesternAspenFuel.liveStemLoad', // 156
'WesternAspenFuel.liveStemSavr', // 157
'Math.max', // 158
'Calc.or', // 159
'SurfaceFire.arithmeticMeanSpreadRate', // 160
'SurfaceFire.expectedValueSpreadRateMOCK', // 161
'SurfaceFire.harmonicMeanSpreadRate', // 162
'FireEllipse.eccentricity', // 163
'FireEllipse.majorSpreadRate', // 164
'FireEllipse.minorSpreadRate', // 165
'FireEllipse.fSpreadRate', // 166
'FireEllipse.gSpreadRate', // 167
'FireEllipse.hSpreadRate', // 168
'FireEllipse.area', // 169
'FireEllipse.spreadDistance', // 170
'FireEllipse.perimeter', // 171
'FireEllipse.mapArea', // 172
'FireEllipse.fliAtAzimuth', // 173
'FireEllipse.backingSpreadRate', // 174
'TreeMortality.mortalityRate', // 175
'FireEllipse.flankingSpreadRate', // 176
'FireEllipse.psiSpreadRate', // 177
'FireEllipse.betaSpreadRate', // 178
'FireEllipse.thetaFromBeta', // 179
'FireEllipse.psiFromTheta', // 180
'Spotting.criticalCoverHeight', // 181
'Spotting.burningPileFirebrandHeight', // 182
'Spotting.distanceFlatTerrain', // 183
'Spotting.distanceFlatTerrainWithDrift', // 184
'Spotting.distanceMountainTerrain', // 185
'CrownSpotting.zdrop', // 186
'CrownSpotting.xdrift', // 187
'CrownSpotting.xdrop', // 188
'CrownSpotting.xspot', // 189
'CrownSpotting.firelineIntensityThomas', // 190
'CrownSpotting.flatDistance', // 191
'Spotting.surfaceFireFirebrandHeight', // 192
'Spotting.surfaceFireFirebrandDrift', // 193
'Spotting.torchingTreesFirebrandHeight', // 194
'Spotting.torchingTreesSteadyFlameHeight', // 195
'Spotting.torchingTreesSteadyFlameDuration', // 196
'TreeMortality.crownLengthScorched', // 197
'TreeMortality.crownVolumeScorched', // 198
'CrownFire.area', // 199
'CrownFire.perimeter', // 200
'CrownFire.lengthToWidthRatio', // 201
'CrownFire.rActive', // 202
'CrownFire.fliActive', // 203
'CrownFire.flameLengthThomas', // 204
'CrownFire.hpuaActive', // 205
'CrownFire.powerOfTheFire', // 206
'CrownFire.powerOfTheWind', // 207
'CrownFire.isPlumeDominated', // 208
'CrownFire.isWindDriven', // 209
'CrownFire.rSa', // 210
'CrownFire.crownFractionBurned', // 211
'CrownFire.rFinal', // 212
'CrownFire.fliFinal', // 213
'CrownFire.fliInit', // 214
'CrownFire.rInit', // 215
'CrownFire.rPrimeActive', // 216
'CrownFire.transitionRatio', // 217
'CrownFire.canTransition', // 218
'CrownFire.activeRatio', // 219
'CrownFire.type', // 220
'CrownFire.isActive', // 221
'CrownFire.isCrown', // 222
'CrownFire.isPassive', // 223
'CrownFire.isConditional', // 224
'CrownFire.isSurface', // 225
'CrownFire.oActive', // 226
'CrownFire.crowningIndex', // 227
],
// Array of Genes where each Gene is:
// [<geneIdx>, <geneKey>, <variantIdx>, [<valueUpdaters>]], where each valueUpdater is:
// [[<configIdx>, <configValue>], [methodIdx, ...<methodArgs>]], and where each methodArg is:
// [<0|1>, <geneIdx|literalIdx>]
genesArray: [
[0,`module.surfaceFire`,0,[[[],[0]]]],
[1,`module.surfaceSpot`,0,[[[],[0]]]],
[2,`module.crownFire`,0,[[[],[0]]]],
[3,`module.crownSpot`,0,[[[],[0]]]],
[4,`module.fireEllipse`,0,[[[],[0]]]],
[5,`module.fireContain`,0,[[[],[0]]]],
[6,`module.${sh}`,0,[[[],[0]]]],
[7,`module.treeMortality`,0,[[[],[0]]]],
[8,`module.spotting`,0,[[[],[0]]]],
[9,`module.ignitionProbability`,0,[[[],[0]]]],
[10,`link.crownFire`,4,[[[],[1]]]],
[11,`link.crownSpot`,1,[[[],[1]]]],
[12,`link.fireContain`,2,[[[],[1]]]],
[13,`link.fireEllipse`,4,[[[],[1]]]],
[14,`link.${sh}`,4,[[[],[1]]]],
[15,`link.surfaceSpot`,4,[[[],[1]]]],
[16,`link.treeMortality`,3,[[[],[1]]]],
[17,`configure.fuel.primary`,7,[[[],[1]]]],
[18,`configure.fuel.secondary`,8,[[[],[1]]]],
[19,`configure.fuel.moisture`,9,[[[],[1]]]],
[20,`configure.fuel.${waf}`,10,[[[],[1]]]],
[21,`configure.fuel.curedHerbFraction`,6,[[[],[1]]]],
[22,`configure.fuel.chaparralTotalLoad`,5,[[[],[1]]]],
[23,`configure.slope.steepness`,11,[[[],[1]]]],
[24,`configure.temperature.humidity`,12,[[[],[1]]]],
[25,`configure.wind.direction`,13,[[[],[1]]]],
[26,`configure.wind.speed`,14,[[[],[1]]]],
[27,`configure.fire.${fli}`,15,[[[],[1]]]],
[28,`configure.fire.${lwr}`,16,[[[],[1]]]],
[29,`configure.fire.${ews}Limit`,17,[[[],[1]]]],
[30,`configure.fire.weightingMethod`,18,[[[],[1]]]],
[31,`configure.fire.vector`,19,[[[],[1]]]],
[32,`docs.run.mainTitle`,51,[[[],[2]]]],
[33,`docs.run.subTitle`,51,[[[],[2]]]],
[34,`docs.run.description`,51,[[[],[2]]]],
[35,`docs.run.userName`,51,[[[],[2]]]],
[36,`ignition.firebrand.probability`,103,[[[],[3,[0,125],[0,111]]]]],
[37,`ignition.lightningStrike.charge`,26,[[[],[2]]]],
[38,`ignition.lightningStrike.fuel.depth`,102,[[[],[2]]]],
[39,`ignition.lightningStrike.fuel.type`,25,[[[],[2]]]],
[40,`ignition.lightningStrike.probability`,103,[[[],[4,[0,39],[0,38],[0,113],[0,37]]]]],
[41,`site.canopy.cover`,78,[[[],[2]]]],
[42,`site.canopy.crown.baseHeight`,124,[[[],[2]]]],
[43,`site.canopy.crown.fill`,41,[[[],[5,[0,41],[0,45]]]]],
[44,`site.canopy.crown.length`,124,[[[],[6,[0,42],[0,46]]]]],
[45,`site.canopy.crown.ratio`,44,[[[],[7,[0,44],[0,46]]]]],
[46,`site.canopy.crown.totalHeight`,124,[[[],[2]]]],
[47,`site.canopy.fire.${hpua}`,60,[[[],[8,[0,52],[0,50]]]]],
[48,`site.canopy.fuel.bulkDensity`,74,[[[],[2]]]],
[49,`site.canopy.fuel.foliar.${mois}`,88,[[[],[2]]]],
[50,`site.canopy.fuel.${heat}`,84,[[[],[9,[1,0]]]]],
[51,`site.canopy.fuel.isSheltered`,36,[[[],[10,[0,41],[0,46],[0,43]]]]],
[52,`site.canopy.fuel.${load}`,91,[[[],[11,[0,48],[0,44]]]]],
[53,`site.canopy.fuel.shading`,78,[[[],[2]]]],
[54,`site.canopy.sheltered.${waf}`,127,[[[],[12,[0,41],[0,46],[0,43]]]]],
[55,`site.canopy.downwind.height`,124,[[[],[2]]]],
[56,`site.canopy.downwind.isOpen`,33,[[[],[2]]]],
[57,`site.canopy.downwind.appliedHeight`,124,[[[],[13,[0,55],[0,56]]]]],
[58,`site.canopy.tree.barkThickness`,121,[[[],[14,[0,60],[0,59]]]]],
[59,`site.canopy.tree.dbh`,123,[[[],[2]]]],
[60,`site.canopy.tree.species.fofem6.code`,30,[[[],[2]]]],
[61,`site.date.dayOfMonth`,46,[[[],[2]]]],
[62,`site.date.dayOfYear`,47,[[[],[2]]]],
[63,`site.date.julian`,48,[[[],[2]]]],
[64,`site.date.month`,49,[[[],[2]]]],
[65,`site.date.year`,50,[[[],[2]]]],
[66,`site.time.hour`,117,[[[],[2]]]],
[67,`site.time.minute`,118,[[[],[2]]]],
[68,`site.time.second`,119,[[[],[2]]]],
[69,`site.time.sunrise`,120,[[[],[2]]]],
[70,`site.time.sunset`,120,[[[],[2]]]],
[71,`site.doc.date`,51,[[[],[2]]]],
[72,`site.doc.id`,51,[[[],[2]]]],
[73,`site.doc.location`,51,[[[],[2]]]],
[74,`site.doc.station`,51,[[[],[2]]]],
[75,`site.doc.time`,51,[[[],[2]]]],
[76,`site.fire.observed.${ews}`,126,[[[28,1],[15,[0,82]]],[[],[2]]]],
[77,`site.fire.observed.${fli}`,57,[[[27,2],[16,[0,78]]],[[],[2]]]],
[78,`site.fire.observed.${fl}`,59,[[[27,3],[17,[0,77]]],[[],[2]]]],
[79,`site.fire.observed.heading.fromUpslope`,40,[[[25,4],[2]],[[25,5],[2]],[[],[18,[0,80],[0,119]]]]],
[80,`site.fire.observed.heading.fromNorth`,40,[[[25,6],[2]],[[],[19,[0,119],[0,79]]]]],
[81,`site.fire.observed.${hpua}`,60,[[[],[2]]]],
[82,`site.fire.observed.${lwr}`,61,[[[28,7],[20,[0,76]]],[[],[2]]]],
[83,`site.fire.observed.${ros}`,71,[[[],[2]]]],
[84,`site.fire.observed.${sh}`,68,[[[],[2]]]],
[85,`site.fire.crown.${fl}`,59,[[[],[2]]]],
[86,`site.fire.time.sinceIgnition`,56,[[[],[2]]]],
[87,`site.fire.vector.fromHead`,40,[[[],[2]]]],
[88,`site.fire.vector.fromNorth`,40,[[[],[2]]]],
[89,`site.fire.vector.fromUpslope`,40,[[[],[2]]]],
[90,`site.location.elevation`,52,[[[],[2]]]],
[91,`site.location.elevation.diff`,53,[[[],[2]]]],
[92,`site.location.gmtDiff`,101,[[[],[2]]]],
[93,`site.location.latitude.degrees`,104,[[[],[2]]]],
[94,`site.location.latitude.ns`,27,[[[],[2]]]],
[95,`site.location.longitude.degrees`,105,[[[],[2]]]],
[96,`site.location.longitude.ew`,22,[[[],[2]]]],
[97,`site.map.scale`,110,[[[],[2]]]],
[98,`site.map.contours`,107,[[[],[2]]]],
[99,`site.map.distance`,70,[[[],[2]]]],
[100,`site.map.factor`,109,[[[],[21,[1,8],[0,97]]]]],
[101,`site.map.interval`,70,[[[],[2]]]],
[102,`site.map.reach`,70,[[[],[22,[0,97],[0,99]]]]],
[103,`site.map.rise`,70,[[[],[22,[0,101],[0,98]]]]],
[104,`site.map.slope.ratio`,115,[[[],[23,[0,97],[0,101],[0,98],[0,99]]]]],
[105,`site.map.slope.degrees`,114,[[[],[24,[0,97],[0,101],[0,98],[0,99]]]]],
[106,`site.moisture.dead.fosberg.reference`,88,[[[],[25,[0,122],[0,126]]]]],
[107,`site.moisture.dead.fosberg.correction`,88,[[[],[26,[0,64],[0,127],[0,118],[0,121],[0,66],[0,91]]]]],
[108,`site.moisture.dead.fosberg.tl1h`,88,[[[],[27,[0,106],[0,107]]]]],
[109,`site.moisture.dead.fosberg.tl10h`,88,[[[],[28,[0,108]]]]],
[110,`site.moisture.dead.fosberg.tl100h`,88,[[[],[29,[0,108]]]]],
[111,`site.moisture.dead.tl1h`,88,[[[19,9],[30,[0,114]]],[[19,10],[30,[0,108]]],[[],[2]]]],
[112,`site.moisture.dead.tl10h`,88,[[[19,9],[30,[0,114]]],[[19,10],[30,[0,109]]],[[],[2]]]],
[113,`site.moisture.dead.tl100h`,88,[[[19,9],[30,[0,114]]],[[19,10],[30,[0,110]]],[[],[2]]]],
[114,`site.moisture.dead.category`,88,[[[],[2]]]],
[115,`site.moisture.live.herb`,88,[[[19,9],[30,[0,117]]],[[19,11],[30,[0,117]]],[[],[2]]]],
[116,`site.moisture.live.stem`,88,[[[19,9],[30,[0,117]]],[[19,11],[30,[0,117]]],[[],[2]]]],
[117,`site.moisture.live.category`,88,[[[],[2]]]],
[118,`site.slope.direction.aspect`,40,[[[],[2]]]],
[119,`site.slope.direction.upslope`,40,[[[],[31,[0,118]]]]],
[120,`site.slope.steepness.degrees`,114,[[[23,12],[2]],[[23,13],[30,[0,105]]],[[],[32,[0,121]]]]],
[121,`site.slope.steepness.ratio`,115,[[[23,12],[33,[0,120]]],[[23,13],[30,[0,104]]],[[],[2]]]],
[122,`site.temperature.air`,39,[[[],[2]]]],
[123,`site.temperature.dewPoint`,39,[[[24,14],[34,[0,124],[0,126]]],[[24,15],[35,[0,124],[0,128],[0,90]]],[[],[2]]]],
[124,`site.temperature.dryBulb`,39,[[[],[30,[0,122]]]]],
[125,`site.temperature.fuel`,39,[[[],[36,[0,122],[0,53]]]]],
[126,`site.temperature.relativeHumidity`,112,[[[24,14],[2]],[[],[37,[0,124],[0,123]]]]],
[127,`site.temperature.shading`,113,[[[],[2]]]],
[128,`site.temperature.wetBulb`,39,[[[],[2]]]],
[129,`site.temperature.wetBulbDepression`,39,[[[],[38,[0,124],[0,128]]]]],
[130,`site.wind.direction.heading.fromUpslope`,40,[[[25,4],[2]],[[25,6],[18,[0,133],[0,119]]],[[25,5],[9,[1,16]]],[[],[9,[1,16]]]]],
[131,`site.wind.direction.source.fromUpslope`,40,[[[],[31,[0,130]]]]],
[132,`site.wind.direction.source.fromNorth`,40,[[[25,4],[31,[0,133]]],[[25,6],[2]],[[25,5],[31,[0,119]]],[[],[31,[0,119]]]]],
[133,`site.wind.direction.heading.fromNorth`,40,[[[25,4],[19,[0,130],[0,119]]],[[25,6],[31,[0,132]]],[[25,5],[30,[0,119]]],[[],[30,[0,119]]]]],
[134,`site.wind.speed.at10m`,126,[[[26,17],[2]],[[],[39,[0,135]]]]],
[135,`site.wind.speed.at20ft`,126,[[[26,18],[2]],[[26,17],[40,[0,134]]],[[],[41,[0,136],[0,137]]]]],
[136,`site.wind.speed.atMidflame`,126,[[[26,19],[2]],[[],[42,[0,135],[0,137]]]]],
[137,`site.${waf}`,127,[[[],[2]]]],
[138,`${spfbdp}1.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,22],[1,20]]]]],
[139,`${spfbdp}1.${heat}`,84,[[[],[43,[0,409],[0,423],[1,0],[1,23],[1,0]]]]],
[140,`${spfbdp}1.${load}`,91,[[[],[43,[0,409],[0,416],[0,439],[0,455],[0,466]]]]],
[141,`${spfbdp}1.${mois}`,88,[[[],[43,[0,409],[0,111],[0,111],[0,111],[0,111]]]]],
[142,`${spfbdp}1.${savr}`,95,[[[],[43,[0,409],[0,420],[1,24],[1,25],[0,468]]]]],
[143,`${spfbdp}1.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,26],[1,26]]]]],
[144,`${spfbdp}1.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[145,`${spfbdp}1.${ef}.${ehn}`,82,[[[],[44,[0,142]]]]],
[146,`${spfbdp}1.${ef}.${load}`,91,[[[],[45,[0,142],[0,140],[1,31]]]]],
[147,`${spfbdp}1.${qig}`,85,[[[],[46,[0,141],[0,145]]]]],
[148,`${spfbdp}1.net.${load}`,91,[[[],[47,[0,140],[0,144]]]]],
[149,`${spfbdp}1.${sc}`,93,[[[],[48,[0,142]]]]],
[150,`${spfbdp}1.${sc}.${wf}`,125,[[[],[49,[0,149],[0,319]]]]],
[151,`${spfbdp}1.${sa}`,94,[[[],[50,[0,140],[0,142],[0,138]]]]],
[152,`${spfbdp}1.${sa}.${wf}`,125,[[[],[51,[0,151],[0,303]]]]],
[153,`${spfbdp}1.volume`,100,[[[],[52,[0,140],[0,138]]]]],
[154,`${spfbdp}1.${ef}.waterLoad`,91,[[[],[53,[0,146],[0,141]]]]],
[155,`${spfbdp}2.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,22],[1,20]]]]],
[156,`${spfbdp}2.${heat}`,84,[[[],[43,[0,409],[0,423],[1,0],[1,23],[1,0]]]]],
[157,`${spfbdp}2.${load}`,91,[[[],[43,[0,409],[0,417],[0,440],[0,456],[0,467]]]]],
[158,`${spfbdp}2.${mois}`,88,[[[],[43,[0,409],[0,112],[0,112],[0,112],[0,112]]]]],
[159,`${spfbdp}2.${savr}`,95,[[[],[43,[0,409],[1,32],[1,33],[1,34],[1,32]]]]],
[160,`${spfbdp}2.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,26],[1,26]]]]],
[161,`${spfbdp}2.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[162,`${spfbdp}2.${ef}.${ehn}`,82,[[[],[44,[0,159]]]]],
[163,`${spfbdp}2.${ef}.${load}`,91,[[[],[45,[0,159],[0,157],[1,31]]]]],
[164,`${spfbdp}2.${qig}`,85,[[[],[46,[0,158],[0,162]]]]],
[165,`${spfbdp}2.net.${load}`,91,[[[],[47,[0,157],[0,161]]]]],
[166,`${spfbdp}2.${sc}`,93,[[[],[48,[0,159]]]]],
[167,`${spfbdp}2.${sc}.${wf}`,125,[[[],[49,[0,166],[0,319]]]]],
[168,`${spfbdp}2.${sa}`,94,[[[],[50,[0,157],[0,159],[0,155]]]]],
[169,`${spfbdp}2.${sa}.${wf}`,125,[[[],[51,[0,168],[0,303]]]]],
[170,`${spfbdp}2.volume`,100,[[[],[52,[0,157],[0,155]]]]],
[171,`${spfbdp}2.${ef}.waterLoad`,91,[[[],[53,[0,163],[0,158]]]]],
[172,`${spfbdp}3.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,22],[1,20]]]]],
[173,`${spfbdp}3.${heat}`,84,[[[],[43,[0,409],[0,423],[1,0],[1,23],[1,0]]]]],
[174,`${spfbdp}3.${load}`,91,[[[],[43,[0,409],[0,418],[0,441],[0,457],[1,16]]]]],
[175,`${spfbdp}3.${mois}`,88,[[[],[43,[0,409],[0,113],[0,112],[0,111],[1,35]]]]],
[176,`${spfbdp}3.${savr}`,95,[[[],[43,[0,409],[1,22],[1,36],[1,37],[1,8]]]]],
[177,`${spfbdp}3.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,26],[1,26]]]]],
[178,`${spfbdp}3.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[179,`${spfbdp}3.${ef}.${ehn}`,82,[[[],[44,[0,176]]]]],
[180,`${spfbdp}3.${ef}.${load}`,91,[[[],[45,[0,176],[0,174],[1,31]]]]],
[181,`${spfbdp}3.${qig}`,85,[[[],[46,[0,175],[0,179]]]]],
[182,`${spfbdp}3.net.${load}`,91,[[[],[47,[0,174],[0,178]]]]],
[183,`${spfbdp}3.${sc}`,93,[[[],[48,[0,176]]]]],
[184,`${spfbdp}3.${sc}.${wf}`,125,[[[],[49,[0,183],[0,319]]]]],
[185,`${spfbdp}3.${sa}`,94,[[[],[50,[0,174],[0,176],[0,172]]]]],
[186,`${spfbdp}3.${sa}.${wf}`,125,[[[],[51,[0,185],[0,303]]]]],
[187,`${spfbdp}3.volume`,100,[[[],[52,[0,174],[0,172]]]]],
[188,`${spfbdp}3.${ef}.waterLoad`,91,[[[],[53,[0,180],[0,175]]]]],
[189,`${spfbdp}4.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,22],[1,20]]]]],
[190,`${spfbdp}4.${heat}`,84,[[[],[43,[0,409],[0,423],[1,0],[1,23],[1,0]]]]],
[191,`${spfbdp}4.${load}`,91,[[[],[43,[0,409],[0,425],[0,442],[0,458],[1,16]]]]],
[192,`${spfbdp}4.${mois}`,88,[[[],[43,[0,409],[0,111],[0,113],[0,113],[1,35]]]]],
[193,`${spfbdp}4.${savr}`,95,[[[],[43,[0,409],[0,421],[1,38],[1,37],[1,8]]]]],
[194,`${spfbdp}4.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,26],[1,26]]]]],
[195,`${spfbdp}4.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[196,`${spfbdp}4.${ef}.${ehn}`,82,[[[],[44,[0,193]]]]],
[197,`${spfbdp}4.${ef}.${load}`,91,[[[],[45,[0,193],[0,191],[1,31]]]]],
[198,`${spfbdp}4.${qig}`,85,[[[],[46,[0,192],[0,196]]]]],
[199,`${spfbdp}4.net.${load}`,91,[[[],[47,[0,191],[0,195]]]]],
[200,`${spfbdp}4.${sc}`,93,[[[],[48,[0,193]]]]],
[201,`${spfbdp}4.${sc}.${wf}`,125,[[[],[49,[0,200],[0,319]]]]],
[202,`${spfbdp}4.${sa}`,94,[[[],[50,[0,191],[0,193],[0,189]]]]],
[203,`${spfbdp}4.${sa}.${wf}`,125,[[[],[51,[0,202],[0,303]]]]],
[204,`${spfbdp}4.volume`,100,[[[],[52,[0,191],[0,189]]]]],
[205,`${spfbdp}4.${ef}.waterLoad`,91,[[[],[53,[0,197],[0,192]]]]],
[206,`${spfbdp}5.${dens}`,92,[[[],[9,[1,20]]]]],
[207,`${spfbdp}5.${heat}`,84,[[[],[9,[1,0]]]]],
[208,`${spfbdp}5.${load}`,91,[[[],[9,[1,16]]]]],
[209,`${spfbdp}5.${mois}`,88,[[[],[9,[1,35]]]]],
[210,`${spfbdp}5.${savr}`,95,[[[],[9,[1,8]]]]],
[211,`${spfbdp}5.${emc}`,83,[[[],[9,[1,26]]]]],
[212,`${spfbdp}5.${tmc}`,99,[[[],[9,[1,28]]]]],
[213,`${spfbdp}5.${ef}.${ehn}`,82,[[[],[44,[0,210]]]]],
[214,`${spfbdp}5.${ef}.${load}`,91,[[[],[45,[0,210],[0,208],[1,31]]]]],
[215,`${spfbdp}5.${qig}`,85,[[[],[46,[0,209],[0,213]]]]],
[216,`${spfbdp}5.net.${load}`,91,[[[],[47,[0,208],[0,212]]]]],
[217,`${spfbdp}5.${sc}`,93,[[[],[48,[0,210]]]]],
[218,`${spfbdp}5.${sc}.${wf}`,125,[[[],[49,[0,217],[0,319]]]]],
[219,`${spfbdp}5.${sa}`,94,[[[],[50,[0,208],[0,210],[0,206]]]]],
[220,`${spfbdp}5.${sa}.${wf}`,125,[[[],[51,[0,219],[0,303]]]]],
[221,`${spfbdp}5.volume`,100,[[[],[52,[0,208],[0,206]]]]],
[222,`${spfbdp}5.${ef}.waterLoad`,91,[[[],[53,[0,214],[0,209]]]]],
[223,`${spfblp}1.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,21],[1,20]]]]],
[224,`${spfblp}1.${heat}`,84,[[[],[43,[0,409],[0,424],[1,39],[1,23],[1,0]]]]],
[225,`${spfblp}1.${load}`,91,[[[],[43,[0,409],[0,426],[0,444],[0,459],[0,469]]]]],
[226,`${spfblp}1.${mois}`,88,[[[],[43,[0,409],[0,115],[0,116],[0,116],[0,115]]]]],
[227,`${spfblp}1.${savr}`,95,[[[],[43,[0,409],[0,421],[1,24],[1,25],[1,40]]]]],
[228,`${spfblp}1.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,27],[1,26]]]]],
[229,`${spfblp}1.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[230,`${spfblp}1.${ef}.${ehn}`,82,[[[],[44,[0,227]]]]],
[231,`${spfblp}1.${ef}.${load}`,91,[[[],[45,[0,227],[0,225],[1,41]]]]],
[232,`${spfblp}1.${qig}`,85,[[[],[46,[0,226],[0,230]]]]],
[233,`${spfblp}1.net.${load}`,91,[[[],[47,[0,225],[0,229]]]]],
[234,`${spfblp}1.${sc}`,93,[[[],[48,[0,227]]]]],
[235,`${spfblp}1.${sc}.${wf}`,125,[[[],[49,[0,234],[0,339]]]]],
[236,`${spfblp}1.${sa}`,94,[[[],[50,[0,225],[0,227],[0,223]]]]],
[237,`${spfblp}1.${sa}.${wf}`,125,[[[],[51,[0,236],[0,323]]]]],
[238,`${spfblp}1.volume`,100,[[[],[52,[0,225],[0,223]]]]],
[239,`${spfblp}2.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,21],[1,20]]]]],
[240,`${spfblp}2.${heat}`,84,[[[],[43,[0,409],[0,424],[1,42],[1,23],[1,0]]]]],
[241,`${spfblp}2.${load}`,91,[[[],[43,[0,409],[0,419],[0,445],[0,460],[0,470]]]]],
[242,`${spfblp}2.${mois}`,88,[[[],[43,[0,409],[0,116],[0,116],[0,116],[0,116]]]]],
[243,`${spfblp}2.${savr}`,95,[[[],[43,[0,409],[0,422],[1,33],[1,34],[0,471]]]]],
[244,`${spfblp}2.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,27],[1,26]]]]],
[245,`${spfblp}2.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[246,`${spfblp}2.${ef}.${ehn}`,82,[[[],[44,[0,243]]]]],
[247,`${spfblp}2.${ef}.${load}`,91,[[[],[45,[0,243],[0,241],[1,41]]]]],
[248,`${spfblp}2.${qig}`,85,[[[],[46,[0,242],[0,246]]]]],
[249,`${spfblp}2.net.${load}`,91,[[[],[47,[0,241],[0,245]]]]],
[250,`${spfblp}2.${sc}`,93,[[[],[48,[0,243]]]]],
[251,`${spfblp}2.${sc}.${wf}`,125,[[[],[49,[0,250],[0,339]]]]],
[252,`${spfblp}2.${sa}`,94,[[[],[50,[0,241],[0,243],[0,239]]]]],
[253,`${spfblp}2.${sa}.${wf}`,125,[[[],[51,[0,252],[0,323]]]]],
[254,`${spfblp}2.volume`,100,[[[],[52,[0,241],[0,239]]]]],
[255,`${spfblp}3.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,21],[1,20]]]]],
[256,`${spfblp}3.${heat}`,84,[[[],[43,[0,409],[0,424],[1,42],[1,23],[1,0]]]]],
[257,`${spfblp}3.${load}`,91,[[[],[43,[0,409],[1,16],[0,446],[0,461],[1,16]]]]],
[258,`${spfblp}3.${mois}`,88,[[[],[43,[0,409],[1,35],[0,116],[0,116],[1,35]]]]],
[259,`${spfblp}3.${savr}`,95,[[[],[43,[0,409],[1,8],[1,36],[1,37],[1,8]]]]],
[260,`${spfblp}3.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,27],[1,26]]]]],
[261,`${spfblp}3.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[262,`${spfblp}3.${ef}.${ehn}`,82,[[[],[44,[0,259]]]]],
[263,`${spfblp}3.${ef}.${load}`,91,[[[],[45,[0,259],[0,257],[1,41]]]]],
[264,`${spfblp}3.${qig}`,85,[[[],[46,[0,258],[0,262]]]]],
[265,`${spfblp}3.net.${load}`,91,[[[],[47,[0,257],[0,261]]]]],
[266,`${spfblp}3.${sc}`,93,[[[],[48,[0,259]]]]],
[267,`${spfblp}3.${sc}.${wf}`,125,[[[],[49,[0,266],[0,339]]]]],
[268,`${spfblp}3.${sa}`,94,[[[],[50,[0,257],[0,259],[0,255]]]]],
[269,`${spfblp}3.${sa}.${wf}`,125,[[[],[51,[0,268],[0,323]]]]],
[270,`${spfblp}3.volume`,100,[[[],[52,[0,257],[0,255]]]]],
[271,`${spfblp}4.${dens}`,92,[[[],[43,[0,409],[1,20],[1,21],[1,21],[1,20]]]]],
[272,`${spfblp}4.${heat}`,84,[[[],[43,[0,409],[0,424],[1,42],[1,23],[1,0]]]]],
[273,`${spfblp}4.${load}`,91,[[[],[43,[0,409],[1,16],[0,447],[1,16],[1,16]]]]],
[274,`${spfblp}4.${mois}`,88,[[[],[43,[0,409],[1,35],[0,116],[1,35],[1,35]]]]],
[275,`${spfblp}4.${savr}`,95,[[[],[43,[0,409],[1,8],[1,38],[1,8],[1,8]]]]],
[276,`${spfblp}4.${emc}`,83,[[[],[43,[0,409],[1,26],[1,27],[1,27],[1,26]]]]],
[277,`${spfblp}4.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[278,`${spfblp}4.${ef}.${ehn}`,82,[[[],[44,[0,275]]]]],
[279,`${spfblp}4.${ef}.${load}`,91,[[[],[45,[0,275],[0,273],[1,41]]]]],
[280,`${spfblp}4.${qig}`,85,[[[],[46,[0,274],[0,278]]]]],
[281,`${spfblp}4.net.${load}`,91,[[[],[47,[0,273],[0,277]]]]],
[282,`${spfblp}4.${sc}`,93,[[[],[48,[0,275]]]]],
[283,`${spfblp}4.${sc}.${wf}`,125,[[[],[49,[0,282],[0,339]]]]],
[284,`${spfblp}4.${sa}`,94,[[[],[50,[0,273],[0,275],[0,271]]]]],
[285,`${spfblp}4.${sa}.${wf}`,125,[[[],[51,[0,284],[0,323]]]]],
[286,`${spfblp}4.volume`,100,[[[],[52,[0,273],[0,271]]]]],
[287,`${spfblp}5.${dens}`,92,[[[],[43,[0,409],[1,20],[1,20],[1,21],[1,20]]]]],
[288,`${spfblp}5.${heat}`,84,[[[],[43,[0,409],[0,424],[1,39],[1,23],[1,0]]]]],
[289,`${spfblp}5.${load}`,91,[[[],[43,[0,409],[1,16],[0,448],[1,16],[1,16]]]]],
[290,`${spfblp}5.${mois}`,88,[[[],[43,[0,409],[1,35],[0,115],[1,35],[1,35]]]]],
[291,`${spfblp}5.${savr}`,95,[[[],[43,[0,409],[1,8],[1,43],[1,8],[1,8]]]]],
[292,`${spfblp}5.${emc}`,83,[[[],[43,[0,409],[1,26],[1,44],[1,27],[1,26]]]]],
[293,`${spfblp}5.${tmc}`,99,[[[],[43,[0,409],[1,28],[1,29],[1,30],[1,29]]]]],
[294,`${spfblp}5.${ef}.${ehn}`,82,[[[],[44,[0,291]]]]],
[295,`${spfblp}5.${ef}.${load}`,91,[[[],[45,[0,291],[0,289],[1,41]]]]],
[296,`${spfblp}5.${qig}`,85,[[[],[46,[0,290],[0,294]]]]],
[297,`${spfblp}5.net.${load}`,91,[[[],[47,[0,289],[0,293]]]]],
[298,`${spfblp}5.${sc}`,93,[[[],[48,[0,291]]]]],
[299,`${spfblp}5.${sc}.${wf}`,125,[[[],[49,[0,298],[0,339]]]]],
[300,`${spfblp}5.${sa}`,94,[[[],[50,[0,289],[0,291],[0,287]]]]],
[301,`${spfblp}5.${sa}.${wf}`,125,[[[],[51,[0,300],[0,323]]]]],
[302,`${spfblp}5.volume`,100,[[[],[52,[0,289],[0,287]]]]],
[303,`${spfbd}.${sa}`,94,[[[],[54,[0,151],[0,168],[0,185],[0,202],[0,219]]]]],
[304,`${spfbd}.${sa}.${wf}`,125,[[[],[21,[0,303],[0,358]]]]],
[305,`${spfbd}.mineralDamping`,55,[[[],[55,[0,318]]]]],
[306,`${spfbd}.moistureDamping`,55,[[[],[56,[0,312],[0,310]]]]],
[307,`${spfbd}.${heat}`,84,[[[],[57,[0,152],[0,169],[0,186],[0,203],[0,220],[0,139],[0,156],[0,173],[0,190],[0,207]]]]],
[308,`${spfbd}.${load}`,91,[[[],[54,[0,140],[0,157],[0,174],[0,191],[0,208]]]]],
[309,`${spfbd}.${ef}.${load}`,91,[[[],[54,[0,146],[0,163],[0,180],[0,197],[0,214]]]]],
[310,`${spfbd}.extinction.${mois}`,88,[[[],[43,[0,409],[0,414],[1,45],[1,46],[1,47]]]]],
[311,`${spfbd}.extinction.${mois}Factor`,37,[[[],[58,[0,309],[0,329]]]]],
[312,`${spfbd}.${mois}`,88,[[[],[57,[0,152],[0,169],[0,186],[0,203],[0,220],[0,141],[0,158],[0,175],[0,192],[0,209]]]]],
[313,`${spfbd}.volume`,75,[[[],[54,[0,153],[0,170],[0,187],[0,204],[0,221]]]]],
[314,`${spfbd}.${qig}`,85,[[[],[57,[0,152],[0,169],[0,186],[0,203],[0,220],[0,147],[0,164],[0,181],[0,198],[0,215]]]]],
[315,`${spfbd}.${rxi}`,65,[[[],[22,[0,316],[0,306]]]]],
[316,`${spfbd}.${rxi}Dry`,65,[[[],[59,[0,355],[0,320],[0,307],[0,305]]]]],
[317,`${spfbd}.${savr}`,95,[[[],[57,[0,152],[0,169],[0,186],[0,203],[0,220],[0,142],[0,159],[0,176],[0,193],[0,210]]]]],
[318,`${spfbd}.${emc}`,83,[[[],[57,[0,152],[0,169],[0,186],[0,203],[0,220],[0,143],[0,160],[0,177],[0,194],[0,211]]]]],
[319,`${spfbd}.${sc}.${wf}`,125,[[[],[60,[0,151],[0,149],[0,168],[0,166],[0,185],[0,183],[0,202],[0,200],[0,219],[0,217]]]]],
[320,`${spfbd}.net.${load}`,91,[[[],[57,[0,150],[0,167],[0,184],[0,201],[0,218],[0,148],[0,165],[0,182],[0,199],[0,216]]]]],
[321,`${spfbd}.${ef}.waterLoad`,91,[[[],[54,[0,154],[0,171],[0,188],[0,205],[0,222]]]]],
[322,`${spfbd}.${ef}.${mois}`,88,[[[],[21,[0,321],[0,309]]]]],
[323,`${spfbl}.${sa}`,94,[[[],[54,[0,236],[0,252],[0,268],[0,284],[0,300]]]]],
[324,`${spfbl}.${sa}.${wf}`,125,[[[],[21,[0,323],[0,358]]]]],
[325,`${spfbl}.mineralDamping`,55,[[[],[55,[0,338]]]]],
[326,`${spfbl}.moistureDamping`,55,[[[],[56,[0,332],[0,330]]]]],
[327,`${spfbl}.${heat}`,84,[[[],[57,[0,237],[0,253],[0,269],[0,285],[0,301],[0,224],[0,240],[0,256],[0,272],[0,288]]]]],
[328,`${spfbl}.${load}`,91,[[[],[54,[0,225],[0,241],[0,257],[0,273],[0,289]]]]],
[329,`${spfbl}.${ef}.${load}`,91,[[[],[54,[0,231],[0,247],[0,263],[0,279],[0,295]]]]],
[330,`${spfbl}.extinction.${mois}`,88,[[[],[61,[0,331],[0,322],[0,310]]]]],
[331,`${spfbl}.extinction.${mois}Factor`,37,[[[],[58,[0,309],[0,329]]]]],
[332,`${spfbl}.${mois}`,88,[[[],[57,[0,237],[0,253],[0,269],[0,285],[0,301],[0,226],[0,242],[0,258],[0,274],[0,290]]]]],
[333,`${spfbl}.volume`,75,[[[],[54,[0,238],[0,254],[0,270],[0,286],[0,302]]]]],
[334,`${spfbl}.${qig}`,85,[[[],[57,[0,237],[0,253],[0,269],[0,285],[0,301],[0,232],[0,248],[0,264],[0,280],[0,296]]]]],
[335,`${spfbl}.${rxi}`,65,[[[],[22,[0,336],[0,326]]]]],
[336,`${spfbl}.${rxi}Dry`,65,[[[],[59,[0,355],[0,340],[0,327],[0,325]]]]],
[337,`${spfbl}.${savr}`,95,[[[],[57,[0,237],[0,253],[0,269],[0,285],[0,301],[0,227],[0,243],[0,259],[0,275],[0,291]]]]],
[338,`${spfbl}.${emc}`,83,[[[],[57,[0,237],[0,253],[0,269],[0,285],[0,301],[0,228],[0,244],[0,260],[0,276],[0,292]]]]],
[339,`${spfbl}.${sc}.${wf}`,125,[[[],[60,[0,236],[0,234],[0,252],[0,250],[0,268],[0,266],[0,284],[0,282],[0,300],[0,298]]]]],
[340,`${spfbl}.net.${load}`,91,[[[],[57,[0,235],[0,251],[0,267],[0,283],[0,299],[0,233],[0,249],[0,265],[0,281],[0,297]]]]],
[341,`${spfb}.depth`,75,[[[],[43,[0,409],[0,413],[0,430],[0,454],[0,465]]]]],
[342,`${spfb}.bulkDensity`,74,[[[],[21,[0,346],[0,341]]]]],
[343,`${spfb}.${qig}`,76,[[[],[57,[0,304],[0,324],[0,314],[0,334]]]]],
[344,`${spfb}.heatSink`,86,[[[],[62,[0,343],[0,342]]]]],
[345,`${spfb}.noWindNoSlope.${ros}`,71,[[[],[63,[0,352],[0,351],[0,344]]]]],
[346,`${spfb}.${load}`,91,[[[],[54,[0,308],[0,328]]]]],
[347,`${spfb}.open.${waf}`,127,[[[],[64,[0,341]]]]],
[348,`${spfb}.packingRatio`,77,[[[],[65,[0,313],[0,333],[0,341]]]]],
[349,`${spfb}.packingRatio.optimum`,77,[[[],[66,[0,356]]]]],
[350,`${spfb}.packingRatio.ratio`,77,[[[],[21,[0,348],[0,349]]]]],
[351,`${spfb}.propagatingFluxRatio`,64,[[[],[67,[0,356],[0,348]]]]],
[352,`${spfb}.${rxi}`,65,[[[],[54,[0,315],[0,335]]]]],
[353,`${spfb}.reactionVelocityExponent`,37,[[[],[68,[0,356]]]]],
[354,`${spfb}.reactionVelocityMaximum`,66,[[[],[69,[0,357]]]]],
[355,`${spfb}.reactionVelocityOptimum`,66,[[[],[70,[0,350],[0,354],[0,353]]]]],
[356,`${spfb}.${savr}`,95,[[[],[57,[0,304],[0,324],[0,317],[0,337]]]]],
[357,`${spfb}.savr15`,37,[[[],[71,[0,356]]]]],
[358,`${spfb}.${sa}`,94,[[[],[54,[0,303],[0,323]]]]],
[359,`${spff}.maximumDirection.slope.${ros}`,71,[[[],[72,[0,408],[0,372]]]]],
[360,`${spff}.maximumDirection.wind.${ros}`,71,[[[],[73,[0,408],[0,395]]]]],
[361,`${spff}.wind.heading.fromUpslope`,40,[[[],[30,[0,130]]]]],
[362,`${spff}.maximumDirection.xComponent`,37,[[[],[74,[0,360],[0,359],[0,361]]]]],
[363,`${spff}.maximumDirection.yComponent`,37,[[[],[75,[0,360],[0,361]]]]],
[364,`${spff}.maximumDirection.${ros}`,71,[[[],[76,[0,362],[0,363]]]]],
[365,`${spff}.limit.${ews}.exceeded`,34,[[[],[77,[0,376],[0,367]]]]],
[366,`${spff}.limit.${ros}.exceeded`,35,[[[],[77,[0,378],[0,384]]]]],
[367,`${spff}.limit.${ews}`,126,[[[],[78,[0,405]]]]],
[368,`${spff}.limit.windSlopeSpreadRateCoefficient`,37,[[[],[79,[0,367],[0,390],[0,393]]]]],
[369,`${spff}.limit.${ros}`,71,[[[],[80,[0,408],[0,368]]]]],
[370,`${spff}.slope.ratio`,115,[[[],[30,[0,121]]]]],
[371,`${spff}.slope.k`,37,[[[],[81,[0,348]]]]],
[372,`${spff}.slope.phi`,37,[[[],[82,[0,370],[0,371]]]]],
[373,`${spff}.spread.step1.${ews}`,126,[[[],[83,[0,374],[0,390],[0,394]]]]],
[374,`${spff}.spread.step1.${phiew}`,37,[[[],[84,[0,395],[0,372]]]]],
[375,`${spff}.spread.step1.${ros}`,71,[[[],[80,[0,408],[0,374]]]]],
[376,`${spff}.spread.step2.${ews}`,126,[[[],[83,[0,377],[0,390],[0,394]]]]],
[377,`${spff}.spread.step2.${phiew}`,37,[[[],[85,[0,408],[0,378]]]]],
[378,`${spff}.spread.step2.${ros}`,71,[[[],[86,[0,408],[0,364]]]]],
[379,`${spff}.spread.step3a.${ews}`,126,[[[],[87,[0,376],[0,367]]]]],
[380,`${spff}.spread.step3a.${phiew}`,37,[[[],[87,[0,377],[0,368]]]]],
[381,`${spff}.spread.step3a.${ros}`,71,[[[],[87,[0,378],[0,369]]]]],
[382,`${spff}.spread.step3b.${ews}`,126,[[[],[83,[0,383],[0,390],[0,394]]]]],
[383,`${spff}.spread.step3b.${phiew}`,37,[[[],[85,[0,408],[0,384]]]]],
[384,`${spff}.spread.step3b.${ros}`,71,[[[],[88,[0,378],[0,376]]]]],
[385,`${spff}.spread.step4.${ews}`,126,[[[],[83,[0,386],[0,390],[0,394]]]]],
[386,`${spff}.spread.step4.${phiew}`,37,[[[],[85,[0,408],[0,387]]]]],
[387,`${spff}.spread.step4.${ros}`,71,[[[],[88,[0,381],[0,379]]]]],
[388,`${spff}.${waf}`,127,[[[20,48],[30,[0,137]]],[[],[89,[0,51],[0,54],[0,347]]]]],
[389,`${spff}.wind.speed.atMidflame`,126,[[[26,19],[30,[0,136]]],[[],[42,[0,135],[0,388]]]]],
[390,`${spff}.wind.factor.b`,37,[[[],[90,[0,356]]]]],
[391,`${spff}.wind.factor.c`,37,[[[],[91,[0,356]]]]],
[392,`${spff}.wind.factor.e`,37,[[[],[92,[0,356]]]]],
[393,`${spff}.wind.factor.k`,37,[[[],[93,[0,350],[0,392],[0,391]]]]],
[394,`${spff}.wind.factor.i`,37,[[[],[94,[0,350],[0,392],[0,391]]]]],
[395,`${spff}.wind.phi`,37,[[[],[95,[0,389],[0,390],[0,393]]]]],
[396,`${spff}.${ews}`,126,[[[29,49],[30,[0,385]]],[[],[30,[0,382]]]]],
[397,`${spff}.${fli}`,57,[[[],[96,[0,407],[0,405],[0,399]]]]],
[398,`${spff}.${fl}`,59,[[[],[17,[0,397]]]]],
[399,`${spff}.${taur}`,67,[[[],[97,[0,356]]]]],
[400,`${spff}.heading.fromUpslope`,40,[[[],[98,[0,362],[0,363],[0,364]]]]],
[401,`${spff}.heading.fromNorth`,40,[[[],[19,[0,119],[0,400]]]]],
[402,`${spff}.${hpua}`,60,[[[],[99,[0,405],[0,399]]]]],
[403,`${spff}.${lwr}`,61,[[[],[20,[0,396]]]]],
[404,`${spff}.${phiew}`,37,[[[29,49],[30,[0,386]]],[[],[30,[0,383]]]]],
[405,`${spff}.${rxi}`,65,[[[],[30,[0,352]]]]],
[406,`${spff}.${sh}`,68,[[[],[100,[0,397],[0,389],[0,122]]]]],
[407,`${spff}.${ros}`,71,[[[29,49],[30,[0,387]]],[[],[30,[0,384]]]]],
[408,`${spff}.noWindNoSlope.${ros}`,71,[[[],[30,[0,345]]]]],
[409,`${spf}.model.domain`,23,[[[17,50],[101,[0,410]]],[[17,51],[9,[1,51]]],[[17,52],[9,[1,52]]],[[17,53],[9,[1,53]]],[[17,54],[9,[1,54]]],[[],[9,[1,55]]]]],
[410,`${spf}.model.catalogKey`,24,[[[],[2]]]],
[411,`${spf}.model.behave.domain`,23,[[[],[9,[1,51]]]]],
[412,`${spf}.${mbp}.cured.herb.fraction`,81,[[[21,56],[102,[0,115]]],[[],[2]]]],
[413,`${spf}.${mbp}.depth`,75,[[[17,50],[103,[0,410]]],[[17,51],[2]],[[],[9,[1,26]]]]],
[414,`${spf}.${mbp}.dead.extinction.${mois}`,88,[[[17,50],[104,[0,410]]],[[17,51],[2]],[[],[9,[1,47]]]]],
[415,`${spf}.${mbp}.total.herb.${load}`,91,[[[17,50],[105,[0,410]]],[[17,51],[2]],[[],[9,[1,16]]]]],
[416,`${spf}.${mbp}.dead.tl1h.${load}`,91,[[[17,50],[106,[0,410]]],[[17,51],[2]],[[],[9,[1,16]]]]],
[417,`${spf}.${mbp}.dead.tl10h.${load}`,91,[[[17,50],[107,[0,410]]],[[17,51],[2]],[[],[9,[1,16]]]]],
[418,`${spf}.${mbp}.dead.tl100h.${load}`,91,[[[17,50],[108,[0,410]]],[[17,51],[2]],[[],[9,[1,16]]]]],
[419,`${spf}.${mbp}.live.stem.${load}`,91,[[[17,50],[109,[0,410]]],[[17,51],[2]],[[],[9,[1,16]]]]],
[420,`${spf}.${mbp}.dead.tl1h.${savr}`,95,[[[17,50],[110,[0,410]]],[[17,51],[2]],[[],[9,[1,16]]]]],
[421,`${spf}.${mbp}.live.herb.${savr}`,95,[[[17,50],[111,[0,410]]],[[17,51],[2]],[[],[9,[1,8]]]]],
[422,`${spf}.${mbp}.live.stem.${savr}`,95,[[[17,50],[112,[0,410]]],[[17,51],[2]],[[],[9,[1,8]]]]],
[423,`${spf}.${mbp}.dead.${heat}`,84,[[[17,50],[113,[0,410]]],[[17,51],[2]],[[],[9,[1,0]]]]],
[424,`${spf}.${mbp}.live.${heat}`,84,[[[17,50],[114,[0,410]]],[[17,51],[2]],[[],[9,[1,0]]]]],
[425,`${spf}.${mbd}.dead.herb.${load}`,91,[[[],[115,[0,415],[0,412]]]]],
[426,`${spf}.${mbd}.live.herb.${load}`,91,[[[],[116,[0,415],[0,412]]]]],
[427,`${spf}.model.chaparral.domain`,23,[[[],[9,[1,52]]]]],
[428,`${spf}.${mcp}.chaparralType`,20,[[[17,50],[117,[0,410]]],[[17,52],[2]],[[],[9,[1,57]]]]],
[429,`${spf}.${mcp}.observed.deadFuelFraction`,81,[[[17,50],[118,[0,410]]],[[17,52],[2]],[[],[9,[1,16]]]]],
[430,`${spf}.${mcp}.observed.depth`,75,[[[17,50],[119,[0,410]]],[[17,52],[2]],[[],[9,[1,26]]]]],
[431,`${spf}.${mcp}.observed.totalLoad`,91,[[[17,50],[120,[0,410]]],[[17,52],[2]],[[],[9,[1,16]]]]],
[432,`${spf}.${mcp}.applied.totalLoad`,91,[[[22,56],[30,[0,437]]],[[],[30,[0,431]]]]],
[433,`${spf}.${mcd}.age`,72,[[[],[121,[0,430],[0,428]]]]],
[434,`${spf}.${mcd}.averageMortality`,111,[[[],[122,[0,433]]]]],
[435,`${spf}.${mcd}.severeMortality`,111,[[[],[123,[0,433]]]]],
[436,`${spf}.${mcd}.depth`,75,[[[],[124,[0,433],[0,428]]]]],
[437,`${spf}.${mcd}.totalLoad`,91,[[[],[125,[0,433],[0,428]]]]],
[438,`${spf}.${mcd}.deadLoad`,91,[[[],[126,[0,432],[0,429]]]]],
[439,`${spf}.${mcd}.deadFineLoad`,91,[[[],[127,[0,432],[0,429]]]]],
[440,`${spf}.${mcd}.deadSmallLoad`,91,[[[],[128,[0,432],[0,429]]]]],
[441,`${spf}.${mcd}.deadMediumLoad`,91,[[[],[129,[0,432],[0,429]]]]],
[442,`${spf}.${mcd}.deadLargeLoad`,91,[[[],[130,[0,432],[0,429]]]]],
[443,`${spf}.${mcd}.liveLoad`,91,[[[],[131,[0,432],[0,429]]]]],
[444,`${spf}.${mcd}.liveFineLoad`,91,[[[],[132,[0,432],[0,429]]]]],
[445,`${spf}.${mcd}.liveSmallLoad`,91,[[[],[133,[0,432],[0,429]]]]],
[446,`${spf}.${mcd}.liveMediumLoad`,91,[[[],[134,[0,432],[0,429]]]]],
[447,`${spf}.${mcd}.liveLargeLoad`,91,[[[],[135,[0,432],[0,429]]]]],
[448,`${spf}.${mcd}.liveLeafLoad`,91,[[[],[136,[0,432],[0,429]]]]],
[449,`${spf}.model.palmettoGallberry.domain`,23,[[[],[9,[1,53]]]]],
[450,`${spf}.${mpp}.age`,72,[[[17,50],[137,[0,410]]],[[17,53],[2]],[[],[9,[1,16]]]]],
[451,`${spf}.${mpp}.basalArea`,73,[[[17,50],[138,[0,410]]],[[17,53],[2]],[[],[9,[1,16]]]]],
[452,`${spf}.${mpp}.cover`,78,[[[17,50],[139,[0,410]]],[[17,53],[2]],[[],[9,[1,16]]]]],
[453,`${spf}.${mpp}.height`,75,[[[17,50],[140,[0,410]]],[[17,53],[2]],[[],[9,[1,26]]]]],
[454,`${spf}.${mpd}.depth`,75,[[[],[141,[0,453]]]]],
[455,`${spf}.${mpd}.deadFineLoad`,91,[[[],[142,[0,450],[0,453]]]]],
[456,`${spf}.${mpd}.deadSmallLoad`,91,[[[],[143,[0,450],[0,452]]]]],
[457,`${spf}.${mpd}.deadFoliageLoad`,91,[[[],[144,[0,450],[0,452]]]]],
[458,`${spf}.${mpd}.deadLitterLoad`,91,[[[],[145,[0,450],[0,451]]]]],
[459,`${spf}.${mpd}.liveFineLoad`,91,[[[],[146,[0,450],[0,453]]]]],
[460,`${spf}.${mpd}.liveSmallLoad`,91,[[[],[147,[0,450],[0,453]]]]],
[461,`${spf}.${mpd}.liveFoliageLoad`,91,[[[],[148,[0,450],[0,452],[0,453]]]]],
[462,`${spf}.model.westernAspen.domain`,23,[[[],[9,[1,54]]]]],
[463,`${spf}.${mwp}.aspenType`,31,[[[17,50],[149,[0,410]]],[[17,54],[2]],[[],[9,[1,58]]]]],
[464,`${spf}.${mwp}.curingLevel`,81,[[[17,50],[150,[0,410]]],[[17,54],[2]],[[],[9,[1,16]]]]],
[465,`${spf}.${mwd}.depth`,75,[[[],[151,[0,463]]]]],
[466,`${spf}.${mwd}.dead.fine.${load}`,91,[[[],[152,[0,463],[0,464]]]]],
[467,`${spf}.${mwd}.dead.small.${load}`,91,[[[],[153,[0,463]]]]],
[468,`${spf}.${mwd}.dead.fine.${savr}`,91,[[[],[154,[0,463],[0,464]]]]],
[469,`${spf}.${mwd}.live.herb.${load}`,91,[[[],[155,[0,463],[0,464]]]]],
[470,`${spf}.${mwd}.live.stem.${load}`,91,[[[],[156,[0,463],[0,464]]]]],
[471,`${spf}.${mwd}.live.stem.${savr}`,91,[[[],[157,[0,463],[0,464]]]]],
[472,`${ssfbdp}1.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,22],[1,20]]]]],
[473,`${ssfbdp}1.${heat}`,84,[[[],[43,[0,743],[0,757],[1,0],[1,23],[1,0]]]]],
[474,`${ssfbdp}1.${load}`,91,[[[],[43,[0,743],[0,750],[0,773],[0,789],[0,800]]]]],
[475,`${ssfbdp}1.${mois}`,88,[[[],[43,[0,743],[0,111],[0,111],[0,111],[0,111]]]]],
[476,`${ssfbdp}1.${savr}`,95,[[[],[43,[0,743],[0,754],[1,24],[1,25],[0,802]]]]],
[477,`${ssfbdp}1.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,26],[1,26]]]]],
[478,`${ssfbdp}1.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[479,`${ssfbdp}1.${ef}.${ehn}`,82,[[[],[44,[0,476]]]]],
[480,`${ssfbdp}1.${ef}.${load}`,91,[[[],[45,[0,476],[0,474],[1,31]]]]],
[481,`${ssfbdp}1.${qig}`,85,[[[],[46,[0,475],[0,479]]]]],
[482,`${ssfbdp}1.net.${load}`,91,[[[],[47,[0,474],[0,478]]]]],
[483,`${ssfbdp}1.${sc}`,93,[[[],[48,[0,476]]]]],
[484,`${ssfbdp}1.${sc}.${wf}`,125,[[[],[49,[0,483],[0,653]]]]],
[485,`${ssfbdp}1.${sa}`,94,[[[],[50,[0,474],[0,476],[0,472]]]]],
[486,`${ssfbdp}1.${sa}.${wf}`,125,[[[],[51,[0,485],[0,637]]]]],
[487,`${ssfbdp}1.volume`,100,[[[],[52,[0,474],[0,472]]]]],
[488,`${ssfbdp}1.${ef}.waterLoad`,91,[[[],[53,[0,480],[0,475]]]]],
[489,`${ssfbdp}2.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,22],[1,20]]]]],
[490,`${ssfbdp}2.${heat}`,84,[[[],[43,[0,743],[0,757],[1,0],[1,23],[1,0]]]]],
[491,`${ssfbdp}2.${load}`,91,[[[],[43,[0,743],[0,751],[0,774],[0,790],[0,801]]]]],
[492,`${ssfbdp}2.${mois}`,88,[[[],[43,[0,743],[0,112],[0,112],[0,112],[0,112]]]]],
[493,`${ssfbdp}2.${savr}`,95,[[[],[43,[0,743],[1,32],[1,33],[1,34],[1,32]]]]],
[494,`${ssfbdp}2.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,26],[1,26]]]]],
[495,`${ssfbdp}2.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[496,`${ssfbdp}2.${ef}.${ehn}`,82,[[[],[44,[0,493]]]]],
[497,`${ssfbdp}2.${ef}.${load}`,91,[[[],[45,[0,493],[0,491],[1,31]]]]],
[498,`${ssfbdp}2.${qig}`,85,[[[],[46,[0,492],[0,496]]]]],
[499,`${ssfbdp}2.net.${load}`,91,[[[],[47,[0,491],[0,495]]]]],
[500,`${ssfbdp}2.${sc}`,93,[[[],[48,[0,493]]]]],
[501,`${ssfbdp}2.${sc}.${wf}`,125,[[[],[49,[0,500],[0,653]]]]],
[502,`${ssfbdp}2.${sa}`,94,[[[],[50,[0,491],[0,493],[0,489]]]]],
[503,`${ssfbdp}2.${sa}.${wf}`,125,[[[],[51,[0,502],[0,637]]]]],
[504,`${ssfbdp}2.volume`,100,[[[],[52,[0,491],[0,489]]]]],
[505,`${ssfbdp}2.${ef}.waterLoad`,91,[[[],[53,[0,497],[0,492]]]]],
[506,`${ssfbdp}3.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,22],[1,20]]]]],
[507,`${ssfbdp}3.${heat}`,84,[[[],[43,[0,743],[0,757],[1,0],[1,23],[1,0]]]]],
[508,`${ssfbdp}3.${load}`,91,[[[],[43,[0,743],[0,752],[0,775],[0,791],[1,16]]]]],
[509,`${ssfbdp}3.${mois}`,88,[[[],[43,[0,743],[0,113],[0,112],[0,111],[1,35]]]]],
[510,`${ssfbdp}3.${savr}`,95,[[[],[43,[0,743],[1,22],[1,36],[1,37],[1,8]]]]],
[511,`${ssfbdp}3.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,26],[1,26]]]]],
[512,`${ssfbdp}3.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[513,`${ssfbdp}3.${ef}.${ehn}`,82,[[[],[44,[0,510]]]]],
[514,`${ssfbdp}3.${ef}.${load}`,91,[[[],[45,[0,510],[0,508],[1,31]]]]],
[515,`${ssfbdp}3.${qig}`,85,[[[],[46,[0,509],[0,513]]]]],
[516,`${ssfbdp}3.net.${load}`,91,[[[],[47,[0,508],[0,512]]]]],
[517,`${ssfbdp}3.${sc}`,93,[[[],[48,[0,510]]]]],
[518,`${ssfbdp}3.${sc}.${wf}`,125,[[[],[49,[0,517],[0,653]]]]],
[519,`${ssfbdp}3.${sa}`,94,[[[],[50,[0,508],[0,510],[0,506]]]]],
[520,`${ssfbdp}3.${sa}.${wf}`,125,[[[],[51,[0,519],[0,637]]]]],
[521,`${ssfbdp}3.volume`,100,[[[],[52,[0,508],[0,506]]]]],
[522,`${ssfbdp}3.${ef}.waterLoad`,91,[[[],[53,[0,514],[0,509]]]]],
[523,`${ssfbdp}4.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,22],[1,20]]]]],
[524,`${ssfbdp}4.${heat}`,84,[[[],[43,[0,743],[0,757],[1,0],[1,23],[1,0]]]]],
[525,`${ssfbdp}4.${load}`,91,[[[],[43,[0,743],[0,759],[0,776],[0,792],[1,16]]]]],
[526,`${ssfbdp}4.${mois}`,88,[[[],[43,[0,743],[0,111],[0,113],[0,113],[1,35]]]]],
[527,`${ssfbdp}4.${savr}`,95,[[[],[43,[0,743],[0,755],[1,38],[1,37],[1,8]]]]],
[528,`${ssfbdp}4.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,26],[1,26]]]]],
[529,`${ssfbdp}4.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[530,`${ssfbdp}4.${ef}.${ehn}`,82,[[[],[44,[0,527]]]]],
[531,`${ssfbdp}4.${ef}.${load}`,91,[[[],[45,[0,527],[0,525],[1,31]]]]],
[532,`${ssfbdp}4.${qig}`,85,[[[],[46,[0,526],[0,530]]]]],
[533,`${ssfbdp}4.net.${load}`,91,[[[],[47,[0,525],[0,529]]]]],
[534,`${ssfbdp}4.${sc}`,93,[[[],[48,[0,527]]]]],
[535,`${ssfbdp}4.${sc}.${wf}`,125,[[[],[49,[0,534],[0,653]]]]],
[536,`${ssfbdp}4.${sa}`,94,[[[],[50,[0,525],[0,527],[0,523]]]]],
[537,`${ssfbdp}4.${sa}.${wf}`,125,[[[],[51,[0,536],[0,637]]]]],
[538,`${ssfbdp}4.volume`,100,[[[],[52,[0,525],[0,523]]]]],
[539,`${ssfbdp}4.${ef}.waterLoad`,91,[[[],[53,[0,531],[0,526]]]]],
[540,`${ssfbdp}5.${dens}`,92,[[[],[9,[1,20]]]]],
[541,`${ssfbdp}5.${heat}`,84,[[[],[9,[1,0]]]]],
[542,`${ssfbdp}5.${load}`,91,[[[],[9,[1,16]]]]],
[543,`${ssfbdp}5.${mois}`,88,[[[],[9,[1,35]]]]],
[544,`${ssfbdp}5.${savr}`,95,[[[],[9,[1,8]]]]],
[545,`${ssfbdp}5.${emc}`,83,[[[],[9,[1,26]]]]],
[546,`${ssfbdp}5.${tmc}`,99,[[[],[9,[1,28]]]]],
[547,`${ssfbdp}5.${ef}.${ehn}`,82,[[[],[44,[0,544]]]]],
[548,`${ssfbdp}5.${ef}.${load}`,91,[[[],[45,[0,544],[0,542],[1,31]]]]],
[549,`${ssfbdp}5.${qig}`,85,[[[],[46,[0,543],[0,547]]]]],
[550,`${ssfbdp}5.net.${load}`,91,[[[],[47,[0,542],[0,546]]]]],
[551,`${ssfbdp}5.${sc}`,93,[[[],[48,[0,544]]]]],
[552,`${ssfbdp}5.${sc}.${wf}`,125,[[[],[49,[0,551],[0,653]]]]],
[553,`${ssfbdp}5.${sa}`,94,[[[],[50,[0,542],[0,544],[0,540]]]]],
[554,`${ssfbdp}5.${sa}.${wf}`,125,[[[],[51,[0,553],[0,637]]]]],
[555,`${ssfbdp}5.volume`,100,[[[],[52,[0,542],[0,540]]]]],
[556,`${ssfbdp}5.${ef}.waterLoad`,91,[[[],[53,[0,548],[0,543]]]]],
[557,`${ssfblp}1.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,21],[1,20]]]]],
[558,`${ssfblp}1.${heat}`,84,[[[],[43,[0,743],[0,758],[1,39],[1,23],[1,0]]]]],
[559,`${ssfblp}1.${load}`,91,[[[],[43,[0,743],[0,760],[0,778],[0,793],[0,803]]]]],
[560,`${ssfblp}1.${mois}`,88,[[[],[43,[0,743],[0,115],[0,116],[0,116],[0,115]]]]],
[561,`${ssfblp}1.${savr}`,95,[[[],[43,[0,743],[0,755],[1,24],[1,25],[1,40]]]]],
[562,`${ssfblp}1.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,27],[1,26]]]]],
[563,`${ssfblp}1.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[564,`${ssfblp}1.${ef}.${ehn}`,82,[[[],[44,[0,561]]]]],
[565,`${ssfblp}1.${ef}.${load}`,91,[[[],[45,[0,561],[0,559],[1,41]]]]],
[566,`${ssfblp}1.${qig}`,85,[[[],[46,[0,560],[0,564]]]]],
[567,`${ssfblp}1.net.${load}`,91,[[[],[47,[0,559],[0,563]]]]],
[568,`${ssfblp}1.${sc}`,93,[[[],[48,[0,561]]]]],
[569,`${ssfblp}1.${sc}.${wf}`,125,[[[],[49,[0,568],[0,673]]]]],
[570,`${ssfblp}1.${sa}`,94,[[[],[50,[0,559],[0,561],[0,557]]]]],
[571,`${ssfblp}1.${sa}.${wf}`,125,[[[],[51,[0,570],[0,657]]]]],
[572,`${ssfblp}1.volume`,100,[[[],[52,[0,559],[0,557]]]]],
[573,`${ssfblp}2.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,21],[1,20]]]]],
[574,`${ssfblp}2.${heat}`,84,[[[],[43,[0,743],[0,758],[1,42],[1,23],[1,0]]]]],
[575,`${ssfblp}2.${load}`,91,[[[],[43,[0,743],[0,753],[0,779],[0,794],[0,804]]]]],
[576,`${ssfblp}2.${mois}`,88,[[[],[43,[0,743],[0,116],[0,116],[0,116],[0,116]]]]],
[577,`${ssfblp}2.${savr}`,95,[[[],[43,[0,743],[0,756],[1,33],[1,34],[0,805]]]]],
[578,`${ssfblp}2.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,27],[1,26]]]]],
[579,`${ssfblp}2.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[580,`${ssfblp}2.${ef}.${ehn}`,82,[[[],[44,[0,577]]]]],
[581,`${ssfblp}2.${ef}.${load}`,91,[[[],[45,[0,577],[0,575],[1,41]]]]],
[582,`${ssfblp}2.${qig}`,85,[[[],[46,[0,576],[0,580]]]]],
[583,`${ssfblp}2.net.${load}`,91,[[[],[47,[0,575],[0,579]]]]],
[584,`${ssfblp}2.${sc}`,93,[[[],[48,[0,577]]]]],
[585,`${ssfblp}2.${sc}.${wf}`,125,[[[],[49,[0,584],[0,673]]]]],
[586,`${ssfblp}2.${sa}`,94,[[[],[50,[0,575],[0,577],[0,573]]]]],
[587,`${ssfblp}2.${sa}.${wf}`,125,[[[],[51,[0,586],[0,657]]]]],
[588,`${ssfblp}2.volume`,100,[[[],[52,[0,575],[0,573]]]]],
[589,`${ssfblp}3.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,21],[1,20]]]]],
[590,`${ssfblp}3.${heat}`,84,[[[],[43,[0,743],[0,758],[1,42],[1,23],[1,0]]]]],
[591,`${ssfblp}3.${load}`,91,[[[],[43,[0,743],[1,16],[0,780],[0,795],[1,16]]]]],
[592,`${ssfblp}3.${mois}`,88,[[[],[43,[0,743],[1,35],[0,116],[0,116],[1,35]]]]],
[593,`${ssfblp}3.${savr}`,95,[[[],[43,[0,743],[1,8],[1,36],[1,37],[1,8]]]]],
[594,`${ssfblp}3.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,27],[1,26]]]]],
[595,`${ssfblp}3.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[596,`${ssfblp}3.${ef}.${ehn}`,82,[[[],[44,[0,593]]]]],
[597,`${ssfblp}3.${ef}.${load}`,91,[[[],[45,[0,593],[0,591],[1,41]]]]],
[598,`${ssfblp}3.${qig}`,85,[[[],[46,[0,592],[0,596]]]]],
[599,`${ssfblp}3.net.${load}`,91,[[[],[47,[0,591],[0,595]]]]],
[600,`${ssfblp}3.${sc}`,93,[[[],[48,[0,593]]]]],
[601,`${ssfblp}3.${sc}.${wf}`,125,[[[],[49,[0,600],[0,673]]]]],
[602,`${ssfblp}3.${sa}`,94,[[[],[50,[0,591],[0,593],[0,589]]]]],
[603,`${ssfblp}3.${sa}.${wf}`,125,[[[],[51,[0,602],[0,657]]]]],
[604,`${ssfblp}3.volume`,100,[[[],[52,[0,591],[0,589]]]]],
[605,`${ssfblp}4.${dens}`,92,[[[],[43,[0,743],[1,20],[1,21],[1,21],[1,20]]]]],
[606,`${ssfblp}4.${heat}`,84,[[[],[43,[0,743],[0,758],[1,42],[1,23],[1,0]]]]],
[607,`${ssfblp}4.${load}`,91,[[[],[43,[0,743],[1,16],[0,781],[1,16],[1,16]]]]],
[608,`${ssfblp}4.${mois}`,88,[[[],[43,[0,743],[1,35],[0,116],[1,35],[1,35]]]]],
[609,`${ssfblp}4.${savr}`,95,[[[],[43,[0,743],[1,8],[1,38],[1,8],[1,8]]]]],
[610,`${ssfblp}4.${emc}`,83,[[[],[43,[0,743],[1,26],[1,27],[1,27],[1,26]]]]],
[611,`${ssfblp}4.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[612,`${ssfblp}4.${ef}.${ehn}`,82,[[[],[44,[0,609]]]]],
[613,`${ssfblp}4.${ef}.${load}`,91,[[[],[45,[0,609],[0,607],[1,41]]]]],
[614,`${ssfblp}4.${qig}`,85,[[[],[46,[0,608],[0,612]]]]],
[615,`${ssfblp}4.net.${load}`,91,[[[],[47,[0,607],[0,611]]]]],
[616,`${ssfblp}4.${sc}`,93,[[[],[48,[0,609]]]]],
[617,`${ssfblp}4.${sc}.${wf}`,125,[[[],[49,[0,616],[0,673]]]]],
[618,`${ssfblp}4.${sa}`,94,[[[],[50,[0,607],[0,609],[0,605]]]]],
[619,`${ssfblp}4.${sa}.${wf}`,125,[[[],[51,[0,618],[0,657]]]]],
[620,`${ssfblp}4.volume`,100,[[[],[52,[0,607],[0,605]]]]],
[621,`${ssfblp}5.${dens}`,92,[[[],[43,[0,743],[1,20],[1,20],[1,21],[1,20]]]]],
[622,`${ssfblp}5.${heat}`,84,[[[],[43,[0,743],[0,758],[1,39],[1,23],[1,0]]]]],
[623,`${ssfblp}5.${load}`,91,[[[],[43,[0,743],[1,16],[0,782],[1,16],[1,16]]]]],
[624,`${ssfblp}5.${mois}`,88,[[[],[43,[0,743],[1,35],[0,115],[1,35],[1,35]]]]],
[625,`${ssfblp}5.${savr}`,95,[[[],[43,[0,743],[1,8],[1,43],[1,8],[1,8]]]]],
[626,`${ssfblp}5.${emc}`,83,[[[],[43,[0,743],[1,26],[1,44],[1,27],[1,26]]]]],
[627,`${ssfblp}5.${tmc}`,99,[[[],[43,[0,743],[1,28],[1,29],[1,30],[1,29]]]]],
[628,`${ssfblp}5.${ef}.${ehn}`,82,[[[],[44,[0,625]]]]],
[629,`${ssfblp}5.${ef}.${load}`,91,[[[],[45,[0,625],[0,623],[1,41]]]]],
[630,`${ssfblp}5.${qig}`,85,[[[],[46,[0,624],[0,628]]]]],
[631,`${ssfblp}5.net.${load}`,91,[[[],[47,[0,623],[0,627]]]]],
[632,`${ssfblp}5.${sc}`,93,[[[],[48,[0,625]]]]],
[633,`${ssfblp}5.${sc}.${wf}`,125,[[[],[49,[0,632],[0,673]]]]],
[634,`${ssfblp}5.${sa}`,94,[[[],[50,[0,623],[0,625],[0,621]]]]],
[635,`${ssfblp}5.${sa}.${wf}`,125,[[[],[51,[0,634],[0,657]]]]],
[636,`${ssfblp}5.volume`,100,[[[],[52,[0,623],[0,621]]]]],
[637,`${ssfbd}.${sa}`,94,[[[],[54,[0,485],[0,502],[0,519],[0,536],[0,553]]]]],
[638,`${ssfbd}.${sa}.${wf}`,125,[[[],[21,[0,637],[0,692]]]]],
[639,`${ssfbd}.mineralDamping`,55,[[[],[55,[0,652]]]]],
[640,`${ssfbd}.moistureDamping`,55,[[[],[56,[0,646],[0,644]]]]],
[641,`${ssfbd}.${heat}`,84,[[[],[57,[0,486],[0,503],[0,520],[0,537],[0,554],[0,473],[0,490],[0,507],[0,524],[0,541]]]]],
[642,`${ssfbd}.${load}`,91,[[[],[54,[0,474],[0,491],[0,508],[0,525],[0,542]]]]],
[643,`${ssfbd}.${ef}.${load}`,91,[[[],[54,[0,480],[0,497],[0,514],[0,531],[0,548]]]]],
[644,`${ssfbd}.extinction.${mois}`,88,[[[],[43,[0,743],[0,748],[1,45],[1,46],[1,47]]]]],
[645,`${ssfbd}.extinction.${mois}Factor`,37,[[[],[58,[0,643],[0,663]]]]],
[646,`${ssfbd}.${mois}`,88,[[[],[57,[0,486],[0,503],[0,520],[0,537],[0,554],[0,475],[0,492],[0,509],[0,526],[0,543]]]]],
[647,`${ssfbd}.volume`,75,[[[],[54,[0,487],[0,504],[0,521],[0,538],[0,555]]]]],
[648,`${ssfbd}.${qig}`,85,[[[],[57,[0,486],[0,503],[0,520],[0,537],[0,554],[0,481],[0,498],[0,515],[0,532],[0,549]]]]],
[649,`${ssfbd}.${rxi}`,65,[[[],[22,[0,650],[0,640]]]]],
[650,`${ssfbd}.${rxi}Dry`,65,[[[],[59,[0,689],[0,654],[0,641],[0,639]]]]],
[651,`${ssfbd}.${savr}`,95,[[[],[57,[0,486],[0,503],[0,520],[0,537],[0,554],[0,476],[0,493],[0,510],[0,527],[0,544]]]]],
[652,`${ssfbd}.${emc}`,83,[[[],[57,[0,486],[0,503],[0,520],[0,537],[0,554],[0,477],[0,494],[0,511],[0,528],[0,545]]]]],
[653,`${ssfbd}.${sc}.${wf}`,125,[[[],[60,[0,485],[0,483],[0,502],[0,500],[0,519],[0,517],[0,536],[0,534],[0,553],[0,551]]]]],
[654,`${ssfbd}.net.${load}`,91,[[[],[57,[0,484],[0,501],[0,518],[0,535],[0,552],[0,482],[0,499],[0,516],[0,533],[0,550]]]]],
[655,`${ssfbd}.${ef}.waterLoad`,91,[[[],[54,[0,488],[0,505],[0,522],[0,539],[0,556]]]]],
[656,`${ssfbd}.${ef}.${mois}`,88,[[[],[21,[0,655],[0,643]]]]],
[657,`${ssfbl}.${sa}`,94,[[[],[54,[0,570],[0,586],[0,602],[0,618],[0,634]]]]],
[658,`${ssfbl}.${sa}.${wf}`,125,[[[],[21,[0,657],[0,692]]]]],
[659,`${ssfbl}.mineralDamping`,55,[[[],[55,[0,672]]]]],
[660,`${ssfbl}.moistureDamping`,55,[[[],[56,[0,666],[0,664]]]]],
[661,`${ssfbl}.${heat}`,84,[[[],[57,[0,571],[0,587],[0,603],[0,619],[0,635],[0,558],[0,574],[0,590],[0,606],[0,622]]]]],
[662,`${ssfbl}.${load}`,91,[[[],[54,[0,559],[0,575],[0,591],[0,607],[0,623]]]]],
[663,`${ssfbl}.${ef}.${load}`,91,[[[],[54,[0,565],[0,581],[0,597],[0,613],[0,629]]]]],
[664,`${ssfbl}.extinction.${mois}`,88,[[[],[61,[0,665],[0,656],[0,644]]]]],
[665,`${ssfbl}.extinction.${mois}Factor`,37,[[[],[58,[0,643],[0,663]]]]],
[666,`${ssfbl}.${mois}`,88,[[[],[57,[0,571],[0,587],[0,603],[0,619],[0,635],[0,560],[0,576],[0,592],[0,608],[0,624]]]]],
[667,`${ssfbl}.volume`,75,[[[],[54,[0,572],[0,588],[0,604],[0,620],[0,636]]]]],
[668,`${ssfbl}.${qig}`,85,[[[],[57,[0,571],[0,587],[0,603],[0,619],[0,635],[0,566],[0,582],[0,598],[0,614],[0,630]]]]],
[669,`${ssfbl}.${rxi}`,65,[[[],[22,[0,670],[0,660]]]]],
[670,`${ssfbl}.${rxi}Dry`,65,[[[],[59,[0,689],[0,674],[0,661],[0,659]]]]],
[671,`${ssfbl}.${savr}`,95,[[[],[57,[0,571],[0,587],[0,603],[0,619],[0,635],[0,561],[0,577],[0,593],[0,609],[0,625]]]]],
[672,`${ssfbl}.${emc}`,83,[[[],[57,[0,571],[0,587],[0,603],[0,619],[0,635],[0,562],[0,578],[0,594],[0,610],[0,626]]]]],
[673,`${ssfbl}.${sc}.${wf}`,125,[[[],[60,[0,570],[0,568],[0,586],[0,584],[0,602],[0,600],[0,618],[0,616],[0,634],[0,632]]]]],
[674,`${ssfbl}.net.${load}`,91,[[[],[57,[0,569],[0,585],[0,601],[0,617],[0,633],[0,567],[0,583],[0,599],[0,615],[0,631]]]]],
[675,`${ssfb}.depth`,75,[[[],[43,[0,743],[0,747],[0,764],[0,788],[0,799]]]]],
[676,`${ssfb}.bulkDensity`,74,[[[],[21,[0,680],[0,675]]]]],
[677,`${ssfb}.${qig}`,76,[[[],[57,[0,638],[0,658],[0,648],[0,668]]]]],
[678,`${ssfb}.heatSink`,86,[[[],[62,[0,677],[0,676]]]]],
[679,`${ssfb}.noWindNoSlope.${ros}`,71,[[[],[63,[0,686],[0,685],[0,678]]]]],
[680,`${ssfb}.${load}`,91,[[[],[54,[0,642],[0,662]]]]],
[681,`${ssfb}.open.${waf}`,127,[[[],[64,[0,675]]]]],
[682,`${ssfb}.packingRatio`,77,[[[],[65,[0,647],[0,667],[0,675]]]]],
[683,`${ssfb}.packingRatio.optimum`,77,[[[],[66,[0,690]]]]],
[684,`${ssfb}.packingRatio.ratio`,77,[[[],[21,[0,682],[0,683]]]]],
[685,`${ssfb}.propagatingFluxRatio`,64,[[[],[67,[0,690],[0,682]]]]],
[686,`${ssfb}.${rxi}`,65,[[[],[54,[0,649],[0,669]]]]],
[687,`${ssfb}.reactionVelocityExponent`,37,[[[],[68,[0,690]]]]],
[688,`${ssfb}.reactionVelocityMaximum`,66,[[[],[69,[0,691]]]]],
[689,`${ssfb}.reactionVelocityOptimum`,66,[[[],[70,[0,684],[0,688],[0,687]]]]],
[690,`${ssfb}.${savr}`,95,[[[],[57,[0,638],[0,658],[0,651],[0,671]]]]],
[691,`${ssfb}.savr15`,37,[[[],[71,[0,690]]]]],
[692,`${ssfb}.${sa}`,94,[[[],[54,[0,637],[0,657]]]]],
[693,`${ssff}.maximumDirection.slope.${ros}`,71,[[[],[72,[0,742],[0,706]]]]],
[694,`${ssff}.maximumDirection.wind.${ros}`,71,[[[],[73,[0,742],[0,729]]]]],
[695,`${ssff}.wind.heading.fromUpslope`,40,[[[],[30,[0,130]]]]],
[696,`${ssff}.maximumDirection.xComponent`,37,[[[],[74,[0,694],[0,693],[0,695]]]]],
[697,`${ssff}.maximumDirection.yComponent`,37,[[[],[75,[0,694],[0,695]]]]],
[698,`${ssff}.maximumDirection.${ros}`,71,[[[],[76,[0,696],[0,697]]]]],
[699,`${ssff}.limit.${ews}.exceeded`,34,[[[],[77,[0,710],[0,701]]]]],
[700,`${ssff}.limit.${ros}.exceeded`,35,[[[],[77,[0,712],[0,718]]]]],
[701,`${ssff}.limit.${ews}`,126,[[[],[78,[0,739]]]]],
[702,`${ssff}.limit.windSlopeSpreadRateCoefficient`,37,[[[],[79,[0,701],[0,724],[0,727]]]]],
[703,`${ssff}.limit.${ros}`,71,[[[],[80,[0,742],[0,702]]]]],
[704,`${ssff}.slope.ratio`,115,[[[],[30,[0,121]]]]],
[705,`${ssff}.slope.k`,37,[[[],[81,[0,682]]]]],
[706,`${ssff}.slope.phi`,37,[[[],[82,[0,704],[0,705]]]]],
[707,`${ssff}.spread.step1.${ews}`,126,[[[],[83,[0,708],[0,724],[0,728]]]]],
[708,`${ssff}.spread.step1.${phiew}`,37,[[[],[84,[0,729],[0,706]]]]],
[709,`${ssff}.spread.step1.${ros}`,71,[[[],[80,[0,742],[0,708]]]]],
[710,`${ssff}.spread.step2.${ews}`,126,[[[],[83,[0,711],[0,724],[0,728]]]]],
[711,`${ssff}.spread.step2.${phiew}`,37,[[[],[85,[0,742],[0,712]]]]],
[712,`${ssff}.spread.step2.${ros}`,71,[[[],[86,[0,742],[0,698]]]]],
[713,`${ssff}.spread.step3a.${ews}`,126,[[[],[87,[0,710],[0,701]]]]],
[714,`${ssff}.spread.step3a.${phiew}`,37,[[[],[87,[0,711],[0,702]]]]],
[715,`${ssff}.spread.step3a.${ros}`,71,[[[],[87,[0,712],[0,703]]]]],
[716,`${ssff}.spread.step3b.${ews}`,126,[[[],[83,[0,717],[0,724],[0,728]]]]],
[717,`${ssff}.spread.step3b.${phiew}`,37,[[[],[85,[0,742],[0,718]]]]],
[718,`${ssff}.spread.step3b.${ros}`,71,[[[],[88,[0,712],[0,710]]]]],
[719,`${ssff}.spread.step4.${ews}`,126,[[[],[83,[0,720],[0,724],[0,728]]]]],
[720,`${ssff}.spread.step4.${phiew}`,37,[[[],[85,[0,742],[0,721]]]]],
[721,`${ssff}.spread.step4.${ros}`,71,[[[],[88,[0,715],[0,713]]]]],
[722,`${ssff}.${waf}`,127,[[[20,48],[30,[0,137]]],[[],[89,[0,51],[0,54],[0,681]]]]],
[723,`${ssff}.wind.speed.atMidflame`,126,[[[26,19],[30,[0,136]]],[[],[42,[0,135],[0,722]]]]],
[724,`${ssff}.wind.factor.b`,37,[[[],[90,[0,690]]]]],
[725,`${ssff}.wind.factor.c`,37,[[[],[91,[0,690]]]]],
[726,`${ssff}.wind.factor.e`,37,[[[],[92,[0,690]]]]],
[727,`${ssff}.wind.factor.k`,37,[[[],[93,[0,684],[0,726],[0,725]]]]],
[728,`${ssff}.wind.factor.i`,37,[[[],[94,[0,684],[0,726],[0,725]]]]],
[729,`${ssff}.wind.phi`,37,[[[],[95,[0,723],[0,724],[0,727]]]]],
[730,`${ssff}.${ews}`,126,[[[29,49],[30,[0,719]]],[[],[30,[0,716]]]]],
[731,`${ssff}.${fli}`,57,[[[],[96,[0,741],[0,739],[0,733]]]]],
[732,`${ssff}.${fl}`,59,[[[],[17,[0,731]]]]],
[733,`${ssff}.${taur}`,67,[[[],[97,[0,690]]]]],
[734,`${ssff}.heading.fromUpslope`,40,[[[],[98,[0,696],[0,697],[0,698]]]]],
[735,`${ssff}.heading.fromNorth`,40,[[[],[19,[0,119],[0,734]]]]],
[736,`${ssff}.${hpua}`,60,[[[],[99,[0,739],[0,733]]]]],
[737,`${ssff}.${lwr}`,61,[[[],[20,[0,730]]]]],
[738,`${ssff}.${phiew}`,37,[[[29,49],[30,[0,720]]],[[],[30,[0,717]]]]],
[739,`${ssff}.${rxi}`,65,[[[],[30,[0,686]]]]],
[740,`${ssff}.${sh}`,68,[[[],[100,[0,731],[0,723],[0,122]]]]],
[741,`${ssff}.${ros}`,71,[[[29,49],[30,[0,721]]],[[],[30,[0,718]]]]],
[742,`${ssff}.noWindNoSlope.${ros}`,71,[[[],[30,[0,679]]]]],
[743,`${ssf}.model.domain`,23,[[[18,50],[101,[0,744]]],[[18,51],[9,[1,51]]],[[18,52],[9,[1,52]]],[[18,53],[9,[1,53]]],[[18,54],[9,[1,54]]],[[],[9,[1,55]]]]],
[744,`${ssf}.model.catalogKey`,24,[[[],[2]]]],
[745,`${ssf}.model.behave.domain`,23,[[[],[9,[1,51]]]]],
[746,`${ssf}.${mbp}.cured.herb.fraction`,81,[[[21,56],[102,[0,115]]],[[],[2]]]],
[747,`${ssf}.${mbp}.depth`,75,[[[18,50],[103,[0,744]]],[[18,51],[2]],[[],[9,[1,26]]]]],
[748,`${ssf}.${mbp}.dead.extinction.${mois}`,88,[[[18,50],[104,[0,744]]],[[18,51],[2]],[[],[9,[1,47]]]]],
[749,`${ssf}.${mbp}.total.herb.${load}`,91,[[[18,50],[105,[0,744]]],[[18,51],[2]],[[],[9,[1,16]]]]],
[750,`${ssf}.${mbp}.dead.tl1h.${load}`,91,[[[18,50],[106,[0,744]]],[[18,51],[2]],[[],[9,[1,16]]]]],
[751,`${ssf}.${mbp}.dead.tl10h.${load}`,91,[[[18,50],[107,[0,744]]],[[18,51],[2]],[[],[9,[1,16]]]]],
[752,`${ssf}.${mbp}.dead.tl100h.${load}`,91,[[[18,50],[108,[0,744]]],[[18,51],[2]],[[],[9,[1,16]]]]],
[753,`${ssf}.${mbp}.live.stem.${load}`,91,[[[18,50],[109,[0,744]]],[[18,51],[2]],[[],[9,[1,16]]]]],
[754,`${ssf}.${mbp}.dead.tl1h.${savr}`,95,[[[18,50],[110,[0,744]]],[[18,51],[2]],[[],[9,[1,16]]]]],
[755,`${ssf}.${mbp}.live.herb.${savr}`,95,[[[18,50],[111,[0,744]]],[[18,51],[2]],[[],[9,[1,8]]]]],
[756,`${ssf}.${mbp}.live.stem.${savr}`,95,[[[18,50],[112,[0,744]]],[[18,51],[2]],[[],[9,[1,8]]]]],
[757,`${ssf}.${mbp}.dead.${heat}`,84,[[[18,50],[113,[0,744]]],[[18,51],[2]],[[],[9,[1,0]]]]],
[758,`${ssf}.${mbp}.live.${heat}`,84,[[[18,50],[114,[0,744]]],[[18,51],[2]],[[],[9,[1,0]]]]],
[759,`${ssf}.${mbd}.dead.herb.${load}`,91,[[[],[115,[0,749],[0,746]]]]],
[760,`${ssf}.${mbd}.live.herb.${load}`,91,[[[],[116,[0,749],[0,746]]]]],
[761,`${ssf}.model.chaparral.domain`,23,[[[],[9,[1,52]]]]],
[762,`${ssf}.${mcp}.chaparralType`,20,[[[18,50],[117,[0,744]]],[[18,52],[2]],[[],[9,[1,57]]]]],
[763,`${ssf}.${mcp}.observed.deadFuelFraction`,81,[[[18,50],[118,[0,744]]],[[18,52],[2]],[[],[9,[1,16]]]]],
[764,`${ssf}.${mcp}.observed.depth`,75,[[[18,50],[119,[0,744]]],[[18,52],[2]],[[],[9,[1,26]]]]],
[765,`${ssf}.${mcp}.observed.totalLoad`,91,[[[18,50],[120,[0,744]]],[[18,52],[2]],[[],[9,[1,16]]]]],
[766,`${ssf}.${mcp}.applied.totalLoad`,91,[[[22,56],[30,[0,771]]],[[],[30,[0,765]]]]],
[767,`${ssf}.${mcd}.age`,72,[[[],[121,[0,764],[0,762]]]]],
[768,`${ssf}.${mcd}.averageMortality`,111,[[[],[122,[0,767]]]]],
[769,`${ssf}.${mcd}.severeMortality`,111,[[[],[123,[0,767]]]]],
[770,`${ssf}.${mcd}.depth`,75,[[[],[124,[0,767],[0,762]]]]],
[771,`${ssf}.${mcd}.totalLoad`,91,[[[],[125,[0,767],[0,762]]]]],
[772,`${ssf}.${mcd}.deadLoad`,91,[[[],[126,[0,766],[0,763]]]]],
[773,`${ssf}.${mcd}.deadFineLoad`,91,[[[],[127,[0,766],[0,763]]]]],
[774,`${ssf}.${mcd}.deadSmallLoad`,91,[[[],[128,[0,766],[0,763]]]]],
[775,`${ssf}.${mcd}.deadMediumLoad`,91,[[[],[129,[0,766],[0,763]]]]],
[776,`${ssf}.${mcd}.deadLargeLoad`,91,[[[],[130,[0,766],[0,763]]]]],
[777,`${ssf}.${mcd}.liveLoad`,91,[[[],[131,[0,766],[0,763]]]]],
[778,`${ssf}.${mcd}.liveFineLoad`,91,[[[],[132,[0,766],[0,763]]]]],
[779,`${ssf}.${mcd}.liveSmallLoad`,91,[[[],[133,[0,766],[0,763]]]]],
[780,`${ssf}.${mcd}.liveMediumLoad`,91,[[[],[134,[0,766],[0,763]]]]],
[781,`${ssf}.${mcd}.liveLargeLoad`,91,[[[],[135,[0,766],[0,763]]]]],
[782,`${ssf}.${mcd}.liveLeafLoad`,91,[[[],[136,[0,766],[0,763]]]]],
[783,`${ssf}.model.palmettoGallberry.domain`,23,[[[],[9,[1,53]]]]],
[784,`${ssf}.${mpp}.age`,72,[[[18,50],[137,[0,744]]],[[18,53],[2]],[[],[9,[1,16]]]]],
[785,`${ssf}.${mpp}.basalArea`,73,[[[18,50],[138,[0,744]]],[[18,53],[2]],[[],[9,[1,16]]]]],
[786,`${ssf}.${mpp}.cover`,78,[[[18,50],[139,[0,744]]],[[18,53],[2]],[[],[9,[1,16]]]]],
[787,`${ssf}.${mpp}.height`,75,[[[18,50],[140,[0,744]]],[[18,53],[2]],[[],[9,[1,26]]]]],
[788,`${ssf}.${mpd}.depth`,75,[[[],[141,[0,787]]]]],
[789,`${ssf}.${mpd}.deadFineLoad`,91,[[[],[142,[0,784],[0,787]]]]],
[790,`${ssf}.${mpd}.deadSmallLoad`,91,[[[],[143,[0,784],[0,786]]]]],
[791,`${ssf}.${mpd}.deadFoliageLoad`,91,[[[],[144,[0,784],[0,786]]]]],
[792,`${ssf}.${mpd}.deadLitterLoad`,91,[[[],[145,[0,784],[0,785]]]]],
[793,`${ssf}.${mpd}.liveFineLoad`,91,[[[],[146,[0,784],[0,787]]]]],
[794,`${ssf}.${mpd}.liveSmallLoad`,91,[[[],[147,[0,784],[0,787]]]]],
[795,`${ssf}.${mpd}.liveFoliageLoad`,91,[[[],[148,[0,784],[0,786],[0,787]]]]],
[796,`${ssf}.model.westernAspen.domain`,23,[[[],[9,[1,54]]]]],
[797,`${ssf}.${mwp}.aspenType`,31,[[[18,50],[149,[0,744]]],[[18,54],[2]],[[],[9,[1,58]]]]],
[798,`${ssf}.${mwp}.curingLevel`,81,[[[18,50],[150,[0,744]]],[[18,54],[2]],[[],[9,[1,16]]]]],
[799,`${ssf}.${mwd}.depth`,75,[[[],[151,[0,797]]]]],
[800,`${ssf}.${mwd}.dead.fine.${load}`,91,[[[],[152,[0,797],[0,798]]]]],
[801,`${ssf}.${mwd}.dead.small.${load}`,91,[[[],[153,[0,797]]]]],
[802,`${ssf}.${mwd}.dead.fine.${savr}`,91,[[[],[154,[0,797],[0,798]]]]],
[803,`${ssf}.${mwd}.live.herb.${load}`,91,[[[],[155,[0,797],[0,798]]]]],
[804,`${ssf}.${mwd}.live.stem.${load}`,91,[[[],[156,[0,797],[0,798]]]]],
[805,`${ssf}.${mwd}.live.stem.${savr}`,91,[[[],[157,[0,797],[0,798]]]]],
[806,`${swf}.primaryCover`,78,[[[18,55],[9,[1,8]]],[[],[2]]]],
[807,`${swf}.${ews}`,126,[[[],[30,[0,396]]]]],
[808,`${swf}.heading.fromUpslope`,40,[[[],[30,[0,400]]]]],
[809,`${swf}.heading.fromNorth`,40,[[[],[30,[0,401]]]]],
[810,`${swf}.${lwr}`,61,[[[],[30,[0,403]]]]],
[811,`${swf}.wind.speed.atMidflame`,126,[[[],[30,[0,389]]]]],
[812,`${swf}.${waf}`,127,[[[],[30,[0,388]]]]],
[813,`${swf}.${fli}`,57,[[[18,55],[30,[0,397]]],[[],[158,[0,397],[0,731]]]]],
[814,`${swf}.${fl}`,59,[[[18,55],[30,[0,398]]],[[],[158,[0,398],[0,732]]]]],
[815,`${swf}.${hpua}`,60,[[[18,55],[30,[0,402]]],[[],[158,[0,402],[0,736]]]]],
[816,`${swf}.${rxi}`,65,[[[18,55],[30,[0,405]]],[[],[158,[0,405],[0,739]]]]],
[817,`${swf}.${sh}`,68,[[[18,55],[30,[0,406]]],[[],[158,[0,406],[0,740]]]]],
[818,`${swf}.limit.${ews}.exceeded`,34,[[[18,55],[30,[0,365]]],[[],[159,[0,365],[0,699]]]]],
[819,`${swf}.limit.${ews}`,126,[[[18,55],[30,[0,367]]],[[],[87,[0,367],[0,701]]]]],
[820,`${swf}.${ros}`,71,[[[30,59],[30,[0,822]]],[[30,60],[30,[0,823]]],[[],[30,[0,821]]]]],
[821,`${swf}.arithmeticMean.${ros}`,71,[[[18,55],[30,[0,407]]],[[],[160,[0,806],[0,407],[0,741]]]]],
[822,`${swf}.expectedValue.${ros}`,71,[[[18,55],[30,[0,407]]],[[],[161,[0,806],[0,407],[0,741]]]]],
[823,`${swf}.harmonicMean.${ros}`,71,[[[18,55],[30,[0,407]]],[[],[162,[0,806],[0,407],[0,741]]]]],
[824,`${sfe}.axis.eccentricity`,61,[[[],[163,[0,826]]]]],
[825,`${sfe}.axis.${ews}`,126,[[[13,61],[30,[0,807]]],[[],[30,[0,76]]]]],
[826,`${sfe}.axis.${lwr}`,61,[[[13,61],[30,[0,810]]],[[],[30,[0,82]]]]],
[827,`${sfe}.axis.major.${ros}`,71,[[[],[164,[0,861],[0,847]]]]],
[828,`${sfe}.axis.minor.${ros}`,71,[[[],[165,[0,827],[0,826]]]]],
[829,`${sfe}.axis.f.${ros}`,71,[[[],[166,[0,827]]]]],
[830,`${sfe}.axis.g.${ros}`,71,[[[],[167,[0,827],[0,847]]]]],
[831,`${sfe}.axis.h.${ros}`,71,[[[],[168,[0,828]]]]],
[832,`${sfe}.vector.fromHead`,40,[[[31,62],[30,[0,87]]],[[31,63],[18,[0,834],[0,888]]],[[31,64],[18,[0,833],[0,889]]],[[],[18,[0,833],[0,889]]]]],
[833,`${sfe}.vector.fromNorth`,40,[[[31,64],[30,[0,88]]],[[31,62],[19,[0,832],[0,889]]],[[31,63],[19,[0,834],[0,119]]],[[],[19,[0,834],[0,119]]]]],
[834,`${sfe}.vector.fromUpslope`,40,[[[31,63],[30,[0,89]]],[[31,62],[19,[0,832],[0,888]]],[[31,64],[18,[0,833],[0,119]]],[[],[18,[0,833],[0,119]]]]],
[835,`${sfe}.size.area`,54,[[[],[169,[0,836],[0,826]]]]],
[836,`${sfe}.size.length`,70,[[[],[170,[0,827],[0,86]]]]],
[837,`${sfe}.size.perimeter`,70,[[[],[171,[0,836],[0,838]]]]],
[838,`${sfe}.size.width`,70,[[[],[170,[0,828],[0,86]]]]],
[839,`${sfe}.map.area`,106,[[[],[172,[0,835],[0,97]]]]],
[840,`${sfe}.map.length`,108,[[[],[21,[0,836],[0,97]]]]],
[841,`${sfe}.map.perimeter`,108,[[[],[21,[0,837],[0,97]]]]],
[842,`${sfe}.map.width`,108,[[[],[21,[0,838],[0,97]]]]],
[843,`${sfe}.back.spreadDistance`,70,[[[],[170,[0,847],[0,86]]]]],
[844,`${sfe}.back.${fli}`,57,[[[],[173,[0,858],[0,861],[0,847]]]]],
[845,`${sfe}.back.${fl}`,59,[[[],[17,[0,844]]]]],
[846,`${sfe}.back.mapDistance`,108,[[[],[21,[0,843],[0,97]]]]],
[847,`${sfe}.back.${ros}`,71,[[[],[174,[0,861],[0,824]]]]],
[848,`${sfe}.back.${sh}`,68,[[[],[100,[0,844],[0,890],[0,122]]]]],
[849,`${sfe}.back.treeMortality`,111,[[[],[175,[0,60],[0,59],[0,46],[0,42],[0,848]]]]],
[850,`${sfe}.flank.spreadDistance`,70,[[[],[170,[0,854],[0,86]]]]],
[851,`${sfe}.flank.${fli}`,57,[[[],[173,[0,858],[0,861],[0,854]]]]],
[852,`${sfe}.flank.${fl}`,59,[[[],[17,[0,851]]]]],
[853,`${sfe}.flank.mapDistance`,108,[[[],[21,[0,850],[0,97]]]]],
[854,`${sfe}.flank.${ros}`,71,[[[],[176,[0,828]]]]],
[855,`${sfe}.flank.${sh}`,68,[[[],[100,[0,851],[0,890],[0,122]]]]],
[856,`${sfe}.flank.treeMortality`,111,[[[],[175,[0,60],[0,59],[0,46],[0,42],[0,855]]]]],
[857,`${sfe}.head.spreadDistance`,70,[[[],[170,[0,861],[0,86]]]]],
[858,`${sfe}.head.${fli}`,57,[[[13,61],[30,[0,813]]],[[],[30,[0,77]]]]],
[859,`${sfe}.head.${fl}`,59,[[[13,61],[30,[0,814]]],[[],[30,[0,78]]]]],
[860,`${sfe}.head.mapDistance`,108,[[[],[21,[0,857],[0,97]]]]],
[861,`${sfe}.head.${ros}`,71,[[[13,61],[30,[0,820]]],[[],[30,[0,83]]]]],
[862,`${sfe}.head.${sh}`,68,[[[],[100,[0,858],[0,890],[0,122]]]]],
[863,`${sfe}.head.treeMortality`,111,[[[],[175,[0,60],[0,59],[0,46],[0,42],[0,862]]]]],
[864,`${sfe}.psi.spreadDistance`,70,[[[],[170,[0,868],[0,86]]]]],
[865,`${sfe}.psi.${fli}`,57,[[[],[173,[0,858],[0,861],[0,868]]]]],
[866,`${sfe}.psi.${fl}`,59,[[[],[17,[0,865]]]]],
[867,`${sfe}.psi.mapDistance`,108,[[[],[21,[0,864],[0,97]]]]],
[868,`${sfe}.psi.${ros}`,71,[[[],[177,[0,832],[0,829],[0,830],[0,831]]]]],
[869,`${sfe}.psi.${sh}`,68,[[[],[100,[0,865],[0,890],[0,122]]]]],
[870,`${sfe}.psi.treeMortality`,111,[[[],[175,[0,60],[0,59],[0,46],[0,42],[0,869]]]]],
[871,`${sfe}.beta5.spreadDistance`,70,[[[],[170,[0,875],[0,86]]]]],
[872,`${sfe}.beta5.${fli}`,57,[[[],[173,[0,858],[0,861],[0,882]]]]],
[873,`${sfe}.beta5.${fl}`,59,[[[],[17,[0,872]]]]],
[874,`${sfe}.beta5.mapDistance`,108,[[[],[21,[0,871],[0,97]]]]],
[875,`${sfe}.beta5.${ros}`,71,[[[],[30,[0,882]]]]],
[876,`${sfe}.beta5.${sh}`,68,[[[],[100,[0,872],[0,890],[0,122]]]]],
[877,`${sfe}.beta5.treeMortality`,111,[[[],[175,[0,60],[0,59],[0,46],[0,42],[0,876]]]]],
[878,`${sfe}.beta.spreadDistance`,70,[[[],[170,[0,882],[0,86]]]]],
[879,`${sfe}.beta.${fli}`,57,[[[],[173,[0,858],[0,861],[0,887]]]]],
[880,`${sfe}.beta.${fl}`,59,[[[],[17,[0,879]]]]],
[881,`${sfe}.beta.mapDistance`,108,[[[],[21,[0,878],[0,97]]]]],
[882,`${sfe}.beta.${ros}`,71,[[[],[178,[0,832],[0,861],[0,824]]]]],
[883,`${sfe}.beta.${sh}`,68,[[[],[100,[0,879],[0,890],[0,122]]]]],
[884,`${sfe}.beta.treeMortality`,111,[[[],[175,[0,60],[0,59],[0,46],[0,42],[0,883]]]]],
[885,`${sfe}.beta.theta`,40,[[[],[179,[0,832],[0,829],[0,830],[0,831]]]]],
[886,`${sfe}.beta.psi`,40,[[[],[180,[0,885],[0,829],[0,831]]]]],
[887,`${sfe}.beta.psiSpreadRate`,71,[[[],[177,[0,886],[0,829],[0,830],[0,831]]]]],
[888,`${sfe}.heading.fromUpslope`,40,[[[13,61],[30,[0,808]]],[[],[30,[0,79]]]]],
[889,`${sfe}.heading.fromNorth`,40,[[[],[19,[0,119],[0,888]]]]],
[890,`${sfe}.wind.speed.atMidflame`,126,[[[13,61],[30,[0,811]]],[[],[30,[0,136]]]]],
[891,`site.terrain.spotSourceLocation`,28,[[[],[2]]]],
[892,`site.terrain.ridgeValleyDistance`,69,[[[],[2]]]],
[893,`site.terrain.ridgeValleyElevation`,70,[[[],[2]]]],
[894,`${spotb}.firebrand.criticalCoverHeight`,124,[[[],[181,[0,895],[0,57]]]]],
[895,`${spotb}.firebrand.height`,124,[[[],[182,[0,900]]]]],
[896,`${spotb}.firebrand.drift`,69,[[[],[9,[1,16]]]]],
[897,`${spotb}.spotDistance.flatTerrain`,69,[[[],[183,[0,895],[0,894],[0,135]]]]],
[898,`${spotb}.spotDistance.flatTerrainWithDrift`,69,[[[],[184,[0,897],[0,896]]]]],
[899,`${spotb}.spotDistance.mountainTerrain`,69,[[[],[185,[0,898],[0,891],[0,892],[0,893]]]]],
[900,`${spotb}.flameHeight`,59,[[[],[2]]]],
[901,`${spotc}.firebrand.criticalCoverHeight`,124,[[[],[9,[1,16]]]]],
[902,`${spotc}.firebrand.height`,124,[[[],[186,[0,908]]]]],
[903,`${spotc}.firebrand.drift`,69,[[[],[187,[0,908]]]]],
[904,`${spotc}.spotDistance.flatTerrain`,69,[[[],[188,[0,908]]]]],
[905,`${spotc}.spotDistance.flatTerrainWithDrift`,69,[[[],[189,[0,908]]]]],
[906,`${spotc}.spotDistance.mountainTerrain`,69,[[[],[185,[0,905],[0,891],[0,892],[0,893]]]]],
[907,`${spotc}.${fli}`,57,[[[11,65],[30,[0,1214]]],[[],[190,[0,85]]]]],
[908,`${spotc}.firebrandObject`,116,[[[],[191,[0,46],[0,135],[0,907]]]]],
[909,`${spots}.firebrand.criticalCoverHeight`,124,[[[],[181,[0,911],[0,57]]]]],
[910,`${spots}.${fli}`,57,[[[15,61],[30,[0,813]]],[[],[30,[0,77]]]]],
[911,`${spots}.firebrand.height`,124,[[[],[192,[0,910],[0,135]]]]],
[912,`${spots}.firebrand.drift`,69,[[[],[193,[0,911],[0,135]]]]],
[913,`${spots}.spotDistance.flatTerrain`,69,[[[],[183,[0,911],[0,909],[0,135]]]]],
[914,`${spots}.spotDistance.flatTerrainWithDrift`,69,[[[],[184,[0,913],[0,912]]]]],
[915,`${spots}.spotDistance.mountainTerrain`,69,[[[],[185,[0,914],[0,891],[0,892],[0,893]]]]],
[916,`${spott}.firebrand.criticalCoverHeight`,124,[[[],[181,[0,917],[0,57]]]]],
[917,`${spott}.firebrand.height`,124,[[[],[194,[0,923],[0,926],[0,927]]]]],
[918,`${spott}.firebrand.drift`,69,[[[],[9,[1,16]]]]],
[919,`${spott}.spotDistance.flatTerrain`,69,[[[],[183,[0,917],[0,916],[0,135]]]]],
[920,`${spott}.spotDistance.flatTerrainWithDrift`,69,[[[],[184,[0,919],[0,918]]]]],
[921,`${spott}.spotDistance.mountainTerrain`,69,[[[],[185,[0,920],[0,891],[0,892],[0,893]]]]],
[922,`${spott}.species`,29,[[[],[2]]]],
[923,`${spott}.height`,124,[[[],[2]]]],
[924,`${spott}.dbh`,123,[[[],[2]]]],
[925,`${spott}.count`,122,[[[],[2]]]],
[926,`${spott}.flameHeight`,59,[[[],[195,[0,922],[0,924],[0,925]]]]],
[927,`${spott}.flameDuration`,58,[[[],[196,[0,922],[0,924],[0,925]]]]],
[928,`scorch.height`,68,[[[14,66],[100,[0,77],[0,136],[0,122]]],[[],[30,[0,817]]]]],
[929,`mortality.${sh}`,68,[[[16,66],[30,[0,84]]],[[],[30,[0,928]]]]],
[930,`mortality.rate`,111,[[[],[175,[0,60],[0,59],[0,46],[0,42],[0,929]]]]],
[931,`mortality.crownLengthScorched`,111,[[[],[197,[0,46],[0,42],[0,929]]]]],
[932,`mortality.crownVolumeScorched`,111,[[[],[198,[0,46],[0,42],[0,929]]]]],
[933,`${ccfbdp}1.${dens}`,92,[[[],[9,[1,20]]]]],
[934,`${ccfbdp}1.${heat}`,84,[[[],[9,[1,0]]]]],
[935,`${ccfbdp}1.${load}`,91,[[[],[9,[1,67]]]]],
[936,`${ccfbdp}1.${mois}`,88,[[[],[30,[0,111]]]]],
[937,`${ccfbdp}1.${savr}`,95,[[[],[9,[1,37]]]]],
[938,`${ccfbdp}1.${emc}`,83,[[[],[9,[1,26]]]]],
[939,`${ccfbdp}1.${tmc}`,99,[[[],[9,[1,28]]]]],
[940,`${ccfbdp}2.${dens}`,92,[[[],[9,[1,20]]]]],
[941,`${ccfbdp}2.${heat}`,84,[[[],[9,[1,0]]]]],
[942,`${ccfbdp}2.${load}`,91,[[[],[9,[1,68]]]]],
[943,`${ccfbdp}2.${mois}`,88,[[[],[30,[0,112]]]]],
[944,`${ccfbdp}2.${savr}`,95,[[[],[9,[1,32]]]]],
[945,`${ccfbdp}2.${emc}`,83,[[[],[9,[1,26]]]]],
[946,`${ccfbdp}2.${tmc}`,99,[[[],[9,[1,28]]]]],
[947,`${ccfbdp}3.${dens}`,92,[[[],[9,[1,20]]]]],
[948,`${ccfbdp}3.${heat}`,84,[[[],[9,[1,0]]]]],
[949,`${ccfbdp}3.${load}`,91,[[[],[9,[1,69]]]]],
[950,`${ccfbdp}3.${mois}`,88,[[[],[30,[0,113]]]]],
[951,`${ccfbdp}3.${savr}`,95,[[[],[9,[1,22]]]]],
[952,`${ccfbdp}3.${emc}`,83,[[[],[9,[1,26]]]]],
[953,`${ccfbdp}3.${tmc}`,99,[[[],[9,[1,28]]]]],
[954,`${ccfbdp}4.${dens}`,92,[[[],[9,[1,20]]]]],
[955,`${ccfbdp}4.${heat}`,84,[[[],[9,[1,0]]]]],
[956,`${ccfbdp}4.${load}`,91,[[[],[9,[1,16]]]]],
[957,`${ccfbdp}4.${mois}`,88,[[[],[30,[0,111]]]]],
[958,`${ccfbdp}4.${savr}`,95,[[[],[9,[1,70]]]]],
[959,`${ccfbdp}4.${emc}`,83,[[[],[9,[1,26]]]]],
[960,`${ccfbdp}4.${tmc}`,99,[[[],[9,[1,28]]]]],
[961,`${ccfbdp}5.${dens}`,92,[[[],[9,[1,20]]]]],
[962,`${ccfbdp}5.${heat}`,84,[[[],[9,[1,0]]]]],
[963,`${ccfbdp}5.${load}`,91,[[[],[9,[1,16]]]]],
[964,`${ccfbdp}5.${mois}`,88,[[[],[9,[1,35]]]]],
[965,`${ccfbdp}5.${savr}`,95,[[[],[9,[1,8]]]]],
[966,`${ccfbdp}5.${emc}`,83,[[[],[9,[1,26]]]]],
[967,`${ccfbdp}5.${tmc}`,99,[[[],[9,[1,28]]]]],
[968,`${ccfblp}1.${dens}`,92,[[[],[9,[1,20]]]]],
[969,`${ccfblp}1.${heat}`,84,[[[],[9,[1,0]]]]],
[970,`${ccfblp}1.${load}`,91,[[[],[9,[1,16]]]]],
[971,`${ccfblp}1.${mois}`,88,[[[],[30,[0,115]]]]],
[972,`${ccfblp}1.${savr}`,95,[[[],[9,[1,70]]]]],
[973,`${ccfblp}1.${emc}`,83,[[[],[9,[1,26]]]]],
[974,`${ccfblp}1.${tmc}`,99,[[[],[9,[1,28]]]]],
[975,`${ccfblp}2.${dens}`,92,[[[],[9,[1,20]]]]],
[976,`${ccfblp}2.${heat}`,84,[[[],[9,[1,0]]]]],
[977,`${ccfblp}2.${load}`,91,[[[],[9,[1,68]]]]],
[978,`${ccfblp}2.${mois}`,88,[[[],[30,[0,116]]]]],
[979,`${ccfblp}2.${savr}`,95,[[[],[9,[1,70]]]]],
[980,`${ccfblp}2.${emc}`,83,[[[],[9,[1,26]]]]],
[981,`${ccfblp}2.${tmc}`,99,[[[],[9,[1,28]]]]],
[982,`${ccfblp}3.${dens}`,92,[[[],[9,[1,20]]]]],
[983,`${ccfblp}3.${heat}`,84,[[[],[9,[1,0]]]]],
[984,`${ccfblp}3.${load}`,91,[[[],[9,[1,16]]]]],
[985,`${ccfblp}3.${mois}`,88,[[[],[9,[1,35]]]]],
[986,`${ccfblp}3.${savr}`,95,[[[],[9,[1,8]]]]],
[987,`${ccfblp}3.${emc}`,83,[[[],[9,[1,26]]]]],
[988,`${ccfblp}3.${tmc}`,99,[[[],[9,[1,28]]]]],
[989,`${ccfblp}4.${dens}`,92,[[[],[9,[1,20]]]]],
[990,`${ccfblp}4.${heat}`,84,[[[],[9,[1,0]]]]],
[991,`${ccfblp}4.${load}`,91,[[[],[9,[1,16]]]]],
[992,`${ccfblp}4.${mois}`,88,[[[],[9,[1,35]]]]],
[993,`${ccfblp}4.${savr}`,95,[[[],[9,[1,8]]]]],
[994,`${ccfblp}4.${emc}`,83,[[[],[9,[1,26]]]]],
[995,`${ccfblp}4.${tmc}`,99,[[[],[9,[1,28]]]]],
[996,`${ccfblp}5.${dens}`,92,[[[],[9,[1,20]]]]],
[997,`${ccfblp}5.${heat}`,84,[[[],[9,[1,0]]]]],
[998,`${ccfblp}5.${load}`,91,[[[],[9,[1,16]]]]],
[999,`${ccfblp}5.${mois}`,88,[[[],[9,[1,35]]]]],
[1000,`${ccfblp}5.${savr}`,95,[[[],[9,[1,8]]]]],
[1001,`${ccfblp}5.${emc}`,83,[[[],[9,[1,26]]]]],
[1002,`${ccfblp}5.${tmc}`,99,[[[],[9,[1,28]]]]],
[1003,`${ccfbdp}1.${ef}.${ehn}`,82,[[[],[44,[0,937]]]]],
[1004,`${ccfbdp}1.${ef}.${load}`,91,[[[],[45,[0,937],[0,935],[1,31]]]]],
[1005,`${ccfbdp}1.${qig}`,85,[[[],[46,[0,936],[0,1003]]]]],
[1006,`${ccfbdp}1.net.${load}`,91,[[[],[47,[0,935],[0,939]]]]],
[1007,`${ccfbdp}1.${sc}`,93,[[[],[48,[0,937]]]]],
[1008,`${ccfbdp}1.${sc}.${wf}`,125,[[[],[49,[0,1007],[0,1114]]]]],
[1009,`${ccfbdp}1.${sa}`,94,[[[],[50,[0,935],[0,937],[0,933]]]]],
[1010,`${ccfbdp}1.${sa}.${wf}`,125,[[[],[51,[0,1009],[0,1098]]]]],
[1011,`${ccfbdp}1.volume`,100,[[[],[52,[0,935],[0,933]]]]],
[1012,`${ccfbdp}1.${ef}.waterLoad`,91,[[[],[53,[0,1004],[0,936]]]]],
[1013,`${ccfbdp}2.${ef}.${ehn}`,82,[[[],[44,[0,944]]]]],
[1014,`${ccfbdp}2.${ef}.${load}`,91,[[[],[45,[0,944],[0,942],[1,31]]]]],
[1015,`${ccfbdp}2.${qig}`,85,[[[],[46,[0,943],[0,1013]]]]],
[1016,`${ccfbdp}2.net.${load}`,91,[[[],[47,[0,942],[0,946]]]]],
[1017,`${ccfbdp}2.${sc}`,93,[[[],[48,[0,944]]]]],
[1018,`${ccfbdp}2.${sc}.${wf}`,125,[[[],[49,[0,1017],[0,1114]]]]],
[1019,`${ccfbdp}2.${sa}`,94,[[[],[50,[0,942],[0,944],[0,940]]]]],
[1020,`${ccfbdp}2.${sa}.${wf}`,125,[[[],[51,[0,1019],[0,1098]]]]],
[1021,`${ccfbdp}2.volume`,100,[[[],[52,[0,942],[0,940]]]]],
[1022,`${ccfbdp}2.${ef}.waterLoad`,91,[[[],[53,[0,1014],[0,943]]]]],
[1023,`${ccfbdp}3.${ef}.${ehn}`,82,[[[],[44,[0,951]]]]],
[1024,`${ccfbdp}3.${ef}.${load}`,91,[[[],[45,[0,951],[0,949],[1,31]]]]],
[1025,`${ccfbdp}3.${qig}`,85,[[[],[46,[0,950],[0,1023]]]]],
[1026,`${ccfbdp}3.net.${load}`,91,[[[],[47,[0,949],[0,953]]]]],
[1027,`${ccfbdp}3.${sc}`,93,[[[],[48,[0,951]]]]],
[1028,`${ccfbdp}3.${sc}.${wf}`,125,[[[],[49,[0,1027],[0,1114]]]]],
[1029,`${ccfbdp}3.${sa}`,94,[[[],[50,[0,949],[0,951],[0,947]]]]],
[1030,`${ccfbdp}3.${sa}.${wf}`,125,[[[],[51,[0,1029],[0,1098]]]]],
[1031,`${ccfbdp}3.volume`,100,[[[],[52,[0,949],[0,947]]]]],
[1032,`${ccfbdp}3.${ef}.waterLoad`,91,[[[],[53,[0,1024],[0,950]]]]],
[1033,`${ccfbdp}4.${ef}.${ehn}`,82,[[[],[44,[0,958]]]]],
[1034,`${ccfbdp}4.${ef}.${load}`,91,[[[],[45,[0,958],[0,956],[1,31]]]]],
[1035,`${ccfbdp}4.${qig}`,85,[[[],[46,[0,957],[0,1033]]]]],
[1036,`${ccfbdp}4.net.${load}`,91,[[[],[47,[0,956],[0,960]]]]],
[1037,`${ccfbdp}4.${sc}`,93,[[[],[48,[0,958]]]]],
[1038,`${ccfbdp}4.${sc}.${wf}`,125,[[[],[49,[0,1037],[0,1114]]]]],
[1039,`${ccfbdp}4.${sa}`,94,[[[],[50,[0,956],[0,958],[0,954]]]]],
[1040,`${ccfbdp}4.${sa}.${wf}`,125,[[[],[51,[0,1039],[0,1098]]]]],
[1041,`${ccfbdp}4.volume`,100,[[[],[52,[0,956],[0,954]]]]],
[1042,`${ccfbdp}4.${ef}.waterLoad`,91,[[[],[53,[0,1034],[0,957]]]]],
[1043,`${ccfbdp}5.${ef}.${ehn}`,82,[[[],[44,[0,965]]]]],
[1044,`${ccfbdp}5.${ef}.${load}`,91,[[[],[45,[0,965],[0,963],[1,31]]]]],
[1045,`${ccfbdp}5.${qig}`,85,[[[],[46,[0,964],[0,1043]]]]],
[1046,`${ccfbdp}5.net.${load}`,91,[[[],[47,[0,963],[0,967]]]]],
[1047,`${ccfbdp}5.${sc}`,93,[[[],[48,[0,965]]]]],
[1048,`${ccfbdp}5.${sc}.${wf}`,125,[[[],[49,[0,1047],[0,1114]]]]],
[1049,`${ccfbdp}5.${sa}`,94,[[[],[50,[0,963],[0,965],[0,961]]]]],
[1050,`${ccfbdp}5.${sa}.${wf}`,125,[[[],[51,[0,1049],[0,1098]]]]],
[1051,`${ccfbdp}5.volume`,100,[[[],[52,[0,963],[0,961]]]]],
[1052,`${ccfbdp}5.${ef}.waterLoad`,91,[[[],[53,[0,1044],[0,964]]]]],
[1053,`${ccfblp}1.${ef}.${ehn}`,82,[[[],[44,[0,972]]]]],
[1054,`${ccfblp}1.${ef}.${load}`,91,[[[],[45,[0,972],[0,970],[1,41]]]]],
[1055,`${ccfblp}1.${qig}`,85,[[[],[46,[0,971],[0,1053]]]]],
[1056,`${ccfblp}1.net.${load}`,91,[[[],[47,[0,970],[0,974]]]]],
[1057,`${ccfblp}1.${sc}`,93,[[[],[48,[0,972]]]]],
[1058,`${ccfblp}1.${sc}.${wf}`,125,[[[],[49,[0,1057],[0,1134]]]]],
[1059,`${ccfblp}1.${sa}`,94,[[[],[50,[0,970],[0,972],[0,968]]]]],
[1060,`${ccfblp}1.${sa}.${wf}`,125,[[[],[51,[0,1059],[0,1118]]]]],
[1061,`${ccfblp}1.volume`,100,[[[],[52,[0,970],[0,968]]]]],
[1062,`${ccfblp}2.${ef}.${ehn}`,82,[[[],[44,[0,979]]]]],
[1063,`${ccfblp}2.${ef}.${load}`,91,[[[],[45,[0,979],[0,977],[1,41]]]]],
[1064,`${ccfblp}2.${qig}`,85,[[[],[46,[0,978],[0,1062]]]]],
[1065,`${ccfblp}2.net.${load}`,91,[[[],[47,[0,977],[0,981]]]]],
[1066,`${ccfblp}2.${sc}`,93,[[[],[48,[0,979]]]]],
[1067,`${ccfblp}2.${sc}.${wf}`,125,[[[],[49,[0,1066],[0,1134]]]]],
[1068,`${ccfblp}2.${sa}`,94,[[[],[50,[0,977],[0,979],[0,975]]]]],
[1069,`${ccfblp}2.${sa}.${wf}`,125,[[[],[51,[0,1068],[0,1118]]]]],
[1070,`${ccfblp}2.volume`,100,[[[],[52,[0,977],[0,975]]]]],
[1071,`${ccfblp}3.${ef}.${ehn}`,82,[[[],[44,[0,986]]]]],
[1072,`${ccfblp}3.${ef}.${load}`,91,[[[],[45,[0,986],[0,984],[1,41]]]]],
[1073,`${ccfblp}3.${qig}`,85,[[[],[46,[0,985],[0,1071]]]]],
[1074,`${ccfblp}3.net.${load}`,91,[[[],[47,[0,984],[0,988]]]]],
[1075,`${ccfblp}3.${sc}`,93,[[[],[48,[0,986]]]]],
[1076,`${ccfblp}3.${sc}.${wf}`,125,[[[],[49,[0,1075],[0,1134]]]]],
[1077,`${ccfblp}3.${sa}`,94,[[[],[50,[0,984],[0,986],[0,982]]]]],
[1078,`${ccfblp}3.${sa}.${wf}`,125,[[[],[51,[0,1077],[0,1118]]]]],
[1079,`${ccfblp}3.volume`,100,[[[],[52,[0,984],[0,982]]]]],
[1080,`${ccfblp}4.${ef}.${ehn}`,82,[[[],[44,[0,993]]]]],
[1081,`${ccfblp}4.${ef}.${load}`,91,[[[],[45,[0,993],[0,991],[1,41]]]]],
[1082,`${ccfblp}4.${qig}`,85,[[[],[46,[0,992],[0,1080]]]]],
[1083,`${ccfblp}4.net.${load}`,91,[[[],[47,[0,991],[0,995]]]]],
[1084,`${ccfblp}4.${sc}`,93,[[[],[48,[0,993]]]]],
[1085,`${ccfblp}4.${sc}.${wf}`,125,[[[],[49,[0,1084],[0,1134]]]]],
[1086,`${ccfblp}4.${sa}`,94,[[[],[50,[0,991],[0,993],[0,989]]]]],
[1087,`${ccfblp}4.${sa}.${wf}`,125,[[[],[51,[0,1086],[0,1118]]]]],
[1088,`${ccfblp}4.volume`,100,[[[],[52,[0,991],[0,989]]]]],
[1089,`${ccfblp}5.${ef}.${ehn}`,82,[[[],[44,[0,1000]]]]],
[1090,`${ccfblp}5.${ef}.${load}`,91,[[[],[45,[0,1000],[0,998],[1,41]]]]],
[1091,`${ccfblp}5.${qig}`,85,[[[],[46,[0,999],[0,1089]]]]],
[1092,`${ccfblp}5.net.${load}`,91,[[[],[47,[0,998],[0,1002]]]]],
[1093,`${ccfblp}5.${sc}`,93,[[[],[48,[0,1000]]]]],
[1094,`${ccfblp}5.${sc}.${wf}`,125,[[[],[49,[0,1093],[0,1134]]]]],
[1095,`${ccfblp}5.${sa}`,94,[[[],[50,[0,998],[0,1000],[0,996]]]]],
[1096,`${ccfblp}5.${sa}.${wf}`,125,[[[],[51,[0,1095],[0,1118]]]]],
[1097,`${ccfblp}5.volume`,100,[[[],[52,[0,998],[0,996]]]]],
[1098,`${ccfbd}.${sa}`,94,[[[],[54,[0,1009],[0,1019],[0,1029],[0,1039],[0,1049]]]]],
[1099,`${ccfbd}.${sa}.${wf}`,125,[[[],[21,[0,1098],[0,1153]]]]],
[1100,`${ccfbd}.mineralDamping`,55,[[[],[55,[0,1113]]]]],
[1101,`${ccfbd}.moistureDamping`,55,[[[],[56,[0,1107],[0,1105]]]]],
[1102,`${ccfbd}.${heat}`,84,[[[],[57,[0,1010],[0,1020],[0,1030],[0,1040],[0,1050],[0,934],[0,941],[0,948],[0,955],[0,962]]]]],
[1103,`${ccfbd}.${load}`,91,[[[],[54,[0,935],[0,942],[0,949],[0,956],[0,963]]]]],
[1104,`${ccfbd}.${ef}.${load}`,91,[[[],[54,[0,1004],[0,1014],[0,1024],[0,1034],[0,1044]]]]],
[1105,`${ccfbd}.extinction.${mois}`,88,[[[],[9,[1,47]]]]],
[1106,`${ccfbd}.extinction.${mois}Factor`,37,[[[],[58,[0,1104],[0,1124]]]]],
[1107,`${ccfbd}.${mois}`,88,[[[],[57,[0,1010],[0,1020],[0,1030],[0,1040],[0,1050],[0,936],[0,943],[0,950],[0,957],[0,964]]]]],
[1108,`${ccfbd}.volume`,75,[[[],[54,[0,1011],[0,1021],[0,1031],[0,1041],[0,1051]]]]],
[1109,`${ccfbd}.${qig}`,85,[[[],[57,[0,1010],[0,1020],[0,1030],[0,1040],[0,1050],[0,1005],[0,1015],[0,1025],[0,1035],[0,1045]]]]],
[1110,`${ccfbd}.${rxi}`,65,[[[],[22,[0,1111],[0,1101]]]]],
[1111,`${ccfbd}.${rxi}Dry`,65,[[[],[59,[0,1150],[0,1115],[0,1102],[0,1100]]]]],
[1112,`${ccfbd}.${savr}`,95,[[[],[57,[0,1010],[0,1020],[0,1030],[0,1040],[0,1050],[0,937],[0,944],[0,951],[0,958],[0,965]]]]],
[1113,`${ccfbd}.${emc}`,83,[[[],[57,[0,1010],[0,1020],[0,1030],[0,1040],[0,1050],[0,938],[0,945],[0,952],[0,959],[0,966]]]]],
[1114,`${ccfbd}.${sc}.${wf}`,125,[[[],[60,[0,1009],[0,1007],[0,1019],[0,1017],[0,1029],[0,1027],[0,1039],[0,1037],[0,1049],[0,1047]]]]],
[1115,`${ccfbd}.net.${load}`,91,[[[],[57,[0,1008],[0,1018],[0,1028],[0,1038],[0,1048],[0,1006],[0,1016],[0,1026],[0,1036],[0,1046]]]]],
[1116,`${ccfbd}.${ef}.waterLoad`,91,[[[],[54,[0,1012],[0,1022],[0,1032],[0,1042],[0,1052]]]]],
[1117,`${ccfbd}.${ef}.${mois}`,88,[[[],[21,[0,1116],[0,1104]]]]],
[1118,`${ccfbl}.${sa}`,94,[[[],[54,[0,1059],[0,1068],[0,1077],[0,1086],[0,1095]]]]],
[1119,`${ccfbl}.${sa}.${wf}`,125,[[[],[21,[0,1118],[0,1153]]]]],
[1120,`${ccfbl}.mineralDamping`,55,[[[],[55,[0,1133]]]]],
[1121,`${ccfbl}.moistureDamping`,55,[[[],[56,[0,1127],[0,1125]]]]],
[1122,`${ccfbl}.${heat}`,84,[[[],[57,[0,1060],[0,1069],[0,1078],[0,1087],[0,1096],[0,969],[0,976],[0,983],[0,990],[0,997]]]]],
[1123,`${ccfbl}.${load}`,91,[[[],[54,[0,970],[0,977],[0,984],[0,991],[0,998]]]]],
[1124,`${ccfbl}.${ef}.${load}`,91,[[[],[54,[0,1054],[0,1063],[0,1072],[0,1081],[0,1090]]]]],
[1125,`${ccfbl}.extinction.${mois}`,88,[[[],[61,[0,1126],[0,1117],[0,1105]]]]],
[1126,`${ccfbl}.extinction.${mois}Factor`,37,[[[],[58,[0,1104],[0,1124]]]]],
[1127,`${ccfbl}.${mois}`,88,[[[],[57,[0,1060],[0,1069],[0,1078],[0,1087],[0,1096],[0,971],[0,978],[0,985],[0,992],[0,999]]]]],
[1128,`${ccfbl}.volume`,75,[[[],[54,[0,1061],[0,1070],[0,1079],[0,1088],[0,1097]]]]],
[1129,`${ccfbl}.${qig}`,85,[[[],[57,[0,1060],[0,1069],[0,1078],[0,1087],[0,1096],[0,1055],[0,1064],[0,1073],[0,1082],[0,1091]]]]],
[1130,`${ccfbl}.${rxi}`,65,[[[],[22,[0,1131],[0,1121]]]]],
[1131,`${ccfbl}.${rxi}Dry`,65,[[[],[59,[0,1150],[0,1135],[0,1122],[0,1120]]]]],
[1132,`${ccfbl}.${savr}`,95,[[[],[57,[0,1060],[0,1069],[0,1078],[0,1087],[0,1096],[0,972],[0,979],[0,986],[0,993],[0,1000]]]]],
[1133,`${ccfbl}.${emc}`,83,[[[],[57,[0,1060],[0,1069],[0,1078],[0,1087],[0,1096],[0,973],[0,980],[0,987],[0,994],[0,1001]]]]],
[1134,`${ccfbl}.${sc}.${wf}`,125,[[[],[60,[0,1059],[0,1057],[0,1068],[0,1066],[0,1077],[0,1075],[0,1086],[0,1084],[0,1095],[0,1093]]]]],
[1135,`${ccfbl}.net.${load}`,91,[[[],[57,[0,1058],[0,1067],[0,1076],[0,1085],[0,1094],[0,1056],[0,1065],[0,1074],[0,1083],[0,1092]]]]],
[1136,`${ccfb}.depth`,75,[[[],[9,[1,8]]]]],
[1137,`${ccfb}.bulkDensity`,74,[[[],[21,[0,1141],[0,1136]]]]],
[1138,`${ccfb}.${qig}`,76,[[[],[57,[0,1099],[0,1119],[0,1109],[0,1129]]]]],
[1139,`${ccfb}.heatSink`,86,[[[],[62,[0,1138],[0,1137]]]]],
[1140,`${ccfb}.noWindNoSlope.${ros}`,71,[[[],[63,[0,1147],[0,1146],[0,1139]]]]],
[1141,`${ccfb}.${load}`,91,[[[],[54,[0,1103],[0,1123]]]]],
[1142,`${ccfb}.open.${waf}`,127,[[[],[64,[0,1136]]]]],
[1143,`${ccfb}.packingRatio`,77,[[[],[65,[0,1108],[0,1128],[0,1136]]]]],
[1144,`${ccfb}.packingRatio.optimum`,77,[[[],[66,[0,1151]]]]],
[1145,`${ccfb}.packingRatio.ratio`,77,[[[],[21,[0,1143],[0,1144]]]]],
[1146,`${ccfb}.propagatingFluxRatio`,64,[[[],[67,[0,1151],[0,1143]]]]],
[1147,`${ccfb}.${rxi}`,65,[[[],[54,[0,1110],[0,1130]]]]],
[1148,`${ccfb}.reactionVelocityExponent`,37,[[[],[68,[0,1151]]]]],
[1149,`${ccfb}.reactionVelocityMaximum`,66,[[[],[69,[0,1152]]]]],
[1150,`${ccfb}.reactionVelocityOptimum`,66,[[[],[70,[0,1145],[0,1149],[0,1148]]]]],
[1151,`${ccfb}.${savr}`,95,[[[],[57,[0,1099],[0,1119],[0,1112],[0,1132]]]]],
[1152,`${ccfb}.savr15`,37,[[[],[71,[0,1151]]]]],
[1153,`${ccfb}.${sa}`,94,[[[],[54,[0,1098],[0,1118]]]]],
[1154,`${ccff}.maximumDirection.slope.${ros}`,71,[[[],[72,[0,1203],[0,1167]]]]],
[1155,`${ccff}.maximumDirection.wind.${ros}`,71,[[[],[73,[0,1203],[0,1190]]]]],
[1156,`${ccff}.wind.heading.fromUpslope`,40,[[[],[9,[1,16]]]]],
[1157,`${ccff}.maximumDirection.xComponent`,37,[[[],[74,[0,1155],[0,1154],[0,1156]]]]],
[1158,`${ccff}.maximumDirection.yComponent`,37,[[[],[75,[0,1155],[0,1156]]]]],
[1159,`${ccff}.maximumDirection.${ros}`,71,[[[],[76,[0,1157],[0,1158]]]]],
[1160,`${ccff}.limit.${ews}.exceeded`,34,[[[],[77,[0,1171],[0,1162]]]]],
[1161,`${ccff}.limit.${ros}.exceeded`,35,[[[],[77,[0,1173],[0,1179]]]]],
[1162,`${ccff}.limit.${ews}`,126,[[[],[78,[0,1200]]]]],
[1163,`${ccff}.limit.windSlopeSpreadRateCoefficient`,37,[[[],[79,[0,1162],[0,1185],[0,1188]]]]],
[1164,`${ccff}.limit.${ros}`,71,[[[],[80,[0,1203],[0,1163]]]]],
[1165,`${ccff}.slope.ratio`,115,[[[],[9,[1,16]]]]],
[1166,`${ccff}.slope.k`,37,[[[],[81,[0,1143]]]]],
[1167,`${ccff}.slope.phi`,37,[[[],[82,[0,1165],[0,1166]]]]],
[1168,`${ccff}.spread.step1.${ews}`,126,[[[],[83,[0,1169],[0,1185],[0,1189]]]]],
[1169,`${ccff}.spread.step1.${phiew}`,37,[[[],[84,[0,1190],[0,1167]]]]],
[1170,`${ccff}.spread.step1.${ros}`,71,[[[],[80,[0,1203],[0,1169]]]]],
[1171,`${ccff}.spread.step2.${ews}`,126,[[[],[83,[0,1172],[0,1185],[0,1189]]]]],
[1172,`${ccff}.spread.step2.${phiew}`,37,[[[],[85,[0,1203],[0,1173]]]]],
[1173,`${ccff}.spread.step2.${ros}`,71,[[[],[86,[0,1203],[0,1159]]]]],
[1174,`${ccff}.spread.step3a.${ews}`,126,[[[],[87,[0,1171],[0,1162]]]]],
[1175,`${ccff}.spread.step3a.${phiew}`,37,[[[],[87,[0,1172],[0,1163]]]]],
[1176,`${ccff}.spread.step3a.${ros}`,71,[[[],[87,[0,1173],[0,1164]]]]],
[1177,`${ccff}.spread.step3b.${ews}`,126,[[[],[83,[0,1178],[0,1185],[0,1189]]]]],
[1178,`${ccff}.spread.step3b.${phiew}`,37,[[[],[85,[0,1203],[0,1179]]]]],
[1179,`${ccff}.spread.step3b.${ros}`,71,[[[],[88,[0,1173],[0,1171]]]]],
[1180,`${ccff}.spread.step4.${ews}`,126,[[[],[83,[0,1181],[0,1185],[0,1189]]]]],
[1181,`${ccff}.spread.step4.${phiew}`,37,[[[],[85,[0,1203],[0,1182]]]]],
[1182,`${ccff}.spread.step4.${ros}`,71,[[[],[88,[0,1176],[0,1174]]]]],
[1183,`${ccff}.${waf}`,127,[[[],[9,[1,46]]]]],
[1184,`${ccff}.wind.speed.atMidflame`,126,[[[26,19],[30,[0,136]]],[[],[42,[0,135],[0,1183]]]]],
[1185,`${ccff}.wind.factor.b`,37,[[[],[90,[0,1151]]]]],
[1186,`${ccff}.wind.factor.c`,37,[[[],[91,[0,1151]]]]],
[1187,`${ccff}.wind.factor.e`,37,[[[],[92,[0,1151]]]]],
[1188,`${ccff}.wind.factor.k`,37,[[[],[93,[0,1145],[0,1187],[0,1186]]]]],
[1189,`${ccff}.wind.factor.i`,37,[[[],[94,[0,1145],[0,1187],[0,1186]]]]],
[1190,`${ccff}.wind.phi`,37,[[[],[95,[0,1184],[0,1185],[0,1188]]]]],
[1191,`${ccff}.${ews}`,126,[[[29,49],[30,[0,1180]]],[[],[30,[0,1177]]]]],
[1192,`${ccff}.${fli}`,57,[[[],[96,[0,1202],[0,1200],[0,1194]]]]],
[1193,`${ccff}.${fl}`,59,[[[],[17,[0,1192]]]]],
[1194,`${ccff}.${taur}`,67,[[[],[97,[0,1151]]]]],
[1195,`${ccff}.heading.fromUpslope`,40,[[[],[98,[0,1157],[0,1158],[0,1159]]]]],
[1196,`${ccff}.heading.fromNorth`,40,[[[],[19,[0,119],[0,1195]]]]],
[1197,`${ccff}.${hpua}`,60,[[[],[99,[0,1200],[0,1194]]]]],
[1198,`${ccff}.${lwr}`,61,[[[],[20,[0,1191]]]]],
[1199,`${ccff}.${phiew}`,37,[[[29,49],[30,[0,1181]]],[[],[30,[0,1178]]]]],
[1200,`${ccff}.${rxi}`,65,[[[],[30,[0,1147]]]]],
[1201,`${ccff}.${sh}`,68,[[[],[100,[0,1192],[0,1184],[0,122]]]]],
[1202,`${ccff}.${ros}`,71,[[[29,49],[30,[0,1182]]],[[],[30,[0,1179]]]]],
[1203,`${ccff}.noWindNoSlope.${ros}`,71,[[[],[30,[0,1140]]]]],
[1204,`${cfa}.size.area`,54,[[[],[199,[0,1205],[0,1212]]]]],
[1205,`${cfa}.size.length`,70,[[[],[170,[0,1213],[0,86]]]]],
[1206,`${cfa}.size.perimeter`,70,[[[],[200,[0,1205],[0,1212]]]]],
[1207,`${cfa}.size.width`,70,[[[],[21,[0,1205],[0,1212]]]]],
[1208,`${cfa}.map.area`,106,[[[],[172,[0,1204],[0,97]]]]],
[1209,`${cfa}.map.length`,108,[[[],[21,[0,1205],[0,97]]]]],
[1210,`${cfa}.map.perimeter`,108,[[[],[21,[0,1206],[0,97]]]]],
[1211,`${cfa}.map.width`,108,[[[],[21,[0,1207],[0,97]]]]],
[1212,`${cfa}.${lwr}`,61,[[[],[201,[0,135]]]]],
[1213,`${cfa}.${ros}`,71,[[[],[202,[0,1202]]]]],
[1214,`${cfa}.${fli}`,57,[[[],[203,[0,1216],[0,1213]]]]],
[1215,`${cfa}.${fl}`,59,[[[],[204,[0,1214]]]]],
[1216,`${cfa}.${hpua}`,60,[[[],[205,[0,47],[0,1252]]]]],
[1217,`${cfa}.powerOfTheFire`,62,[[[],[206,[0,1214]]]]],
[1218,`${cfa}.powerOfTheWind`,62,[[[],[207,[0,135],[0,1213]]]]],
[1219,`${cfa}.powerRatio`,63,[[[],[21,[0,1217],[0,1218]]]]],
[1220,`${cfa}.isPlumeDominated`,32,[[[],[208,[0,1219]]]]],
[1221,`${cfa}.isWindDriven`,32,[[[],[209,[0,1219]]]]],
[1222,`${cff}.size.area`,54,[[[],[199,[0,1223],[0,1212]]]]],
[1223,`${cff}.size.length`,70,[[[],[170,[0,1232],[0,86]]]]],
[1224,`${cff}.size.perimeter`,70,[[[],[200,[0,1223],[0,1212]]]]],
[1225,`${cff}.size.width`,70,[[[],[21,[0,1223],[0,1212]]]]],
[1226,`${cff}.map.area`,106,[[[],[172,[0,1222],[0,97]]]]],
[1227,`${cff}.map.length`,108,[[[],[21,[0,1223],[0,97]]]]],
[1228,`${cff}.map.perimeter`,108,[[[],[21,[0,1224],[0,97]]]]],
[1229,`${cff}.map.width`,108,[[[],[21,[0,1225],[0,97]]]]],
[1230,`${cff}.rSa`,71,[[[],[210,[0,1248],[0,345],[0,388],[0,390],[0,393],[0,372]]]]],
[1231,`${cff}.crownFractionBurned`,43,[[[],[211,[0,407],[0,1237],[0,1230]]]]],
[1232,`${cff}.${ros}`,71,[[[],[212,[0,407],[0,1213],[0,1231]]]]],
[1233,`${cff}.${fli}`,57,[[[],[213,[0,1232],[0,1231],[0,47],[0,1252]]]]],
[1234,`${cff}.${fl}`,57,[[[],[204,[0,1233]]]]],
[1235,`${cfi}.${fli}`,57,[[[],[214,[0,49],[0,42]]]]],
[1236,`${cfi}.${fl}`,59,[[[],[17,[0,1235]]]]],
[1237,`${cfi}.${ros}`,71,[[[],[215,[0,1235],[0,1252]]]]],
[1238,`${cfi}.rPrime`,71,[[[],[216,[0,48]]]]],
[1239,`${cfi}.transitionRatio`,45,[[[],[217,[0,1250],[0,1235]]]]],
[1240,`${cfi}.canTransition`,32,[[[],[218,[0,1239]]]]],
[1241,`${cfi}.activeRatio`,42,[[[],[219,[0,1213],[0,1238]]]]],
[1242,`${cfi}.type`,21,[[[],[220,[0,1239],[0,1241]]]]],
[1243,`${cfi}.isActiveCrownFire`,32,[[[],[221,[0,1239],[0,1241]]]]],
[1244,`${cfi}.isCrownFire`,32,[[[],[222,[0,1239],[0,1241]]]]],
[1245,`${cfi}.isPassiveCrownFire`,32,[[[],[223,[0,1239],[0,1241]]]]],
[1246,`${cfi}.isConditionalCrownFire`,32,[[[],[224,[0,1239],[0,1241]]]]],
[1247,`${cfi}.isSurfaceFire`,32,[[[],[225,[0,1239],[0,1241]]]]],
[1248,`${cfi}.oActive`,126,[[[],[226,[0,48],[0,1200],[0,1139],[0,1167]]]]],
[1249,`${cfi}.crowningIndex`,37,[[[],[227,[0,1248]]]]],
[1250,`crown.fire.surface.${fli}`,57,[[[10,61],[30,[0,813]]],[[],[30,[0,77]]]]],
[1251,`crown.fire.surface.${fl}`,59,[[[10,61],[30,[0,814]]],[[],[30,[0,78]]]]],
[1252,`crown.fire.surface.${hpua}`,60,[[[10,61],[30,[0,815]]],[[],[30,[0,81]]]]],
]
}
