// autogenerated by GenomeCompiler.js on 4/18/2021, 6:29:11 PM
// Gene key abbreviations
const spfbdp = 'surface.primary.fuel.bed.dead.particle.class'
const spfblp = 'surface.primary.fuel.bed.live.particle.class'
const ssfbdp = 'surface.secondary.fuel.bed.dead.particle.class'
const ssfblp = 'surface.secondary.fuel.bed.live.particle.class'
const ccfbdp = 'crown.canopy.fuel.bed.dead.particle.class'
const ccfblp = 'crown.canopy.fuel.bed.live.particle.class'
const spfbd = 'surface.primary.fuel.bed.dead'
const spfbl = 'surface.primary.fuel.bed.live'
const spff = 'surface.primary.fuel.fire'
const ssfbd = 'surface.secondary.fuel.bed.dead'
const ssfbl = 'surface.secondary.fuel.bed.live'
const ssff = 'surface.secondary.fuel.fire'
const ccfbd = 'crown.canopy.fuel.bed.dead'
const ccfbl = 'crown.canopy.fuel.bed.live'
const ccff = 'crown.canopy.fuel.fire'
const spfb = 'surface.primary.fuel.bed'
const ssfb = 'surface.secondary.fuel.bed'
const ccfb = 'crown.canopy.fuel.bed'
const cfa = 'crown.fire.active'
const cff = 'crown.fire.final'
const cfi = 'crown.fire.initiation'
const spf = 'surface.primary.fuel'
const ssf = 'surface.secondary.fuel'
const mbd = 'model.behave.derived'
const mbp = 'model.behave.parms'
const mcd = 'model.chaparral.derived'
const mcp = 'model.chaparral.parms'
const mpd = 'model.palmettoGallberry.derived'
const mpp = 'model.palmettoGallberry.parms'
const mwd = 'model.westernAspen.derived'
const mwp = 'model.westernAspen.parms'
const sfe = 'surface.fire.ellipse'
const swf = 'surface.weighted.fire'
const spotb = 'spotting.burningPile'
const spotc = 'spotting.crownFire'
const spots = 'spotting.surfaceFire'
const spott = 'spotting.torchingTrees'
const savr = 'surfaceAreaToVolumeRatio'
const emc = 'effective.mineralContent'
const tmc = 'total.mineralContent'
const heat = 'heatOfCombustion'
const ef = 'effectiveFuel'
const sa = 'surfaceArea'
const sc = 'sizeClass'
const wf = 'weightingFactor'
const qig = 'heatOfPreignition'
const waf = 'windSpeedAdjustmentFactor'
const load = 'ovendryLoad'
const mois = 'moistureContent'
const fli = 'firelineIntensity'
const fl = 'flameLength'
const lwr = 'lengthToWidthRatio'
const ros = 'spreadRate'
const rxi = 'reactionIntensity'
const sh = 'scorchHeight'
const hpua = 'heatPerUnitArea'
const phiew = 'phiEffectiveWind'
const taur = 'flameResidenceTime'
const ews = 'effectiveWindSpeed'
const dens = 'fiberDensity'
const ehn = 'heatingNumber'

export const CompiledGenome = {
// Array of literals used by Gene updater config conditions and method parameters
literalArgsArray: [
8000, // 0
'lengthToWidthRatio', // 1
'flameLength', // 2
'firelineIntensity', // 3
'headingFromUpslope', // 4
'upslope', // 5
'sourceFromNorth', // 6
'effectiveWindSpeed', // 7
1, // 8
'category', // 9
'fosberg', // 10
'liveCategory', // 11
'degrees', // 12
'map', // 13
0, // 14
'at10m', // 15
'at20ft', // 16
'atMidflame', // 17
32, // 18
46, // 19
30, // 20
8300, // 21
640, // 22
350, // 23
0.01, // 24
0.015, // 25
0.0555, // 26
0.055, // 27
0.03, // 28
'dead', // 29
109, // 30
127, // 31
140, // 32
5, // 33
61, // 34
2000, // 35
27, // 36
10500, // 37
2800, // 38
'live', // 39
9550, // 40
2200, // 41
0.035, // 42
0.3, // 43
0.4, // 44
0.25, // 45
'input', // 46
'applied', // 47
'catalog', // 48
'behave', // 49
'chaparral', // 50
'palmettoGallberry', // 51
'westernAspen', // 52
'none', // 53
'estimated', // 54
'chamise', // 55
'aspenShrub', // 56
'expected', // 57
'harmonic', // 58
'linkedToSurfaceFire', // 59
'fromHead', // 60
'fromUpslope', // 61
'fromNorth', // 62
'linkedToCrownFire', // 63
'standAlone', // 64
0.138, // 65
0.092, // 66
0.23, // 67
1500, // 68
],
// Simple array of updater method <file>.<function> names
methodRefsArray: [
'Dag.module', // 0
'Dag.config', // 1
'Dag.input', // 2
'IgnitionProbability.firebrand', // 3
'IgnitionProbability.lightningStrike', // 4
'Canopy.crownFill', // 5
'Canopy.crownLength', // 6
'Canopy.crownRatio', // 7
'Canopy.heatPerUnitArea', // 8
'Dag.fixed', // 9
'Canopy.sheltersFuelFromWind', // 10
'Canopy.fuelLoad', // 11
'Canopy.windSpeedAdjustmentFactor', // 12
'Spotting.appliedDownWindCoverHeight', // 13
'TreeMortality.barkThickness', // 14
'SurfaceFire.effectiveWindSpeedFromLwr', // 15
'SurfaceFire.firelineIntensityFromFlameLength', // 16
'SurfaceFire.flameLength', // 17
'Compass.diff', // 18
'Compass.sum', // 19
'SurfaceFire.lengthToWidthRatio', // 20
'Calc.divide', // 21
'Calc.multiply', // 22
'Compass.slopeRatioMap', // 23
'Compass.slopeDegreesMap', // 24
'FuelMoisture.fosbergReference', // 25
'FuelMoisture.fosbergCorrection', // 26
'FuelMoisture.fosbergDead1h', // 27
'FuelMoisture.fosbergDead10h', // 28
'FuelMoisture.fosbergDead100h', // 29
'Dag.bind', // 30
'Compass.opposite', // 31
'Compass.slopeDegrees', // 32
'Compass.slopeRatio', // 33
'IgnitionProbability.fuelTemperature', // 34
'Wind.speedAt10m', // 35
'Wind.speedAt20ft', // 36
'Wind.speedAt20ftFromMidflame', // 37
'Wind.speedAtMidflame', // 38
'FuelParticle.selectByDomain', // 39
'FuelParticle.effectiveHeatingNumber', // 40
'FuelParticle.effectiveFuelLoad', // 41
'FuelParticle.heatOfPreignition', // 42
'FuelParticle.netOvendryLoad', // 43
'FuelParticle.sizeClass', // 44
'FuelParticle.sizeClassWeightingFactor', // 45
'FuelParticle.surfaceArea', // 46
'FuelParticle.surfaceAreaWeightingFactor', // 47
'FuelParticle.volume', // 48
'FuelParticle.effectiveFuelWaterLoad', // 49
'Calc.sum', // 50
'FuelBed.mineralDamping', // 51
'FuelBed.moistureDamping', // 52
'Calc.sumOfProducts', // 53
'FuelBed.extinctionMoistureContentFactor', // 54
'FuelBed.reactionIntensityDry', // 55
'FuelBed.sizeClassWeightingFactorArray', // 56
'FuelBed.extinctionMoistureContent', // 57
'FuelBed.heatSink', // 58
'FuelBed.noWindNoSlopeSpreadRate', // 59
'FuelBed.openWindSpeedAdjustmentFactor', // 60
'FuelBed.packingRatio', // 61
'FuelBed.optimumPackingRatio', // 62
'FuelBed.propagatingFluxRatio', // 63
'FuelBed.reactionVelocityExponent', // 64
'FuelBed.reactionVelocityMaximum', // 65
'FuelBed.reactionVelocityOptimum', // 66
'FuelBed.savr15', // 67
'SurfaceFire.maximumDirectionSlopeSpreadRate', // 68
'SurfaceFire.maximumDirectionWindSpreadRate', // 69
'SurfaceFire.maximumDirectionXComponent', // 70
'SurfaceFire.maximumDirectionYComponent', // 71
'SurfaceFire.maximumDirectionSpreadRate', // 72
'Calc.greaterThan', // 73
'SurfaceFire.effectiveWindSpeedLimit', // 74
'SurfaceFire.phiEwFromEws', // 75
'SurfaceFire.maximumSpreadRate', // 76
'FuelBed.slopeK', // 77
'SurfaceFire.phiSlope', // 78
'SurfaceFire.effectiveWindSpeed', // 79
'SurfaceFire.phiEffectiveWind', // 80
'SurfaceFire.phiEffectiveWindInferred', // 81
'SurfaceFire.spreadRateWithCrossSlopeWind', // 82
'Math.min', // 83
'SurfaceFire.spreadRateWithRosLimitApplied', // 84
'FuelBed.windSpeedAdjustmentFactor', // 85
'FuelBed.windB', // 86
'FuelBed.windC', // 87
'FuelBed.windE', // 88
'FuelBed.windK', // 89
'FuelBed.windI', // 90
'SurfaceFire.phiWind', // 91
'SurfaceFire.firelineIntensity', // 92
'FuelBed.taur', // 93
'SurfaceFire.spreadDirectionFromUpslope', // 94
'FuelBed.heatPerUnitArea', // 95
'SurfaceFire.scorchHeight', // 96
'FuelCatalog.domain', // 97
'BehaveFuel.curedHerbFraction', // 98
'FuelCatalog.behaveDepth', // 99
'FuelCatalog.behaveDeadMext', // 100
'FuelCatalog.behaveTotalHerbLoad', // 101
'FuelCatalog.behaveDead1Load', // 102
'FuelCatalog.behaveDead10Load', // 103
'FuelCatalog.behaveDead100Load', // 104
'FuelCatalog.behaveLiveStemLoad', // 105
'FuelCatalog.behaveDead1Savr', // 106
'FuelCatalog.behaveLiveHerbSavr', // 107
'FuelCatalog.behaveLiveStemSavr', // 108
'FuelCatalog.behaveDeadHeat', // 109
'FuelCatalog.behaveLiveHeat', // 110
'BehaveFuel.deadHerbLoad', // 111
'BehaveFuel.liveHerbLoad', // 112
'FuelCatalog.chaparralFuelType', // 113
'FuelCatalog.chaparralDeadFraction', // 114
'FuelCatalog.chaparralDepth', // 115
'FuelCatalog.chaparralTotalLoad', // 116
'ChaparralFuel.age', // 117
'ChaparralFuel.deadFractionAverageMortality', // 118
'ChaparralFuel.deadFractionSevereMortality', // 119
'ChaparralFuel.fuelDepth', // 120
'ChaparralFuel.totalLoad', // 121
'ChaparralFuel.deadLoad', // 122
'ChaparralFuel.deadClass1Load', // 123
'ChaparralFuel.deadClass2Load', // 124
'ChaparralFuel.deadClass3Load', // 125
'ChaparralFuel.deadClass4Load', // 126
'ChaparralFuel.liveLoad', // 127
'ChaparralFuel.liveClass1Load', // 128
'ChaparralFuel.liveClass2Load', // 129
'ChaparralFuel.liveClass3Load', // 130
'ChaparralFuel.liveClass4Load', // 131
'ChaparralFuel.liveClass5Load', // 132
'FuelCatalog.palmettoGallberryAge', // 133
'FuelCatalog.palmettoGallberryBasalArea', // 134
'FuelCatalog.palmettoGallberryCover', // 135
'FuelCatalog.palmettoGallberryHeight', // 136
'PalmettoGallberryFuel.fuelDepth', // 137
'PalmettoGallberryFuel.deadFineLoad', // 138
'PalmettoGallberryFuel.deadSmallLoad', // 139
'PalmettoGallberryFuel.deadFoliageLoad', // 140
'PalmettoGallberryFuel.deadLitterLoad', // 141
'PalmettoGallberryFuel.liveFineLoad', // 142
'PalmettoGallberryFuel.liveSmallLoad', // 143
'PalmettoGallberryFuel.liveFoliageLoad', // 144
'FuelCatalog.westernAspenFuelType', // 145
'FuelCatalog.westernAspenCuringLevel', // 146
'WesternAspenFuel.depth', // 147
'WesternAspenFuel.deadFineLoad', // 148
'WesternAspenFuel.deadSmallLoad', // 149
'WesternAspenFuel.deadFineSavr', // 150
'WesternAspenFuel.liveHerbLoad', // 151
'WesternAspenFuel.liveStemLoad', // 152
'WesternAspenFuel.liveStemSavr', // 153
'Math.max', // 154
'Calc.or', // 155
'SurfaceFire.arithmeticMeanSpreadRate', // 156
'SurfaceFire.expectedValueSpreadRateMOCK', // 157
'SurfaceFire.harmonicMeanSpreadRate', // 158
'FireEllipse.eccentricity', // 159
'FireEllipse.majorSpreadRate', // 160
'FireEllipse.minorSpreadRate', // 161
'FireEllipse.fSpreadRate', // 162
'FireEllipse.gSpreadRate', // 163
'FireEllipse.hSpreadRate', // 164
'FireEllipse.area', // 165
'FireEllipse.spreadDistance', // 166
'FireEllipse.perimeter', // 167
'FireEllipse.mapArea', // 168
'FireEllipse.fliAtAzimuth', // 169
'FireEllipse.backingSpreadRate', // 170
'TreeMortality.mortalityRate', // 171
'FireEllipse.flankingSpreadRate', // 172
'FireEllipse.psiSpreadRate', // 173
'FireEllipse.betaSpreadRate', // 174
'FireEllipse.thetaFromBeta', // 175
'FireEllipse.psiFromTheta', // 176
'Spotting.criticalCoverHeight', // 177
'Spotting.burningPileFirebrandHeight', // 178
'Spotting.distanceFlatTerrain', // 179
'Spotting.distanceFlatTerrainWithDrift', // 180
'Spotting.distanceMountainTerrain', // 181
'CrownSpotting.zdrop', // 182
'CrownSpotting.xdrift', // 183
'CrownSpotting.xdrop', // 184
'CrownSpotting.xspot', // 185
'CrownSpotting.firelineIntensityThomas', // 186
'CrownSpotting.flatDistance', // 187
'Spotting.surfaceFireFirebrandHeight', // 188
'Spotting.surfaceFireFirebrandDrift', // 189
'Spotting.torchingTreesFirebrandHeight', // 190
'Spotting.torchingTreesSteadyFlameHeight', // 191
'Spotting.torchingTreesSteadyFlameDuration', // 192
'TreeMortality.crownLengthScorched', // 193
'TreeMortality.crownVolumeScorched', // 194
'CrownFire.area', // 195
'CrownFire.perimeter', // 196
'CrownFire.lengthToWidthRatio', // 197
'CrownFire.rActive', // 198
'CrownFire.fliActive', // 199
'CrownFire.flameLengthThomas', // 200
'CrownFire.hpuaActive', // 201
'CrownFire.powerOfTheFire', // 202
'CrownFire.powerOfTheWind', // 203
'CrownFire.isPlumeDominated', // 204
'CrownFire.isWindDriven', // 205
'CrownFire.rSa', // 206
'CrownFire.crownFractionBurned', // 207
'CrownFire.rFinal', // 208
'CrownFire.fliFinal', // 209
'CrownFire.fliInit', // 210
'CrownFire.rInit', // 211
'CrownFire.rPrimeActive', // 212
'CrownFire.transitionRatio', // 213
'CrownFire.canTransition', // 214
'CrownFire.activeRatio', // 215
'CrownFire.type', // 216
'CrownFire.isActive', // 217
'CrownFire.isCrown', // 218
'CrownFire.isPassive', // 219
'CrownFire.isConditional', // 220
'CrownFire.isSurface', // 221
'CrownFire.oActive', // 222
'CrownFire.crowningIndex', // 223
],
// Array of Genes where each Gene is:
// [<geneIdx>, <geneKey>, <variantIdx>, [<valueUpdaters>]], where each valueUpdater is:
// [[<configIdx>, <configValue>], [methodIdx, ...<methodArgs>]], and where each methodArg is:
// [<0|1>, <geneIdx|literalIdx>]
genesArray: [
[0,`module.surfaceFire`,0,[[[],[0]]]],
[1,`module.surfaceSpot`,0,[[[],[0]]]],
[2,`module.crownFire`,0,[[[],[0]]]],
[3,`module.crownSpot`,0,[[[],[0]]]],
[4,`module.fireEllipse`,0,[[[],[0]]]],
[5,`module.fireContain`,0,[[[],[0]]]],
[6,`module.${sh}`,0,[[[],[0]]]],
[7,`module.treeMortality`,0,[[[],[0]]]],
[8,`module.spotting`,0,[[[],[0]]]],
[9,`module.ignitionProbability`,0,[[[],[0]]]],
[10,`link.crownFire`,4,[[[],[1]]]],
[11,`link.crownSpot`,1,[[[],[1]]]],
[12,`link.fireContain`,2,[[[],[1]]]],
[13,`link.fireEllipse`,4,[[[],[1]]]],
[14,`link.${sh}`,4,[[[],[1]]]],
[15,`link.surfaceSpot`,4,[[[],[1]]]],
[16,`link.treeMortality`,3,[[[],[1]]]],
[17,`configure.fuel.primary`,7,[[[],[1]]]],
[18,`configure.fuel.secondary`,8,[[[],[1]]]],
[19,`configure.fuel.moisture`,9,[[[],[1]]]],
[20,`configure.fuel.${waf}`,10,[[[],[1]]]],
[21,`configure.fuel.curedHerbFraction`,6,[[[],[1]]]],
[22,`configure.fuel.chaparralTotalLoad`,5,[[[],[1]]]],
[23,`configure.slope.steepness`,11,[[[],[1]]]],
[24,`configure.wind.direction`,12,[[[],[1]]]],
[25,`configure.wind.speed`,13,[[[],[1]]]],
[26,`configure.fire.${fli}`,14,[[[],[1]]]],
[27,`configure.fire.${lwr}`,15,[[[],[1]]]],
[28,`configure.fire.${ews}Limit`,16,[[[],[1]]]],
[29,`configure.fire.weightingMethod`,17,[[[],[1]]]],
[30,`configure.fire.vector`,18,[[[],[1]]]],
[31,`docs.run.mainTitle`,50,[[[],[2]]]],
[32,`docs.run.subTitle`,50,[[[],[2]]]],
[33,`docs.run.description`,50,[[[],[2]]]],
[34,`docs.run.userName`,50,[[[],[2]]]],
[35,`ignition.firebrand.probability`,102,[[[],[3,[0,124],[0,110]]]]],
[36,`ignition.lightningStrike.charge`,25,[[[],[2]]]],
[37,`ignition.lightningStrike.fuel.depth`,101,[[[],[2]]]],
[38,`ignition.lightningStrike.fuel.type`,24,[[[],[2]]]],
[39,`ignition.lightningStrike.probability`,102,[[[],[4,[0,38],[0,37],[0,112],[0,36]]]]],
[40,`site.canopy.cover`,77,[[[],[2]]]],
[41,`site.canopy.crown.baseHeight`,123,[[[],[2]]]],
[42,`site.canopy.crown.fill`,40,[[[],[5,[0,40],[0,44]]]]],
[43,`site.canopy.crown.length`,123,[[[],[6,[0,41],[0,45]]]]],
[44,`site.canopy.crown.ratio`,43,[[[],[7,[0,43],[0,45]]]]],
[45,`site.canopy.crown.totalHeight`,123,[[[],[2]]]],
[46,`site.canopy.fire.${hpua}`,59,[[[],[8,[0,51],[0,49]]]]],
[47,`site.canopy.fuel.bulkDensity`,73,[[[],[2]]]],
[48,`site.canopy.fuel.foliar.${mois}`,87,[[[],[2]]]],
[49,`site.canopy.fuel.${heat}`,83,[[[],[9,[1,0]]]]],
[50,`site.canopy.fuel.isSheltered`,35,[[[],[10,[0,40],[0,45],[0,42]]]]],
[51,`site.canopy.fuel.${load}`,90,[[[],[11,[0,47],[0,43]]]]],
[52,`site.canopy.fuel.shading`,77,[[[],[2]]]],
[53,`site.canopy.sheltered.${waf}`,126,[[[],[12,[0,40],[0,45],[0,42]]]]],
[54,`site.canopy.downwind.height`,123,[[[],[2]]]],
[55,`site.canopy.downwind.isOpen`,32,[[[],[2]]]],
[56,`site.canopy.downwind.appliedHeight`,123,[[[],[13,[0,54],[0,55]]]]],
[57,`site.canopy.tree.barkThickness`,120,[[[],[14,[0,59],[0,58]]]]],
[58,`site.canopy.tree.dbh`,122,[[[],[2]]]],
[59,`site.canopy.tree.species.fofem6.code`,29,[[[],[2]]]],
[60,`site.date.dayOfMonth`,45,[[[],[2]]]],
[61,`site.date.dayOfYear`,46,[[[],[2]]]],
[62,`site.date.julian`,47,[[[],[2]]]],
[63,`site.date.month`,48,[[[],[2]]]],
[64,`site.date.year`,49,[[[],[2]]]],
[65,`site.time.hour`,116,[[[],[2]]]],
[66,`site.time.minute`,117,[[[],[2]]]],
[67,`site.time.second`,118,[[[],[2]]]],
[68,`site.time.sunrise`,119,[[[],[2]]]],
[69,`site.time.sunset`,119,[[[],[2]]]],
[70,`site.doc.date`,50,[[[],[2]]]],
[71,`site.doc.id`,50,[[[],[2]]]],
[72,`site.doc.location`,50,[[[],[2]]]],
[73,`site.doc.station`,50,[[[],[2]]]],
[74,`site.doc.time`,50,[[[],[2]]]],
[75,`site.fire.observed.${ews}`,125,[[[27,1],[15,[0,81]]],[[],[2]]]],
[76,`site.fire.observed.${fli}`,56,[[[26,2],[16,[0,77]]],[[],[2]]]],
[77,`site.fire.observed.${fl}`,58,[[[26,3],[17,[0,76]]],[[],[2]]]],
[78,`site.fire.observed.heading.fromUpslope`,39,[[[24,4],[2]],[[24,5],[2]],[[],[18,[0,79],[0,118]]]]],
[79,`site.fire.observed.heading.fromNorth`,39,[[[24,6],[2]],[[],[19,[0,118],[0,78]]]]],
[80,`site.fire.observed.${hpua}`,59,[[[],[2]]]],
[81,`site.fire.observed.${lwr}`,60,[[[27,7],[20,[0,75]]],[[],[2]]]],
[82,`site.fire.observed.${ros}`,70,[[[],[2]]]],
[83,`site.fire.observed.${sh}`,67,[[[],[2]]]],
[84,`site.fire.crown.${fl}`,58,[[[],[2]]]],
[85,`site.fire.time.sinceIgnition`,55,[[[],[2]]]],
[86,`site.fire.vector.fromHead`,39,[[[],[2]]]],
[87,`site.fire.vector.fromNorth`,39,[[[],[2]]]],
[88,`site.fire.vector.fromUpslope`,39,[[[],[2]]]],
[89,`site.location.elevation`,51,[[[],[2]]]],
[90,`site.location.elevation.diff`,52,[[[],[2]]]],
[91,`site.location.gmtDiff`,100,[[[],[2]]]],
[92,`site.location.latitude.degrees`,103,[[[],[2]]]],
[93,`site.location.latitude.ns`,26,[[[],[2]]]],
[94,`site.location.longitude.degrees`,104,[[[],[2]]]],
[95,`site.location.longitude.ew`,21,[[[],[2]]]],
[96,`site.map.scale`,109,[[[],[2]]]],
[97,`site.map.contours`,106,[[[],[2]]]],
[98,`site.map.distance`,69,[[[],[2]]]],
[99,`site.map.factor`,108,[[[],[21,[1,8],[0,96]]]]],
[100,`site.map.interval`,69,[[[],[2]]]],
[101,`site.map.reach`,69,[[[],[22,[0,96],[0,98]]]]],
[102,`site.map.rise`,69,[[[],[22,[0,100],[0,97]]]]],
[103,`site.map.slope.ratio`,114,[[[],[23,[0,96],[0,100],[0,97],[0,98]]]]],
[104,`site.map.slope.degrees`,113,[[[],[24,[0,96],[0,100],[0,97],[0,98]]]]],
[105,`site.moisture.dead.fosberg.reference`,87,[[[],[25,[0,121],[0,125]]]]],
[106,`site.moisture.dead.fosberg.correction`,87,[[[],[26,[0,63],[0,126],[0,117],[0,120],[0,65],[0,90]]]]],
[107,`site.moisture.dead.fosberg.tl1h`,87,[[[],[27,[0,105],[0,106]]]]],
[108,`site.moisture.dead.fosberg.tl10h`,87,[[[],[28,[0,107]]]]],
[109,`site.moisture.dead.fosberg.tl100h`,87,[[[],[29,[0,107]]]]],
[110,`site.moisture.dead.tl1h`,87,[[[19,9],[30,[0,113]]],[[19,10],[30,[0,107]]],[[],[2]]]],
[111,`site.moisture.dead.tl10h`,87,[[[19,9],[30,[0,113]]],[[19,10],[30,[0,108]]],[[],[2]]]],
[112,`site.moisture.dead.tl100h`,87,[[[19,9],[30,[0,113]]],[[19,10],[30,[0,109]]],[[],[2]]]],
[113,`site.moisture.dead.category`,87,[[[],[2]]]],
[114,`site.moisture.live.herb`,87,[[[19,9],[30,[0,116]]],[[19,11],[30,[0,116]]],[[],[2]]]],
[115,`site.moisture.live.stem`,87,[[[19,9],[30,[0,116]]],[[19,11],[30,[0,116]]],[[],[2]]]],
[116,`site.moisture.live.category`,87,[[[],[2]]]],
[117,`site.slope.direction.aspect`,39,[[[],[2]]]],
[118,`site.slope.direction.upslope`,39,[[[],[31,[0,117]]]]],
[119,`site.slope.steepness.degrees`,113,[[[23,12],[2]],[[23,13],[30,[0,104]]],[[],[32,[0,120]]]]],
[120,`site.slope.steepness.ratio`,114,[[[23,12],[33,[0,119]]],[[23,13],[30,[0,103]]],[[],[2]]]],
[121,`site.temperature.air`,38,[[[],[2]]]],
[122,`site.temperature.dewPoint`,38,[[[],[2]]]],
[123,`site.temperature.dryBulb`,38,[[[],[2]]]],
[124,`site.temperature.fuel`,38,[[[],[34,[0,121],[0,52]]]]],
[125,`site.temperature.relativeHumidity`,111,[[[],[2]]]],
[126,`site.temperature.shading`,112,[[[],[2]]]],
[127,`site.temperature.wetBulb`,38,[[[],[2]]]],
[128,`site.temperature.wetBulbDepression`,38,[[[],[2]]]],
[129,`site.wind.direction.heading.fromUpslope`,39,[[[24,4],[2]],[[24,6],[18,[0,132],[0,118]]],[[24,5],[9,[1,14]]],[[],[9,[1,14]]]]],
[130,`site.wind.direction.source.fromUpslope`,39,[[[],[31,[0,129]]]]],
[131,`site.wind.direction.source.fromNorth`,39,[[[24,4],[31,[0,132]]],[[24,6],[2]],[[24,5],[31,[0,118]]],[[],[31,[0,118]]]]],
[132,`site.wind.direction.heading.fromNorth`,39,[[[24,4],[19,[0,129],[0,118]]],[[24,6],[31,[0,131]]],[[24,5],[30,[0,118]]],[[],[30,[0,118]]]]],
[133,`site.wind.speed.at10m`,125,[[[25,15],[2]],[[],[35,[0,134]]]]],
[134,`site.wind.speed.at20ft`,125,[[[25,16],[2]],[[25,15],[36,[0,133]]],[[],[37,[0,135],[0,136]]]]],
[135,`site.wind.speed.atMidflame`,125,[[[25,17],[2]],[[],[38,[0,134],[0,136]]]]],
[136,`site.${waf}`,126,[[[],[2]]]],
[137,`${spfbdp}1.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,20],[1,18]]]]],
[138,`${spfbdp}1.${heat}`,83,[[[],[39,[0,408],[0,422],[1,0],[1,21],[1,0]]]]],
[139,`${spfbdp}1.${load}`,90,[[[],[39,[0,408],[0,415],[0,438],[0,454],[0,465]]]]],
[140,`${spfbdp}1.${mois}`,87,[[[],[39,[0,408],[0,110],[0,110],[0,110],[0,110]]]]],
[141,`${spfbdp}1.${savr}`,94,[[[],[39,[0,408],[0,419],[1,22],[1,23],[0,467]]]]],
[142,`${spfbdp}1.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,24],[1,24]]]]],
[143,`${spfbdp}1.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[144,`${spfbdp}1.${ef}.${ehn}`,81,[[[],[40,[0,141]]]]],
[145,`${spfbdp}1.${ef}.${load}`,90,[[[],[41,[0,141],[0,139],[1,29]]]]],
[146,`${spfbdp}1.${qig}`,84,[[[],[42,[0,140],[0,144]]]]],
[147,`${spfbdp}1.net.${load}`,90,[[[],[43,[0,139],[0,143]]]]],
[148,`${spfbdp}1.${sc}`,92,[[[],[44,[0,141]]]]],
[149,`${spfbdp}1.${sc}.${wf}`,124,[[[],[45,[0,148],[0,318]]]]],
[150,`${spfbdp}1.${sa}`,93,[[[],[46,[0,139],[0,141],[0,137]]]]],
[151,`${spfbdp}1.${sa}.${wf}`,124,[[[],[47,[0,150],[0,302]]]]],
[152,`${spfbdp}1.volume`,99,[[[],[48,[0,139],[0,137]]]]],
[153,`${spfbdp}1.${ef}.waterLoad`,90,[[[],[49,[0,145],[0,140]]]]],
[154,`${spfbdp}2.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,20],[1,18]]]]],
[155,`${spfbdp}2.${heat}`,83,[[[],[39,[0,408],[0,422],[1,0],[1,21],[1,0]]]]],
[156,`${spfbdp}2.${load}`,90,[[[],[39,[0,408],[0,416],[0,439],[0,455],[0,466]]]]],
[157,`${spfbdp}2.${mois}`,87,[[[],[39,[0,408],[0,111],[0,111],[0,111],[0,111]]]]],
[158,`${spfbdp}2.${savr}`,94,[[[],[39,[0,408],[1,30],[1,31],[1,32],[1,30]]]]],
[159,`${spfbdp}2.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,24],[1,24]]]]],
[160,`${spfbdp}2.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[161,`${spfbdp}2.${ef}.${ehn}`,81,[[[],[40,[0,158]]]]],
[162,`${spfbdp}2.${ef}.${load}`,90,[[[],[41,[0,158],[0,156],[1,29]]]]],
[163,`${spfbdp}2.${qig}`,84,[[[],[42,[0,157],[0,161]]]]],
[164,`${spfbdp}2.net.${load}`,90,[[[],[43,[0,156],[0,160]]]]],
[165,`${spfbdp}2.${sc}`,92,[[[],[44,[0,158]]]]],
[166,`${spfbdp}2.${sc}.${wf}`,124,[[[],[45,[0,165],[0,318]]]]],
[167,`${spfbdp}2.${sa}`,93,[[[],[46,[0,156],[0,158],[0,154]]]]],
[168,`${spfbdp}2.${sa}.${wf}`,124,[[[],[47,[0,167],[0,302]]]]],
[169,`${spfbdp}2.volume`,99,[[[],[48,[0,156],[0,154]]]]],
[170,`${spfbdp}2.${ef}.waterLoad`,90,[[[],[49,[0,162],[0,157]]]]],
[171,`${spfbdp}3.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,20],[1,18]]]]],
[172,`${spfbdp}3.${heat}`,83,[[[],[39,[0,408],[0,422],[1,0],[1,21],[1,0]]]]],
[173,`${spfbdp}3.${load}`,90,[[[],[39,[0,408],[0,417],[0,440],[0,456],[1,14]]]]],
[174,`${spfbdp}3.${mois}`,87,[[[],[39,[0,408],[0,112],[0,111],[0,110],[1,33]]]]],
[175,`${spfbdp}3.${savr}`,94,[[[],[39,[0,408],[1,20],[1,34],[1,35],[1,8]]]]],
[176,`${spfbdp}3.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,24],[1,24]]]]],
[177,`${spfbdp}3.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[178,`${spfbdp}3.${ef}.${ehn}`,81,[[[],[40,[0,175]]]]],
[179,`${spfbdp}3.${ef}.${load}`,90,[[[],[41,[0,175],[0,173],[1,29]]]]],
[180,`${spfbdp}3.${qig}`,84,[[[],[42,[0,174],[0,178]]]]],
[181,`${spfbdp}3.net.${load}`,90,[[[],[43,[0,173],[0,177]]]]],
[182,`${spfbdp}3.${sc}`,92,[[[],[44,[0,175]]]]],
[183,`${spfbdp}3.${sc}.${wf}`,124,[[[],[45,[0,182],[0,318]]]]],
[184,`${spfbdp}3.${sa}`,93,[[[],[46,[0,173],[0,175],[0,171]]]]],
[185,`${spfbdp}3.${sa}.${wf}`,124,[[[],[47,[0,184],[0,302]]]]],
[186,`${spfbdp}3.volume`,99,[[[],[48,[0,173],[0,171]]]]],
[187,`${spfbdp}3.${ef}.waterLoad`,90,[[[],[49,[0,179],[0,174]]]]],
[188,`${spfbdp}4.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,20],[1,18]]]]],
[189,`${spfbdp}4.${heat}`,83,[[[],[39,[0,408],[0,422],[1,0],[1,21],[1,0]]]]],
[190,`${spfbdp}4.${load}`,90,[[[],[39,[0,408],[0,424],[0,441],[0,457],[1,14]]]]],
[191,`${spfbdp}4.${mois}`,87,[[[],[39,[0,408],[0,110],[0,112],[0,112],[1,33]]]]],
[192,`${spfbdp}4.${savr}`,94,[[[],[39,[0,408],[0,420],[1,36],[1,35],[1,8]]]]],
[193,`${spfbdp}4.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,24],[1,24]]]]],
[194,`${spfbdp}4.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[195,`${spfbdp}4.${ef}.${ehn}`,81,[[[],[40,[0,192]]]]],
[196,`${spfbdp}4.${ef}.${load}`,90,[[[],[41,[0,192],[0,190],[1,29]]]]],
[197,`${spfbdp}4.${qig}`,84,[[[],[42,[0,191],[0,195]]]]],
[198,`${spfbdp}4.net.${load}`,90,[[[],[43,[0,190],[0,194]]]]],
[199,`${spfbdp}4.${sc}`,92,[[[],[44,[0,192]]]]],
[200,`${spfbdp}4.${sc}.${wf}`,124,[[[],[45,[0,199],[0,318]]]]],
[201,`${spfbdp}4.${sa}`,93,[[[],[46,[0,190],[0,192],[0,188]]]]],
[202,`${spfbdp}4.${sa}.${wf}`,124,[[[],[47,[0,201],[0,302]]]]],
[203,`${spfbdp}4.volume`,99,[[[],[48,[0,190],[0,188]]]]],
[204,`${spfbdp}4.${ef}.waterLoad`,90,[[[],[49,[0,196],[0,191]]]]],
[205,`${spfbdp}5.${dens}`,91,[[[],[9,[1,18]]]]],
[206,`${spfbdp}5.${heat}`,83,[[[],[9,[1,0]]]]],
[207,`${spfbdp}5.${load}`,90,[[[],[9,[1,14]]]]],
[208,`${spfbdp}5.${mois}`,87,[[[],[9,[1,33]]]]],
[209,`${spfbdp}5.${savr}`,94,[[[],[9,[1,8]]]]],
[210,`${spfbdp}5.${emc}`,82,[[[],[9,[1,24]]]]],
[211,`${spfbdp}5.${tmc}`,98,[[[],[9,[1,26]]]]],
[212,`${spfbdp}5.${ef}.${ehn}`,81,[[[],[40,[0,209]]]]],
[213,`${spfbdp}5.${ef}.${load}`,90,[[[],[41,[0,209],[0,207],[1,29]]]]],
[214,`${spfbdp}5.${qig}`,84,[[[],[42,[0,208],[0,212]]]]],
[215,`${spfbdp}5.net.${load}`,90,[[[],[43,[0,207],[0,211]]]]],
[216,`${spfbdp}5.${sc}`,92,[[[],[44,[0,209]]]]],
[217,`${spfbdp}5.${sc}.${wf}`,124,[[[],[45,[0,216],[0,318]]]]],
[218,`${spfbdp}5.${sa}`,93,[[[],[46,[0,207],[0,209],[0,205]]]]],
[219,`${spfbdp}5.${sa}.${wf}`,124,[[[],[47,[0,218],[0,302]]]]],
[220,`${spfbdp}5.volume`,99,[[[],[48,[0,207],[0,205]]]]],
[221,`${spfbdp}5.${ef}.waterLoad`,90,[[[],[49,[0,213],[0,208]]]]],
[222,`${spfblp}1.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,19],[1,18]]]]],
[223,`${spfblp}1.${heat}`,83,[[[],[39,[0,408],[0,423],[1,37],[1,21],[1,0]]]]],
[224,`${spfblp}1.${load}`,90,[[[],[39,[0,408],[0,425],[0,443],[0,458],[0,468]]]]],
[225,`${spfblp}1.${mois}`,87,[[[],[39,[0,408],[0,114],[0,115],[0,115],[0,114]]]]],
[226,`${spfblp}1.${savr}`,94,[[[],[39,[0,408],[0,420],[1,22],[1,23],[1,38]]]]],
[227,`${spfblp}1.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,25],[1,24]]]]],
[228,`${spfblp}1.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[229,`${spfblp}1.${ef}.${ehn}`,81,[[[],[40,[0,226]]]]],
[230,`${spfblp}1.${ef}.${load}`,90,[[[],[41,[0,226],[0,224],[1,39]]]]],
[231,`${spfblp}1.${qig}`,84,[[[],[42,[0,225],[0,229]]]]],
[232,`${spfblp}1.net.${load}`,90,[[[],[43,[0,224],[0,228]]]]],
[233,`${spfblp}1.${sc}`,92,[[[],[44,[0,226]]]]],
[234,`${spfblp}1.${sc}.${wf}`,124,[[[],[45,[0,233],[0,338]]]]],
[235,`${spfblp}1.${sa}`,93,[[[],[46,[0,224],[0,226],[0,222]]]]],
[236,`${spfblp}1.${sa}.${wf}`,124,[[[],[47,[0,235],[0,322]]]]],
[237,`${spfblp}1.volume`,99,[[[],[48,[0,224],[0,222]]]]],
[238,`${spfblp}2.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,19],[1,18]]]]],
[239,`${spfblp}2.${heat}`,83,[[[],[39,[0,408],[0,423],[1,40],[1,21],[1,0]]]]],
[240,`${spfblp}2.${load}`,90,[[[],[39,[0,408],[0,418],[0,444],[0,459],[0,469]]]]],
[241,`${spfblp}2.${mois}`,87,[[[],[39,[0,408],[0,115],[0,115],[0,115],[0,115]]]]],
[242,`${spfblp}2.${savr}`,94,[[[],[39,[0,408],[0,421],[1,31],[1,32],[0,470]]]]],
[243,`${spfblp}2.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,25],[1,24]]]]],
[244,`${spfblp}2.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[245,`${spfblp}2.${ef}.${ehn}`,81,[[[],[40,[0,242]]]]],
[246,`${spfblp}2.${ef}.${load}`,90,[[[],[41,[0,242],[0,240],[1,39]]]]],
[247,`${spfblp}2.${qig}`,84,[[[],[42,[0,241],[0,245]]]]],
[248,`${spfblp}2.net.${load}`,90,[[[],[43,[0,240],[0,244]]]]],
[249,`${spfblp}2.${sc}`,92,[[[],[44,[0,242]]]]],
[250,`${spfblp}2.${sc}.${wf}`,124,[[[],[45,[0,249],[0,338]]]]],
[251,`${spfblp}2.${sa}`,93,[[[],[46,[0,240],[0,242],[0,238]]]]],
[252,`${spfblp}2.${sa}.${wf}`,124,[[[],[47,[0,251],[0,322]]]]],
[253,`${spfblp}2.volume`,99,[[[],[48,[0,240],[0,238]]]]],
[254,`${spfblp}3.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,19],[1,18]]]]],
[255,`${spfblp}3.${heat}`,83,[[[],[39,[0,408],[0,423],[1,40],[1,21],[1,0]]]]],
[256,`${spfblp}3.${load}`,90,[[[],[39,[0,408],[1,14],[0,445],[0,460],[1,14]]]]],
[257,`${spfblp}3.${mois}`,87,[[[],[39,[0,408],[1,33],[0,115],[0,115],[1,33]]]]],
[258,`${spfblp}3.${savr}`,94,[[[],[39,[0,408],[1,8],[1,34],[1,35],[1,8]]]]],
[259,`${spfblp}3.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,25],[1,24]]]]],
[260,`${spfblp}3.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[261,`${spfblp}3.${ef}.${ehn}`,81,[[[],[40,[0,258]]]]],
[262,`${spfblp}3.${ef}.${load}`,90,[[[],[41,[0,258],[0,256],[1,39]]]]],
[263,`${spfblp}3.${qig}`,84,[[[],[42,[0,257],[0,261]]]]],
[264,`${spfblp}3.net.${load}`,90,[[[],[43,[0,256],[0,260]]]]],
[265,`${spfblp}3.${sc}`,92,[[[],[44,[0,258]]]]],
[266,`${spfblp}3.${sc}.${wf}`,124,[[[],[45,[0,265],[0,338]]]]],
[267,`${spfblp}3.${sa}`,93,[[[],[46,[0,256],[0,258],[0,254]]]]],
[268,`${spfblp}3.${sa}.${wf}`,124,[[[],[47,[0,267],[0,322]]]]],
[269,`${spfblp}3.volume`,99,[[[],[48,[0,256],[0,254]]]]],
[270,`${spfblp}4.${dens}`,91,[[[],[39,[0,408],[1,18],[1,19],[1,19],[1,18]]]]],
[271,`${spfblp}4.${heat}`,83,[[[],[39,[0,408],[0,423],[1,40],[1,21],[1,0]]]]],
[272,`${spfblp}4.${load}`,90,[[[],[39,[0,408],[1,14],[0,446],[1,14],[1,14]]]]],
[273,`${spfblp}4.${mois}`,87,[[[],[39,[0,408],[1,33],[0,115],[1,33],[1,33]]]]],
[274,`${spfblp}4.${savr}`,94,[[[],[39,[0,408],[1,8],[1,36],[1,8],[1,8]]]]],
[275,`${spfblp}4.${emc}`,82,[[[],[39,[0,408],[1,24],[1,25],[1,25],[1,24]]]]],
[276,`${spfblp}4.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[277,`${spfblp}4.${ef}.${ehn}`,81,[[[],[40,[0,274]]]]],
[278,`${spfblp}4.${ef}.${load}`,90,[[[],[41,[0,274],[0,272],[1,39]]]]],
[279,`${spfblp}4.${qig}`,84,[[[],[42,[0,273],[0,277]]]]],
[280,`${spfblp}4.net.${load}`,90,[[[],[43,[0,272],[0,276]]]]],
[281,`${spfblp}4.${sc}`,92,[[[],[44,[0,274]]]]],
[282,`${spfblp}4.${sc}.${wf}`,124,[[[],[45,[0,281],[0,338]]]]],
[283,`${spfblp}4.${sa}`,93,[[[],[46,[0,272],[0,274],[0,270]]]]],
[284,`${spfblp}4.${sa}.${wf}`,124,[[[],[47,[0,283],[0,322]]]]],
[285,`${spfblp}4.volume`,99,[[[],[48,[0,272],[0,270]]]]],
[286,`${spfblp}5.${dens}`,91,[[[],[39,[0,408],[1,18],[1,18],[1,19],[1,18]]]]],
[287,`${spfblp}5.${heat}`,83,[[[],[39,[0,408],[0,423],[1,37],[1,21],[1,0]]]]],
[288,`${spfblp}5.${load}`,90,[[[],[39,[0,408],[1,14],[0,447],[1,14],[1,14]]]]],
[289,`${spfblp}5.${mois}`,87,[[[],[39,[0,408],[1,33],[0,114],[1,33],[1,33]]]]],
[290,`${spfblp}5.${savr}`,94,[[[],[39,[0,408],[1,8],[1,41],[1,8],[1,8]]]]],
[291,`${spfblp}5.${emc}`,82,[[[],[39,[0,408],[1,24],[1,42],[1,25],[1,24]]]]],
[292,`${spfblp}5.${tmc}`,98,[[[],[39,[0,408],[1,26],[1,27],[1,28],[1,27]]]]],
[293,`${spfblp}5.${ef}.${ehn}`,81,[[[],[40,[0,290]]]]],
[294,`${spfblp}5.${ef}.${load}`,90,[[[],[41,[0,290],[0,288],[1,39]]]]],
[295,`${spfblp}5.${qig}`,84,[[[],[42,[0,289],[0,293]]]]],
[296,`${spfblp}5.net.${load}`,90,[[[],[43,[0,288],[0,292]]]]],
[297,`${spfblp}5.${sc}`,92,[[[],[44,[0,290]]]]],
[298,`${spfblp}5.${sc}.${wf}`,124,[[[],[45,[0,297],[0,338]]]]],
[299,`${spfblp}5.${sa}`,93,[[[],[46,[0,288],[0,290],[0,286]]]]],
[300,`${spfblp}5.${sa}.${wf}`,124,[[[],[47,[0,299],[0,322]]]]],
[301,`${spfblp}5.volume`,99,[[[],[48,[0,288],[0,286]]]]],
[302,`${spfbd}.${sa}`,93,[[[],[50,[0,150],[0,167],[0,184],[0,201],[0,218]]]]],
[303,`${spfbd}.${sa}.${wf}`,124,[[[],[21,[0,302],[0,357]]]]],
[304,`${spfbd}.mineralDamping`,54,[[[],[51,[0,317]]]]],
[305,`${spfbd}.moistureDamping`,54,[[[],[52,[0,311],[0,309]]]]],
[306,`${spfbd}.${heat}`,83,[[[],[53,[0,151],[0,168],[0,185],[0,202],[0,219],[0,138],[0,155],[0,172],[0,189],[0,206]]]]],
[307,`${spfbd}.${load}`,90,[[[],[50,[0,139],[0,156],[0,173],[0,190],[0,207]]]]],
[308,`${spfbd}.${ef}.${load}`,90,[[[],[50,[0,145],[0,162],[0,179],[0,196],[0,213]]]]],
[309,`${spfbd}.extinction.${mois}`,87,[[[],[39,[0,408],[0,413],[1,43],[1,44],[1,45]]]]],
[310,`${spfbd}.extinction.${mois}Factor`,36,[[[],[54,[0,308],[0,328]]]]],
[311,`${spfbd}.${mois}`,87,[[[],[53,[0,151],[0,168],[0,185],[0,202],[0,219],[0,140],[0,157],[0,174],[0,191],[0,208]]]]],
[312,`${spfbd}.volume`,74,[[[],[50,[0,152],[0,169],[0,186],[0,203],[0,220]]]]],
[313,`${spfbd}.${qig}`,84,[[[],[53,[0,151],[0,168],[0,185],[0,202],[0,219],[0,146],[0,163],[0,180],[0,197],[0,214]]]]],
[314,`${spfbd}.${rxi}`,64,[[[],[22,[0,315],[0,305]]]]],
[315,`${spfbd}.${rxi}Dry`,64,[[[],[55,[0,354],[0,319],[0,306],[0,304]]]]],
[316,`${spfbd}.${savr}`,94,[[[],[53,[0,151],[0,168],[0,185],[0,202],[0,219],[0,141],[0,158],[0,175],[0,192],[0,209]]]]],
[317,`${spfbd}.${emc}`,82,[[[],[53,[0,151],[0,168],[0,185],[0,202],[0,219],[0,142],[0,159],[0,176],[0,193],[0,210]]]]],
[318,`${spfbd}.${sc}.${wf}`,124,[[[],[56,[0,150],[0,148],[0,167],[0,165],[0,184],[0,182],[0,201],[0,199],[0,218],[0,216]]]]],
[319,`${spfbd}.net.${load}`,90,[[[],[53,[0,149],[0,166],[0,183],[0,200],[0,217],[0,147],[0,164],[0,181],[0,198],[0,215]]]]],
[320,`${spfbd}.${ef}.waterLoad`,90,[[[],[50,[0,153],[0,170],[0,187],[0,204],[0,221]]]]],
[321,`${spfbd}.${ef}.${mois}`,87,[[[],[21,[0,320],[0,308]]]]],
[322,`${spfbl}.${sa}`,93,[[[],[50,[0,235],[0,251],[0,267],[0,283],[0,299]]]]],
[323,`${spfbl}.${sa}.${wf}`,124,[[[],[21,[0,322],[0,357]]]]],
[324,`${spfbl}.mineralDamping`,54,[[[],[51,[0,337]]]]],
[325,`${spfbl}.moistureDamping`,54,[[[],[52,[0,331],[0,329]]]]],
[326,`${spfbl}.${heat}`,83,[[[],[53,[0,236],[0,252],[0,268],[0,284],[0,300],[0,223],[0,239],[0,255],[0,271],[0,287]]]]],
[327,`${spfbl}.${load}`,90,[[[],[50,[0,224],[0,240],[0,256],[0,272],[0,288]]]]],
[328,`${spfbl}.${ef}.${load}`,90,[[[],[50,[0,230],[0,246],[0,262],[0,278],[0,294]]]]],
[329,`${spfbl}.extinction.${mois}`,87,[[[],[57,[0,330],[0,321],[0,309]]]]],
[330,`${spfbl}.extinction.${mois}Factor`,36,[[[],[54,[0,308],[0,328]]]]],
[331,`${spfbl}.${mois}`,87,[[[],[53,[0,236],[0,252],[0,268],[0,284],[0,300],[0,225],[0,241],[0,257],[0,273],[0,289]]]]],
[332,`${spfbl}.volume`,74,[[[],[50,[0,237],[0,253],[0,269],[0,285],[0,301]]]]],
[333,`${spfbl}.${qig}`,84,[[[],[53,[0,236],[0,252],[0,268],[0,284],[0,300],[0,231],[0,247],[0,263],[0,279],[0,295]]]]],
[334,`${spfbl}.${rxi}`,64,[[[],[22,[0,335],[0,325]]]]],
[335,`${spfbl}.${rxi}Dry`,64,[[[],[55,[0,354],[0,339],[0,326],[0,324]]]]],
[336,`${spfbl}.${savr}`,94,[[[],[53,[0,236],[0,252],[0,268],[0,284],[0,300],[0,226],[0,242],[0,258],[0,274],[0,290]]]]],
[337,`${spfbl}.${emc}`,82,[[[],[53,[0,236],[0,252],[0,268],[0,284],[0,300],[0,227],[0,243],[0,259],[0,275],[0,291]]]]],
[338,`${spfbl}.${sc}.${wf}`,124,[[[],[56,[0,235],[0,233],[0,251],[0,249],[0,267],[0,265],[0,283],[0,281],[0,299],[0,297]]]]],
[339,`${spfbl}.net.${load}`,90,[[[],[53,[0,234],[0,250],[0,266],[0,282],[0,298],[0,232],[0,248],[0,264],[0,280],[0,296]]]]],
[340,`${spfb}.depth`,74,[[[],[39,[0,408],[0,412],[0,429],[0,453],[0,464]]]]],
[341,`${spfb}.bulkDensity`,73,[[[],[21,[0,345],[0,340]]]]],
[342,`${spfb}.${qig}`,75,[[[],[53,[0,303],[0,323],[0,313],[0,333]]]]],
[343,`${spfb}.heatSink`,85,[[[],[58,[0,342],[0,341]]]]],
[344,`${spfb}.noWindNoSlope.${ros}`,70,[[[],[59,[0,351],[0,350],[0,343]]]]],
[345,`${spfb}.${load}`,90,[[[],[50,[0,307],[0,327]]]]],
[346,`${spfb}.open.${waf}`,126,[[[],[60,[0,340]]]]],
[347,`${spfb}.packingRatio`,76,[[[],[61,[0,312],[0,332],[0,340]]]]],
[348,`${spfb}.packingRatio.optimum`,76,[[[],[62,[0,355]]]]],
[349,`${spfb}.packingRatio.ratio`,76,[[[],[21,[0,347],[0,348]]]]],
[350,`${spfb}.propagatingFluxRatio`,63,[[[],[63,[0,355],[0,347]]]]],
[351,`${spfb}.${rxi}`,64,[[[],[50,[0,314],[0,334]]]]],
[352,`${spfb}.reactionVelocityExponent`,36,[[[],[64,[0,355]]]]],
[353,`${spfb}.reactionVelocityMaximum`,65,[[[],[65,[0,356]]]]],
[354,`${spfb}.reactionVelocityOptimum`,65,[[[],[66,[0,349],[0,353],[0,352]]]]],
[355,`${spfb}.${savr}`,94,[[[],[53,[0,303],[0,323],[0,316],[0,336]]]]],
[356,`${spfb}.savr15`,36,[[[],[67,[0,355]]]]],
[357,`${spfb}.${sa}`,93,[[[],[50,[0,302],[0,322]]]]],
[358,`${spff}.maximumDirection.slope.${ros}`,70,[[[],[68,[0,407],[0,371]]]]],
[359,`${spff}.maximumDirection.wind.${ros}`,70,[[[],[69,[0,407],[0,394]]]]],
[360,`${spff}.wind.heading.fromUpslope`,39,[[[],[30,[0,129]]]]],
[361,`${spff}.maximumDirection.xComponent`,36,[[[],[70,[0,359],[0,358],[0,360]]]]],
[362,`${spff}.maximumDirection.yComponent`,36,[[[],[71,[0,359],[0,360]]]]],
[363,`${spff}.maximumDirection.${ros}`,70,[[[],[72,[0,361],[0,362]]]]],
[364,`${spff}.limit.${ews}.exceeded`,33,[[[],[73,[0,375],[0,366]]]]],
[365,`${spff}.limit.${ros}.exceeded`,34,[[[],[73,[0,377],[0,383]]]]],
[366,`${spff}.limit.${ews}`,125,[[[],[74,[0,404]]]]],
[367,`${spff}.limit.windSlopeSpreadRateCoefficient`,36,[[[],[75,[0,366],[0,389],[0,392]]]]],
[368,`${spff}.limit.${ros}`,70,[[[],[76,[0,407],[0,367]]]]],
[369,`${spff}.slope.ratio`,114,[[[],[30,[0,120]]]]],
[370,`${spff}.slope.k`,36,[[[],[77,[0,347]]]]],
[371,`${spff}.slope.phi`,36,[[[],[78,[0,369],[0,370]]]]],
[372,`${spff}.spread.step1.${ews}`,125,[[[],[79,[0,373],[0,389],[0,393]]]]],
[373,`${spff}.spread.step1.${phiew}`,36,[[[],[80,[0,394],[0,371]]]]],
[374,`${spff}.spread.step1.${ros}`,70,[[[],[76,[0,407],[0,373]]]]],
[375,`${spff}.spread.step2.${ews}`,125,[[[],[79,[0,376],[0,389],[0,393]]]]],
[376,`${spff}.spread.step2.${phiew}`,36,[[[],[81,[0,407],[0,377]]]]],
[377,`${spff}.spread.step2.${ros}`,70,[[[],[82,[0,407],[0,363]]]]],
[378,`${spff}.spread.step3a.${ews}`,125,[[[],[83,[0,375],[0,366]]]]],
[379,`${spff}.spread.step3a.${phiew}`,36,[[[],[83,[0,376],[0,367]]]]],
[380,`${spff}.spread.step3a.${ros}`,70,[[[],[83,[0,377],[0,368]]]]],
[381,`${spff}.spread.step3b.${ews}`,125,[[[],[79,[0,382],[0,389],[0,393]]]]],
[382,`${spff}.spread.step3b.${phiew}`,36,[[[],[81,[0,407],[0,383]]]]],
[383,`${spff}.spread.step3b.${ros}`,70,[[[],[84,[0,377],[0,375]]]]],
[384,`${spff}.spread.step4.${ews}`,125,[[[],[79,[0,385],[0,389],[0,393]]]]],
[385,`${spff}.spread.step4.${phiew}`,36,[[[],[81,[0,407],[0,386]]]]],
[386,`${spff}.spread.step4.${ros}`,70,[[[],[84,[0,380],[0,378]]]]],
[387,`${spff}.${waf}`,126,[[[20,46],[30,[0,136]]],[[],[85,[0,50],[0,53],[0,346]]]]],
[388,`${spff}.wind.speed.atMidflame`,125,[[[25,17],[30,[0,135]]],[[],[38,[0,134],[0,387]]]]],
[389,`${spff}.wind.factor.b`,36,[[[],[86,[0,355]]]]],
[390,`${spff}.wind.factor.c`,36,[[[],[87,[0,355]]]]],
[391,`${spff}.wind.factor.e`,36,[[[],[88,[0,355]]]]],
[392,`${spff}.wind.factor.k`,36,[[[],[89,[0,349],[0,391],[0,390]]]]],
[393,`${spff}.wind.factor.i`,36,[[[],[90,[0,349],[0,391],[0,390]]]]],
[394,`${spff}.wind.phi`,36,[[[],[91,[0,388],[0,389],[0,392]]]]],
[395,`${spff}.${ews}`,125,[[[28,47],[30,[0,384]]],[[],[30,[0,381]]]]],
[396,`${spff}.${fli}`,56,[[[],[92,[0,406],[0,404],[0,398]]]]],
[397,`${spff}.${fl}`,58,[[[],[17,[0,396]]]]],
[398,`${spff}.${taur}`,66,[[[],[93,[0,355]]]]],
[399,`${spff}.heading.fromUpslope`,39,[[[],[94,[0,361],[0,362],[0,363]]]]],
[400,`${spff}.heading.fromNorth`,39,[[[],[19,[0,118],[0,399]]]]],
[401,`${spff}.${hpua}`,59,[[[],[95,[0,404],[0,398]]]]],
[402,`${spff}.${lwr}`,60,[[[],[20,[0,395]]]]],
[403,`${spff}.${phiew}`,36,[[[28,47],[30,[0,385]]],[[],[30,[0,382]]]]],
[404,`${spff}.${rxi}`,64,[[[],[30,[0,351]]]]],
[405,`${spff}.${sh}`,67,[[[],[96,[0,396],[0,388],[0,121]]]]],
[406,`${spff}.${ros}`,70,[[[28,47],[30,[0,386]]],[[],[30,[0,383]]]]],
[407,`${spff}.noWindNoSlope.${ros}`,70,[[[],[30,[0,344]]]]],
[408,`${spf}.model.domain`,22,[[[17,48],[97,[0,409]]],[[17,49],[9,[1,49]]],[[17,50],[9,[1,50]]],[[17,51],[9,[1,51]]],[[17,52],[9,[1,52]]],[[],[9,[1,53]]]]],
[409,`${spf}.model.catalogKey`,23,[[[],[2]]]],
[410,`${spf}.model.behave.domain`,22,[[[],[9,[1,49]]]]],
[411,`${spf}.${mbp}.cured.herb.fraction`,80,[[[21,54],[98,[0,114]]],[[],[2]]]],
[412,`${spf}.${mbp}.depth`,74,[[[17,48],[99,[0,409]]],[[17,49],[2]],[[],[9,[1,24]]]]],
[413,`${spf}.${mbp}.dead.extinction.${mois}`,87,[[[17,48],[100,[0,409]]],[[17,49],[2]],[[],[9,[1,45]]]]],
[414,`${spf}.${mbp}.total.herb.${load}`,90,[[[17,48],[101,[0,409]]],[[17,49],[2]],[[],[9,[1,14]]]]],
[415,`${spf}.${mbp}.dead.tl1h.${load}`,90,[[[17,48],[102,[0,409]]],[[17,49],[2]],[[],[9,[1,14]]]]],
[416,`${spf}.${mbp}.dead.tl10h.${load}`,90,[[[17,48],[103,[0,409]]],[[17,49],[2]],[[],[9,[1,14]]]]],
[417,`${spf}.${mbp}.dead.tl100h.${load}`,90,[[[17,48],[104,[0,409]]],[[17,49],[2]],[[],[9,[1,14]]]]],
[418,`${spf}.${mbp}.live.stem.${load}`,90,[[[17,48],[105,[0,409]]],[[17,49],[2]],[[],[9,[1,14]]]]],
[419,`${spf}.${mbp}.dead.tl1h.${savr}`,94,[[[17,48],[106,[0,409]]],[[17,49],[2]],[[],[9,[1,14]]]]],
[420,`${spf}.${mbp}.live.herb.${savr}`,94,[[[17,48],[107,[0,409]]],[[17,49],[2]],[[],[9,[1,8]]]]],
[421,`${spf}.${mbp}.live.stem.${savr}`,94,[[[17,48],[108,[0,409]]],[[17,49],[2]],[[],[9,[1,8]]]]],
[422,`${spf}.${mbp}.dead.${heat}`,83,[[[17,48],[109,[0,409]]],[[17,49],[2]],[[],[9,[1,0]]]]],
[423,`${spf}.${mbp}.live.${heat}`,83,[[[17,48],[110,[0,409]]],[[17,49],[2]],[[],[9,[1,0]]]]],
[424,`${spf}.${mbd}.dead.herb.${load}`,90,[[[],[111,[0,414],[0,411]]]]],
[425,`${spf}.${mbd}.live.herb.${load}`,90,[[[],[112,[0,414],[0,411]]]]],
[426,`${spf}.model.chaparral.domain`,22,[[[],[9,[1,50]]]]],
[427,`${spf}.${mcp}.chaparralType`,19,[[[17,48],[113,[0,409]]],[[17,50],[2]],[[],[9,[1,55]]]]],
[428,`${spf}.${mcp}.observed.deadFuelFraction`,80,[[[17,48],[114,[0,409]]],[[17,50],[2]],[[],[9,[1,14]]]]],
[429,`${spf}.${mcp}.observed.depth`,74,[[[17,48],[115,[0,409]]],[[17,50],[2]],[[],[9,[1,24]]]]],
[430,`${spf}.${mcp}.observed.totalLoad`,90,[[[17,48],[116,[0,409]]],[[17,50],[2]],[[],[9,[1,14]]]]],
[431,`${spf}.${mcp}.applied.totalLoad`,90,[[[22,54],[30,[0,436]]],[[],[30,[0,430]]]]],
[432,`${spf}.${mcd}.age`,71,[[[],[117,[0,429],[0,427]]]]],
[433,`${spf}.${mcd}.averageMortality`,110,[[[],[118,[0,432]]]]],
[434,`${spf}.${mcd}.severeMortality`,110,[[[],[119,[0,432]]]]],
[435,`${spf}.${mcd}.depth`,74,[[[],[120,[0,432],[0,427]]]]],
[436,`${spf}.${mcd}.totalLoad`,90,[[[],[121,[0,432],[0,427]]]]],
[437,`${spf}.${mcd}.deadLoad`,90,[[[],[122,[0,431],[0,428]]]]],
[438,`${spf}.${mcd}.deadFineLoad`,90,[[[],[123,[0,431],[0,428]]]]],
[439,`${spf}.${mcd}.deadSmallLoad`,90,[[[],[124,[0,431],[0,428]]]]],
[440,`${spf}.${mcd}.deadMediumLoad`,90,[[[],[125,[0,431],[0,428]]]]],
[441,`${spf}.${mcd}.deadLargeLoad`,90,[[[],[126,[0,431],[0,428]]]]],
[442,`${spf}.${mcd}.liveLoad`,90,[[[],[127,[0,431],[0,428]]]]],
[443,`${spf}.${mcd}.liveFineLoad`,90,[[[],[128,[0,431],[0,428]]]]],
[444,`${spf}.${mcd}.liveSmallLoad`,90,[[[],[129,[0,431],[0,428]]]]],
[445,`${spf}.${mcd}.liveMediumLoad`,90,[[[],[130,[0,431],[0,428]]]]],
[446,`${spf}.${mcd}.liveLargeLoad`,90,[[[],[131,[0,431],[0,428]]]]],
[447,`${spf}.${mcd}.liveLeafLoad`,90,[[[],[132,[0,431],[0,428]]]]],
[448,`${spf}.model.palmettoGallberry.domain`,22,[[[],[9,[1,51]]]]],
[449,`${spf}.${mpp}.age`,71,[[[17,48],[133,[0,409]]],[[17,51],[2]],[[],[9,[1,14]]]]],
[450,`${spf}.${mpp}.basalArea`,72,[[[17,48],[134,[0,409]]],[[17,51],[2]],[[],[9,[1,14]]]]],
[451,`${spf}.${mpp}.cover`,77,[[[17,48],[135,[0,409]]],[[17,51],[2]],[[],[9,[1,14]]]]],
[452,`${spf}.${mpp}.height`,74,[[[17,48],[136,[0,409]]],[[17,51],[2]],[[],[9,[1,24]]]]],
[453,`${spf}.${mpd}.depth`,74,[[[],[137,[0,452]]]]],
[454,`${spf}.${mpd}.deadFineLoad`,90,[[[],[138,[0,449],[0,452]]]]],
[455,`${spf}.${mpd}.deadSmallLoad`,90,[[[],[139,[0,449],[0,451]]]]],
[456,`${spf}.${mpd}.deadFoliageLoad`,90,[[[],[140,[0,449],[0,451]]]]],
[457,`${spf}.${mpd}.deadLitterLoad`,90,[[[],[141,[0,449],[0,450]]]]],
[458,`${spf}.${mpd}.liveFineLoad`,90,[[[],[142,[0,449],[0,452]]]]],
[459,`${spf}.${mpd}.liveSmallLoad`,90,[[[],[143,[0,449],[0,452]]]]],
[460,`${spf}.${mpd}.liveFoliageLoad`,90,[[[],[144,[0,449],[0,451],[0,452]]]]],
[461,`${spf}.model.westernAspen.domain`,22,[[[],[9,[1,52]]]]],
[462,`${spf}.${mwp}.aspenType`,30,[[[17,48],[145,[0,409]]],[[17,52],[2]],[[],[9,[1,56]]]]],
[463,`${spf}.${mwp}.curingLevel`,80,[[[17,48],[146,[0,409]]],[[17,52],[2]],[[],[9,[1,14]]]]],
[464,`${spf}.${mwd}.depth`,74,[[[],[147,[0,462]]]]],
[465,`${spf}.${mwd}.dead.fine.${load}`,90,[[[],[148,[0,462],[0,463]]]]],
[466,`${spf}.${mwd}.dead.small.${load}`,90,[[[],[149,[0,462]]]]],
[467,`${spf}.${mwd}.dead.fine.${savr}`,90,[[[],[150,[0,462],[0,463]]]]],
[468,`${spf}.${mwd}.live.herb.${load}`,90,[[[],[151,[0,462],[0,463]]]]],
[469,`${spf}.${mwd}.live.stem.${load}`,90,[[[],[152,[0,462],[0,463]]]]],
[470,`${spf}.${mwd}.live.stem.${savr}`,90,[[[],[153,[0,462],[0,463]]]]],
[471,`${ssfbdp}1.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,20],[1,18]]]]],
[472,`${ssfbdp}1.${heat}`,83,[[[],[39,[0,742],[0,756],[1,0],[1,21],[1,0]]]]],
[473,`${ssfbdp}1.${load}`,90,[[[],[39,[0,742],[0,749],[0,772],[0,788],[0,799]]]]],
[474,`${ssfbdp}1.${mois}`,87,[[[],[39,[0,742],[0,110],[0,110],[0,110],[0,110]]]]],
[475,`${ssfbdp}1.${savr}`,94,[[[],[39,[0,742],[0,753],[1,22],[1,23],[0,801]]]]],
[476,`${ssfbdp}1.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,24],[1,24]]]]],
[477,`${ssfbdp}1.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[478,`${ssfbdp}1.${ef}.${ehn}`,81,[[[],[40,[0,475]]]]],
[479,`${ssfbdp}1.${ef}.${load}`,90,[[[],[41,[0,475],[0,473],[1,29]]]]],
[480,`${ssfbdp}1.${qig}`,84,[[[],[42,[0,474],[0,478]]]]],
[481,`${ssfbdp}1.net.${load}`,90,[[[],[43,[0,473],[0,477]]]]],
[482,`${ssfbdp}1.${sc}`,92,[[[],[44,[0,475]]]]],
[483,`${ssfbdp}1.${sc}.${wf}`,124,[[[],[45,[0,482],[0,652]]]]],
[484,`${ssfbdp}1.${sa}`,93,[[[],[46,[0,473],[0,475],[0,471]]]]],
[485,`${ssfbdp}1.${sa}.${wf}`,124,[[[],[47,[0,484],[0,636]]]]],
[486,`${ssfbdp}1.volume`,99,[[[],[48,[0,473],[0,471]]]]],
[487,`${ssfbdp}1.${ef}.waterLoad`,90,[[[],[49,[0,479],[0,474]]]]],
[488,`${ssfbdp}2.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,20],[1,18]]]]],
[489,`${ssfbdp}2.${heat}`,83,[[[],[39,[0,742],[0,756],[1,0],[1,21],[1,0]]]]],
[490,`${ssfbdp}2.${load}`,90,[[[],[39,[0,742],[0,750],[0,773],[0,789],[0,800]]]]],
[491,`${ssfbdp}2.${mois}`,87,[[[],[39,[0,742],[0,111],[0,111],[0,111],[0,111]]]]],
[492,`${ssfbdp}2.${savr}`,94,[[[],[39,[0,742],[1,30],[1,31],[1,32],[1,30]]]]],
[493,`${ssfbdp}2.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,24],[1,24]]]]],
[494,`${ssfbdp}2.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[495,`${ssfbdp}2.${ef}.${ehn}`,81,[[[],[40,[0,492]]]]],
[496,`${ssfbdp}2.${ef}.${load}`,90,[[[],[41,[0,492],[0,490],[1,29]]]]],
[497,`${ssfbdp}2.${qig}`,84,[[[],[42,[0,491],[0,495]]]]],
[498,`${ssfbdp}2.net.${load}`,90,[[[],[43,[0,490],[0,494]]]]],
[499,`${ssfbdp}2.${sc}`,92,[[[],[44,[0,492]]]]],
[500,`${ssfbdp}2.${sc}.${wf}`,124,[[[],[45,[0,499],[0,652]]]]],
[501,`${ssfbdp}2.${sa}`,93,[[[],[46,[0,490],[0,492],[0,488]]]]],
[502,`${ssfbdp}2.${sa}.${wf}`,124,[[[],[47,[0,501],[0,636]]]]],
[503,`${ssfbdp}2.volume`,99,[[[],[48,[0,490],[0,488]]]]],
[504,`${ssfbdp}2.${ef}.waterLoad`,90,[[[],[49,[0,496],[0,491]]]]],
[505,`${ssfbdp}3.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,20],[1,18]]]]],
[506,`${ssfbdp}3.${heat}`,83,[[[],[39,[0,742],[0,756],[1,0],[1,21],[1,0]]]]],
[507,`${ssfbdp}3.${load}`,90,[[[],[39,[0,742],[0,751],[0,774],[0,790],[1,14]]]]],
[508,`${ssfbdp}3.${mois}`,87,[[[],[39,[0,742],[0,112],[0,111],[0,110],[1,33]]]]],
[509,`${ssfbdp}3.${savr}`,94,[[[],[39,[0,742],[1,20],[1,34],[1,35],[1,8]]]]],
[510,`${ssfbdp}3.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,24],[1,24]]]]],
[511,`${ssfbdp}3.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[512,`${ssfbdp}3.${ef}.${ehn}`,81,[[[],[40,[0,509]]]]],
[513,`${ssfbdp}3.${ef}.${load}`,90,[[[],[41,[0,509],[0,507],[1,29]]]]],
[514,`${ssfbdp}3.${qig}`,84,[[[],[42,[0,508],[0,512]]]]],
[515,`${ssfbdp}3.net.${load}`,90,[[[],[43,[0,507],[0,511]]]]],
[516,`${ssfbdp}3.${sc}`,92,[[[],[44,[0,509]]]]],
[517,`${ssfbdp}3.${sc}.${wf}`,124,[[[],[45,[0,516],[0,652]]]]],
[518,`${ssfbdp}3.${sa}`,93,[[[],[46,[0,507],[0,509],[0,505]]]]],
[519,`${ssfbdp}3.${sa}.${wf}`,124,[[[],[47,[0,518],[0,636]]]]],
[520,`${ssfbdp}3.volume`,99,[[[],[48,[0,507],[0,505]]]]],
[521,`${ssfbdp}3.${ef}.waterLoad`,90,[[[],[49,[0,513],[0,508]]]]],
[522,`${ssfbdp}4.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,20],[1,18]]]]],
[523,`${ssfbdp}4.${heat}`,83,[[[],[39,[0,742],[0,756],[1,0],[1,21],[1,0]]]]],
[524,`${ssfbdp}4.${load}`,90,[[[],[39,[0,742],[0,758],[0,775],[0,791],[1,14]]]]],
[525,`${ssfbdp}4.${mois}`,87,[[[],[39,[0,742],[0,110],[0,112],[0,112],[1,33]]]]],
[526,`${ssfbdp}4.${savr}`,94,[[[],[39,[0,742],[0,754],[1,36],[1,35],[1,8]]]]],
[527,`${ssfbdp}4.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,24],[1,24]]]]],
[528,`${ssfbdp}4.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[529,`${ssfbdp}4.${ef}.${ehn}`,81,[[[],[40,[0,526]]]]],
[530,`${ssfbdp}4.${ef}.${load}`,90,[[[],[41,[0,526],[0,524],[1,29]]]]],
[531,`${ssfbdp}4.${qig}`,84,[[[],[42,[0,525],[0,529]]]]],
[532,`${ssfbdp}4.net.${load}`,90,[[[],[43,[0,524],[0,528]]]]],
[533,`${ssfbdp}4.${sc}`,92,[[[],[44,[0,526]]]]],
[534,`${ssfbdp}4.${sc}.${wf}`,124,[[[],[45,[0,533],[0,652]]]]],
[535,`${ssfbdp}4.${sa}`,93,[[[],[46,[0,524],[0,526],[0,522]]]]],
[536,`${ssfbdp}4.${sa}.${wf}`,124,[[[],[47,[0,535],[0,636]]]]],
[537,`${ssfbdp}4.volume`,99,[[[],[48,[0,524],[0,522]]]]],
[538,`${ssfbdp}4.${ef}.waterLoad`,90,[[[],[49,[0,530],[0,525]]]]],
[539,`${ssfbdp}5.${dens}`,91,[[[],[9,[1,18]]]]],
[540,`${ssfbdp}5.${heat}`,83,[[[],[9,[1,0]]]]],
[541,`${ssfbdp}5.${load}`,90,[[[],[9,[1,14]]]]],
[542,`${ssfbdp}5.${mois}`,87,[[[],[9,[1,33]]]]],
[543,`${ssfbdp}5.${savr}`,94,[[[],[9,[1,8]]]]],
[544,`${ssfbdp}5.${emc}`,82,[[[],[9,[1,24]]]]],
[545,`${ssfbdp}5.${tmc}`,98,[[[],[9,[1,26]]]]],
[546,`${ssfbdp}5.${ef}.${ehn}`,81,[[[],[40,[0,543]]]]],
[547,`${ssfbdp}5.${ef}.${load}`,90,[[[],[41,[0,543],[0,541],[1,29]]]]],
[548,`${ssfbdp}5.${qig}`,84,[[[],[42,[0,542],[0,546]]]]],
[549,`${ssfbdp}5.net.${load}`,90,[[[],[43,[0,541],[0,545]]]]],
[550,`${ssfbdp}5.${sc}`,92,[[[],[44,[0,543]]]]],
[551,`${ssfbdp}5.${sc}.${wf}`,124,[[[],[45,[0,550],[0,652]]]]],
[552,`${ssfbdp}5.${sa}`,93,[[[],[46,[0,541],[0,543],[0,539]]]]],
[553,`${ssfbdp}5.${sa}.${wf}`,124,[[[],[47,[0,552],[0,636]]]]],
[554,`${ssfbdp}5.volume`,99,[[[],[48,[0,541],[0,539]]]]],
[555,`${ssfbdp}5.${ef}.waterLoad`,90,[[[],[49,[0,547],[0,542]]]]],
[556,`${ssfblp}1.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,19],[1,18]]]]],
[557,`${ssfblp}1.${heat}`,83,[[[],[39,[0,742],[0,757],[1,37],[1,21],[1,0]]]]],
[558,`${ssfblp}1.${load}`,90,[[[],[39,[0,742],[0,759],[0,777],[0,792],[0,802]]]]],
[559,`${ssfblp}1.${mois}`,87,[[[],[39,[0,742],[0,114],[0,115],[0,115],[0,114]]]]],
[560,`${ssfblp}1.${savr}`,94,[[[],[39,[0,742],[0,754],[1,22],[1,23],[1,38]]]]],
[561,`${ssfblp}1.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,25],[1,24]]]]],
[562,`${ssfblp}1.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[563,`${ssfblp}1.${ef}.${ehn}`,81,[[[],[40,[0,560]]]]],
[564,`${ssfblp}1.${ef}.${load}`,90,[[[],[41,[0,560],[0,558],[1,39]]]]],
[565,`${ssfblp}1.${qig}`,84,[[[],[42,[0,559],[0,563]]]]],
[566,`${ssfblp}1.net.${load}`,90,[[[],[43,[0,558],[0,562]]]]],
[567,`${ssfblp}1.${sc}`,92,[[[],[44,[0,560]]]]],
[568,`${ssfblp}1.${sc}.${wf}`,124,[[[],[45,[0,567],[0,672]]]]],
[569,`${ssfblp}1.${sa}`,93,[[[],[46,[0,558],[0,560],[0,556]]]]],
[570,`${ssfblp}1.${sa}.${wf}`,124,[[[],[47,[0,569],[0,656]]]]],
[571,`${ssfblp}1.volume`,99,[[[],[48,[0,558],[0,556]]]]],
[572,`${ssfblp}2.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,19],[1,18]]]]],
[573,`${ssfblp}2.${heat}`,83,[[[],[39,[0,742],[0,757],[1,40],[1,21],[1,0]]]]],
[574,`${ssfblp}2.${load}`,90,[[[],[39,[0,742],[0,752],[0,778],[0,793],[0,803]]]]],
[575,`${ssfblp}2.${mois}`,87,[[[],[39,[0,742],[0,115],[0,115],[0,115],[0,115]]]]],
[576,`${ssfblp}2.${savr}`,94,[[[],[39,[0,742],[0,755],[1,31],[1,32],[0,804]]]]],
[577,`${ssfblp}2.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,25],[1,24]]]]],
[578,`${ssfblp}2.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[579,`${ssfblp}2.${ef}.${ehn}`,81,[[[],[40,[0,576]]]]],
[580,`${ssfblp}2.${ef}.${load}`,90,[[[],[41,[0,576],[0,574],[1,39]]]]],
[581,`${ssfblp}2.${qig}`,84,[[[],[42,[0,575],[0,579]]]]],
[582,`${ssfblp}2.net.${load}`,90,[[[],[43,[0,574],[0,578]]]]],
[583,`${ssfblp}2.${sc}`,92,[[[],[44,[0,576]]]]],
[584,`${ssfblp}2.${sc}.${wf}`,124,[[[],[45,[0,583],[0,672]]]]],
[585,`${ssfblp}2.${sa}`,93,[[[],[46,[0,574],[0,576],[0,572]]]]],
[586,`${ssfblp}2.${sa}.${wf}`,124,[[[],[47,[0,585],[0,656]]]]],
[587,`${ssfblp}2.volume`,99,[[[],[48,[0,574],[0,572]]]]],
[588,`${ssfblp}3.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,19],[1,18]]]]],
[589,`${ssfblp}3.${heat}`,83,[[[],[39,[0,742],[0,757],[1,40],[1,21],[1,0]]]]],
[590,`${ssfblp}3.${load}`,90,[[[],[39,[0,742],[1,14],[0,779],[0,794],[1,14]]]]],
[591,`${ssfblp}3.${mois}`,87,[[[],[39,[0,742],[1,33],[0,115],[0,115],[1,33]]]]],
[592,`${ssfblp}3.${savr}`,94,[[[],[39,[0,742],[1,8],[1,34],[1,35],[1,8]]]]],
[593,`${ssfblp}3.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,25],[1,24]]]]],
[594,`${ssfblp}3.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[595,`${ssfblp}3.${ef}.${ehn}`,81,[[[],[40,[0,592]]]]],
[596,`${ssfblp}3.${ef}.${load}`,90,[[[],[41,[0,592],[0,590],[1,39]]]]],
[597,`${ssfblp}3.${qig}`,84,[[[],[42,[0,591],[0,595]]]]],
[598,`${ssfblp}3.net.${load}`,90,[[[],[43,[0,590],[0,594]]]]],
[599,`${ssfblp}3.${sc}`,92,[[[],[44,[0,592]]]]],
[600,`${ssfblp}3.${sc}.${wf}`,124,[[[],[45,[0,599],[0,672]]]]],
[601,`${ssfblp}3.${sa}`,93,[[[],[46,[0,590],[0,592],[0,588]]]]],
[602,`${ssfblp}3.${sa}.${wf}`,124,[[[],[47,[0,601],[0,656]]]]],
[603,`${ssfblp}3.volume`,99,[[[],[48,[0,590],[0,588]]]]],
[604,`${ssfblp}4.${dens}`,91,[[[],[39,[0,742],[1,18],[1,19],[1,19],[1,18]]]]],
[605,`${ssfblp}4.${heat}`,83,[[[],[39,[0,742],[0,757],[1,40],[1,21],[1,0]]]]],
[606,`${ssfblp}4.${load}`,90,[[[],[39,[0,742],[1,14],[0,780],[1,14],[1,14]]]]],
[607,`${ssfblp}4.${mois}`,87,[[[],[39,[0,742],[1,33],[0,115],[1,33],[1,33]]]]],
[608,`${ssfblp}4.${savr}`,94,[[[],[39,[0,742],[1,8],[1,36],[1,8],[1,8]]]]],
[609,`${ssfblp}4.${emc}`,82,[[[],[39,[0,742],[1,24],[1,25],[1,25],[1,24]]]]],
[610,`${ssfblp}4.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[611,`${ssfblp}4.${ef}.${ehn}`,81,[[[],[40,[0,608]]]]],
[612,`${ssfblp}4.${ef}.${load}`,90,[[[],[41,[0,608],[0,606],[1,39]]]]],
[613,`${ssfblp}4.${qig}`,84,[[[],[42,[0,607],[0,611]]]]],
[614,`${ssfblp}4.net.${load}`,90,[[[],[43,[0,606],[0,610]]]]],
[615,`${ssfblp}4.${sc}`,92,[[[],[44,[0,608]]]]],
[616,`${ssfblp}4.${sc}.${wf}`,124,[[[],[45,[0,615],[0,672]]]]],
[617,`${ssfblp}4.${sa}`,93,[[[],[46,[0,606],[0,608],[0,604]]]]],
[618,`${ssfblp}4.${sa}.${wf}`,124,[[[],[47,[0,617],[0,656]]]]],
[619,`${ssfblp}4.volume`,99,[[[],[48,[0,606],[0,604]]]]],
[620,`${ssfblp}5.${dens}`,91,[[[],[39,[0,742],[1,18],[1,18],[1,19],[1,18]]]]],
[621,`${ssfblp}5.${heat}`,83,[[[],[39,[0,742],[0,757],[1,37],[1,21],[1,0]]]]],
[622,`${ssfblp}5.${load}`,90,[[[],[39,[0,742],[1,14],[0,781],[1,14],[1,14]]]]],
[623,`${ssfblp}5.${mois}`,87,[[[],[39,[0,742],[1,33],[0,114],[1,33],[1,33]]]]],
[624,`${ssfblp}5.${savr}`,94,[[[],[39,[0,742],[1,8],[1,41],[1,8],[1,8]]]]],
[625,`${ssfblp}5.${emc}`,82,[[[],[39,[0,742],[1,24],[1,42],[1,25],[1,24]]]]],
[626,`${ssfblp}5.${tmc}`,98,[[[],[39,[0,742],[1,26],[1,27],[1,28],[1,27]]]]],
[627,`${ssfblp}5.${ef}.${ehn}`,81,[[[],[40,[0,624]]]]],
[628,`${ssfblp}5.${ef}.${load}`,90,[[[],[41,[0,624],[0,622],[1,39]]]]],
[629,`${ssfblp}5.${qig}`,84,[[[],[42,[0,623],[0,627]]]]],
[630,`${ssfblp}5.net.${load}`,90,[[[],[43,[0,622],[0,626]]]]],
[631,`${ssfblp}5.${sc}`,92,[[[],[44,[0,624]]]]],
[632,`${ssfblp}5.${sc}.${wf}`,124,[[[],[45,[0,631],[0,672]]]]],
[633,`${ssfblp}5.${sa}`,93,[[[],[46,[0,622],[0,624],[0,620]]]]],
[634,`${ssfblp}5.${sa}.${wf}`,124,[[[],[47,[0,633],[0,656]]]]],
[635,`${ssfblp}5.volume`,99,[[[],[48,[0,622],[0,620]]]]],
[636,`${ssfbd}.${sa}`,93,[[[],[50,[0,484],[0,501],[0,518],[0,535],[0,552]]]]],
[637,`${ssfbd}.${sa}.${wf}`,124,[[[],[21,[0,636],[0,691]]]]],
[638,`${ssfbd}.mineralDamping`,54,[[[],[51,[0,651]]]]],
[639,`${ssfbd}.moistureDamping`,54,[[[],[52,[0,645],[0,643]]]]],
[640,`${ssfbd}.${heat}`,83,[[[],[53,[0,485],[0,502],[0,519],[0,536],[0,553],[0,472],[0,489],[0,506],[0,523],[0,540]]]]],
[641,`${ssfbd}.${load}`,90,[[[],[50,[0,473],[0,490],[0,507],[0,524],[0,541]]]]],
[642,`${ssfbd}.${ef}.${load}`,90,[[[],[50,[0,479],[0,496],[0,513],[0,530],[0,547]]]]],
[643,`${ssfbd}.extinction.${mois}`,87,[[[],[39,[0,742],[0,747],[1,43],[1,44],[1,45]]]]],
[644,`${ssfbd}.extinction.${mois}Factor`,36,[[[],[54,[0,642],[0,662]]]]],
[645,`${ssfbd}.${mois}`,87,[[[],[53,[0,485],[0,502],[0,519],[0,536],[0,553],[0,474],[0,491],[0,508],[0,525],[0,542]]]]],
[646,`${ssfbd}.volume`,74,[[[],[50,[0,486],[0,503],[0,520],[0,537],[0,554]]]]],
[647,`${ssfbd}.${qig}`,84,[[[],[53,[0,485],[0,502],[0,519],[0,536],[0,553],[0,480],[0,497],[0,514],[0,531],[0,548]]]]],
[648,`${ssfbd}.${rxi}`,64,[[[],[22,[0,649],[0,639]]]]],
[649,`${ssfbd}.${rxi}Dry`,64,[[[],[55,[0,688],[0,653],[0,640],[0,638]]]]],
[650,`${ssfbd}.${savr}`,94,[[[],[53,[0,485],[0,502],[0,519],[0,536],[0,553],[0,475],[0,492],[0,509],[0,526],[0,543]]]]],
[651,`${ssfbd}.${emc}`,82,[[[],[53,[0,485],[0,502],[0,519],[0,536],[0,553],[0,476],[0,493],[0,510],[0,527],[0,544]]]]],
[652,`${ssfbd}.${sc}.${wf}`,124,[[[],[56,[0,484],[0,482],[0,501],[0,499],[0,518],[0,516],[0,535],[0,533],[0,552],[0,550]]]]],
[653,`${ssfbd}.net.${load}`,90,[[[],[53,[0,483],[0,500],[0,517],[0,534],[0,551],[0,481],[0,498],[0,515],[0,532],[0,549]]]]],
[654,`${ssfbd}.${ef}.waterLoad`,90,[[[],[50,[0,487],[0,504],[0,521],[0,538],[0,555]]]]],
[655,`${ssfbd}.${ef}.${mois}`,87,[[[],[21,[0,654],[0,642]]]]],
[656,`${ssfbl}.${sa}`,93,[[[],[50,[0,569],[0,585],[0,601],[0,617],[0,633]]]]],
[657,`${ssfbl}.${sa}.${wf}`,124,[[[],[21,[0,656],[0,691]]]]],
[658,`${ssfbl}.mineralDamping`,54,[[[],[51,[0,671]]]]],
[659,`${ssfbl}.moistureDamping`,54,[[[],[52,[0,665],[0,663]]]]],
[660,`${ssfbl}.${heat}`,83,[[[],[53,[0,570],[0,586],[0,602],[0,618],[0,634],[0,557],[0,573],[0,589],[0,605],[0,621]]]]],
[661,`${ssfbl}.${load}`,90,[[[],[50,[0,558],[0,574],[0,590],[0,606],[0,622]]]]],
[662,`${ssfbl}.${ef}.${load}`,90,[[[],[50,[0,564],[0,580],[0,596],[0,612],[0,628]]]]],
[663,`${ssfbl}.extinction.${mois}`,87,[[[],[57,[0,664],[0,655],[0,643]]]]],
[664,`${ssfbl}.extinction.${mois}Factor`,36,[[[],[54,[0,642],[0,662]]]]],
[665,`${ssfbl}.${mois}`,87,[[[],[53,[0,570],[0,586],[0,602],[0,618],[0,634],[0,559],[0,575],[0,591],[0,607],[0,623]]]]],
[666,`${ssfbl}.volume`,74,[[[],[50,[0,571],[0,587],[0,603],[0,619],[0,635]]]]],
[667,`${ssfbl}.${qig}`,84,[[[],[53,[0,570],[0,586],[0,602],[0,618],[0,634],[0,565],[0,581],[0,597],[0,613],[0,629]]]]],
[668,`${ssfbl}.${rxi}`,64,[[[],[22,[0,669],[0,659]]]]],
[669,`${ssfbl}.${rxi}Dry`,64,[[[],[55,[0,688],[0,673],[0,660],[0,658]]]]],
[670,`${ssfbl}.${savr}`,94,[[[],[53,[0,570],[0,586],[0,602],[0,618],[0,634],[0,560],[0,576],[0,592],[0,608],[0,624]]]]],
[671,`${ssfbl}.${emc}`,82,[[[],[53,[0,570],[0,586],[0,602],[0,618],[0,634],[0,561],[0,577],[0,593],[0,609],[0,625]]]]],
[672,`${ssfbl}.${sc}.${wf}`,124,[[[],[56,[0,569],[0,567],[0,585],[0,583],[0,601],[0,599],[0,617],[0,615],[0,633],[0,631]]]]],
[673,`${ssfbl}.net.${load}`,90,[[[],[53,[0,568],[0,584],[0,600],[0,616],[0,632],[0,566],[0,582],[0,598],[0,614],[0,630]]]]],
[674,`${ssfb}.depth`,74,[[[],[39,[0,742],[0,746],[0,763],[0,787],[0,798]]]]],
[675,`${ssfb}.bulkDensity`,73,[[[],[21,[0,679],[0,674]]]]],
[676,`${ssfb}.${qig}`,75,[[[],[53,[0,637],[0,657],[0,647],[0,667]]]]],
[677,`${ssfb}.heatSink`,85,[[[],[58,[0,676],[0,675]]]]],
[678,`${ssfb}.noWindNoSlope.${ros}`,70,[[[],[59,[0,685],[0,684],[0,677]]]]],
[679,`${ssfb}.${load}`,90,[[[],[50,[0,641],[0,661]]]]],
[680,`${ssfb}.open.${waf}`,126,[[[],[60,[0,674]]]]],
[681,`${ssfb}.packingRatio`,76,[[[],[61,[0,646],[0,666],[0,674]]]]],
[682,`${ssfb}.packingRatio.optimum`,76,[[[],[62,[0,689]]]]],
[683,`${ssfb}.packingRatio.ratio`,76,[[[],[21,[0,681],[0,682]]]]],
[684,`${ssfb}.propagatingFluxRatio`,63,[[[],[63,[0,689],[0,681]]]]],
[685,`${ssfb}.${rxi}`,64,[[[],[50,[0,648],[0,668]]]]],
[686,`${ssfb}.reactionVelocityExponent`,36,[[[],[64,[0,689]]]]],
[687,`${ssfb}.reactionVelocityMaximum`,65,[[[],[65,[0,690]]]]],
[688,`${ssfb}.reactionVelocityOptimum`,65,[[[],[66,[0,683],[0,687],[0,686]]]]],
[689,`${ssfb}.${savr}`,94,[[[],[53,[0,637],[0,657],[0,650],[0,670]]]]],
[690,`${ssfb}.savr15`,36,[[[],[67,[0,689]]]]],
[691,`${ssfb}.${sa}`,93,[[[],[50,[0,636],[0,656]]]]],
[692,`${ssff}.maximumDirection.slope.${ros}`,70,[[[],[68,[0,741],[0,705]]]]],
[693,`${ssff}.maximumDirection.wind.${ros}`,70,[[[],[69,[0,741],[0,728]]]]],
[694,`${ssff}.wind.heading.fromUpslope`,39,[[[],[30,[0,129]]]]],
[695,`${ssff}.maximumDirection.xComponent`,36,[[[],[70,[0,693],[0,692],[0,694]]]]],
[696,`${ssff}.maximumDirection.yComponent`,36,[[[],[71,[0,693],[0,694]]]]],
[697,`${ssff}.maximumDirection.${ros}`,70,[[[],[72,[0,695],[0,696]]]]],
[698,`${ssff}.limit.${ews}.exceeded`,33,[[[],[73,[0,709],[0,700]]]]],
[699,`${ssff}.limit.${ros}.exceeded`,34,[[[],[73,[0,711],[0,717]]]]],
[700,`${ssff}.limit.${ews}`,125,[[[],[74,[0,738]]]]],
[701,`${ssff}.limit.windSlopeSpreadRateCoefficient`,36,[[[],[75,[0,700],[0,723],[0,726]]]]],
[702,`${ssff}.limit.${ros}`,70,[[[],[76,[0,741],[0,701]]]]],
[703,`${ssff}.slope.ratio`,114,[[[],[30,[0,120]]]]],
[704,`${ssff}.slope.k`,36,[[[],[77,[0,681]]]]],
[705,`${ssff}.slope.phi`,36,[[[],[78,[0,703],[0,704]]]]],
[706,`${ssff}.spread.step1.${ews}`,125,[[[],[79,[0,707],[0,723],[0,727]]]]],
[707,`${ssff}.spread.step1.${phiew}`,36,[[[],[80,[0,728],[0,705]]]]],
[708,`${ssff}.spread.step1.${ros}`,70,[[[],[76,[0,741],[0,707]]]]],
[709,`${ssff}.spread.step2.${ews}`,125,[[[],[79,[0,710],[0,723],[0,727]]]]],
[710,`${ssff}.spread.step2.${phiew}`,36,[[[],[81,[0,741],[0,711]]]]],
[711,`${ssff}.spread.step2.${ros}`,70,[[[],[82,[0,741],[0,697]]]]],
[712,`${ssff}.spread.step3a.${ews}`,125,[[[],[83,[0,709],[0,700]]]]],
[713,`${ssff}.spread.step3a.${phiew}`,36,[[[],[83,[0,710],[0,701]]]]],
[714,`${ssff}.spread.step3a.${ros}`,70,[[[],[83,[0,711],[0,702]]]]],
[715,`${ssff}.spread.step3b.${ews}`,125,[[[],[79,[0,716],[0,723],[0,727]]]]],
[716,`${ssff}.spread.step3b.${phiew}`,36,[[[],[81,[0,741],[0,717]]]]],
[717,`${ssff}.spread.step3b.${ros}`,70,[[[],[84,[0,711],[0,709]]]]],
[718,`${ssff}.spread.step4.${ews}`,125,[[[],[79,[0,719],[0,723],[0,727]]]]],
[719,`${ssff}.spread.step4.${phiew}`,36,[[[],[81,[0,741],[0,720]]]]],
[720,`${ssff}.spread.step4.${ros}`,70,[[[],[84,[0,714],[0,712]]]]],
[721,`${ssff}.${waf}`,126,[[[20,46],[30,[0,136]]],[[],[85,[0,50],[0,53],[0,680]]]]],
[722,`${ssff}.wind.speed.atMidflame`,125,[[[25,17],[30,[0,135]]],[[],[38,[0,134],[0,721]]]]],
[723,`${ssff}.wind.factor.b`,36,[[[],[86,[0,689]]]]],
[724,`${ssff}.wind.factor.c`,36,[[[],[87,[0,689]]]]],
[725,`${ssff}.wind.factor.e`,36,[[[],[88,[0,689]]]]],
[726,`${ssff}.wind.factor.k`,36,[[[],[89,[0,683],[0,725],[0,724]]]]],
[727,`${ssff}.wind.factor.i`,36,[[[],[90,[0,683],[0,725],[0,724]]]]],
[728,`${ssff}.wind.phi`,36,[[[],[91,[0,722],[0,723],[0,726]]]]],
[729,`${ssff}.${ews}`,125,[[[28,47],[30,[0,718]]],[[],[30,[0,715]]]]],
[730,`${ssff}.${fli}`,56,[[[],[92,[0,740],[0,738],[0,732]]]]],
[731,`${ssff}.${fl}`,58,[[[],[17,[0,730]]]]],
[732,`${ssff}.${taur}`,66,[[[],[93,[0,689]]]]],
[733,`${ssff}.heading.fromUpslope`,39,[[[],[94,[0,695],[0,696],[0,697]]]]],
[734,`${ssff}.heading.fromNorth`,39,[[[],[19,[0,118],[0,733]]]]],
[735,`${ssff}.${hpua}`,59,[[[],[95,[0,738],[0,732]]]]],
[736,`${ssff}.${lwr}`,60,[[[],[20,[0,729]]]]],
[737,`${ssff}.${phiew}`,36,[[[28,47],[30,[0,719]]],[[],[30,[0,716]]]]],
[738,`${ssff}.${rxi}`,64,[[[],[30,[0,685]]]]],
[739,`${ssff}.${sh}`,67,[[[],[96,[0,730],[0,722],[0,121]]]]],
[740,`${ssff}.${ros}`,70,[[[28,47],[30,[0,720]]],[[],[30,[0,717]]]]],
[741,`${ssff}.noWindNoSlope.${ros}`,70,[[[],[30,[0,678]]]]],
[742,`${ssf}.model.domain`,22,[[[18,48],[97,[0,743]]],[[18,49],[9,[1,49]]],[[18,50],[9,[1,50]]],[[18,51],[9,[1,51]]],[[18,52],[9,[1,52]]],[[],[9,[1,53]]]]],
[743,`${ssf}.model.catalogKey`,23,[[[],[2]]]],
[744,`${ssf}.model.behave.domain`,22,[[[],[9,[1,49]]]]],
[745,`${ssf}.${mbp}.cured.herb.fraction`,80,[[[21,54],[98,[0,114]]],[[],[2]]]],
[746,`${ssf}.${mbp}.depth`,74,[[[18,48],[99,[0,743]]],[[18,49],[2]],[[],[9,[1,24]]]]],
[747,`${ssf}.${mbp}.dead.extinction.${mois}`,87,[[[18,48],[100,[0,743]]],[[18,49],[2]],[[],[9,[1,45]]]]],
[748,`${ssf}.${mbp}.total.herb.${load}`,90,[[[18,48],[101,[0,743]]],[[18,49],[2]],[[],[9,[1,14]]]]],
[749,`${ssf}.${mbp}.dead.tl1h.${load}`,90,[[[18,48],[102,[0,743]]],[[18,49],[2]],[[],[9,[1,14]]]]],
[750,`${ssf}.${mbp}.dead.tl10h.${load}`,90,[[[18,48],[103,[0,743]]],[[18,49],[2]],[[],[9,[1,14]]]]],
[751,`${ssf}.${mbp}.dead.tl100h.${load}`,90,[[[18,48],[104,[0,743]]],[[18,49],[2]],[[],[9,[1,14]]]]],
[752,`${ssf}.${mbp}.live.stem.${load}`,90,[[[18,48],[105,[0,743]]],[[18,49],[2]],[[],[9,[1,14]]]]],
[753,`${ssf}.${mbp}.dead.tl1h.${savr}`,94,[[[18,48],[106,[0,743]]],[[18,49],[2]],[[],[9,[1,14]]]]],
[754,`${ssf}.${mbp}.live.herb.${savr}`,94,[[[18,48],[107,[0,743]]],[[18,49],[2]],[[],[9,[1,8]]]]],
[755,`${ssf}.${mbp}.live.stem.${savr}`,94,[[[18,48],[108,[0,743]]],[[18,49],[2]],[[],[9,[1,8]]]]],
[756,`${ssf}.${mbp}.dead.${heat}`,83,[[[18,48],[109,[0,743]]],[[18,49],[2]],[[],[9,[1,0]]]]],
[757,`${ssf}.${mbp}.live.${heat}`,83,[[[18,48],[110,[0,743]]],[[18,49],[2]],[[],[9,[1,0]]]]],
[758,`${ssf}.${mbd}.dead.herb.${load}`,90,[[[],[111,[0,748],[0,745]]]]],
[759,`${ssf}.${mbd}.live.herb.${load}`,90,[[[],[112,[0,748],[0,745]]]]],
[760,`${ssf}.model.chaparral.domain`,22,[[[],[9,[1,50]]]]],
[761,`${ssf}.${mcp}.chaparralType`,19,[[[18,48],[113,[0,743]]],[[18,50],[2]],[[],[9,[1,55]]]]],
[762,`${ssf}.${mcp}.observed.deadFuelFraction`,80,[[[18,48],[114,[0,743]]],[[18,50],[2]],[[],[9,[1,14]]]]],
[763,`${ssf}.${mcp}.observed.depth`,74,[[[18,48],[115,[0,743]]],[[18,50],[2]],[[],[9,[1,24]]]]],
[764,`${ssf}.${mcp}.observed.totalLoad`,90,[[[18,48],[116,[0,743]]],[[18,50],[2]],[[],[9,[1,14]]]]],
[765,`${ssf}.${mcp}.applied.totalLoad`,90,[[[22,54],[30,[0,770]]],[[],[30,[0,764]]]]],
[766,`${ssf}.${mcd}.age`,71,[[[],[117,[0,763],[0,761]]]]],
[767,`${ssf}.${mcd}.averageMortality`,110,[[[],[118,[0,766]]]]],
[768,`${ssf}.${mcd}.severeMortality`,110,[[[],[119,[0,766]]]]],
[769,`${ssf}.${mcd}.depth`,74,[[[],[120,[0,766],[0,761]]]]],
[770,`${ssf}.${mcd}.totalLoad`,90,[[[],[121,[0,766],[0,761]]]]],
[771,`${ssf}.${mcd}.deadLoad`,90,[[[],[122,[0,765],[0,762]]]]],
[772,`${ssf}.${mcd}.deadFineLoad`,90,[[[],[123,[0,765],[0,762]]]]],
[773,`${ssf}.${mcd}.deadSmallLoad`,90,[[[],[124,[0,765],[0,762]]]]],
[774,`${ssf}.${mcd}.deadMediumLoad`,90,[[[],[125,[0,765],[0,762]]]]],
[775,`${ssf}.${mcd}.deadLargeLoad`,90,[[[],[126,[0,765],[0,762]]]]],
[776,`${ssf}.${mcd}.liveLoad`,90,[[[],[127,[0,765],[0,762]]]]],
[777,`${ssf}.${mcd}.liveFineLoad`,90,[[[],[128,[0,765],[0,762]]]]],
[778,`${ssf}.${mcd}.liveSmallLoad`,90,[[[],[129,[0,765],[0,762]]]]],
[779,`${ssf}.${mcd}.liveMediumLoad`,90,[[[],[130,[0,765],[0,762]]]]],
[780,`${ssf}.${mcd}.liveLargeLoad`,90,[[[],[131,[0,765],[0,762]]]]],
[781,`${ssf}.${mcd}.liveLeafLoad`,90,[[[],[132,[0,765],[0,762]]]]],
[782,`${ssf}.model.palmettoGallberry.domain`,22,[[[],[9,[1,51]]]]],
[783,`${ssf}.${mpp}.age`,71,[[[18,48],[133,[0,743]]],[[18,51],[2]],[[],[9,[1,14]]]]],
[784,`${ssf}.${mpp}.basalArea`,72,[[[18,48],[134,[0,743]]],[[18,51],[2]],[[],[9,[1,14]]]]],
[785,`${ssf}.${mpp}.cover`,77,[[[18,48],[135,[0,743]]],[[18,51],[2]],[[],[9,[1,14]]]]],
[786,`${ssf}.${mpp}.height`,74,[[[18,48],[136,[0,743]]],[[18,51],[2]],[[],[9,[1,24]]]]],
[787,`${ssf}.${mpd}.depth`,74,[[[],[137,[0,786]]]]],
[788,`${ssf}.${mpd}.deadFineLoad`,90,[[[],[138,[0,783],[0,786]]]]],
[789,`${ssf}.${mpd}.deadSmallLoad`,90,[[[],[139,[0,783],[0,785]]]]],
[790,`${ssf}.${mpd}.deadFoliageLoad`,90,[[[],[140,[0,783],[0,785]]]]],
[791,`${ssf}.${mpd}.deadLitterLoad`,90,[[[],[141,[0,783],[0,784]]]]],
[792,`${ssf}.${mpd}.liveFineLoad`,90,[[[],[142,[0,783],[0,786]]]]],
[793,`${ssf}.${mpd}.liveSmallLoad`,90,[[[],[143,[0,783],[0,786]]]]],
[794,`${ssf}.${mpd}.liveFoliageLoad`,90,[[[],[144,[0,783],[0,785],[0,786]]]]],
[795,`${ssf}.model.westernAspen.domain`,22,[[[],[9,[1,52]]]]],
[796,`${ssf}.${mwp}.aspenType`,30,[[[18,48],[145,[0,743]]],[[18,52],[2]],[[],[9,[1,56]]]]],
[797,`${ssf}.${mwp}.curingLevel`,80,[[[18,48],[146,[0,743]]],[[18,52],[2]],[[],[9,[1,14]]]]],
[798,`${ssf}.${mwd}.depth`,74,[[[],[147,[0,796]]]]],
[799,`${ssf}.${mwd}.dead.fine.${load}`,90,[[[],[148,[0,796],[0,797]]]]],
[800,`${ssf}.${mwd}.dead.small.${load}`,90,[[[],[149,[0,796]]]]],
[801,`${ssf}.${mwd}.dead.fine.${savr}`,90,[[[],[150,[0,796],[0,797]]]]],
[802,`${ssf}.${mwd}.live.herb.${load}`,90,[[[],[151,[0,796],[0,797]]]]],
[803,`${ssf}.${mwd}.live.stem.${load}`,90,[[[],[152,[0,796],[0,797]]]]],
[804,`${ssf}.${mwd}.live.stem.${savr}`,90,[[[],[153,[0,796],[0,797]]]]],
[805,`${swf}.primaryCover`,77,[[[18,53],[9,[1,8]]],[[],[2]]]],
[806,`${swf}.${ews}`,125,[[[],[30,[0,395]]]]],
[807,`${swf}.heading.fromUpslope`,39,[[[],[30,[0,399]]]]],
[808,`${swf}.heading.fromNorth`,39,[[[],[30,[0,400]]]]],
[809,`${swf}.${lwr}`,60,[[[],[30,[0,402]]]]],
[810,`${swf}.wind.speed.atMidflame`,125,[[[],[30,[0,388]]]]],
[811,`${swf}.${waf}`,126,[[[],[30,[0,387]]]]],
[812,`${swf}.${fli}`,56,[[[18,53],[30,[0,396]]],[[],[154,[0,396],[0,730]]]]],
[813,`${swf}.${fl}`,58,[[[18,53],[30,[0,397]]],[[],[154,[0,397],[0,731]]]]],
[814,`${swf}.${hpua}`,59,[[[18,53],[30,[0,401]]],[[],[154,[0,401],[0,735]]]]],
[815,`${swf}.${rxi}`,64,[[[18,53],[30,[0,404]]],[[],[154,[0,404],[0,738]]]]],
[816,`${swf}.${sh}`,67,[[[18,53],[30,[0,405]]],[[],[154,[0,405],[0,739]]]]],
[817,`${swf}.limit.${ews}.exceeded`,33,[[[18,53],[30,[0,364]]],[[],[155,[0,364],[0,698]]]]],
[818,`${swf}.limit.${ews}`,125,[[[18,53],[30,[0,366]]],[[],[83,[0,366],[0,700]]]]],
[819,`${swf}.${ros}`,70,[[[29,57],[30,[0,821]]],[[29,58],[30,[0,822]]],[[],[30,[0,820]]]]],
[820,`${swf}.arithmeticMean.${ros}`,70,[[[18,53],[30,[0,406]]],[[],[156,[0,805],[0,406],[0,740]]]]],
[821,`${swf}.expectedValue.${ros}`,70,[[[18,53],[30,[0,406]]],[[],[157,[0,805],[0,406],[0,740]]]]],
[822,`${swf}.harmonicMean.${ros}`,70,[[[18,53],[30,[0,406]]],[[],[158,[0,805],[0,406],[0,740]]]]],
[823,`${sfe}.axis.eccentricity`,60,[[[],[159,[0,825]]]]],
[824,`${sfe}.axis.${ews}`,125,[[[13,59],[30,[0,806]]],[[],[30,[0,75]]]]],
[825,`${sfe}.axis.${lwr}`,60,[[[13,59],[30,[0,809]]],[[],[30,[0,81]]]]],
[826,`${sfe}.axis.major.${ros}`,70,[[[],[160,[0,860],[0,846]]]]],
[827,`${sfe}.axis.minor.${ros}`,70,[[[],[161,[0,826],[0,825]]]]],
[828,`${sfe}.axis.f.${ros}`,70,[[[],[162,[0,826]]]]],
[829,`${sfe}.axis.g.${ros}`,70,[[[],[163,[0,826],[0,846]]]]],
[830,`${sfe}.axis.h.${ros}`,70,[[[],[164,[0,827]]]]],
[831,`${sfe}.vector.fromHead`,39,[[[30,60],[30,[0,86]]],[[30,61],[18,[0,833],[0,887]]],[[30,62],[18,[0,832],[0,888]]],[[],[18,[0,832],[0,888]]]]],
[832,`${sfe}.vector.fromNorth`,39,[[[30,62],[30,[0,87]]],[[30,60],[19,[0,831],[0,888]]],[[30,61],[19,[0,833],[0,118]]],[[],[19,[0,833],[0,118]]]]],
[833,`${sfe}.vector.fromUpslope`,39,[[[30,61],[30,[0,88]]],[[30,60],[19,[0,831],[0,887]]],[[30,62],[18,[0,832],[0,118]]],[[],[18,[0,832],[0,118]]]]],
[834,`${sfe}.size.area`,53,[[[],[165,[0,835],[0,825]]]]],
[835,`${sfe}.size.length`,69,[[[],[166,[0,826],[0,85]]]]],
[836,`${sfe}.size.perimeter`,69,[[[],[167,[0,835],[0,837]]]]],
[837,`${sfe}.size.width`,69,[[[],[166,[0,827],[0,85]]]]],
[838,`${sfe}.map.area`,105,[[[],[168,[0,834],[0,96]]]]],
[839,`${sfe}.map.length`,107,[[[],[21,[0,835],[0,96]]]]],
[840,`${sfe}.map.perimeter`,107,[[[],[21,[0,836],[0,96]]]]],
[841,`${sfe}.map.width`,107,[[[],[21,[0,837],[0,96]]]]],
[842,`${sfe}.back.spreadDistance`,69,[[[],[166,[0,846],[0,85]]]]],
[843,`${sfe}.back.${fli}`,56,[[[],[169,[0,857],[0,860],[0,846]]]]],
[844,`${sfe}.back.${fl}`,58,[[[],[17,[0,843]]]]],
[845,`${sfe}.back.mapDistance`,107,[[[],[21,[0,842],[0,96]]]]],
[846,`${sfe}.back.${ros}`,70,[[[],[170,[0,860],[0,823]]]]],
[847,`${sfe}.back.${sh}`,67,[[[],[96,[0,843],[0,889],[0,121]]]]],
[848,`${sfe}.back.treeMortality`,110,[[[],[171,[0,59],[0,58],[0,45],[0,41],[0,847]]]]],
[849,`${sfe}.flank.spreadDistance`,69,[[[],[166,[0,853],[0,85]]]]],
[850,`${sfe}.flank.${fli}`,56,[[[],[169,[0,857],[0,860],[0,853]]]]],
[851,`${sfe}.flank.${fl}`,58,[[[],[17,[0,850]]]]],
[852,`${sfe}.flank.mapDistance`,107,[[[],[21,[0,849],[0,96]]]]],
[853,`${sfe}.flank.${ros}`,70,[[[],[172,[0,827]]]]],
[854,`${sfe}.flank.${sh}`,67,[[[],[96,[0,850],[0,889],[0,121]]]]],
[855,`${sfe}.flank.treeMortality`,110,[[[],[171,[0,59],[0,58],[0,45],[0,41],[0,854]]]]],
[856,`${sfe}.head.spreadDistance`,69,[[[],[166,[0,860],[0,85]]]]],
[857,`${sfe}.head.${fli}`,56,[[[13,59],[30,[0,812]]],[[],[30,[0,76]]]]],
[858,`${sfe}.head.${fl}`,58,[[[13,59],[30,[0,813]]],[[],[30,[0,77]]]]],
[859,`${sfe}.head.mapDistance`,107,[[[],[21,[0,856],[0,96]]]]],
[860,`${sfe}.head.${ros}`,70,[[[13,59],[30,[0,819]]],[[],[30,[0,82]]]]],
[861,`${sfe}.head.${sh}`,67,[[[],[96,[0,857],[0,889],[0,121]]]]],
[862,`${sfe}.head.treeMortality`,110,[[[],[171,[0,59],[0,58],[0,45],[0,41],[0,861]]]]],
[863,`${sfe}.psi.spreadDistance`,69,[[[],[166,[0,867],[0,85]]]]],
[864,`${sfe}.psi.${fli}`,56,[[[],[169,[0,857],[0,860],[0,867]]]]],
[865,`${sfe}.psi.${fl}`,58,[[[],[17,[0,864]]]]],
[866,`${sfe}.psi.mapDistance`,107,[[[],[21,[0,863],[0,96]]]]],
[867,`${sfe}.psi.${ros}`,70,[[[],[173,[0,831],[0,828],[0,829],[0,830]]]]],
[868,`${sfe}.psi.${sh}`,67,[[[],[96,[0,864],[0,889],[0,121]]]]],
[869,`${sfe}.psi.treeMortality`,110,[[[],[171,[0,59],[0,58],[0,45],[0,41],[0,868]]]]],
[870,`${sfe}.beta5.spreadDistance`,69,[[[],[166,[0,874],[0,85]]]]],
[871,`${sfe}.beta5.${fli}`,56,[[[],[169,[0,857],[0,860],[0,881]]]]],
[872,`${sfe}.beta5.${fl}`,58,[[[],[17,[0,871]]]]],
[873,`${sfe}.beta5.mapDistance`,107,[[[],[21,[0,870],[0,96]]]]],
[874,`${sfe}.beta5.${ros}`,70,[[[],[30,[0,881]]]]],
[875,`${sfe}.beta5.${sh}`,67,[[[],[96,[0,871],[0,889],[0,121]]]]],
[876,`${sfe}.beta5.treeMortality`,110,[[[],[171,[0,59],[0,58],[0,45],[0,41],[0,875]]]]],
[877,`${sfe}.beta.spreadDistance`,69,[[[],[166,[0,881],[0,85]]]]],
[878,`${sfe}.beta.${fli}`,56,[[[],[169,[0,857],[0,860],[0,886]]]]],
[879,`${sfe}.beta.${fl}`,58,[[[],[17,[0,878]]]]],
[880,`${sfe}.beta.mapDistance`,107,[[[],[21,[0,877],[0,96]]]]],
[881,`${sfe}.beta.${ros}`,70,[[[],[174,[0,831],[0,860],[0,823]]]]],
[882,`${sfe}.beta.${sh}`,67,[[[],[96,[0,878],[0,889],[0,121]]]]],
[883,`${sfe}.beta.treeMortality`,110,[[[],[171,[0,59],[0,58],[0,45],[0,41],[0,882]]]]],
[884,`${sfe}.beta.theta`,39,[[[],[175,[0,831],[0,828],[0,829],[0,830]]]]],
[885,`${sfe}.beta.psi`,39,[[[],[176,[0,884],[0,828],[0,830]]]]],
[886,`${sfe}.beta.psiSpreadRate`,70,[[[],[173,[0,885],[0,828],[0,829],[0,830]]]]],
[887,`${sfe}.heading.fromUpslope`,39,[[[13,59],[30,[0,807]]],[[],[30,[0,78]]]]],
[888,`${sfe}.heading.fromNorth`,39,[[[],[19,[0,118],[0,887]]]]],
[889,`${sfe}.wind.speed.atMidflame`,125,[[[13,59],[30,[0,810]]],[[],[30,[0,135]]]]],
[890,`site.terrain.spotSourceLocation`,27,[[[],[2]]]],
[891,`site.terrain.ridgeValleyDistance`,68,[[[],[2]]]],
[892,`site.terrain.ridgeValleyElevation`,69,[[[],[2]]]],
[893,`${spotb}.firebrand.criticalCoverHeight`,123,[[[],[177,[0,894],[0,56]]]]],
[894,`${spotb}.firebrand.height`,123,[[[],[178,[0,899]]]]],
[895,`${spotb}.firebrand.drift`,68,[[[],[9,[1,14]]]]],
[896,`${spotb}.spotDistance.flatTerrain`,68,[[[],[179,[0,894],[0,893],[0,134]]]]],
[897,`${spotb}.spotDistance.flatTerrainWithDrift`,68,[[[],[180,[0,896],[0,895]]]]],
[898,`${spotb}.spotDistance.mountainTerrain`,68,[[[],[181,[0,897],[0,890],[0,891],[0,892]]]]],
[899,`${spotb}.flameHeight`,58,[[[],[2]]]],
[900,`${spotc}.firebrand.criticalCoverHeight`,123,[[[],[9,[1,14]]]]],
[901,`${spotc}.firebrand.height`,123,[[[],[182,[0,907]]]]],
[902,`${spotc}.firebrand.drift`,68,[[[],[183,[0,907]]]]],
[903,`${spotc}.spotDistance.flatTerrain`,68,[[[],[184,[0,907]]]]],
[904,`${spotc}.spotDistance.flatTerrainWithDrift`,68,[[[],[185,[0,907]]]]],
[905,`${spotc}.spotDistance.mountainTerrain`,68,[[[],[181,[0,904],[0,890],[0,891],[0,892]]]]],
[906,`${spotc}.${fli}`,56,[[[11,63],[30,[0,1213]]],[[],[186,[0,84]]]]],
[907,`${spotc}.firebrandObject`,115,[[[],[187,[0,45],[0,134],[0,906]]]]],
[908,`${spots}.firebrand.criticalCoverHeight`,123,[[[],[177,[0,910],[0,56]]]]],
[909,`${spots}.${fli}`,56,[[[15,59],[30,[0,812]]],[[],[30,[0,76]]]]],
[910,`${spots}.firebrand.height`,123,[[[],[188,[0,909],[0,134]]]]],
[911,`${spots}.firebrand.drift`,68,[[[],[189,[0,910],[0,134]]]]],
[912,`${spots}.spotDistance.flatTerrain`,68,[[[],[179,[0,910],[0,908],[0,134]]]]],
[913,`${spots}.spotDistance.flatTerrainWithDrift`,68,[[[],[180,[0,912],[0,911]]]]],
[914,`${spots}.spotDistance.mountainTerrain`,68,[[[],[181,[0,913],[0,890],[0,891],[0,892]]]]],
[915,`${spott}.firebrand.criticalCoverHeight`,123,[[[],[177,[0,916],[0,56]]]]],
[916,`${spott}.firebrand.height`,123,[[[],[190,[0,922],[0,925],[0,926]]]]],
[917,`${spott}.firebrand.drift`,68,[[[],[9,[1,14]]]]],
[918,`${spott}.spotDistance.flatTerrain`,68,[[[],[179,[0,916],[0,915],[0,134]]]]],
[919,`${spott}.spotDistance.flatTerrainWithDrift`,68,[[[],[180,[0,918],[0,917]]]]],
[920,`${spott}.spotDistance.mountainTerrain`,68,[[[],[181,[0,919],[0,890],[0,891],[0,892]]]]],
[921,`${spott}.species`,28,[[[],[2]]]],
[922,`${spott}.height`,123,[[[],[2]]]],
[923,`${spott}.dbh`,122,[[[],[2]]]],
[924,`${spott}.count`,121,[[[],[2]]]],
[925,`${spott}.flameHeight`,58,[[[],[191,[0,921],[0,923],[0,924]]]]],
[926,`${spott}.flameDuration`,57,[[[],[192,[0,921],[0,923],[0,924]]]]],
[927,`scorch.height`,67,[[[14,64],[96,[0,76],[0,135],[0,121]]],[[],[30,[0,816]]]]],
[928,`mortality.${sh}`,67,[[[16,64],[30,[0,83]]],[[],[30,[0,927]]]]],
[929,`mortality.rate`,110,[[[],[171,[0,59],[0,58],[0,45],[0,41],[0,928]]]]],
[930,`mortality.crownLengthScorched`,110,[[[],[193,[0,45],[0,41],[0,928]]]]],
[931,`mortality.crownVolumeScorched`,110,[[[],[194,[0,45],[0,41],[0,928]]]]],
[932,`${ccfbdp}1.${dens}`,91,[[[],[9,[1,18]]]]],
[933,`${ccfbdp}1.${heat}`,83,[[[],[9,[1,0]]]]],
[934,`${ccfbdp}1.${load}`,90,[[[],[9,[1,65]]]]],
[935,`${ccfbdp}1.${mois}`,87,[[[],[30,[0,110]]]]],
[936,`${ccfbdp}1.${savr}`,94,[[[],[9,[1,35]]]]],
[937,`${ccfbdp}1.${emc}`,82,[[[],[9,[1,24]]]]],
[938,`${ccfbdp}1.${tmc}`,98,[[[],[9,[1,26]]]]],
[939,`${ccfbdp}2.${dens}`,91,[[[],[9,[1,18]]]]],
[940,`${ccfbdp}2.${heat}`,83,[[[],[9,[1,0]]]]],
[941,`${ccfbdp}2.${load}`,90,[[[],[9,[1,66]]]]],
[942,`${ccfbdp}2.${mois}`,87,[[[],[30,[0,111]]]]],
[943,`${ccfbdp}2.${savr}`,94,[[[],[9,[1,30]]]]],
[944,`${ccfbdp}2.${emc}`,82,[[[],[9,[1,24]]]]],
[945,`${ccfbdp}2.${tmc}`,98,[[[],[9,[1,26]]]]],
[946,`${ccfbdp}3.${dens}`,91,[[[],[9,[1,18]]]]],
[947,`${ccfbdp}3.${heat}`,83,[[[],[9,[1,0]]]]],
[948,`${ccfbdp}3.${load}`,90,[[[],[9,[1,67]]]]],
[949,`${ccfbdp}3.${mois}`,87,[[[],[30,[0,112]]]]],
[950,`${ccfbdp}3.${savr}`,94,[[[],[9,[1,20]]]]],
[951,`${ccfbdp}3.${emc}`,82,[[[],[9,[1,24]]]]],
[952,`${ccfbdp}3.${tmc}`,98,[[[],[9,[1,26]]]]],
[953,`${ccfbdp}4.${dens}`,91,[[[],[9,[1,18]]]]],
[954,`${ccfbdp}4.${heat}`,83,[[[],[9,[1,0]]]]],
[955,`${ccfbdp}4.${load}`,90,[[[],[9,[1,14]]]]],
[956,`${ccfbdp}4.${mois}`,87,[[[],[30,[0,110]]]]],
[957,`${ccfbdp}4.${savr}`,94,[[[],[9,[1,68]]]]],
[958,`${ccfbdp}4.${emc}`,82,[[[],[9,[1,24]]]]],
[959,`${ccfbdp}4.${tmc}`,98,[[[],[9,[1,26]]]]],
[960,`${ccfbdp}5.${dens}`,91,[[[],[9,[1,18]]]]],
[961,`${ccfbdp}5.${heat}`,83,[[[],[9,[1,0]]]]],
[962,`${ccfbdp}5.${load}`,90,[[[],[9,[1,14]]]]],
[963,`${ccfbdp}5.${mois}`,87,[[[],[9,[1,33]]]]],
[964,`${ccfbdp}5.${savr}`,94,[[[],[9,[1,8]]]]],
[965,`${ccfbdp}5.${emc}`,82,[[[],[9,[1,24]]]]],
[966,`${ccfbdp}5.${tmc}`,98,[[[],[9,[1,26]]]]],
[967,`${ccfblp}1.${dens}`,91,[[[],[9,[1,18]]]]],
[968,`${ccfblp}1.${heat}`,83,[[[],[9,[1,0]]]]],
[969,`${ccfblp}1.${load}`,90,[[[],[9,[1,14]]]]],
[970,`${ccfblp}1.${mois}`,87,[[[],[30,[0,114]]]]],
[971,`${ccfblp}1.${savr}`,94,[[[],[9,[1,68]]]]],
[972,`${ccfblp}1.${emc}`,82,[[[],[9,[1,24]]]]],
[973,`${ccfblp}1.${tmc}`,98,[[[],[9,[1,26]]]]],
[974,`${ccfblp}2.${dens}`,91,[[[],[9,[1,18]]]]],
[975,`${ccfblp}2.${heat}`,83,[[[],[9,[1,0]]]]],
[976,`${ccfblp}2.${load}`,90,[[[],[9,[1,66]]]]],
[977,`${ccfblp}2.${mois}`,87,[[[],[30,[0,115]]]]],
[978,`${ccfblp}2.${savr}`,94,[[[],[9,[1,68]]]]],
[979,`${ccfblp}2.${emc}`,82,[[[],[9,[1,24]]]]],
[980,`${ccfblp}2.${tmc}`,98,[[[],[9,[1,26]]]]],
[981,`${ccfblp}3.${dens}`,91,[[[],[9,[1,18]]]]],
[982,`${ccfblp}3.${heat}`,83,[[[],[9,[1,0]]]]],
[983,`${ccfblp}3.${load}`,90,[[[],[9,[1,14]]]]],
[984,`${ccfblp}3.${mois}`,87,[[[],[9,[1,33]]]]],
[985,`${ccfblp}3.${savr}`,94,[[[],[9,[1,8]]]]],
[986,`${ccfblp}3.${emc}`,82,[[[],[9,[1,24]]]]],
[987,`${ccfblp}3.${tmc}`,98,[[[],[9,[1,26]]]]],
[988,`${ccfblp}4.${dens}`,91,[[[],[9,[1,18]]]]],
[989,`${ccfblp}4.${heat}`,83,[[[],[9,[1,0]]]]],
[990,`${ccfblp}4.${load}`,90,[[[],[9,[1,14]]]]],
[991,`${ccfblp}4.${mois}`,87,[[[],[9,[1,33]]]]],
[992,`${ccfblp}4.${savr}`,94,[[[],[9,[1,8]]]]],
[993,`${ccfblp}4.${emc}`,82,[[[],[9,[1,24]]]]],
[994,`${ccfblp}4.${tmc}`,98,[[[],[9,[1,26]]]]],
[995,`${ccfblp}5.${dens}`,91,[[[],[9,[1,18]]]]],
[996,`${ccfblp}5.${heat}`,83,[[[],[9,[1,0]]]]],
[997,`${ccfblp}5.${load}`,90,[[[],[9,[1,14]]]]],
[998,`${ccfblp}5.${mois}`,87,[[[],[9,[1,33]]]]],
[999,`${ccfblp}5.${savr}`,94,[[[],[9,[1,8]]]]],
[1000,`${ccfblp}5.${emc}`,82,[[[],[9,[1,24]]]]],
[1001,`${ccfblp}5.${tmc}`,98,[[[],[9,[1,26]]]]],
[1002,`${ccfbdp}1.${ef}.${ehn}`,81,[[[],[40,[0,936]]]]],
[1003,`${ccfbdp}1.${ef}.${load}`,90,[[[],[41,[0,936],[0,934],[1,29]]]]],
[1004,`${ccfbdp}1.${qig}`,84,[[[],[42,[0,935],[0,1002]]]]],
[1005,`${ccfbdp}1.net.${load}`,90,[[[],[43,[0,934],[0,938]]]]],
[1006,`${ccfbdp}1.${sc}`,92,[[[],[44,[0,936]]]]],
[1007,`${ccfbdp}1.${sc}.${wf}`,124,[[[],[45,[0,1006],[0,1113]]]]],
[1008,`${ccfbdp}1.${sa}`,93,[[[],[46,[0,934],[0,936],[0,932]]]]],
[1009,`${ccfbdp}1.${sa}.${wf}`,124,[[[],[47,[0,1008],[0,1097]]]]],
[1010,`${ccfbdp}1.volume`,99,[[[],[48,[0,934],[0,932]]]]],
[1011,`${ccfbdp}1.${ef}.waterLoad`,90,[[[],[49,[0,1003],[0,935]]]]],
[1012,`${ccfbdp}2.${ef}.${ehn}`,81,[[[],[40,[0,943]]]]],
[1013,`${ccfbdp}2.${ef}.${load}`,90,[[[],[41,[0,943],[0,941],[1,29]]]]],
[1014,`${ccfbdp}2.${qig}`,84,[[[],[42,[0,942],[0,1012]]]]],
[1015,`${ccfbdp}2.net.${load}`,90,[[[],[43,[0,941],[0,945]]]]],
[1016,`${ccfbdp}2.${sc}`,92,[[[],[44,[0,943]]]]],
[1017,`${ccfbdp}2.${sc}.${wf}`,124,[[[],[45,[0,1016],[0,1113]]]]],
[1018,`${ccfbdp}2.${sa}`,93,[[[],[46,[0,941],[0,943],[0,939]]]]],
[1019,`${ccfbdp}2.${sa}.${wf}`,124,[[[],[47,[0,1018],[0,1097]]]]],
[1020,`${ccfbdp}2.volume`,99,[[[],[48,[0,941],[0,939]]]]],
[1021,`${ccfbdp}2.${ef}.waterLoad`,90,[[[],[49,[0,1013],[0,942]]]]],
[1022,`${ccfbdp}3.${ef}.${ehn}`,81,[[[],[40,[0,950]]]]],
[1023,`${ccfbdp}3.${ef}.${load}`,90,[[[],[41,[0,950],[0,948],[1,29]]]]],
[1024,`${ccfbdp}3.${qig}`,84,[[[],[42,[0,949],[0,1022]]]]],
[1025,`${ccfbdp}3.net.${load}`,90,[[[],[43,[0,948],[0,952]]]]],
[1026,`${ccfbdp}3.${sc}`,92,[[[],[44,[0,950]]]]],
[1027,`${ccfbdp}3.${sc}.${wf}`,124,[[[],[45,[0,1026],[0,1113]]]]],
[1028,`${ccfbdp}3.${sa}`,93,[[[],[46,[0,948],[0,950],[0,946]]]]],
[1029,`${ccfbdp}3.${sa}.${wf}`,124,[[[],[47,[0,1028],[0,1097]]]]],
[1030,`${ccfbdp}3.volume`,99,[[[],[48,[0,948],[0,946]]]]],
[1031,`${ccfbdp}3.${ef}.waterLoad`,90,[[[],[49,[0,1023],[0,949]]]]],
[1032,`${ccfbdp}4.${ef}.${ehn}`,81,[[[],[40,[0,957]]]]],
[1033,`${ccfbdp}4.${ef}.${load}`,90,[[[],[41,[0,957],[0,955],[1,29]]]]],
[1034,`${ccfbdp}4.${qig}`,84,[[[],[42,[0,956],[0,1032]]]]],
[1035,`${ccfbdp}4.net.${load}`,90,[[[],[43,[0,955],[0,959]]]]],
[1036,`${ccfbdp}4.${sc}`,92,[[[],[44,[0,957]]]]],
[1037,`${ccfbdp}4.${sc}.${wf}`,124,[[[],[45,[0,1036],[0,1113]]]]],
[1038,`${ccfbdp}4.${sa}`,93,[[[],[46,[0,955],[0,957],[0,953]]]]],
[1039,`${ccfbdp}4.${sa}.${wf}`,124,[[[],[47,[0,1038],[0,1097]]]]],
[1040,`${ccfbdp}4.volume`,99,[[[],[48,[0,955],[0,953]]]]],
[1041,`${ccfbdp}4.${ef}.waterLoad`,90,[[[],[49,[0,1033],[0,956]]]]],
[1042,`${ccfbdp}5.${ef}.${ehn}`,81,[[[],[40,[0,964]]]]],
[1043,`${ccfbdp}5.${ef}.${load}`,90,[[[],[41,[0,964],[0,962],[1,29]]]]],
[1044,`${ccfbdp}5.${qig}`,84,[[[],[42,[0,963],[0,1042]]]]],
[1045,`${ccfbdp}5.net.${load}`,90,[[[],[43,[0,962],[0,966]]]]],
[1046,`${ccfbdp}5.${sc}`,92,[[[],[44,[0,964]]]]],
[1047,`${ccfbdp}5.${sc}.${wf}`,124,[[[],[45,[0,1046],[0,1113]]]]],
[1048,`${ccfbdp}5.${sa}`,93,[[[],[46,[0,962],[0,964],[0,960]]]]],
[1049,`${ccfbdp}5.${sa}.${wf}`,124,[[[],[47,[0,1048],[0,1097]]]]],
[1050,`${ccfbdp}5.volume`,99,[[[],[48,[0,962],[0,960]]]]],
[1051,`${ccfbdp}5.${ef}.waterLoad`,90,[[[],[49,[0,1043],[0,963]]]]],
[1052,`${ccfblp}1.${ef}.${ehn}`,81,[[[],[40,[0,971]]]]],
[1053,`${ccfblp}1.${ef}.${load}`,90,[[[],[41,[0,971],[0,969],[1,39]]]]],
[1054,`${ccfblp}1.${qig}`,84,[[[],[42,[0,970],[0,1052]]]]],
[1055,`${ccfblp}1.net.${load}`,90,[[[],[43,[0,969],[0,973]]]]],
[1056,`${ccfblp}1.${sc}`,92,[[[],[44,[0,971]]]]],
[1057,`${ccfblp}1.${sc}.${wf}`,124,[[[],[45,[0,1056],[0,1133]]]]],
[1058,`${ccfblp}1.${sa}`,93,[[[],[46,[0,969],[0,971],[0,967]]]]],
[1059,`${ccfblp}1.${sa}.${wf}`,124,[[[],[47,[0,1058],[0,1117]]]]],
[1060,`${ccfblp}1.volume`,99,[[[],[48,[0,969],[0,967]]]]],
[1061,`${ccfblp}2.${ef}.${ehn}`,81,[[[],[40,[0,978]]]]],
[1062,`${ccfblp}2.${ef}.${load}`,90,[[[],[41,[0,978],[0,976],[1,39]]]]],
[1063,`${ccfblp}2.${qig}`,84,[[[],[42,[0,977],[0,1061]]]]],
[1064,`${ccfblp}2.net.${load}`,90,[[[],[43,[0,976],[0,980]]]]],
[1065,`${ccfblp}2.${sc}`,92,[[[],[44,[0,978]]]]],
[1066,`${ccfblp}2.${sc}.${wf}`,124,[[[],[45,[0,1065],[0,1133]]]]],
[1067,`${ccfblp}2.${sa}`,93,[[[],[46,[0,976],[0,978],[0,974]]]]],
[1068,`${ccfblp}2.${sa}.${wf}`,124,[[[],[47,[0,1067],[0,1117]]]]],
[1069,`${ccfblp}2.volume`,99,[[[],[48,[0,976],[0,974]]]]],
[1070,`${ccfblp}3.${ef}.${ehn}`,81,[[[],[40,[0,985]]]]],
[1071,`${ccfblp}3.${ef}.${load}`,90,[[[],[41,[0,985],[0,983],[1,39]]]]],
[1072,`${ccfblp}3.${qig}`,84,[[[],[42,[0,984],[0,1070]]]]],
[1073,`${ccfblp}3.net.${load}`,90,[[[],[43,[0,983],[0,987]]]]],
[1074,`${ccfblp}3.${sc}`,92,[[[],[44,[0,985]]]]],
[1075,`${ccfblp}3.${sc}.${wf}`,124,[[[],[45,[0,1074],[0,1133]]]]],
[1076,`${ccfblp}3.${sa}`,93,[[[],[46,[0,983],[0,985],[0,981]]]]],
[1077,`${ccfblp}3.${sa}.${wf}`,124,[[[],[47,[0,1076],[0,1117]]]]],
[1078,`${ccfblp}3.volume`,99,[[[],[48,[0,983],[0,981]]]]],
[1079,`${ccfblp}4.${ef}.${ehn}`,81,[[[],[40,[0,992]]]]],
[1080,`${ccfblp}4.${ef}.${load}`,90,[[[],[41,[0,992],[0,990],[1,39]]]]],
[1081,`${ccfblp}4.${qig}`,84,[[[],[42,[0,991],[0,1079]]]]],
[1082,`${ccfblp}4.net.${load}`,90,[[[],[43,[0,990],[0,994]]]]],
[1083,`${ccfblp}4.${sc}`,92,[[[],[44,[0,992]]]]],
[1084,`${ccfblp}4.${sc}.${wf}`,124,[[[],[45,[0,1083],[0,1133]]]]],
[1085,`${ccfblp}4.${sa}`,93,[[[],[46,[0,990],[0,992],[0,988]]]]],
[1086,`${ccfblp}4.${sa}.${wf}`,124,[[[],[47,[0,1085],[0,1117]]]]],
[1087,`${ccfblp}4.volume`,99,[[[],[48,[0,990],[0,988]]]]],
[1088,`${ccfblp}5.${ef}.${ehn}`,81,[[[],[40,[0,999]]]]],
[1089,`${ccfblp}5.${ef}.${load}`,90,[[[],[41,[0,999],[0,997],[1,39]]]]],
[1090,`${ccfblp}5.${qig}`,84,[[[],[42,[0,998],[0,1088]]]]],
[1091,`${ccfblp}5.net.${load}`,90,[[[],[43,[0,997],[0,1001]]]]],
[1092,`${ccfblp}5.${sc}`,92,[[[],[44,[0,999]]]]],
[1093,`${ccfblp}5.${sc}.${wf}`,124,[[[],[45,[0,1092],[0,1133]]]]],
[1094,`${ccfblp}5.${sa}`,93,[[[],[46,[0,997],[0,999],[0,995]]]]],
[1095,`${ccfblp}5.${sa}.${wf}`,124,[[[],[47,[0,1094],[0,1117]]]]],
[1096,`${ccfblp}5.volume`,99,[[[],[48,[0,997],[0,995]]]]],
[1097,`${ccfbd}.${sa}`,93,[[[],[50,[0,1008],[0,1018],[0,1028],[0,1038],[0,1048]]]]],
[1098,`${ccfbd}.${sa}.${wf}`,124,[[[],[21,[0,1097],[0,1152]]]]],
[1099,`${ccfbd}.mineralDamping`,54,[[[],[51,[0,1112]]]]],
[1100,`${ccfbd}.moistureDamping`,54,[[[],[52,[0,1106],[0,1104]]]]],
[1101,`${ccfbd}.${heat}`,83,[[[],[53,[0,1009],[0,1019],[0,1029],[0,1039],[0,1049],[0,933],[0,940],[0,947],[0,954],[0,961]]]]],
[1102,`${ccfbd}.${load}`,90,[[[],[50,[0,934],[0,941],[0,948],[0,955],[0,962]]]]],
[1103,`${ccfbd}.${ef}.${load}`,90,[[[],[50,[0,1003],[0,1013],[0,1023],[0,1033],[0,1043]]]]],
[1104,`${ccfbd}.extinction.${mois}`,87,[[[],[9,[1,45]]]]],
[1105,`${ccfbd}.extinction.${mois}Factor`,36,[[[],[54,[0,1103],[0,1123]]]]],
[1106,`${ccfbd}.${mois}`,87,[[[],[53,[0,1009],[0,1019],[0,1029],[0,1039],[0,1049],[0,935],[0,942],[0,949],[0,956],[0,963]]]]],
[1107,`${ccfbd}.volume`,74,[[[],[50,[0,1010],[0,1020],[0,1030],[0,1040],[0,1050]]]]],
[1108,`${ccfbd}.${qig}`,84,[[[],[53,[0,1009],[0,1019],[0,1029],[0,1039],[0,1049],[0,1004],[0,1014],[0,1024],[0,1034],[0,1044]]]]],
[1109,`${ccfbd}.${rxi}`,64,[[[],[22,[0,1110],[0,1100]]]]],
[1110,`${ccfbd}.${rxi}Dry`,64,[[[],[55,[0,1149],[0,1114],[0,1101],[0,1099]]]]],
[1111,`${ccfbd}.${savr}`,94,[[[],[53,[0,1009],[0,1019],[0,1029],[0,1039],[0,1049],[0,936],[0,943],[0,950],[0,957],[0,964]]]]],
[1112,`${ccfbd}.${emc}`,82,[[[],[53,[0,1009],[0,1019],[0,1029],[0,1039],[0,1049],[0,937],[0,944],[0,951],[0,958],[0,965]]]]],
[1113,`${ccfbd}.${sc}.${wf}`,124,[[[],[56,[0,1008],[0,1006],[0,1018],[0,1016],[0,1028],[0,1026],[0,1038],[0,1036],[0,1048],[0,1046]]]]],
[1114,`${ccfbd}.net.${load}`,90,[[[],[53,[0,1007],[0,1017],[0,1027],[0,1037],[0,1047],[0,1005],[0,1015],[0,1025],[0,1035],[0,1045]]]]],
[1115,`${ccfbd}.${ef}.waterLoad`,90,[[[],[50,[0,1011],[0,1021],[0,1031],[0,1041],[0,1051]]]]],
[1116,`${ccfbd}.${ef}.${mois}`,87,[[[],[21,[0,1115],[0,1103]]]]],
[1117,`${ccfbl}.${sa}`,93,[[[],[50,[0,1058],[0,1067],[0,1076],[0,1085],[0,1094]]]]],
[1118,`${ccfbl}.${sa}.${wf}`,124,[[[],[21,[0,1117],[0,1152]]]]],
[1119,`${ccfbl}.mineralDamping`,54,[[[],[51,[0,1132]]]]],
[1120,`${ccfbl}.moistureDamping`,54,[[[],[52,[0,1126],[0,1124]]]]],
[1121,`${ccfbl}.${heat}`,83,[[[],[53,[0,1059],[0,1068],[0,1077],[0,1086],[0,1095],[0,968],[0,975],[0,982],[0,989],[0,996]]]]],
[1122,`${ccfbl}.${load}`,90,[[[],[50,[0,969],[0,976],[0,983],[0,990],[0,997]]]]],
[1123,`${ccfbl}.${ef}.${load}`,90,[[[],[50,[0,1053],[0,1062],[0,1071],[0,1080],[0,1089]]]]],
[1124,`${ccfbl}.extinction.${mois}`,87,[[[],[57,[0,1125],[0,1116],[0,1104]]]]],
[1125,`${ccfbl}.extinction.${mois}Factor`,36,[[[],[54,[0,1103],[0,1123]]]]],
[1126,`${ccfbl}.${mois}`,87,[[[],[53,[0,1059],[0,1068],[0,1077],[0,1086],[0,1095],[0,970],[0,977],[0,984],[0,991],[0,998]]]]],
[1127,`${ccfbl}.volume`,74,[[[],[50,[0,1060],[0,1069],[0,1078],[0,1087],[0,1096]]]]],
[1128,`${ccfbl}.${qig}`,84,[[[],[53,[0,1059],[0,1068],[0,1077],[0,1086],[0,1095],[0,1054],[0,1063],[0,1072],[0,1081],[0,1090]]]]],
[1129,`${ccfbl}.${rxi}`,64,[[[],[22,[0,1130],[0,1120]]]]],
[1130,`${ccfbl}.${rxi}Dry`,64,[[[],[55,[0,1149],[0,1134],[0,1121],[0,1119]]]]],
[1131,`${ccfbl}.${savr}`,94,[[[],[53,[0,1059],[0,1068],[0,1077],[0,1086],[0,1095],[0,971],[0,978],[0,985],[0,992],[0,999]]]]],
[1132,`${ccfbl}.${emc}`,82,[[[],[53,[0,1059],[0,1068],[0,1077],[0,1086],[0,1095],[0,972],[0,979],[0,986],[0,993],[0,1000]]]]],
[1133,`${ccfbl}.${sc}.${wf}`,124,[[[],[56,[0,1058],[0,1056],[0,1067],[0,1065],[0,1076],[0,1074],[0,1085],[0,1083],[0,1094],[0,1092]]]]],
[1134,`${ccfbl}.net.${load}`,90,[[[],[53,[0,1057],[0,1066],[0,1075],[0,1084],[0,1093],[0,1055],[0,1064],[0,1073],[0,1082],[0,1091]]]]],
[1135,`${ccfb}.depth`,74,[[[],[9,[1,8]]]]],
[1136,`${ccfb}.bulkDensity`,73,[[[],[21,[0,1140],[0,1135]]]]],
[1137,`${ccfb}.${qig}`,75,[[[],[53,[0,1098],[0,1118],[0,1108],[0,1128]]]]],
[1138,`${ccfb}.heatSink`,85,[[[],[58,[0,1137],[0,1136]]]]],
[1139,`${ccfb}.noWindNoSlope.${ros}`,70,[[[],[59,[0,1146],[0,1145],[0,1138]]]]],
[1140,`${ccfb}.${load}`,90,[[[],[50,[0,1102],[0,1122]]]]],
[1141,`${ccfb}.open.${waf}`,126,[[[],[60,[0,1135]]]]],
[1142,`${ccfb}.packingRatio`,76,[[[],[61,[0,1107],[0,1127],[0,1135]]]]],
[1143,`${ccfb}.packingRatio.optimum`,76,[[[],[62,[0,1150]]]]],
[1144,`${ccfb}.packingRatio.ratio`,76,[[[],[21,[0,1142],[0,1143]]]]],
[1145,`${ccfb}.propagatingFluxRatio`,63,[[[],[63,[0,1150],[0,1142]]]]],
[1146,`${ccfb}.${rxi}`,64,[[[],[50,[0,1109],[0,1129]]]]],
[1147,`${ccfb}.reactionVelocityExponent`,36,[[[],[64,[0,1150]]]]],
[1148,`${ccfb}.reactionVelocityMaximum`,65,[[[],[65,[0,1151]]]]],
[1149,`${ccfb}.reactionVelocityOptimum`,65,[[[],[66,[0,1144],[0,1148],[0,1147]]]]],
[1150,`${ccfb}.${savr}`,94,[[[],[53,[0,1098],[0,1118],[0,1111],[0,1131]]]]],
[1151,`${ccfb}.savr15`,36,[[[],[67,[0,1150]]]]],
[1152,`${ccfb}.${sa}`,93,[[[],[50,[0,1097],[0,1117]]]]],
[1153,`${ccff}.maximumDirection.slope.${ros}`,70,[[[],[68,[0,1202],[0,1166]]]]],
[1154,`${ccff}.maximumDirection.wind.${ros}`,70,[[[],[69,[0,1202],[0,1189]]]]],
[1155,`${ccff}.wind.heading.fromUpslope`,39,[[[],[9,[1,14]]]]],
[1156,`${ccff}.maximumDirection.xComponent`,36,[[[],[70,[0,1154],[0,1153],[0,1155]]]]],
[1157,`${ccff}.maximumDirection.yComponent`,36,[[[],[71,[0,1154],[0,1155]]]]],
[1158,`${ccff}.maximumDirection.${ros}`,70,[[[],[72,[0,1156],[0,1157]]]]],
[1159,`${ccff}.limit.${ews}.exceeded`,33,[[[],[73,[0,1170],[0,1161]]]]],
[1160,`${ccff}.limit.${ros}.exceeded`,34,[[[],[73,[0,1172],[0,1178]]]]],
[1161,`${ccff}.limit.${ews}`,125,[[[],[74,[0,1199]]]]],
[1162,`${ccff}.limit.windSlopeSpreadRateCoefficient`,36,[[[],[75,[0,1161],[0,1184],[0,1187]]]]],
[1163,`${ccff}.limit.${ros}`,70,[[[],[76,[0,1202],[0,1162]]]]],
[1164,`${ccff}.slope.ratio`,114,[[[],[9,[1,14]]]]],
[1165,`${ccff}.slope.k`,36,[[[],[77,[0,1142]]]]],
[1166,`${ccff}.slope.phi`,36,[[[],[78,[0,1164],[0,1165]]]]],
[1167,`${ccff}.spread.step1.${ews}`,125,[[[],[79,[0,1168],[0,1184],[0,1188]]]]],
[1168,`${ccff}.spread.step1.${phiew}`,36,[[[],[80,[0,1189],[0,1166]]]]],
[1169,`${ccff}.spread.step1.${ros}`,70,[[[],[76,[0,1202],[0,1168]]]]],
[1170,`${ccff}.spread.step2.${ews}`,125,[[[],[79,[0,1171],[0,1184],[0,1188]]]]],
[1171,`${ccff}.spread.step2.${phiew}`,36,[[[],[81,[0,1202],[0,1172]]]]],
[1172,`${ccff}.spread.step2.${ros}`,70,[[[],[82,[0,1202],[0,1158]]]]],
[1173,`${ccff}.spread.step3a.${ews}`,125,[[[],[83,[0,1170],[0,1161]]]]],
[1174,`${ccff}.spread.step3a.${phiew}`,36,[[[],[83,[0,1171],[0,1162]]]]],
[1175,`${ccff}.spread.step3a.${ros}`,70,[[[],[83,[0,1172],[0,1163]]]]],
[1176,`${ccff}.spread.step3b.${ews}`,125,[[[],[79,[0,1177],[0,1184],[0,1188]]]]],
[1177,`${ccff}.spread.step3b.${phiew}`,36,[[[],[81,[0,1202],[0,1178]]]]],
[1178,`${ccff}.spread.step3b.${ros}`,70,[[[],[84,[0,1172],[0,1170]]]]],
[1179,`${ccff}.spread.step4.${ews}`,125,[[[],[79,[0,1180],[0,1184],[0,1188]]]]],
[1180,`${ccff}.spread.step4.${phiew}`,36,[[[],[81,[0,1202],[0,1181]]]]],
[1181,`${ccff}.spread.step4.${ros}`,70,[[[],[84,[0,1175],[0,1173]]]]],
[1182,`${ccff}.${waf}`,126,[[[],[9,[1,44]]]]],
[1183,`${ccff}.wind.speed.atMidflame`,125,[[[25,17],[30,[0,135]]],[[],[38,[0,134],[0,1182]]]]],
[1184,`${ccff}.wind.factor.b`,36,[[[],[86,[0,1150]]]]],
[1185,`${ccff}.wind.factor.c`,36,[[[],[87,[0,1150]]]]],
[1186,`${ccff}.wind.factor.e`,36,[[[],[88,[0,1150]]]]],
[1187,`${ccff}.wind.factor.k`,36,[[[],[89,[0,1144],[0,1186],[0,1185]]]]],
[1188,`${ccff}.wind.factor.i`,36,[[[],[90,[0,1144],[0,1186],[0,1185]]]]],
[1189,`${ccff}.wind.phi`,36,[[[],[91,[0,1183],[0,1184],[0,1187]]]]],
[1190,`${ccff}.${ews}`,125,[[[28,47],[30,[0,1179]]],[[],[30,[0,1176]]]]],
[1191,`${ccff}.${fli}`,56,[[[],[92,[0,1201],[0,1199],[0,1193]]]]],
[1192,`${ccff}.${fl}`,58,[[[],[17,[0,1191]]]]],
[1193,`${ccff}.${taur}`,66,[[[],[93,[0,1150]]]]],
[1194,`${ccff}.heading.fromUpslope`,39,[[[],[94,[0,1156],[0,1157],[0,1158]]]]],
[1195,`${ccff}.heading.fromNorth`,39,[[[],[19,[0,118],[0,1194]]]]],
[1196,`${ccff}.${hpua}`,59,[[[],[95,[0,1199],[0,1193]]]]],
[1197,`${ccff}.${lwr}`,60,[[[],[20,[0,1190]]]]],
[1198,`${ccff}.${phiew}`,36,[[[28,47],[30,[0,1180]]],[[],[30,[0,1177]]]]],
[1199,`${ccff}.${rxi}`,64,[[[],[30,[0,1146]]]]],
[1200,`${ccff}.${sh}`,67,[[[],[96,[0,1191],[0,1183],[0,121]]]]],
[1201,`${ccff}.${ros}`,70,[[[28,47],[30,[0,1181]]],[[],[30,[0,1178]]]]],
[1202,`${ccff}.noWindNoSlope.${ros}`,70,[[[],[30,[0,1139]]]]],
[1203,`${cfa}.size.area`,53,[[[],[195,[0,1204],[0,1211]]]]],
[1204,`${cfa}.size.length`,69,[[[],[166,[0,1212],[0,85]]]]],
[1205,`${cfa}.size.perimeter`,69,[[[],[196,[0,1204],[0,1211]]]]],
[1206,`${cfa}.size.width`,69,[[[],[21,[0,1204],[0,1211]]]]],
[1207,`${cfa}.map.area`,105,[[[],[168,[0,1203],[0,96]]]]],
[1208,`${cfa}.map.length`,107,[[[],[21,[0,1204],[0,96]]]]],
[1209,`${cfa}.map.perimeter`,107,[[[],[21,[0,1205],[0,96]]]]],
[1210,`${cfa}.map.width`,107,[[[],[21,[0,1206],[0,96]]]]],
[1211,`${cfa}.${lwr}`,60,[[[],[197,[0,134]]]]],
[1212,`${cfa}.${ros}`,70,[[[],[198,[0,1201]]]]],
[1213,`${cfa}.${fli}`,56,[[[],[199,[0,1215],[0,1212]]]]],
[1214,`${cfa}.${fl}`,58,[[[],[200,[0,1213]]]]],
[1215,`${cfa}.${hpua}`,59,[[[],[201,[0,46],[0,1251]]]]],
[1216,`${cfa}.powerOfTheFire`,61,[[[],[202,[0,1213]]]]],
[1217,`${cfa}.powerOfTheWind`,61,[[[],[203,[0,134],[0,1212]]]]],
[1218,`${cfa}.powerRatio`,62,[[[],[21,[0,1216],[0,1217]]]]],
[1219,`${cfa}.isPlumeDominated`,31,[[[],[204,[0,1218]]]]],
[1220,`${cfa}.isWindDriven`,31,[[[],[205,[0,1218]]]]],
[1221,`${cff}.size.area`,53,[[[],[195,[0,1222],[0,1211]]]]],
[1222,`${cff}.size.length`,69,[[[],[166,[0,1231],[0,85]]]]],
[1223,`${cff}.size.perimeter`,69,[[[],[196,[0,1222],[0,1211]]]]],
[1224,`${cff}.size.width`,69,[[[],[21,[0,1222],[0,1211]]]]],
[1225,`${cff}.map.area`,105,[[[],[168,[0,1221],[0,96]]]]],
[1226,`${cff}.map.length`,107,[[[],[21,[0,1222],[0,96]]]]],
[1227,`${cff}.map.perimeter`,107,[[[],[21,[0,1223],[0,96]]]]],
[1228,`${cff}.map.width`,107,[[[],[21,[0,1224],[0,96]]]]],
[1229,`${cff}.rSa`,70,[[[],[206,[0,1247],[0,344],[0,387],[0,389],[0,392],[0,371]]]]],
[1230,`${cff}.crownFractionBurned`,42,[[[],[207,[0,406],[0,1236],[0,1229]]]]],
[1231,`${cff}.${ros}`,70,[[[],[208,[0,406],[0,1212],[0,1230]]]]],
[1232,`${cff}.${fli}`,56,[[[],[209,[0,1231],[0,1230],[0,46],[0,1251]]]]],
[1233,`${cff}.${fl}`,56,[[[],[200,[0,1232]]]]],
[1234,`${cfi}.${fli}`,56,[[[],[210,[0,48],[0,41]]]]],
[1235,`${cfi}.${fl}`,58,[[[],[17,[0,1234]]]]],
[1236,`${cfi}.${ros}`,70,[[[],[211,[0,1234],[0,1251]]]]],
[1237,`${cfi}.rPrime`,70,[[[],[212,[0,47]]]]],
[1238,`${cfi}.transitionRatio`,44,[[[],[213,[0,1249],[0,1234]]]]],
[1239,`${cfi}.canTransition`,31,[[[],[214,[0,1238]]]]],
[1240,`${cfi}.activeRatio`,41,[[[],[215,[0,1212],[0,1237]]]]],
[1241,`${cfi}.type`,20,[[[],[216,[0,1238],[0,1240]]]]],
[1242,`${cfi}.isActiveCrownFire`,31,[[[],[217,[0,1238],[0,1240]]]]],
[1243,`${cfi}.isCrownFire`,31,[[[],[218,[0,1238],[0,1240]]]]],
[1244,`${cfi}.isPassiveCrownFire`,31,[[[],[219,[0,1238],[0,1240]]]]],
[1245,`${cfi}.isConditionalCrownFire`,31,[[[],[220,[0,1238],[0,1240]]]]],
[1246,`${cfi}.isSurfaceFire`,31,[[[],[221,[0,1238],[0,1240]]]]],
[1247,`${cfi}.oActive`,125,[[[],[222,[0,47],[0,1199],[0,1138],[0,1166]]]]],
[1248,`${cfi}.crowningIndex`,36,[[[],[223,[0,1247]]]]],
[1249,`crown.fire.surface.${fli}`,56,[[[10,59],[30,[0,812]]],[[],[30,[0,76]]]]],
[1250,`crown.fire.surface.${fl}`,58,[[[10,59],[30,[0,813]]],[[],[30,[0,77]]]]],
[1251,`crown.fire.surface.${hpua}`,59,[[[10,59],[30,[0,814]]],[[],[30,[0,80]]]]],
]
}
