// autogenerated by GenomeCompiler.js on 2/22/2021, 11:04:35 PM
// Gene key abbreviations
const spfbdp = 'surface.primary.fuel.bed.dead.particle.class'
const spfblp = 'surface.primary.fuel.bed.live.particle.class'
const ssfbdp = 'surface.secondary.fuel.bed.dead.particle.class'
const ssfblp = 'surface.secondary.fuel.bed.live.particle.class'
const ccfbdp = 'crown.canopy.fuel.bed.dead.particle.class'
const ccfblp = 'crown.canopy.fuel.bed.live.particle.class'
const spfbd = 'surface.primary.fuel.bed.dead'
const spfbl = 'surface.primary.fuel.bed.live'
const spff = 'surface.primary.fuel.fire'
const ssfbd = 'surface.secondary.fuel.bed.dead'
const ssfbl = 'surface.secondary.fuel.bed.live'
const ssff = 'surface.secondary.fuel.fire'
const ccfbd = 'crown.canopy.fuel.bed.dead'
const ccfbl = 'crown.canopy.fuel.bed.live'
const ccff = 'crown.canopy.fuel.fire'
const spfb = 'surface.primary.fuel.bed'
const ssfb = 'surface.secondary.fuel.bed'
const ccfb = 'crown.canopy.fuel.bed'
const cfa = 'crown.fire.active'
const cff = 'crown.fire.final'
const cfi = 'crown.fire.initiation'
const spf = 'surface.primary.fuel'
const ssf = 'surface.secondary.fuel'
const mbd = 'model.behave.derived'
const mbp = 'model.behave.parms'
const mcd = 'model.chaparral.derived'
const mcp = 'model.chaparral.parms'
const mpd = 'model.palmettoGallberry.derived'
const mpp = 'model.palmettoGallberry.parms'
const mwd = 'model.westernAspen.derived'
const mwp = 'model.westernAspen.parms'
const sfe = 'surface.fire.ellipse'
const swf = 'surface.weighted.fire'
const spotb = 'spotting.burningPile'
const spotc = 'spotting.crownFire'
const spots = 'spotting.surfaceFire'
const spott = 'spotting.torchingTrees'
const savr = 'surfaceAreaToVolumeRatio'
const emc = 'effective.mineralContent'
const tmc = 'total.mineralContent'
const heat = 'heatOfCombustion'
const ef = 'effectiveFuel'
const sa = 'surfaceArea'
const sc = 'sizeClass'
const wf = 'weightingFactor'
const qig = 'heatOfPreignition'
const waf = 'windSpeedAdjustmentFactor'
const load = 'ovendryLoad'
const mois = 'moistureContent'
const fli = 'firelineIntensity'
const fl = 'flameLength'
const lwr = 'lengthToWidthRatio'
const ros = 'spreadRate'
const rxi = 'reactionIntensity'
const sh = 'scorchHeight'
const hpua = 'heatPerUnitArea'
const phiew = 'phiEffectiveWind'
const taur = 'flameResidenceTime'
const ews = 'effectiveWindSpeed'
const dens = 'fiberDensity'
const ehn = 'heatingNumber'

export const CompiledGenome = {
// Array of literals used by Gene updater config conditions and method parameters
literalArgsArray: [
8000, // 0
'lengthToWidthRatio', // 1
'flameLength', // 2
'firelineIntensity', // 3
'headingFromUpslope', // 4
'upslope', // 5
'sourceFromNorth', // 6
'effectiveWindSpeed', // 7
1, // 8
'category', // 9
'liveCategory', // 10
'degrees', // 11
'map', // 12
0, // 13
'at10m', // 14
'at20ft', // 15
'atMidflame', // 16
32, // 17
46, // 18
30, // 19
8300, // 20
640, // 21
350, // 22
0.01, // 23
0.015, // 24
0.0555, // 25
0.055, // 26
0.03, // 27
'dead', // 28
109, // 29
127, // 30
140, // 31
5, // 32
61, // 33
2000, // 34
27, // 35
10500, // 36
2800, // 37
'live', // 38
9550, // 39
2200, // 40
0.035, // 41
0.3, // 42
0.4, // 43
0.25, // 44
'input', // 45
'applied', // 46
'catalog', // 47
'behave', // 48
'chaparral', // 49
'palmettoGallberry', // 50
'westernAspen', // 51
'none', // 52
'estimated', // 53
'chamise', // 54
'aspenShrub', // 55
'expected', // 56
'harmonic', // 57
'linkedToSurfaceFire', // 58
'fromHead', // 59
'fromUpslope', // 60
'fromNorth', // 61
'linkedToCrownFire', // 62
'standAlone', // 63
0.138, // 64
0.092, // 65
0.23, // 66
1500, // 67
],
// Simple array of updater method <file>.<function> names
methodRefsArray: [
'Dag.module', // 0
'Dag.config', // 1
'Dag.input', // 2
'IgnitionProbability.firebrand', // 3
'IgnitionProbability.lightningStrike', // 4
'Canopy.crownFill', // 5
'Canopy.crownLength', // 6
'Canopy.crownRatio', // 7
'Canopy.heatPerUnitArea', // 8
'Dag.fixed', // 9
'Canopy.sheltersFuelFromWind', // 10
'Canopy.fuelLoad', // 11
'Canopy.windSpeedAdjustmentFactor', // 12
'Spotting.appliedDownWindCoverHeight', // 13
'TreeMortality.barkThickness', // 14
'SurfaceFire.effectiveWindSpeedFromLwr', // 15
'SurfaceFire.firelineIntensityFromFlameLength', // 16
'SurfaceFire.flameLength', // 17
'Compass.diff', // 18
'Compass.sum', // 19
'SurfaceFire.lengthToWidthRatio', // 20
'Calc.divide', // 21
'Calc.multiply', // 22
'Compass.slopeRatioMap', // 23
'Compass.slopeDegreesMap', // 24
'Dag.bind', // 25
'Compass.opposite', // 26
'Compass.slopeDegrees', // 27
'Compass.slopeRatio', // 28
'IgnitionProbability.fuelTemperature', // 29
'Wind.speedAt10m', // 30
'Wind.speedAt20ft', // 31
'Wind.speedAt20ftFromMidflame', // 32
'Wind.speedAtMidflame', // 33
'FuelParticle.selectByDomain', // 34
'FuelParticle.effectiveHeatingNumber', // 35
'FuelParticle.effectiveFuelLoad', // 36
'FuelParticle.heatOfPreignition', // 37
'FuelParticle.netOvendryLoad', // 38
'FuelParticle.sizeClass', // 39
'FuelParticle.sizeClassWeightingFactor', // 40
'FuelParticle.surfaceArea', // 41
'FuelParticle.surfaceAreaWeightingFactor', // 42
'FuelParticle.volume', // 43
'FuelParticle.effectiveFuelWaterLoad', // 44
'Calc.sum', // 45
'FuelBed.mineralDamping', // 46
'FuelBed.moistureDamping', // 47
'Calc.sumOfProducts', // 48
'FuelBed.extinctionMoistureContentFactor', // 49
'FuelBed.reactionIntensityDry', // 50
'FuelBed.sizeClassWeightingFactorArray', // 51
'FuelBed.extinctionMoistureContent', // 52
'FuelBed.heatSink', // 53
'FuelBed.noWindNoSlopeSpreadRate', // 54
'FuelBed.openWindSpeedAdjustmentFactor', // 55
'FuelBed.packingRatio', // 56
'FuelBed.optimumPackingRatio', // 57
'FuelBed.propagatingFluxRatio', // 58
'FuelBed.reactionVelocityExponent', // 59
'FuelBed.reactionVelocityMaximum', // 60
'FuelBed.reactionVelocityOptimum', // 61
'FuelBed.savr15', // 62
'SurfaceFire.maximumDirectionSlopeSpreadRate', // 63
'SurfaceFire.maximumDirectionWindSpreadRate', // 64
'SurfaceFire.maximumDirectionXComponent', // 65
'SurfaceFire.maximumDirectionYComponent', // 66
'SurfaceFire.maximumDirectionSpreadRate', // 67
'Calc.greaterThan', // 68
'SurfaceFire.effectiveWindSpeedLimit', // 69
'SurfaceFire.phiEwFromEws', // 70
'SurfaceFire.maximumSpreadRate', // 71
'FuelBed.slopeK', // 72
'SurfaceFire.phiSlope', // 73
'SurfaceFire.effectiveWindSpeed', // 74
'SurfaceFire.phiEffectiveWind', // 75
'SurfaceFire.phiEffectiveWindInferred', // 76
'SurfaceFire.spreadRateWithCrossSlopeWind', // 77
'Math.min', // 78
'SurfaceFire.spreadRateWithRosLimitApplied', // 79
'FuelBed.windSpeedAdjustmentFactor', // 80
'FuelBed.windB', // 81
'FuelBed.windC', // 82
'FuelBed.windE', // 83
'FuelBed.windK', // 84
'FuelBed.windI', // 85
'SurfaceFire.phiWind', // 86
'SurfaceFire.firelineIntensity', // 87
'FuelBed.taur', // 88
'SurfaceFire.spreadDirectionFromUpslope', // 89
'FuelBed.heatPerUnitArea', // 90
'SurfaceFire.scorchHeight', // 91
'FuelCatalog.domain', // 92
'BehaveFuel.curedHerbFraction', // 93
'FuelCatalog.behaveDepth', // 94
'FuelCatalog.behaveDeadMext', // 95
'FuelCatalog.behaveTotalHerbLoad', // 96
'FuelCatalog.behaveDead1Load', // 97
'FuelCatalog.behaveDead10Load', // 98
'FuelCatalog.behaveDead100Load', // 99
'FuelCatalog.behaveLiveStemLoad', // 100
'FuelCatalog.behaveDead1Savr', // 101
'FuelCatalog.behaveLiveHerbSavr', // 102
'FuelCatalog.behaveLiveStemSavr', // 103
'FuelCatalog.behaveDeadHeat', // 104
'FuelCatalog.behaveLiveHeat', // 105
'BehaveFuel.deadHerbLoad', // 106
'BehaveFuel.liveHerbLoad', // 107
'FuelCatalog.chaparralFuelType', // 108
'FuelCatalog.chaparralDeadFraction', // 109
'FuelCatalog.chaparralDepth', // 110
'FuelCatalog.chaparralTotalLoad', // 111
'ChaparralFuel.age', // 112
'ChaparralFuel.deadFractionAverageMortality', // 113
'ChaparralFuel.deadFractionSevereMortality', // 114
'ChaparralFuel.fuelDepth', // 115
'ChaparralFuel.totalLoad', // 116
'ChaparralFuel.deadLoad', // 117
'ChaparralFuel.deadClass1Load', // 118
'ChaparralFuel.deadClass2Load', // 119
'ChaparralFuel.deadClass3Load', // 120
'ChaparralFuel.deadClass4Load', // 121
'ChaparralFuel.liveLoad', // 122
'ChaparralFuel.liveClass1Load', // 123
'ChaparralFuel.liveClass2Load', // 124
'ChaparralFuel.liveClass3Load', // 125
'ChaparralFuel.liveClass4Load', // 126
'ChaparralFuel.liveClass5Load', // 127
'FuelCatalog.palmettoGallberryAge', // 128
'FuelCatalog.palmettoGallberryBasalArea', // 129
'FuelCatalog.palmettoGallberryCover', // 130
'FuelCatalog.palmettoGallberryHeight', // 131
'PalmettoGallberryFuel.fuelDepth', // 132
'PalmettoGallberryFuel.deadFineLoad', // 133
'PalmettoGallberryFuel.deadSmallLoad', // 134
'PalmettoGallberryFuel.deadFoliageLoad', // 135
'PalmettoGallberryFuel.deadLitterLoad', // 136
'PalmettoGallberryFuel.liveFineLoad', // 137
'PalmettoGallberryFuel.liveSmallLoad', // 138
'PalmettoGallberryFuel.liveFoliageLoad', // 139
'FuelCatalog.westernAspenFuelType', // 140
'FuelCatalog.westernAspenCuringLevel', // 141
'WesternAspenFuel.depth', // 142
'WesternAspenFuel.deadFineLoad', // 143
'WesternAspenFuel.deadSmallLoad', // 144
'WesternAspenFuel.deadFineSavr', // 145
'WesternAspenFuel.liveHerbLoad', // 146
'WesternAspenFuel.liveStemLoad', // 147
'WesternAspenFuel.liveStemSavr', // 148
'Math.max', // 149
'Calc.or', // 150
'SurfaceFire.arithmeticMeanSpreadRate', // 151
'SurfaceFire.expectedValueSpreadRateMOCK', // 152
'SurfaceFire.harmonicMeanSpreadRate', // 153
'FireEllipse.eccentricity', // 154
'FireEllipse.majorSpreadRate', // 155
'FireEllipse.minorSpreadRate', // 156
'FireEllipse.fSpreadRate', // 157
'FireEllipse.gSpreadRate', // 158
'FireEllipse.hSpreadRate', // 159
'FireEllipse.area', // 160
'FireEllipse.spreadDistance', // 161
'FireEllipse.perimeter', // 162
'FireEllipse.mapArea', // 163
'FireEllipse.fliAtAzimuth', // 164
'FireEllipse.backingSpreadRate', // 165
'TreeMortality.mortalityRate', // 166
'FireEllipse.flankingSpreadRate', // 167
'FireEllipse.psiSpreadRate', // 168
'FireEllipse.betaSpreadRate', // 169
'FireEllipse.thetaFromBeta', // 170
'FireEllipse.psiFromTheta', // 171
'Spotting.criticalCoverHeight', // 172
'Spotting.burningPileFirebrandHeight', // 173
'Spotting.distanceFlatTerrain', // 174
'Spotting.distanceFlatTerrainWithDrift', // 175
'Spotting.distanceMountainTerrain', // 176
'CrownSpotting.zdrop', // 177
'CrownSpotting.xdrift', // 178
'CrownSpotting.xdrop', // 179
'CrownSpotting.xspot', // 180
'CrownSpotting.firelineIntensityThomas', // 181
'CrownSpotting.flatDistance', // 182
'Spotting.surfaceFireFirebrandHeight', // 183
'Spotting.surfaceFireFirebrandDrift', // 184
'Spotting.torchingTreesFirebrandHeight', // 185
'Spotting.torchingTreesSteadyFlameHeight', // 186
'Spotting.torchingTreesSteadyFlameDuration', // 187
'TreeMortality.crownLengthScorched', // 188
'TreeMortality.crownVolumeScorched', // 189
'CrownFire.area', // 190
'CrownFire.perimeter', // 191
'CrownFire.lengthToWidthRatio', // 192
'CrownFire.rActive', // 193
'CrownFire.fliActive', // 194
'CrownFire.flameLengthThomas', // 195
'CrownFire.hpuaActive', // 196
'CrownFire.powerOfTheFire', // 197
'CrownFire.powerOfTheWind', // 198
'CrownFire.isPlumeDominated', // 199
'CrownFire.isWindDriven', // 200
'CrownFire.rSa', // 201
'CrownFire.crownFractionBurned', // 202
'CrownFire.rFinal', // 203
'CrownFire.fliFinal', // 204
'CrownFire.fliInit', // 205
'CrownFire.rInit', // 206
'CrownFire.rPrimeActive', // 207
'CrownFire.transitionRatio', // 208
'CrownFire.canTransition', // 209
'CrownFire.activeRatio', // 210
'CrownFire.type', // 211
'CrownFire.isActive', // 212
'CrownFire.isCrown', // 213
'CrownFire.isPassive', // 214
'CrownFire.isConditional', // 215
'CrownFire.isSurface', // 216
'CrownFire.oActive', // 217
'CrownFire.crowningIndex', // 218
],
// Array of Genes where each Gene is:
// [<geneIdx>, <geneKey>, <variantIdx>, [<valueUpdaters>]], where each valueUpdater is:
// [[<configIdx>, <configValue>], [methodIdx, ...<methodArgs>]], and where each methodArg is:
// [<0|1>, <geneIdx|literalIdx>]
genesArray: [
[0,`module.surfaceFire`,0,[[[],[0]]]],
[1,`module.surfaceSpot`,0,[[[],[0]]]],
[2,`module.crownFire`,0,[[[],[0]]]],
[3,`module.crownSpot`,0,[[[],[0]]]],
[4,`module.fireEllipse`,0,[[[],[0]]]],
[5,`module.fireContain`,0,[[[],[0]]]],
[6,`module.${sh}`,0,[[[],[0]]]],
[7,`module.treeMortality`,0,[[[],[0]]]],
[8,`module.spotting`,0,[[[],[0]]]],
[9,`module.ignitionProbability`,0,[[[],[0]]]],
[10,`link.crownFire`,4,[[[],[1]]]],
[11,`link.crownSpot`,1,[[[],[1]]]],
[12,`link.fireContain`,2,[[[],[1]]]],
[13,`link.fireEllipse`,4,[[[],[1]]]],
[14,`link.${sh}`,4,[[[],[1]]]],
[15,`link.surfaceSpot`,4,[[[],[1]]]],
[16,`link.treeMortality`,3,[[[],[1]]]],
[17,`configure.fuel.primary`,7,[[[],[1]]]],
[18,`configure.fuel.secondary`,8,[[[],[1]]]],
[19,`configure.fuel.moisture`,9,[[[],[1]]]],
[20,`configure.fuel.${waf}`,10,[[[],[1]]]],
[21,`configure.fuel.curedHerbFraction`,6,[[[],[1]]]],
[22,`configure.fuel.chaparralTotalLoad`,5,[[[],[1]]]],
[23,`configure.slope.steepness`,11,[[[],[1]]]],
[24,`configure.wind.direction`,12,[[[],[1]]]],
[25,`configure.wind.speed`,13,[[[],[1]]]],
[26,`configure.fire.${fli}`,14,[[[],[1]]]],
[27,`configure.fire.${lwr}`,15,[[[],[1]]]],
[28,`configure.fire.${ews}Limit`,16,[[[],[1]]]],
[29,`configure.fire.weightingMethod`,17,[[[],[1]]]],
[30,`configure.fire.vector`,18,[[[],[1]]]],
[31,`docs.run.mainTitle`,43,[[[],[2]]]],
[32,`docs.run.subTitle`,43,[[[],[2]]]],
[33,`docs.run.description`,43,[[[],[2]]]],
[34,`docs.run.userName`,43,[[[],[2]]]],
[35,`ignition.firebrand.probability`,92,[[[],[3,[0,100],[0,88]]]]],
[36,`ignition.lightningStrike.charge`,24,[[[],[2]]]],
[37,`ignition.lightningStrike.fuel.depth`,91,[[[],[2]]]],
[38,`ignition.lightningStrike.fuel.type`,23,[[[],[2]]]],
[39,`ignition.lightningStrike.probability`,92,[[[],[4,[0,38],[0,37],[0,90],[0,36]]]]],
[40,`site.canopy.cover`,68,[[[],[2]]]],
[41,`site.canopy.crown.baseHeight`,105,[[[],[2]]]],
[42,`site.canopy.crown.fill`,38,[[[],[5,[0,40],[0,44]]]]],
[43,`site.canopy.crown.length`,105,[[[],[6,[0,41],[0,45]]]]],
[44,`site.canopy.crown.ratio`,41,[[[],[7,[0,43],[0,45]]]]],
[45,`site.canopy.crown.totalHeight`,105,[[[],[2]]]],
[46,`site.canopy.fire.${hpua}`,50,[[[],[8,[0,51],[0,49]]]]],
[47,`site.canopy.fuel.bulkDensity`,64,[[[],[2]]]],
[48,`site.canopy.fuel.foliar.${mois}`,78,[[[],[2]]]],
[49,`site.canopy.fuel.${heat}`,74,[[[],[9,[1,0]]]]],
[50,`site.canopy.fuel.isSheltered`,33,[[[],[10,[0,40],[0,45],[0,42]]]]],
[51,`site.canopy.fuel.${load}`,81,[[[],[11,[0,47],[0,43]]]]],
[52,`site.canopy.fuel.shading`,68,[[[],[2]]]],
[53,`site.canopy.sheltered.${waf}`,108,[[[],[12,[0,40],[0,45],[0,42]]]]],
[54,`site.canopy.downwind.height`,105,[[[],[2]]]],
[55,`site.canopy.downwind.isOpen`,30,[[[],[2]]]],
[56,`site.canopy.downwind.appliedHeight`,105,[[[],[13,[0,54],[0,55]]]]],
[57,`site.canopy.tree.barkThickness`,102,[[[],[14,[0,59],[0,58]]]]],
[58,`site.canopy.tree.dbh`,104,[[[],[2]]]],
[59,`site.canopy.tree.species.fofem6.code`,27,[[[],[2]]]],
[60,`site.doc.date`,43,[[[],[2]]]],
[61,`site.doc.id`,43,[[[],[2]]]],
[62,`site.doc.location`,43,[[[],[2]]]],
[63,`site.doc.station`,43,[[[],[2]]]],
[64,`site.doc.time`,43,[[[],[2]]]],
[65,`site.fire.observed.${ews}`,107,[[[27,1],[15,[0,71]]],[[],[2]]]],
[66,`site.fire.observed.${fli}`,47,[[[26,2],[16,[0,67]]],[[],[2]]]],
[67,`site.fire.observed.${fl}`,49,[[[26,3],[17,[0,66]]],[[],[2]]]],
[68,`site.fire.observed.heading.fromUpslope`,37,[[[24,4],[2]],[[24,5],[2]],[[],[18,[0,69],[0,96]]]]],
[69,`site.fire.observed.heading.fromNorth`,37,[[[24,6],[2]],[[],[19,[0,96],[0,68]]]]],
[70,`site.fire.observed.${hpua}`,50,[[[],[2]]]],
[71,`site.fire.observed.${lwr}`,51,[[[27,7],[20,[0,65]]],[[],[2]]]],
[72,`site.fire.observed.${ros}`,61,[[[],[2]]]],
[73,`site.fire.observed.${sh}`,58,[[[],[2]]]],
[74,`site.fire.crown.${fl}`,49,[[[],[2]]]],
[75,`site.fire.time.sinceIgnition`,46,[[[],[2]]]],
[76,`site.fire.vector.fromHead`,37,[[[],[2]]]],
[77,`site.fire.vector.fromNorth`,37,[[[],[2]]]],
[78,`site.fire.vector.fromUpslope`,37,[[[],[2]]]],
[79,`site.map.scale`,97,[[[],[2]]]],
[80,`site.map.contours`,94,[[[],[2]]]],
[81,`site.map.distance`,60,[[[],[2]]]],
[82,`site.map.factor`,96,[[[],[21,[1,8],[0,79]]]]],
[83,`site.map.interval`,60,[[[],[2]]]],
[84,`site.map.reach`,60,[[[],[22,[0,79],[0,81]]]]],
[85,`site.map.rise`,60,[[[],[22,[0,83],[0,80]]]]],
[86,`site.map.slope.ratio`,100,[[[],[23,[0,79],[0,83],[0,80],[0,81]]]]],
[87,`site.map.slope.degrees`,99,[[[],[24,[0,79],[0,83],[0,80],[0,81]]]]],
[88,`site.moisture.dead.tl1h`,78,[[[19,9],[25,[0,91]]],[[],[2]]]],
[89,`site.moisture.dead.tl10h`,78,[[[19,9],[25,[0,91]]],[[],[2]]]],
[90,`site.moisture.dead.tl100h`,78,[[[19,9],[25,[0,91]]],[[],[2]]]],
[91,`site.moisture.dead.category`,78,[[[],[2]]]],
[92,`site.moisture.live.herb`,78,[[[19,9],[25,[0,94]]],[[19,10],[25,[0,94]]],[[],[2]]]],
[93,`site.moisture.live.stem`,78,[[[19,9],[25,[0,94]]],[[19,10],[25,[0,94]]],[[],[2]]]],
[94,`site.moisture.live.category`,78,[[[],[2]]]],
[95,`site.slope.direction.aspect`,37,[[[],[2]]]],
[96,`site.slope.direction.upslope`,37,[[[],[26,[0,95]]]]],
[97,`site.slope.steepness.degrees`,99,[[[23,11],[2]],[[23,12],[25,[0,87]]],[[],[27,[0,98]]]]],
[98,`site.slope.steepness.ratio`,100,[[[23,11],[28,[0,97]]],[[23,12],[25,[0,86]]],[[],[2]]]],
[99,`site.temperature.air`,36,[[[],[2]]]],
[100,`site.temperature.fuel`,36,[[[],[29,[0,99],[0,52]]]]],
[101,`site.wind.direction.heading.fromUpslope`,37,[[[24,4],[2]],[[24,6],[18,[0,104],[0,96]]],[[24,5],[9,[1,13]]],[[],[9,[1,13]]]]],
[102,`site.wind.direction.source.fromUpslope`,37,[[[],[26,[0,101]]]]],
[103,`site.wind.direction.source.fromNorth`,37,[[[24,4],[26,[0,104]]],[[24,6],[2]],[[24,5],[26,[0,96]]],[[],[26,[0,96]]]]],
[104,`site.wind.direction.heading.fromNorth`,37,[[[24,4],[19,[0,101],[0,96]]],[[24,6],[26,[0,103]]],[[24,5],[25,[0,96]]],[[],[25,[0,96]]]]],
[105,`site.wind.speed.at10m`,107,[[[25,14],[2]],[[],[30,[0,106]]]]],
[106,`site.wind.speed.at20ft`,107,[[[25,15],[2]],[[25,14],[31,[0,105]]],[[],[32,[0,107],[0,108]]]]],
[107,`site.wind.speed.atMidflame`,107,[[[25,16],[2]],[[],[33,[0,106],[0,108]]]]],
[108,`site.${waf}`,108,[[[],[2]]]],
[109,`${spfbdp}1.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,19],[1,17]]]]],
[110,`${spfbdp}1.${heat}`,74,[[[],[34,[0,380],[0,394],[1,0],[1,20],[1,0]]]]],
[111,`${spfbdp}1.${load}`,81,[[[],[34,[0,380],[0,387],[0,410],[0,426],[0,437]]]]],
[112,`${spfbdp}1.${mois}`,78,[[[],[34,[0,380],[0,88],[0,88],[0,88],[0,88]]]]],
[113,`${spfbdp}1.${savr}`,85,[[[],[34,[0,380],[0,391],[1,21],[1,22],[0,439]]]]],
[114,`${spfbdp}1.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,23],[1,23]]]]],
[115,`${spfbdp}1.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[116,`${spfbdp}1.${ef}.${ehn}`,72,[[[],[35,[0,113]]]]],
[117,`${spfbdp}1.${ef}.${load}`,81,[[[],[36,[0,113],[0,111],[1,28]]]]],
[118,`${spfbdp}1.${qig}`,75,[[[],[37,[0,112],[0,116]]]]],
[119,`${spfbdp}1.net.${load}`,81,[[[],[38,[0,111],[0,115]]]]],
[120,`${spfbdp}1.${sc}`,83,[[[],[39,[0,113]]]]],
[121,`${spfbdp}1.${sc}.${wf}`,106,[[[],[40,[0,120],[0,290]]]]],
[122,`${spfbdp}1.${sa}`,84,[[[],[41,[0,111],[0,113],[0,109]]]]],
[123,`${spfbdp}1.${sa}.${wf}`,106,[[[],[42,[0,122],[0,274]]]]],
[124,`${spfbdp}1.volume`,90,[[[],[43,[0,111],[0,109]]]]],
[125,`${spfbdp}1.${ef}.waterLoad`,81,[[[],[44,[0,117],[0,112]]]]],
[126,`${spfbdp}2.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,19],[1,17]]]]],
[127,`${spfbdp}2.${heat}`,74,[[[],[34,[0,380],[0,394],[1,0],[1,20],[1,0]]]]],
[128,`${spfbdp}2.${load}`,81,[[[],[34,[0,380],[0,388],[0,411],[0,427],[0,438]]]]],
[129,`${spfbdp}2.${mois}`,78,[[[],[34,[0,380],[0,89],[0,89],[0,89],[0,89]]]]],
[130,`${spfbdp}2.${savr}`,85,[[[],[34,[0,380],[1,29],[1,30],[1,31],[1,29]]]]],
[131,`${spfbdp}2.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,23],[1,23]]]]],
[132,`${spfbdp}2.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[133,`${spfbdp}2.${ef}.${ehn}`,72,[[[],[35,[0,130]]]]],
[134,`${spfbdp}2.${ef}.${load}`,81,[[[],[36,[0,130],[0,128],[1,28]]]]],
[135,`${spfbdp}2.${qig}`,75,[[[],[37,[0,129],[0,133]]]]],
[136,`${spfbdp}2.net.${load}`,81,[[[],[38,[0,128],[0,132]]]]],
[137,`${spfbdp}2.${sc}`,83,[[[],[39,[0,130]]]]],
[138,`${spfbdp}2.${sc}.${wf}`,106,[[[],[40,[0,137],[0,290]]]]],
[139,`${spfbdp}2.${sa}`,84,[[[],[41,[0,128],[0,130],[0,126]]]]],
[140,`${spfbdp}2.${sa}.${wf}`,106,[[[],[42,[0,139],[0,274]]]]],
[141,`${spfbdp}2.volume`,90,[[[],[43,[0,128],[0,126]]]]],
[142,`${spfbdp}2.${ef}.waterLoad`,81,[[[],[44,[0,134],[0,129]]]]],
[143,`${spfbdp}3.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,19],[1,17]]]]],
[144,`${spfbdp}3.${heat}`,74,[[[],[34,[0,380],[0,394],[1,0],[1,20],[1,0]]]]],
[145,`${spfbdp}3.${load}`,81,[[[],[34,[0,380],[0,389],[0,412],[0,428],[1,13]]]]],
[146,`${spfbdp}3.${mois}`,78,[[[],[34,[0,380],[0,90],[0,89],[0,88],[1,32]]]]],
[147,`${spfbdp}3.${savr}`,85,[[[],[34,[0,380],[1,19],[1,33],[1,34],[1,8]]]]],
[148,`${spfbdp}3.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,23],[1,23]]]]],
[149,`${spfbdp}3.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[150,`${spfbdp}3.${ef}.${ehn}`,72,[[[],[35,[0,147]]]]],
[151,`${spfbdp}3.${ef}.${load}`,81,[[[],[36,[0,147],[0,145],[1,28]]]]],
[152,`${spfbdp}3.${qig}`,75,[[[],[37,[0,146],[0,150]]]]],
[153,`${spfbdp}3.net.${load}`,81,[[[],[38,[0,145],[0,149]]]]],
[154,`${spfbdp}3.${sc}`,83,[[[],[39,[0,147]]]]],
[155,`${spfbdp}3.${sc}.${wf}`,106,[[[],[40,[0,154],[0,290]]]]],
[156,`${spfbdp}3.${sa}`,84,[[[],[41,[0,145],[0,147],[0,143]]]]],
[157,`${spfbdp}3.${sa}.${wf}`,106,[[[],[42,[0,156],[0,274]]]]],
[158,`${spfbdp}3.volume`,90,[[[],[43,[0,145],[0,143]]]]],
[159,`${spfbdp}3.${ef}.waterLoad`,81,[[[],[44,[0,151],[0,146]]]]],
[160,`${spfbdp}4.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,19],[1,17]]]]],
[161,`${spfbdp}4.${heat}`,74,[[[],[34,[0,380],[0,394],[1,0],[1,20],[1,0]]]]],
[162,`${spfbdp}4.${load}`,81,[[[],[34,[0,380],[0,396],[0,413],[0,429],[1,13]]]]],
[163,`${spfbdp}4.${mois}`,78,[[[],[34,[0,380],[0,88],[0,90],[0,90],[1,32]]]]],
[164,`${spfbdp}4.${savr}`,85,[[[],[34,[0,380],[0,392],[1,35],[1,34],[1,8]]]]],
[165,`${spfbdp}4.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,23],[1,23]]]]],
[166,`${spfbdp}4.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[167,`${spfbdp}4.${ef}.${ehn}`,72,[[[],[35,[0,164]]]]],
[168,`${spfbdp}4.${ef}.${load}`,81,[[[],[36,[0,164],[0,162],[1,28]]]]],
[169,`${spfbdp}4.${qig}`,75,[[[],[37,[0,163],[0,167]]]]],
[170,`${spfbdp}4.net.${load}`,81,[[[],[38,[0,162],[0,166]]]]],
[171,`${spfbdp}4.${sc}`,83,[[[],[39,[0,164]]]]],
[172,`${spfbdp}4.${sc}.${wf}`,106,[[[],[40,[0,171],[0,290]]]]],
[173,`${spfbdp}4.${sa}`,84,[[[],[41,[0,162],[0,164],[0,160]]]]],
[174,`${spfbdp}4.${sa}.${wf}`,106,[[[],[42,[0,173],[0,274]]]]],
[175,`${spfbdp}4.volume`,90,[[[],[43,[0,162],[0,160]]]]],
[176,`${spfbdp}4.${ef}.waterLoad`,81,[[[],[44,[0,168],[0,163]]]]],
[177,`${spfbdp}5.${dens}`,82,[[[],[9,[1,17]]]]],
[178,`${spfbdp}5.${heat}`,74,[[[],[9,[1,0]]]]],
[179,`${spfbdp}5.${load}`,81,[[[],[9,[1,13]]]]],
[180,`${spfbdp}5.${mois}`,78,[[[],[9,[1,32]]]]],
[181,`${spfbdp}5.${savr}`,85,[[[],[9,[1,8]]]]],
[182,`${spfbdp}5.${emc}`,73,[[[],[9,[1,23]]]]],
[183,`${spfbdp}5.${tmc}`,89,[[[],[9,[1,25]]]]],
[184,`${spfbdp}5.${ef}.${ehn}`,72,[[[],[35,[0,181]]]]],
[185,`${spfbdp}5.${ef}.${load}`,81,[[[],[36,[0,181],[0,179],[1,28]]]]],
[186,`${spfbdp}5.${qig}`,75,[[[],[37,[0,180],[0,184]]]]],
[187,`${spfbdp}5.net.${load}`,81,[[[],[38,[0,179],[0,183]]]]],
[188,`${spfbdp}5.${sc}`,83,[[[],[39,[0,181]]]]],
[189,`${spfbdp}5.${sc}.${wf}`,106,[[[],[40,[0,188],[0,290]]]]],
[190,`${spfbdp}5.${sa}`,84,[[[],[41,[0,179],[0,181],[0,177]]]]],
[191,`${spfbdp}5.${sa}.${wf}`,106,[[[],[42,[0,190],[0,274]]]]],
[192,`${spfbdp}5.volume`,90,[[[],[43,[0,179],[0,177]]]]],
[193,`${spfbdp}5.${ef}.waterLoad`,81,[[[],[44,[0,185],[0,180]]]]],
[194,`${spfblp}1.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,18],[1,17]]]]],
[195,`${spfblp}1.${heat}`,74,[[[],[34,[0,380],[0,395],[1,36],[1,20],[1,0]]]]],
[196,`${spfblp}1.${load}`,81,[[[],[34,[0,380],[0,397],[0,415],[0,430],[0,440]]]]],
[197,`${spfblp}1.${mois}`,78,[[[],[34,[0,380],[0,92],[0,93],[0,93],[0,92]]]]],
[198,`${spfblp}1.${savr}`,85,[[[],[34,[0,380],[0,392],[1,21],[1,22],[1,37]]]]],
[199,`${spfblp}1.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,24],[1,23]]]]],
[200,`${spfblp}1.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[201,`${spfblp}1.${ef}.${ehn}`,72,[[[],[35,[0,198]]]]],
[202,`${spfblp}1.${ef}.${load}`,81,[[[],[36,[0,198],[0,196],[1,38]]]]],
[203,`${spfblp}1.${qig}`,75,[[[],[37,[0,197],[0,201]]]]],
[204,`${spfblp}1.net.${load}`,81,[[[],[38,[0,196],[0,200]]]]],
[205,`${spfblp}1.${sc}`,83,[[[],[39,[0,198]]]]],
[206,`${spfblp}1.${sc}.${wf}`,106,[[[],[40,[0,205],[0,310]]]]],
[207,`${spfblp}1.${sa}`,84,[[[],[41,[0,196],[0,198],[0,194]]]]],
[208,`${spfblp}1.${sa}.${wf}`,106,[[[],[42,[0,207],[0,294]]]]],
[209,`${spfblp}1.volume`,90,[[[],[43,[0,196],[0,194]]]]],
[210,`${spfblp}2.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,18],[1,17]]]]],
[211,`${spfblp}2.${heat}`,74,[[[],[34,[0,380],[0,395],[1,39],[1,20],[1,0]]]]],
[212,`${spfblp}2.${load}`,81,[[[],[34,[0,380],[0,390],[0,416],[0,431],[0,441]]]]],
[213,`${spfblp}2.${mois}`,78,[[[],[34,[0,380],[0,93],[0,93],[0,93],[0,93]]]]],
[214,`${spfblp}2.${savr}`,85,[[[],[34,[0,380],[0,393],[1,30],[1,31],[0,442]]]]],
[215,`${spfblp}2.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,24],[1,23]]]]],
[216,`${spfblp}2.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[217,`${spfblp}2.${ef}.${ehn}`,72,[[[],[35,[0,214]]]]],
[218,`${spfblp}2.${ef}.${load}`,81,[[[],[36,[0,214],[0,212],[1,38]]]]],
[219,`${spfblp}2.${qig}`,75,[[[],[37,[0,213],[0,217]]]]],
[220,`${spfblp}2.net.${load}`,81,[[[],[38,[0,212],[0,216]]]]],
[221,`${spfblp}2.${sc}`,83,[[[],[39,[0,214]]]]],
[222,`${spfblp}2.${sc}.${wf}`,106,[[[],[40,[0,221],[0,310]]]]],
[223,`${spfblp}2.${sa}`,84,[[[],[41,[0,212],[0,214],[0,210]]]]],
[224,`${spfblp}2.${sa}.${wf}`,106,[[[],[42,[0,223],[0,294]]]]],
[225,`${spfblp}2.volume`,90,[[[],[43,[0,212],[0,210]]]]],
[226,`${spfblp}3.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,18],[1,17]]]]],
[227,`${spfblp}3.${heat}`,74,[[[],[34,[0,380],[0,395],[1,39],[1,20],[1,0]]]]],
[228,`${spfblp}3.${load}`,81,[[[],[34,[0,380],[1,13],[0,417],[0,432],[1,13]]]]],
[229,`${spfblp}3.${mois}`,78,[[[],[34,[0,380],[1,32],[0,93],[0,93],[1,32]]]]],
[230,`${spfblp}3.${savr}`,85,[[[],[34,[0,380],[1,8],[1,33],[1,34],[1,8]]]]],
[231,`${spfblp}3.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,24],[1,23]]]]],
[232,`${spfblp}3.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[233,`${spfblp}3.${ef}.${ehn}`,72,[[[],[35,[0,230]]]]],
[234,`${spfblp}3.${ef}.${load}`,81,[[[],[36,[0,230],[0,228],[1,38]]]]],
[235,`${spfblp}3.${qig}`,75,[[[],[37,[0,229],[0,233]]]]],
[236,`${spfblp}3.net.${load}`,81,[[[],[38,[0,228],[0,232]]]]],
[237,`${spfblp}3.${sc}`,83,[[[],[39,[0,230]]]]],
[238,`${spfblp}3.${sc}.${wf}`,106,[[[],[40,[0,237],[0,310]]]]],
[239,`${spfblp}3.${sa}`,84,[[[],[41,[0,228],[0,230],[0,226]]]]],
[240,`${spfblp}3.${sa}.${wf}`,106,[[[],[42,[0,239],[0,294]]]]],
[241,`${spfblp}3.volume`,90,[[[],[43,[0,228],[0,226]]]]],
[242,`${spfblp}4.${dens}`,82,[[[],[34,[0,380],[1,17],[1,18],[1,18],[1,17]]]]],
[243,`${spfblp}4.${heat}`,74,[[[],[34,[0,380],[0,395],[1,39],[1,20],[1,0]]]]],
[244,`${spfblp}4.${load}`,81,[[[],[34,[0,380],[1,13],[0,418],[1,13],[1,13]]]]],
[245,`${spfblp}4.${mois}`,78,[[[],[34,[0,380],[1,32],[0,93],[1,32],[1,32]]]]],
[246,`${spfblp}4.${savr}`,85,[[[],[34,[0,380],[1,8],[1,35],[1,8],[1,8]]]]],
[247,`${spfblp}4.${emc}`,73,[[[],[34,[0,380],[1,23],[1,24],[1,24],[1,23]]]]],
[248,`${spfblp}4.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[249,`${spfblp}4.${ef}.${ehn}`,72,[[[],[35,[0,246]]]]],
[250,`${spfblp}4.${ef}.${load}`,81,[[[],[36,[0,246],[0,244],[1,38]]]]],
[251,`${spfblp}4.${qig}`,75,[[[],[37,[0,245],[0,249]]]]],
[252,`${spfblp}4.net.${load}`,81,[[[],[38,[0,244],[0,248]]]]],
[253,`${spfblp}4.${sc}`,83,[[[],[39,[0,246]]]]],
[254,`${spfblp}4.${sc}.${wf}`,106,[[[],[40,[0,253],[0,310]]]]],
[255,`${spfblp}4.${sa}`,84,[[[],[41,[0,244],[0,246],[0,242]]]]],
[256,`${spfblp}4.${sa}.${wf}`,106,[[[],[42,[0,255],[0,294]]]]],
[257,`${spfblp}4.volume`,90,[[[],[43,[0,244],[0,242]]]]],
[258,`${spfblp}5.${dens}`,82,[[[],[34,[0,380],[1,17],[1,17],[1,18],[1,17]]]]],
[259,`${spfblp}5.${heat}`,74,[[[],[34,[0,380],[0,395],[1,36],[1,20],[1,0]]]]],
[260,`${spfblp}5.${load}`,81,[[[],[34,[0,380],[1,13],[0,419],[1,13],[1,13]]]]],
[261,`${spfblp}5.${mois}`,78,[[[],[34,[0,380],[1,32],[0,92],[1,32],[1,32]]]]],
[262,`${spfblp}5.${savr}`,85,[[[],[34,[0,380],[1,8],[1,40],[1,8],[1,8]]]]],
[263,`${spfblp}5.${emc}`,73,[[[],[34,[0,380],[1,23],[1,41],[1,24],[1,23]]]]],
[264,`${spfblp}5.${tmc}`,89,[[[],[34,[0,380],[1,25],[1,26],[1,27],[1,26]]]]],
[265,`${spfblp}5.${ef}.${ehn}`,72,[[[],[35,[0,262]]]]],
[266,`${spfblp}5.${ef}.${load}`,81,[[[],[36,[0,262],[0,260],[1,38]]]]],
[267,`${spfblp}5.${qig}`,75,[[[],[37,[0,261],[0,265]]]]],
[268,`${spfblp}5.net.${load}`,81,[[[],[38,[0,260],[0,264]]]]],
[269,`${spfblp}5.${sc}`,83,[[[],[39,[0,262]]]]],
[270,`${spfblp}5.${sc}.${wf}`,106,[[[],[40,[0,269],[0,310]]]]],
[271,`${spfblp}5.${sa}`,84,[[[],[41,[0,260],[0,262],[0,258]]]]],
[272,`${spfblp}5.${sa}.${wf}`,106,[[[],[42,[0,271],[0,294]]]]],
[273,`${spfblp}5.volume`,90,[[[],[43,[0,260],[0,258]]]]],
[274,`${spfbd}.${sa}`,84,[[[],[45,[0,122],[0,139],[0,156],[0,173],[0,190]]]]],
[275,`${spfbd}.${sa}.${wf}`,106,[[[],[21,[0,274],[0,329]]]]],
[276,`${spfbd}.mineralDamping`,45,[[[],[46,[0,289]]]]],
[277,`${spfbd}.moistureDamping`,45,[[[],[47,[0,283],[0,281]]]]],
[278,`${spfbd}.${heat}`,74,[[[],[48,[0,123],[0,140],[0,157],[0,174],[0,191],[0,110],[0,127],[0,144],[0,161],[0,178]]]]],
[279,`${spfbd}.${load}`,81,[[[],[45,[0,111],[0,128],[0,145],[0,162],[0,179]]]]],
[280,`${spfbd}.${ef}.${load}`,81,[[[],[45,[0,117],[0,134],[0,151],[0,168],[0,185]]]]],
[281,`${spfbd}.extinction.${mois}`,78,[[[],[34,[0,380],[0,385],[1,42],[1,43],[1,44]]]]],
[282,`${spfbd}.extinction.${mois}Factor`,34,[[[],[49,[0,280],[0,300]]]]],
[283,`${spfbd}.${mois}`,78,[[[],[48,[0,123],[0,140],[0,157],[0,174],[0,191],[0,112],[0,129],[0,146],[0,163],[0,180]]]]],
[284,`${spfbd}.volume`,65,[[[],[45,[0,124],[0,141],[0,158],[0,175],[0,192]]]]],
[285,`${spfbd}.${qig}`,75,[[[],[48,[0,123],[0,140],[0,157],[0,174],[0,191],[0,118],[0,135],[0,152],[0,169],[0,186]]]]],
[286,`${spfbd}.${rxi}`,55,[[[],[22,[0,287],[0,277]]]]],
[287,`${spfbd}.${rxi}Dry`,55,[[[],[50,[0,326],[0,291],[0,278],[0,276]]]]],
[288,`${spfbd}.${savr}`,85,[[[],[48,[0,123],[0,140],[0,157],[0,174],[0,191],[0,113],[0,130],[0,147],[0,164],[0,181]]]]],
[289,`${spfbd}.${emc}`,73,[[[],[48,[0,123],[0,140],[0,157],[0,174],[0,191],[0,114],[0,131],[0,148],[0,165],[0,182]]]]],
[290,`${spfbd}.${sc}.${wf}`,106,[[[],[51,[0,122],[0,120],[0,139],[0,137],[0,156],[0,154],[0,173],[0,171],[0,190],[0,188]]]]],
[291,`${spfbd}.net.${load}`,81,[[[],[48,[0,121],[0,138],[0,155],[0,172],[0,189],[0,119],[0,136],[0,153],[0,170],[0,187]]]]],
[292,`${spfbd}.${ef}.waterLoad`,81,[[[],[45,[0,125],[0,142],[0,159],[0,176],[0,193]]]]],
[293,`${spfbd}.${ef}.${mois}`,78,[[[],[21,[0,292],[0,280]]]]],
[294,`${spfbl}.${sa}`,84,[[[],[45,[0,207],[0,223],[0,239],[0,255],[0,271]]]]],
[295,`${spfbl}.${sa}.${wf}`,106,[[[],[21,[0,294],[0,329]]]]],
[296,`${spfbl}.mineralDamping`,45,[[[],[46,[0,309]]]]],
[297,`${spfbl}.moistureDamping`,45,[[[],[47,[0,303],[0,301]]]]],
[298,`${spfbl}.${heat}`,74,[[[],[48,[0,208],[0,224],[0,240],[0,256],[0,272],[0,195],[0,211],[0,227],[0,243],[0,259]]]]],
[299,`${spfbl}.${load}`,81,[[[],[45,[0,196],[0,212],[0,228],[0,244],[0,260]]]]],
[300,`${spfbl}.${ef}.${load}`,81,[[[],[45,[0,202],[0,218],[0,234],[0,250],[0,266]]]]],
[301,`${spfbl}.extinction.${mois}`,78,[[[],[52,[0,302],[0,293],[0,281]]]]],
[302,`${spfbl}.extinction.${mois}Factor`,34,[[[],[49,[0,280],[0,300]]]]],
[303,`${spfbl}.${mois}`,78,[[[],[48,[0,208],[0,224],[0,240],[0,256],[0,272],[0,197],[0,213],[0,229],[0,245],[0,261]]]]],
[304,`${spfbl}.volume`,65,[[[],[45,[0,209],[0,225],[0,241],[0,257],[0,273]]]]],
[305,`${spfbl}.${qig}`,75,[[[],[48,[0,208],[0,224],[0,240],[0,256],[0,272],[0,203],[0,219],[0,235],[0,251],[0,267]]]]],
[306,`${spfbl}.${rxi}`,55,[[[],[22,[0,307],[0,297]]]]],
[307,`${spfbl}.${rxi}Dry`,55,[[[],[50,[0,326],[0,311],[0,298],[0,296]]]]],
[308,`${spfbl}.${savr}`,85,[[[],[48,[0,208],[0,224],[0,240],[0,256],[0,272],[0,198],[0,214],[0,230],[0,246],[0,262]]]]],
[309,`${spfbl}.${emc}`,73,[[[],[48,[0,208],[0,224],[0,240],[0,256],[0,272],[0,199],[0,215],[0,231],[0,247],[0,263]]]]],
[310,`${spfbl}.${sc}.${wf}`,106,[[[],[51,[0,207],[0,205],[0,223],[0,221],[0,239],[0,237],[0,255],[0,253],[0,271],[0,269]]]]],
[311,`${spfbl}.net.${load}`,81,[[[],[48,[0,206],[0,222],[0,238],[0,254],[0,270],[0,204],[0,220],[0,236],[0,252],[0,268]]]]],
[312,`${spfb}.depth`,65,[[[],[34,[0,380],[0,384],[0,401],[0,425],[0,436]]]]],
[313,`${spfb}.bulkDensity`,64,[[[],[21,[0,317],[0,312]]]]],
[314,`${spfb}.${qig}`,66,[[[],[48,[0,275],[0,295],[0,285],[0,305]]]]],
[315,`${spfb}.heatSink`,76,[[[],[53,[0,314],[0,313]]]]],
[316,`${spfb}.noWindNoSlope.${ros}`,61,[[[],[54,[0,323],[0,322],[0,315]]]]],
[317,`${spfb}.${load}`,81,[[[],[45,[0,279],[0,299]]]]],
[318,`${spfb}.open.${waf}`,108,[[[],[55,[0,312]]]]],
[319,`${spfb}.packingRatio`,67,[[[],[56,[0,284],[0,304],[0,312]]]]],
[320,`${spfb}.packingRatio.optimum`,67,[[[],[57,[0,327]]]]],
[321,`${spfb}.packingRatio.ratio`,67,[[[],[21,[0,319],[0,320]]]]],
[322,`${spfb}.propagatingFluxRatio`,54,[[[],[58,[0,327],[0,319]]]]],
[323,`${spfb}.${rxi}`,55,[[[],[45,[0,286],[0,306]]]]],
[324,`${spfb}.reactionVelocityExponent`,34,[[[],[59,[0,327]]]]],
[325,`${spfb}.reactionVelocityMaximum`,56,[[[],[60,[0,328]]]]],
[326,`${spfb}.reactionVelocityOptimum`,56,[[[],[61,[0,321],[0,325],[0,324]]]]],
[327,`${spfb}.${savr}`,85,[[[],[48,[0,275],[0,295],[0,288],[0,308]]]]],
[328,`${spfb}.savr15`,34,[[[],[62,[0,327]]]]],
[329,`${spfb}.${sa}`,84,[[[],[45,[0,274],[0,294]]]]],
[330,`${spff}.maximumDirection.slope.${ros}`,61,[[[],[63,[0,379],[0,343]]]]],
[331,`${spff}.maximumDirection.wind.${ros}`,61,[[[],[64,[0,379],[0,366]]]]],
[332,`${spff}.wind.heading.fromUpslope`,37,[[[],[25,[0,101]]]]],
[333,`${spff}.maximumDirection.xComponent`,34,[[[],[65,[0,331],[0,330],[0,332]]]]],
[334,`${spff}.maximumDirection.yComponent`,34,[[[],[66,[0,331],[0,332]]]]],
[335,`${spff}.maximumDirection.${ros}`,61,[[[],[67,[0,333],[0,334]]]]],
[336,`${spff}.limit.${ews}.exceeded`,31,[[[],[68,[0,347],[0,338]]]]],
[337,`${spff}.limit.${ros}.exceeded`,32,[[[],[68,[0,349],[0,355]]]]],
[338,`${spff}.limit.${ews}`,107,[[[],[69,[0,376]]]]],
[339,`${spff}.limit.windSlopeSpreadRateCoefficient`,34,[[[],[70,[0,338],[0,361],[0,364]]]]],
[340,`${spff}.limit.${ros}`,61,[[[],[71,[0,379],[0,339]]]]],
[341,`${spff}.slope.ratio`,100,[[[],[25,[0,98]]]]],
[342,`${spff}.slope.k`,34,[[[],[72,[0,319]]]]],
[343,`${spff}.slope.phi`,34,[[[],[73,[0,341],[0,342]]]]],
[344,`${spff}.spread.step1.${ews}`,107,[[[],[74,[0,345],[0,361],[0,365]]]]],
[345,`${spff}.spread.step1.${phiew}`,34,[[[],[75,[0,366],[0,343]]]]],
[346,`${spff}.spread.step1.${ros}`,61,[[[],[71,[0,379],[0,345]]]]],
[347,`${spff}.spread.step2.${ews}`,107,[[[],[74,[0,348],[0,361],[0,365]]]]],
[348,`${spff}.spread.step2.${phiew}`,34,[[[],[76,[0,379],[0,349]]]]],
[349,`${spff}.spread.step2.${ros}`,61,[[[],[77,[0,379],[0,335]]]]],
[350,`${spff}.spread.step3a.${ews}`,107,[[[],[78,[0,347],[0,338]]]]],
[351,`${spff}.spread.step3a.${phiew}`,34,[[[],[78,[0,348],[0,339]]]]],
[352,`${spff}.spread.step3a.${ros}`,61,[[[],[78,[0,349],[0,340]]]]],
[353,`${spff}.spread.step3b.${ews}`,107,[[[],[74,[0,354],[0,361],[0,365]]]]],
[354,`${spff}.spread.step3b.${phiew}`,34,[[[],[76,[0,379],[0,355]]]]],
[355,`${spff}.spread.step3b.${ros}`,61,[[[],[79,[0,349],[0,347]]]]],
[356,`${spff}.spread.step4.${ews}`,107,[[[],[74,[0,357],[0,361],[0,365]]]]],
[357,`${spff}.spread.step4.${phiew}`,34,[[[],[76,[0,379],[0,358]]]]],
[358,`${spff}.spread.step4.${ros}`,61,[[[],[79,[0,352],[0,350]]]]],
[359,`${spff}.${waf}`,108,[[[20,45],[25,[0,108]]],[[],[80,[0,50],[0,53],[0,318]]]]],
[360,`${spff}.wind.speed.atMidflame`,107,[[[25,16],[25,[0,107]]],[[],[33,[0,106],[0,359]]]]],
[361,`${spff}.wind.factor.b`,34,[[[],[81,[0,327]]]]],
[362,`${spff}.wind.factor.c`,34,[[[],[82,[0,327]]]]],
[363,`${spff}.wind.factor.e`,34,[[[],[83,[0,327]]]]],
[364,`${spff}.wind.factor.k`,34,[[[],[84,[0,321],[0,363],[0,362]]]]],
[365,`${spff}.wind.factor.i`,34,[[[],[85,[0,321],[0,363],[0,362]]]]],
[366,`${spff}.wind.phi`,34,[[[],[86,[0,360],[0,361],[0,364]]]]],
[367,`${spff}.${ews}`,107,[[[28,46],[25,[0,356]]],[[],[25,[0,353]]]]],
[368,`${spff}.${fli}`,47,[[[],[87,[0,378],[0,376],[0,370]]]]],
[369,`${spff}.${fl}`,49,[[[],[17,[0,368]]]]],
[370,`${spff}.${taur}`,57,[[[],[88,[0,327]]]]],
[371,`${spff}.heading.fromUpslope`,37,[[[],[89,[0,333],[0,334],[0,335]]]]],
[372,`${spff}.heading.fromNorth`,37,[[[],[19,[0,96],[0,371]]]]],
[373,`${spff}.${hpua}`,50,[[[],[90,[0,376],[0,370]]]]],
[374,`${spff}.${lwr}`,51,[[[],[20,[0,367]]]]],
[375,`${spff}.${phiew}`,34,[[[28,46],[25,[0,357]]],[[],[25,[0,354]]]]],
[376,`${spff}.${rxi}`,55,[[[],[25,[0,323]]]]],
[377,`${spff}.${sh}`,58,[[[],[91,[0,368],[0,360],[0,99]]]]],
[378,`${spff}.${ros}`,61,[[[28,46],[25,[0,358]]],[[],[25,[0,355]]]]],
[379,`${spff}.noWindNoSlope.${ros}`,61,[[[],[25,[0,316]]]]],
[380,`${spf}.model.domain`,21,[[[17,47],[92,[0,381]]],[[17,48],[9,[1,48]]],[[17,49],[9,[1,49]]],[[17,50],[9,[1,50]]],[[17,51],[9,[1,51]]],[[],[9,[1,52]]]]],
[381,`${spf}.model.catalogKey`,22,[[[],[2]]]],
[382,`${spf}.model.behave.domain`,21,[[[],[9,[1,48]]]]],
[383,`${spf}.${mbp}.cured.herb.fraction`,71,[[[21,53],[93,[0,92]]],[[],[2]]]],
[384,`${spf}.${mbp}.depth`,65,[[[17,47],[94,[0,381]]],[[17,48],[2]],[[],[9,[1,23]]]]],
[385,`${spf}.${mbp}.dead.extinction.${mois}`,78,[[[17,47],[95,[0,381]]],[[17,48],[2]],[[],[9,[1,44]]]]],
[386,`${spf}.${mbp}.total.herb.${load}`,81,[[[17,47],[96,[0,381]]],[[17,48],[2]],[[],[9,[1,13]]]]],
[387,`${spf}.${mbp}.dead.tl1h.${load}`,81,[[[17,47],[97,[0,381]]],[[17,48],[2]],[[],[9,[1,13]]]]],
[388,`${spf}.${mbp}.dead.tl10h.${load}`,81,[[[17,47],[98,[0,381]]],[[17,48],[2]],[[],[9,[1,13]]]]],
[389,`${spf}.${mbp}.dead.tl100h.${load}`,81,[[[17,47],[99,[0,381]]],[[17,48],[2]],[[],[9,[1,13]]]]],
[390,`${spf}.${mbp}.live.stem.${load}`,81,[[[17,47],[100,[0,381]]],[[17,48],[2]],[[],[9,[1,13]]]]],
[391,`${spf}.${mbp}.dead.tl1h.${savr}`,85,[[[17,47],[101,[0,381]]],[[17,48],[2]],[[],[9,[1,13]]]]],
[392,`${spf}.${mbp}.live.herb.${savr}`,85,[[[17,47],[102,[0,381]]],[[17,48],[2]],[[],[9,[1,8]]]]],
[393,`${spf}.${mbp}.live.stem.${savr}`,85,[[[17,47],[103,[0,381]]],[[17,48],[2]],[[],[9,[1,8]]]]],
[394,`${spf}.${mbp}.dead.${heat}`,74,[[[17,47],[104,[0,381]]],[[17,48],[2]],[[],[9,[1,0]]]]],
[395,`${spf}.${mbp}.live.${heat}`,74,[[[17,47],[105,[0,381]]],[[17,48],[2]],[[],[9,[1,0]]]]],
[396,`${spf}.${mbd}.dead.herb.${load}`,81,[[[],[106,[0,386],[0,383]]]]],
[397,`${spf}.${mbd}.live.herb.${load}`,81,[[[],[107,[0,386],[0,383]]]]],
[398,`${spf}.model.chaparral.domain`,21,[[[],[9,[1,49]]]]],
[399,`${spf}.${mcp}.chaparralType`,19,[[[17,47],[108,[0,381]]],[[17,49],[2]],[[],[9,[1,54]]]]],
[400,`${spf}.${mcp}.observed.deadFuelFraction`,71,[[[17,47],[109,[0,381]]],[[17,49],[2]],[[],[9,[1,13]]]]],
[401,`${spf}.${mcp}.observed.depth`,65,[[[17,47],[110,[0,381]]],[[17,49],[2]],[[],[9,[1,23]]]]],
[402,`${spf}.${mcp}.observed.totalLoad`,81,[[[17,47],[111,[0,381]]],[[17,49],[2]],[[],[9,[1,13]]]]],
[403,`${spf}.${mcp}.applied.totalLoad`,81,[[[22,53],[25,[0,408]]],[[],[25,[0,402]]]]],
[404,`${spf}.${mcd}.age`,62,[[[],[112,[0,401],[0,399]]]]],
[405,`${spf}.${mcd}.averageMortality`,98,[[[],[113,[0,404]]]]],
[406,`${spf}.${mcd}.severeMortality`,98,[[[],[114,[0,404]]]]],
[407,`${spf}.${mcd}.depth`,65,[[[],[115,[0,404],[0,399]]]]],
[408,`${spf}.${mcd}.totalLoad`,81,[[[],[116,[0,404],[0,399]]]]],
[409,`${spf}.${mcd}.deadLoad`,81,[[[],[117,[0,403],[0,400]]]]],
[410,`${spf}.${mcd}.deadFineLoad`,81,[[[],[118,[0,403],[0,400]]]]],
[411,`${spf}.${mcd}.deadSmallLoad`,81,[[[],[119,[0,403],[0,400]]]]],
[412,`${spf}.${mcd}.deadMediumLoad`,81,[[[],[120,[0,403],[0,400]]]]],
[413,`${spf}.${mcd}.deadLargeLoad`,81,[[[],[121,[0,403],[0,400]]]]],
[414,`${spf}.${mcd}.liveLoad`,81,[[[],[122,[0,403],[0,400]]]]],
[415,`${spf}.${mcd}.liveFineLoad`,81,[[[],[123,[0,403],[0,400]]]]],
[416,`${spf}.${mcd}.liveSmallLoad`,81,[[[],[124,[0,403],[0,400]]]]],
[417,`${spf}.${mcd}.liveMediumLoad`,81,[[[],[125,[0,403],[0,400]]]]],
[418,`${spf}.${mcd}.liveLargeLoad`,81,[[[],[126,[0,403],[0,400]]]]],
[419,`${spf}.${mcd}.liveLeafLoad`,81,[[[],[127,[0,403],[0,400]]]]],
[420,`${spf}.model.palmettoGallberry.domain`,21,[[[],[9,[1,50]]]]],
[421,`${spf}.${mpp}.age`,62,[[[17,47],[128,[0,381]]],[[17,50],[2]],[[],[9,[1,13]]]]],
[422,`${spf}.${mpp}.basalArea`,63,[[[17,47],[129,[0,381]]],[[17,50],[2]],[[],[9,[1,13]]]]],
[423,`${spf}.${mpp}.cover`,68,[[[17,47],[130,[0,381]]],[[17,50],[2]],[[],[9,[1,13]]]]],
[424,`${spf}.${mpp}.height`,65,[[[17,47],[131,[0,381]]],[[17,50],[2]],[[],[9,[1,23]]]]],
[425,`${spf}.${mpd}.depth`,65,[[[],[132,[0,424]]]]],
[426,`${spf}.${mpd}.deadFineLoad`,81,[[[],[133,[0,421],[0,424]]]]],
[427,`${spf}.${mpd}.deadSmallLoad`,81,[[[],[134,[0,421],[0,423]]]]],
[428,`${spf}.${mpd}.deadFoliageLoad`,81,[[[],[135,[0,421],[0,423]]]]],
[429,`${spf}.${mpd}.deadLitterLoad`,81,[[[],[136,[0,421],[0,422]]]]],
[430,`${spf}.${mpd}.liveFineLoad`,81,[[[],[137,[0,421],[0,424]]]]],
[431,`${spf}.${mpd}.liveSmallLoad`,81,[[[],[138,[0,421],[0,424]]]]],
[432,`${spf}.${mpd}.liveFoliageLoad`,81,[[[],[139,[0,421],[0,423],[0,424]]]]],
[433,`${spf}.model.westernAspen.domain`,21,[[[],[9,[1,51]]]]],
[434,`${spf}.${mwp}.aspenType`,28,[[[17,47],[140,[0,381]]],[[17,51],[2]],[[],[9,[1,55]]]]],
[435,`${spf}.${mwp}.curingLevel`,71,[[[17,47],[141,[0,381]]],[[17,51],[2]],[[],[9,[1,13]]]]],
[436,`${spf}.${mwd}.depth`,65,[[[],[142,[0,434]]]]],
[437,`${spf}.${mwd}.dead.fine.${load}`,81,[[[],[143,[0,434],[0,435]]]]],
[438,`${spf}.${mwd}.dead.small.${load}`,81,[[[],[144,[0,434]]]]],
[439,`${spf}.${mwd}.dead.fine.${savr}`,81,[[[],[145,[0,434],[0,435]]]]],
[440,`${spf}.${mwd}.live.herb.${load}`,81,[[[],[146,[0,434],[0,435]]]]],
[441,`${spf}.${mwd}.live.stem.${load}`,81,[[[],[147,[0,434],[0,435]]]]],
[442,`${spf}.${mwd}.live.stem.${savr}`,81,[[[],[148,[0,434],[0,435]]]]],
[443,`${ssfbdp}1.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,19],[1,17]]]]],
[444,`${ssfbdp}1.${heat}`,74,[[[],[34,[0,714],[0,728],[1,0],[1,20],[1,0]]]]],
[445,`${ssfbdp}1.${load}`,81,[[[],[34,[0,714],[0,721],[0,744],[0,760],[0,771]]]]],
[446,`${ssfbdp}1.${mois}`,78,[[[],[34,[0,714],[0,88],[0,88],[0,88],[0,88]]]]],
[447,`${ssfbdp}1.${savr}`,85,[[[],[34,[0,714],[0,725],[1,21],[1,22],[0,773]]]]],
[448,`${ssfbdp}1.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,23],[1,23]]]]],
[449,`${ssfbdp}1.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[450,`${ssfbdp}1.${ef}.${ehn}`,72,[[[],[35,[0,447]]]]],
[451,`${ssfbdp}1.${ef}.${load}`,81,[[[],[36,[0,447],[0,445],[1,28]]]]],
[452,`${ssfbdp}1.${qig}`,75,[[[],[37,[0,446],[0,450]]]]],
[453,`${ssfbdp}1.net.${load}`,81,[[[],[38,[0,445],[0,449]]]]],
[454,`${ssfbdp}1.${sc}`,83,[[[],[39,[0,447]]]]],
[455,`${ssfbdp}1.${sc}.${wf}`,106,[[[],[40,[0,454],[0,624]]]]],
[456,`${ssfbdp}1.${sa}`,84,[[[],[41,[0,445],[0,447],[0,443]]]]],
[457,`${ssfbdp}1.${sa}.${wf}`,106,[[[],[42,[0,456],[0,608]]]]],
[458,`${ssfbdp}1.volume`,90,[[[],[43,[0,445],[0,443]]]]],
[459,`${ssfbdp}1.${ef}.waterLoad`,81,[[[],[44,[0,451],[0,446]]]]],
[460,`${ssfbdp}2.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,19],[1,17]]]]],
[461,`${ssfbdp}2.${heat}`,74,[[[],[34,[0,714],[0,728],[1,0],[1,20],[1,0]]]]],
[462,`${ssfbdp}2.${load}`,81,[[[],[34,[0,714],[0,722],[0,745],[0,761],[0,772]]]]],
[463,`${ssfbdp}2.${mois}`,78,[[[],[34,[0,714],[0,89],[0,89],[0,89],[0,89]]]]],
[464,`${ssfbdp}2.${savr}`,85,[[[],[34,[0,714],[1,29],[1,30],[1,31],[1,29]]]]],
[465,`${ssfbdp}2.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,23],[1,23]]]]],
[466,`${ssfbdp}2.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[467,`${ssfbdp}2.${ef}.${ehn}`,72,[[[],[35,[0,464]]]]],
[468,`${ssfbdp}2.${ef}.${load}`,81,[[[],[36,[0,464],[0,462],[1,28]]]]],
[469,`${ssfbdp}2.${qig}`,75,[[[],[37,[0,463],[0,467]]]]],
[470,`${ssfbdp}2.net.${load}`,81,[[[],[38,[0,462],[0,466]]]]],
[471,`${ssfbdp}2.${sc}`,83,[[[],[39,[0,464]]]]],
[472,`${ssfbdp}2.${sc}.${wf}`,106,[[[],[40,[0,471],[0,624]]]]],
[473,`${ssfbdp}2.${sa}`,84,[[[],[41,[0,462],[0,464],[0,460]]]]],
[474,`${ssfbdp}2.${sa}.${wf}`,106,[[[],[42,[0,473],[0,608]]]]],
[475,`${ssfbdp}2.volume`,90,[[[],[43,[0,462],[0,460]]]]],
[476,`${ssfbdp}2.${ef}.waterLoad`,81,[[[],[44,[0,468],[0,463]]]]],
[477,`${ssfbdp}3.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,19],[1,17]]]]],
[478,`${ssfbdp}3.${heat}`,74,[[[],[34,[0,714],[0,728],[1,0],[1,20],[1,0]]]]],
[479,`${ssfbdp}3.${load}`,81,[[[],[34,[0,714],[0,723],[0,746],[0,762],[1,13]]]]],
[480,`${ssfbdp}3.${mois}`,78,[[[],[34,[0,714],[0,90],[0,89],[0,88],[1,32]]]]],
[481,`${ssfbdp}3.${savr}`,85,[[[],[34,[0,714],[1,19],[1,33],[1,34],[1,8]]]]],
[482,`${ssfbdp}3.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,23],[1,23]]]]],
[483,`${ssfbdp}3.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[484,`${ssfbdp}3.${ef}.${ehn}`,72,[[[],[35,[0,481]]]]],
[485,`${ssfbdp}3.${ef}.${load}`,81,[[[],[36,[0,481],[0,479],[1,28]]]]],
[486,`${ssfbdp}3.${qig}`,75,[[[],[37,[0,480],[0,484]]]]],
[487,`${ssfbdp}3.net.${load}`,81,[[[],[38,[0,479],[0,483]]]]],
[488,`${ssfbdp}3.${sc}`,83,[[[],[39,[0,481]]]]],
[489,`${ssfbdp}3.${sc}.${wf}`,106,[[[],[40,[0,488],[0,624]]]]],
[490,`${ssfbdp}3.${sa}`,84,[[[],[41,[0,479],[0,481],[0,477]]]]],
[491,`${ssfbdp}3.${sa}.${wf}`,106,[[[],[42,[0,490],[0,608]]]]],
[492,`${ssfbdp}3.volume`,90,[[[],[43,[0,479],[0,477]]]]],
[493,`${ssfbdp}3.${ef}.waterLoad`,81,[[[],[44,[0,485],[0,480]]]]],
[494,`${ssfbdp}4.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,19],[1,17]]]]],
[495,`${ssfbdp}4.${heat}`,74,[[[],[34,[0,714],[0,728],[1,0],[1,20],[1,0]]]]],
[496,`${ssfbdp}4.${load}`,81,[[[],[34,[0,714],[0,730],[0,747],[0,763],[1,13]]]]],
[497,`${ssfbdp}4.${mois}`,78,[[[],[34,[0,714],[0,88],[0,90],[0,90],[1,32]]]]],
[498,`${ssfbdp}4.${savr}`,85,[[[],[34,[0,714],[0,726],[1,35],[1,34],[1,8]]]]],
[499,`${ssfbdp}4.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,23],[1,23]]]]],
[500,`${ssfbdp}4.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[501,`${ssfbdp}4.${ef}.${ehn}`,72,[[[],[35,[0,498]]]]],
[502,`${ssfbdp}4.${ef}.${load}`,81,[[[],[36,[0,498],[0,496],[1,28]]]]],
[503,`${ssfbdp}4.${qig}`,75,[[[],[37,[0,497],[0,501]]]]],
[504,`${ssfbdp}4.net.${load}`,81,[[[],[38,[0,496],[0,500]]]]],
[505,`${ssfbdp}4.${sc}`,83,[[[],[39,[0,498]]]]],
[506,`${ssfbdp}4.${sc}.${wf}`,106,[[[],[40,[0,505],[0,624]]]]],
[507,`${ssfbdp}4.${sa}`,84,[[[],[41,[0,496],[0,498],[0,494]]]]],
[508,`${ssfbdp}4.${sa}.${wf}`,106,[[[],[42,[0,507],[0,608]]]]],
[509,`${ssfbdp}4.volume`,90,[[[],[43,[0,496],[0,494]]]]],
[510,`${ssfbdp}4.${ef}.waterLoad`,81,[[[],[44,[0,502],[0,497]]]]],
[511,`${ssfbdp}5.${dens}`,82,[[[],[9,[1,17]]]]],
[512,`${ssfbdp}5.${heat}`,74,[[[],[9,[1,0]]]]],
[513,`${ssfbdp}5.${load}`,81,[[[],[9,[1,13]]]]],
[514,`${ssfbdp}5.${mois}`,78,[[[],[9,[1,32]]]]],
[515,`${ssfbdp}5.${savr}`,85,[[[],[9,[1,8]]]]],
[516,`${ssfbdp}5.${emc}`,73,[[[],[9,[1,23]]]]],
[517,`${ssfbdp}5.${tmc}`,89,[[[],[9,[1,25]]]]],
[518,`${ssfbdp}5.${ef}.${ehn}`,72,[[[],[35,[0,515]]]]],
[519,`${ssfbdp}5.${ef}.${load}`,81,[[[],[36,[0,515],[0,513],[1,28]]]]],
[520,`${ssfbdp}5.${qig}`,75,[[[],[37,[0,514],[0,518]]]]],
[521,`${ssfbdp}5.net.${load}`,81,[[[],[38,[0,513],[0,517]]]]],
[522,`${ssfbdp}5.${sc}`,83,[[[],[39,[0,515]]]]],
[523,`${ssfbdp}5.${sc}.${wf}`,106,[[[],[40,[0,522],[0,624]]]]],
[524,`${ssfbdp}5.${sa}`,84,[[[],[41,[0,513],[0,515],[0,511]]]]],
[525,`${ssfbdp}5.${sa}.${wf}`,106,[[[],[42,[0,524],[0,608]]]]],
[526,`${ssfbdp}5.volume`,90,[[[],[43,[0,513],[0,511]]]]],
[527,`${ssfbdp}5.${ef}.waterLoad`,81,[[[],[44,[0,519],[0,514]]]]],
[528,`${ssfblp}1.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,18],[1,17]]]]],
[529,`${ssfblp}1.${heat}`,74,[[[],[34,[0,714],[0,729],[1,36],[1,20],[1,0]]]]],
[530,`${ssfblp}1.${load}`,81,[[[],[34,[0,714],[0,731],[0,749],[0,764],[0,774]]]]],
[531,`${ssfblp}1.${mois}`,78,[[[],[34,[0,714],[0,92],[0,93],[0,93],[0,92]]]]],
[532,`${ssfblp}1.${savr}`,85,[[[],[34,[0,714],[0,726],[1,21],[1,22],[1,37]]]]],
[533,`${ssfblp}1.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,24],[1,23]]]]],
[534,`${ssfblp}1.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[535,`${ssfblp}1.${ef}.${ehn}`,72,[[[],[35,[0,532]]]]],
[536,`${ssfblp}1.${ef}.${load}`,81,[[[],[36,[0,532],[0,530],[1,38]]]]],
[537,`${ssfblp}1.${qig}`,75,[[[],[37,[0,531],[0,535]]]]],
[538,`${ssfblp}1.net.${load}`,81,[[[],[38,[0,530],[0,534]]]]],
[539,`${ssfblp}1.${sc}`,83,[[[],[39,[0,532]]]]],
[540,`${ssfblp}1.${sc}.${wf}`,106,[[[],[40,[0,539],[0,644]]]]],
[541,`${ssfblp}1.${sa}`,84,[[[],[41,[0,530],[0,532],[0,528]]]]],
[542,`${ssfblp}1.${sa}.${wf}`,106,[[[],[42,[0,541],[0,628]]]]],
[543,`${ssfblp}1.volume`,90,[[[],[43,[0,530],[0,528]]]]],
[544,`${ssfblp}2.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,18],[1,17]]]]],
[545,`${ssfblp}2.${heat}`,74,[[[],[34,[0,714],[0,729],[1,39],[1,20],[1,0]]]]],
[546,`${ssfblp}2.${load}`,81,[[[],[34,[0,714],[0,724],[0,750],[0,765],[0,775]]]]],
[547,`${ssfblp}2.${mois}`,78,[[[],[34,[0,714],[0,93],[0,93],[0,93],[0,93]]]]],
[548,`${ssfblp}2.${savr}`,85,[[[],[34,[0,714],[0,727],[1,30],[1,31],[0,776]]]]],
[549,`${ssfblp}2.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,24],[1,23]]]]],
[550,`${ssfblp}2.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[551,`${ssfblp}2.${ef}.${ehn}`,72,[[[],[35,[0,548]]]]],
[552,`${ssfblp}2.${ef}.${load}`,81,[[[],[36,[0,548],[0,546],[1,38]]]]],
[553,`${ssfblp}2.${qig}`,75,[[[],[37,[0,547],[0,551]]]]],
[554,`${ssfblp}2.net.${load}`,81,[[[],[38,[0,546],[0,550]]]]],
[555,`${ssfblp}2.${sc}`,83,[[[],[39,[0,548]]]]],
[556,`${ssfblp}2.${sc}.${wf}`,106,[[[],[40,[0,555],[0,644]]]]],
[557,`${ssfblp}2.${sa}`,84,[[[],[41,[0,546],[0,548],[0,544]]]]],
[558,`${ssfblp}2.${sa}.${wf}`,106,[[[],[42,[0,557],[0,628]]]]],
[559,`${ssfblp}2.volume`,90,[[[],[43,[0,546],[0,544]]]]],
[560,`${ssfblp}3.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,18],[1,17]]]]],
[561,`${ssfblp}3.${heat}`,74,[[[],[34,[0,714],[0,729],[1,39],[1,20],[1,0]]]]],
[562,`${ssfblp}3.${load}`,81,[[[],[34,[0,714],[1,13],[0,751],[0,766],[1,13]]]]],
[563,`${ssfblp}3.${mois}`,78,[[[],[34,[0,714],[1,32],[0,93],[0,93],[1,32]]]]],
[564,`${ssfblp}3.${savr}`,85,[[[],[34,[0,714],[1,8],[1,33],[1,34],[1,8]]]]],
[565,`${ssfblp}3.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,24],[1,23]]]]],
[566,`${ssfblp}3.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[567,`${ssfblp}3.${ef}.${ehn}`,72,[[[],[35,[0,564]]]]],
[568,`${ssfblp}3.${ef}.${load}`,81,[[[],[36,[0,564],[0,562],[1,38]]]]],
[569,`${ssfblp}3.${qig}`,75,[[[],[37,[0,563],[0,567]]]]],
[570,`${ssfblp}3.net.${load}`,81,[[[],[38,[0,562],[0,566]]]]],
[571,`${ssfblp}3.${sc}`,83,[[[],[39,[0,564]]]]],
[572,`${ssfblp}3.${sc}.${wf}`,106,[[[],[40,[0,571],[0,644]]]]],
[573,`${ssfblp}3.${sa}`,84,[[[],[41,[0,562],[0,564],[0,560]]]]],
[574,`${ssfblp}3.${sa}.${wf}`,106,[[[],[42,[0,573],[0,628]]]]],
[575,`${ssfblp}3.volume`,90,[[[],[43,[0,562],[0,560]]]]],
[576,`${ssfblp}4.${dens}`,82,[[[],[34,[0,714],[1,17],[1,18],[1,18],[1,17]]]]],
[577,`${ssfblp}4.${heat}`,74,[[[],[34,[0,714],[0,729],[1,39],[1,20],[1,0]]]]],
[578,`${ssfblp}4.${load}`,81,[[[],[34,[0,714],[1,13],[0,752],[1,13],[1,13]]]]],
[579,`${ssfblp}4.${mois}`,78,[[[],[34,[0,714],[1,32],[0,93],[1,32],[1,32]]]]],
[580,`${ssfblp}4.${savr}`,85,[[[],[34,[0,714],[1,8],[1,35],[1,8],[1,8]]]]],
[581,`${ssfblp}4.${emc}`,73,[[[],[34,[0,714],[1,23],[1,24],[1,24],[1,23]]]]],
[582,`${ssfblp}4.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[583,`${ssfblp}4.${ef}.${ehn}`,72,[[[],[35,[0,580]]]]],
[584,`${ssfblp}4.${ef}.${load}`,81,[[[],[36,[0,580],[0,578],[1,38]]]]],
[585,`${ssfblp}4.${qig}`,75,[[[],[37,[0,579],[0,583]]]]],
[586,`${ssfblp}4.net.${load}`,81,[[[],[38,[0,578],[0,582]]]]],
[587,`${ssfblp}4.${sc}`,83,[[[],[39,[0,580]]]]],
[588,`${ssfblp}4.${sc}.${wf}`,106,[[[],[40,[0,587],[0,644]]]]],
[589,`${ssfblp}4.${sa}`,84,[[[],[41,[0,578],[0,580],[0,576]]]]],
[590,`${ssfblp}4.${sa}.${wf}`,106,[[[],[42,[0,589],[0,628]]]]],
[591,`${ssfblp}4.volume`,90,[[[],[43,[0,578],[0,576]]]]],
[592,`${ssfblp}5.${dens}`,82,[[[],[34,[0,714],[1,17],[1,17],[1,18],[1,17]]]]],
[593,`${ssfblp}5.${heat}`,74,[[[],[34,[0,714],[0,729],[1,36],[1,20],[1,0]]]]],
[594,`${ssfblp}5.${load}`,81,[[[],[34,[0,714],[1,13],[0,753],[1,13],[1,13]]]]],
[595,`${ssfblp}5.${mois}`,78,[[[],[34,[0,714],[1,32],[0,92],[1,32],[1,32]]]]],
[596,`${ssfblp}5.${savr}`,85,[[[],[34,[0,714],[1,8],[1,40],[1,8],[1,8]]]]],
[597,`${ssfblp}5.${emc}`,73,[[[],[34,[0,714],[1,23],[1,41],[1,24],[1,23]]]]],
[598,`${ssfblp}5.${tmc}`,89,[[[],[34,[0,714],[1,25],[1,26],[1,27],[1,26]]]]],
[599,`${ssfblp}5.${ef}.${ehn}`,72,[[[],[35,[0,596]]]]],
[600,`${ssfblp}5.${ef}.${load}`,81,[[[],[36,[0,596],[0,594],[1,38]]]]],
[601,`${ssfblp}5.${qig}`,75,[[[],[37,[0,595],[0,599]]]]],
[602,`${ssfblp}5.net.${load}`,81,[[[],[38,[0,594],[0,598]]]]],
[603,`${ssfblp}5.${sc}`,83,[[[],[39,[0,596]]]]],
[604,`${ssfblp}5.${sc}.${wf}`,106,[[[],[40,[0,603],[0,644]]]]],
[605,`${ssfblp}5.${sa}`,84,[[[],[41,[0,594],[0,596],[0,592]]]]],
[606,`${ssfblp}5.${sa}.${wf}`,106,[[[],[42,[0,605],[0,628]]]]],
[607,`${ssfblp}5.volume`,90,[[[],[43,[0,594],[0,592]]]]],
[608,`${ssfbd}.${sa}`,84,[[[],[45,[0,456],[0,473],[0,490],[0,507],[0,524]]]]],
[609,`${ssfbd}.${sa}.${wf}`,106,[[[],[21,[0,608],[0,663]]]]],
[610,`${ssfbd}.mineralDamping`,45,[[[],[46,[0,623]]]]],
[611,`${ssfbd}.moistureDamping`,45,[[[],[47,[0,617],[0,615]]]]],
[612,`${ssfbd}.${heat}`,74,[[[],[48,[0,457],[0,474],[0,491],[0,508],[0,525],[0,444],[0,461],[0,478],[0,495],[0,512]]]]],
[613,`${ssfbd}.${load}`,81,[[[],[45,[0,445],[0,462],[0,479],[0,496],[0,513]]]]],
[614,`${ssfbd}.${ef}.${load}`,81,[[[],[45,[0,451],[0,468],[0,485],[0,502],[0,519]]]]],
[615,`${ssfbd}.extinction.${mois}`,78,[[[],[34,[0,714],[0,719],[1,42],[1,43],[1,44]]]]],
[616,`${ssfbd}.extinction.${mois}Factor`,34,[[[],[49,[0,614],[0,634]]]]],
[617,`${ssfbd}.${mois}`,78,[[[],[48,[0,457],[0,474],[0,491],[0,508],[0,525],[0,446],[0,463],[0,480],[0,497],[0,514]]]]],
[618,`${ssfbd}.volume`,65,[[[],[45,[0,458],[0,475],[0,492],[0,509],[0,526]]]]],
[619,`${ssfbd}.${qig}`,75,[[[],[48,[0,457],[0,474],[0,491],[0,508],[0,525],[0,452],[0,469],[0,486],[0,503],[0,520]]]]],
[620,`${ssfbd}.${rxi}`,55,[[[],[22,[0,621],[0,611]]]]],
[621,`${ssfbd}.${rxi}Dry`,55,[[[],[50,[0,660],[0,625],[0,612],[0,610]]]]],
[622,`${ssfbd}.${savr}`,85,[[[],[48,[0,457],[0,474],[0,491],[0,508],[0,525],[0,447],[0,464],[0,481],[0,498],[0,515]]]]],
[623,`${ssfbd}.${emc}`,73,[[[],[48,[0,457],[0,474],[0,491],[0,508],[0,525],[0,448],[0,465],[0,482],[0,499],[0,516]]]]],
[624,`${ssfbd}.${sc}.${wf}`,106,[[[],[51,[0,456],[0,454],[0,473],[0,471],[0,490],[0,488],[0,507],[0,505],[0,524],[0,522]]]]],
[625,`${ssfbd}.net.${load}`,81,[[[],[48,[0,455],[0,472],[0,489],[0,506],[0,523],[0,453],[0,470],[0,487],[0,504],[0,521]]]]],
[626,`${ssfbd}.${ef}.waterLoad`,81,[[[],[45,[0,459],[0,476],[0,493],[0,510],[0,527]]]]],
[627,`${ssfbd}.${ef}.${mois}`,78,[[[],[21,[0,626],[0,614]]]]],
[628,`${ssfbl}.${sa}`,84,[[[],[45,[0,541],[0,557],[0,573],[0,589],[0,605]]]]],
[629,`${ssfbl}.${sa}.${wf}`,106,[[[],[21,[0,628],[0,663]]]]],
[630,`${ssfbl}.mineralDamping`,45,[[[],[46,[0,643]]]]],
[631,`${ssfbl}.moistureDamping`,45,[[[],[47,[0,637],[0,635]]]]],
[632,`${ssfbl}.${heat}`,74,[[[],[48,[0,542],[0,558],[0,574],[0,590],[0,606],[0,529],[0,545],[0,561],[0,577],[0,593]]]]],
[633,`${ssfbl}.${load}`,81,[[[],[45,[0,530],[0,546],[0,562],[0,578],[0,594]]]]],
[634,`${ssfbl}.${ef}.${load}`,81,[[[],[45,[0,536],[0,552],[0,568],[0,584],[0,600]]]]],
[635,`${ssfbl}.extinction.${mois}`,78,[[[],[52,[0,636],[0,627],[0,615]]]]],
[636,`${ssfbl}.extinction.${mois}Factor`,34,[[[],[49,[0,614],[0,634]]]]],
[637,`${ssfbl}.${mois}`,78,[[[],[48,[0,542],[0,558],[0,574],[0,590],[0,606],[0,531],[0,547],[0,563],[0,579],[0,595]]]]],
[638,`${ssfbl}.volume`,65,[[[],[45,[0,543],[0,559],[0,575],[0,591],[0,607]]]]],
[639,`${ssfbl}.${qig}`,75,[[[],[48,[0,542],[0,558],[0,574],[0,590],[0,606],[0,537],[0,553],[0,569],[0,585],[0,601]]]]],
[640,`${ssfbl}.${rxi}`,55,[[[],[22,[0,641],[0,631]]]]],
[641,`${ssfbl}.${rxi}Dry`,55,[[[],[50,[0,660],[0,645],[0,632],[0,630]]]]],
[642,`${ssfbl}.${savr}`,85,[[[],[48,[0,542],[0,558],[0,574],[0,590],[0,606],[0,532],[0,548],[0,564],[0,580],[0,596]]]]],
[643,`${ssfbl}.${emc}`,73,[[[],[48,[0,542],[0,558],[0,574],[0,590],[0,606],[0,533],[0,549],[0,565],[0,581],[0,597]]]]],
[644,`${ssfbl}.${sc}.${wf}`,106,[[[],[51,[0,541],[0,539],[0,557],[0,555],[0,573],[0,571],[0,589],[0,587],[0,605],[0,603]]]]],
[645,`${ssfbl}.net.${load}`,81,[[[],[48,[0,540],[0,556],[0,572],[0,588],[0,604],[0,538],[0,554],[0,570],[0,586],[0,602]]]]],
[646,`${ssfb}.depth`,65,[[[],[34,[0,714],[0,718],[0,735],[0,759],[0,770]]]]],
[647,`${ssfb}.bulkDensity`,64,[[[],[21,[0,651],[0,646]]]]],
[648,`${ssfb}.${qig}`,66,[[[],[48,[0,609],[0,629],[0,619],[0,639]]]]],
[649,`${ssfb}.heatSink`,76,[[[],[53,[0,648],[0,647]]]]],
[650,`${ssfb}.noWindNoSlope.${ros}`,61,[[[],[54,[0,657],[0,656],[0,649]]]]],
[651,`${ssfb}.${load}`,81,[[[],[45,[0,613],[0,633]]]]],
[652,`${ssfb}.open.${waf}`,108,[[[],[55,[0,646]]]]],
[653,`${ssfb}.packingRatio`,67,[[[],[56,[0,618],[0,638],[0,646]]]]],
[654,`${ssfb}.packingRatio.optimum`,67,[[[],[57,[0,661]]]]],
[655,`${ssfb}.packingRatio.ratio`,67,[[[],[21,[0,653],[0,654]]]]],
[656,`${ssfb}.propagatingFluxRatio`,54,[[[],[58,[0,661],[0,653]]]]],
[657,`${ssfb}.${rxi}`,55,[[[],[45,[0,620],[0,640]]]]],
[658,`${ssfb}.reactionVelocityExponent`,34,[[[],[59,[0,661]]]]],
[659,`${ssfb}.reactionVelocityMaximum`,56,[[[],[60,[0,662]]]]],
[660,`${ssfb}.reactionVelocityOptimum`,56,[[[],[61,[0,655],[0,659],[0,658]]]]],
[661,`${ssfb}.${savr}`,85,[[[],[48,[0,609],[0,629],[0,622],[0,642]]]]],
[662,`${ssfb}.savr15`,34,[[[],[62,[0,661]]]]],
[663,`${ssfb}.${sa}`,84,[[[],[45,[0,608],[0,628]]]]],
[664,`${ssff}.maximumDirection.slope.${ros}`,61,[[[],[63,[0,713],[0,677]]]]],
[665,`${ssff}.maximumDirection.wind.${ros}`,61,[[[],[64,[0,713],[0,700]]]]],
[666,`${ssff}.wind.heading.fromUpslope`,37,[[[],[25,[0,101]]]]],
[667,`${ssff}.maximumDirection.xComponent`,34,[[[],[65,[0,665],[0,664],[0,666]]]]],
[668,`${ssff}.maximumDirection.yComponent`,34,[[[],[66,[0,665],[0,666]]]]],
[669,`${ssff}.maximumDirection.${ros}`,61,[[[],[67,[0,667],[0,668]]]]],
[670,`${ssff}.limit.${ews}.exceeded`,31,[[[],[68,[0,681],[0,672]]]]],
[671,`${ssff}.limit.${ros}.exceeded`,32,[[[],[68,[0,683],[0,689]]]]],
[672,`${ssff}.limit.${ews}`,107,[[[],[69,[0,710]]]]],
[673,`${ssff}.limit.windSlopeSpreadRateCoefficient`,34,[[[],[70,[0,672],[0,695],[0,698]]]]],
[674,`${ssff}.limit.${ros}`,61,[[[],[71,[0,713],[0,673]]]]],
[675,`${ssff}.slope.ratio`,100,[[[],[25,[0,98]]]]],
[676,`${ssff}.slope.k`,34,[[[],[72,[0,653]]]]],
[677,`${ssff}.slope.phi`,34,[[[],[73,[0,675],[0,676]]]]],
[678,`${ssff}.spread.step1.${ews}`,107,[[[],[74,[0,679],[0,695],[0,699]]]]],
[679,`${ssff}.spread.step1.${phiew}`,34,[[[],[75,[0,700],[0,677]]]]],
[680,`${ssff}.spread.step1.${ros}`,61,[[[],[71,[0,713],[0,679]]]]],
[681,`${ssff}.spread.step2.${ews}`,107,[[[],[74,[0,682],[0,695],[0,699]]]]],
[682,`${ssff}.spread.step2.${phiew}`,34,[[[],[76,[0,713],[0,683]]]]],
[683,`${ssff}.spread.step2.${ros}`,61,[[[],[77,[0,713],[0,669]]]]],
[684,`${ssff}.spread.step3a.${ews}`,107,[[[],[78,[0,681],[0,672]]]]],
[685,`${ssff}.spread.step3a.${phiew}`,34,[[[],[78,[0,682],[0,673]]]]],
[686,`${ssff}.spread.step3a.${ros}`,61,[[[],[78,[0,683],[0,674]]]]],
[687,`${ssff}.spread.step3b.${ews}`,107,[[[],[74,[0,688],[0,695],[0,699]]]]],
[688,`${ssff}.spread.step3b.${phiew}`,34,[[[],[76,[0,713],[0,689]]]]],
[689,`${ssff}.spread.step3b.${ros}`,61,[[[],[79,[0,683],[0,681]]]]],
[690,`${ssff}.spread.step4.${ews}`,107,[[[],[74,[0,691],[0,695],[0,699]]]]],
[691,`${ssff}.spread.step4.${phiew}`,34,[[[],[76,[0,713],[0,692]]]]],
[692,`${ssff}.spread.step4.${ros}`,61,[[[],[79,[0,686],[0,684]]]]],
[693,`${ssff}.${waf}`,108,[[[20,45],[25,[0,108]]],[[],[80,[0,50],[0,53],[0,652]]]]],
[694,`${ssff}.wind.speed.atMidflame`,107,[[[25,16],[25,[0,107]]],[[],[33,[0,106],[0,693]]]]],
[695,`${ssff}.wind.factor.b`,34,[[[],[81,[0,661]]]]],
[696,`${ssff}.wind.factor.c`,34,[[[],[82,[0,661]]]]],
[697,`${ssff}.wind.factor.e`,34,[[[],[83,[0,661]]]]],
[698,`${ssff}.wind.factor.k`,34,[[[],[84,[0,655],[0,697],[0,696]]]]],
[699,`${ssff}.wind.factor.i`,34,[[[],[85,[0,655],[0,697],[0,696]]]]],
[700,`${ssff}.wind.phi`,34,[[[],[86,[0,694],[0,695],[0,698]]]]],
[701,`${ssff}.${ews}`,107,[[[28,46],[25,[0,690]]],[[],[25,[0,687]]]]],
[702,`${ssff}.${fli}`,47,[[[],[87,[0,712],[0,710],[0,704]]]]],
[703,`${ssff}.${fl}`,49,[[[],[17,[0,702]]]]],
[704,`${ssff}.${taur}`,57,[[[],[88,[0,661]]]]],
[705,`${ssff}.heading.fromUpslope`,37,[[[],[89,[0,667],[0,668],[0,669]]]]],
[706,`${ssff}.heading.fromNorth`,37,[[[],[19,[0,96],[0,705]]]]],
[707,`${ssff}.${hpua}`,50,[[[],[90,[0,710],[0,704]]]]],
[708,`${ssff}.${lwr}`,51,[[[],[20,[0,701]]]]],
[709,`${ssff}.${phiew}`,34,[[[28,46],[25,[0,691]]],[[],[25,[0,688]]]]],
[710,`${ssff}.${rxi}`,55,[[[],[25,[0,657]]]]],
[711,`${ssff}.${sh}`,58,[[[],[91,[0,702],[0,694],[0,99]]]]],
[712,`${ssff}.${ros}`,61,[[[28,46],[25,[0,692]]],[[],[25,[0,689]]]]],
[713,`${ssff}.noWindNoSlope.${ros}`,61,[[[],[25,[0,650]]]]],
[714,`${ssf}.model.domain`,21,[[[18,47],[92,[0,715]]],[[18,48],[9,[1,48]]],[[18,49],[9,[1,49]]],[[18,50],[9,[1,50]]],[[18,51],[9,[1,51]]],[[],[9,[1,52]]]]],
[715,`${ssf}.model.catalogKey`,22,[[[],[2]]]],
[716,`${ssf}.model.behave.domain`,21,[[[],[9,[1,48]]]]],
[717,`${ssf}.${mbp}.cured.herb.fraction`,71,[[[21,53],[93,[0,92]]],[[],[2]]]],
[718,`${ssf}.${mbp}.depth`,65,[[[18,47],[94,[0,715]]],[[18,48],[2]],[[],[9,[1,23]]]]],
[719,`${ssf}.${mbp}.dead.extinction.${mois}`,78,[[[18,47],[95,[0,715]]],[[18,48],[2]],[[],[9,[1,44]]]]],
[720,`${ssf}.${mbp}.total.herb.${load}`,81,[[[18,47],[96,[0,715]]],[[18,48],[2]],[[],[9,[1,13]]]]],
[721,`${ssf}.${mbp}.dead.tl1h.${load}`,81,[[[18,47],[97,[0,715]]],[[18,48],[2]],[[],[9,[1,13]]]]],
[722,`${ssf}.${mbp}.dead.tl10h.${load}`,81,[[[18,47],[98,[0,715]]],[[18,48],[2]],[[],[9,[1,13]]]]],
[723,`${ssf}.${mbp}.dead.tl100h.${load}`,81,[[[18,47],[99,[0,715]]],[[18,48],[2]],[[],[9,[1,13]]]]],
[724,`${ssf}.${mbp}.live.stem.${load}`,81,[[[18,47],[100,[0,715]]],[[18,48],[2]],[[],[9,[1,13]]]]],
[725,`${ssf}.${mbp}.dead.tl1h.${savr}`,85,[[[18,47],[101,[0,715]]],[[18,48],[2]],[[],[9,[1,13]]]]],
[726,`${ssf}.${mbp}.live.herb.${savr}`,85,[[[18,47],[102,[0,715]]],[[18,48],[2]],[[],[9,[1,8]]]]],
[727,`${ssf}.${mbp}.live.stem.${savr}`,85,[[[18,47],[103,[0,715]]],[[18,48],[2]],[[],[9,[1,8]]]]],
[728,`${ssf}.${mbp}.dead.${heat}`,74,[[[18,47],[104,[0,715]]],[[18,48],[2]],[[],[9,[1,0]]]]],
[729,`${ssf}.${mbp}.live.${heat}`,74,[[[18,47],[105,[0,715]]],[[18,48],[2]],[[],[9,[1,0]]]]],
[730,`${ssf}.${mbd}.dead.herb.${load}`,81,[[[],[106,[0,720],[0,717]]]]],
[731,`${ssf}.${mbd}.live.herb.${load}`,81,[[[],[107,[0,720],[0,717]]]]],
[732,`${ssf}.model.chaparral.domain`,21,[[[],[9,[1,49]]]]],
[733,`${ssf}.${mcp}.chaparralType`,19,[[[18,47],[108,[0,715]]],[[18,49],[2]],[[],[9,[1,54]]]]],
[734,`${ssf}.${mcp}.observed.deadFuelFraction`,71,[[[18,47],[109,[0,715]]],[[18,49],[2]],[[],[9,[1,13]]]]],
[735,`${ssf}.${mcp}.observed.depth`,65,[[[18,47],[110,[0,715]]],[[18,49],[2]],[[],[9,[1,23]]]]],
[736,`${ssf}.${mcp}.observed.totalLoad`,81,[[[18,47],[111,[0,715]]],[[18,49],[2]],[[],[9,[1,13]]]]],
[737,`${ssf}.${mcp}.applied.totalLoad`,81,[[[22,53],[25,[0,742]]],[[],[25,[0,736]]]]],
[738,`${ssf}.${mcd}.age`,62,[[[],[112,[0,735],[0,733]]]]],
[739,`${ssf}.${mcd}.averageMortality`,98,[[[],[113,[0,738]]]]],
[740,`${ssf}.${mcd}.severeMortality`,98,[[[],[114,[0,738]]]]],
[741,`${ssf}.${mcd}.depth`,65,[[[],[115,[0,738],[0,733]]]]],
[742,`${ssf}.${mcd}.totalLoad`,81,[[[],[116,[0,738],[0,733]]]]],
[743,`${ssf}.${mcd}.deadLoad`,81,[[[],[117,[0,737],[0,734]]]]],
[744,`${ssf}.${mcd}.deadFineLoad`,81,[[[],[118,[0,737],[0,734]]]]],
[745,`${ssf}.${mcd}.deadSmallLoad`,81,[[[],[119,[0,737],[0,734]]]]],
[746,`${ssf}.${mcd}.deadMediumLoad`,81,[[[],[120,[0,737],[0,734]]]]],
[747,`${ssf}.${mcd}.deadLargeLoad`,81,[[[],[121,[0,737],[0,734]]]]],
[748,`${ssf}.${mcd}.liveLoad`,81,[[[],[122,[0,737],[0,734]]]]],
[749,`${ssf}.${mcd}.liveFineLoad`,81,[[[],[123,[0,737],[0,734]]]]],
[750,`${ssf}.${mcd}.liveSmallLoad`,81,[[[],[124,[0,737],[0,734]]]]],
[751,`${ssf}.${mcd}.liveMediumLoad`,81,[[[],[125,[0,737],[0,734]]]]],
[752,`${ssf}.${mcd}.liveLargeLoad`,81,[[[],[126,[0,737],[0,734]]]]],
[753,`${ssf}.${mcd}.liveLeafLoad`,81,[[[],[127,[0,737],[0,734]]]]],
[754,`${ssf}.model.palmettoGallberry.domain`,21,[[[],[9,[1,50]]]]],
[755,`${ssf}.${mpp}.age`,62,[[[18,47],[128,[0,715]]],[[18,50],[2]],[[],[9,[1,13]]]]],
[756,`${ssf}.${mpp}.basalArea`,63,[[[18,47],[129,[0,715]]],[[18,50],[2]],[[],[9,[1,13]]]]],
[757,`${ssf}.${mpp}.cover`,68,[[[18,47],[130,[0,715]]],[[18,50],[2]],[[],[9,[1,13]]]]],
[758,`${ssf}.${mpp}.height`,65,[[[18,47],[131,[0,715]]],[[18,50],[2]],[[],[9,[1,23]]]]],
[759,`${ssf}.${mpd}.depth`,65,[[[],[132,[0,758]]]]],
[760,`${ssf}.${mpd}.deadFineLoad`,81,[[[],[133,[0,755],[0,758]]]]],
[761,`${ssf}.${mpd}.deadSmallLoad`,81,[[[],[134,[0,755],[0,757]]]]],
[762,`${ssf}.${mpd}.deadFoliageLoad`,81,[[[],[135,[0,755],[0,757]]]]],
[763,`${ssf}.${mpd}.deadLitterLoad`,81,[[[],[136,[0,755],[0,756]]]]],
[764,`${ssf}.${mpd}.liveFineLoad`,81,[[[],[137,[0,755],[0,758]]]]],
[765,`${ssf}.${mpd}.liveSmallLoad`,81,[[[],[138,[0,755],[0,758]]]]],
[766,`${ssf}.${mpd}.liveFoliageLoad`,81,[[[],[139,[0,755],[0,757],[0,758]]]]],
[767,`${ssf}.model.westernAspen.domain`,21,[[[],[9,[1,51]]]]],
[768,`${ssf}.${mwp}.aspenType`,28,[[[18,47],[140,[0,715]]],[[18,51],[2]],[[],[9,[1,55]]]]],
[769,`${ssf}.${mwp}.curingLevel`,71,[[[18,47],[141,[0,715]]],[[18,51],[2]],[[],[9,[1,13]]]]],
[770,`${ssf}.${mwd}.depth`,65,[[[],[142,[0,768]]]]],
[771,`${ssf}.${mwd}.dead.fine.${load}`,81,[[[],[143,[0,768],[0,769]]]]],
[772,`${ssf}.${mwd}.dead.small.${load}`,81,[[[],[144,[0,768]]]]],
[773,`${ssf}.${mwd}.dead.fine.${savr}`,81,[[[],[145,[0,768],[0,769]]]]],
[774,`${ssf}.${mwd}.live.herb.${load}`,81,[[[],[146,[0,768],[0,769]]]]],
[775,`${ssf}.${mwd}.live.stem.${load}`,81,[[[],[147,[0,768],[0,769]]]]],
[776,`${ssf}.${mwd}.live.stem.${savr}`,81,[[[],[148,[0,768],[0,769]]]]],
[777,`${swf}.primaryCover`,68,[[[18,52],[9,[1,8]]],[[],[2]]]],
[778,`${swf}.${ews}`,107,[[[],[25,[0,367]]]]],
[779,`${swf}.heading.fromUpslope`,37,[[[],[25,[0,371]]]]],
[780,`${swf}.heading.fromNorth`,37,[[[],[25,[0,372]]]]],
[781,`${swf}.${lwr}`,51,[[[],[25,[0,374]]]]],
[782,`${swf}.wind.speed.atMidflame`,107,[[[],[25,[0,360]]]]],
[783,`${swf}.${waf}`,108,[[[],[25,[0,359]]]]],
[784,`${swf}.${fli}`,47,[[[18,52],[25,[0,368]]],[[],[149,[0,368],[0,702]]]]],
[785,`${swf}.${fl}`,49,[[[18,52],[25,[0,369]]],[[],[149,[0,369],[0,703]]]]],
[786,`${swf}.${hpua}`,50,[[[18,52],[25,[0,373]]],[[],[149,[0,373],[0,707]]]]],
[787,`${swf}.${rxi}`,55,[[[18,52],[25,[0,376]]],[[],[149,[0,376],[0,710]]]]],
[788,`${swf}.${sh}`,58,[[[18,52],[25,[0,377]]],[[],[149,[0,377],[0,711]]]]],
[789,`${swf}.limit.${ews}.exceeded`,31,[[[18,52],[25,[0,336]]],[[],[150,[0,336],[0,670]]]]],
[790,`${swf}.limit.${ews}`,107,[[[18,52],[25,[0,338]]],[[],[78,[0,338],[0,672]]]]],
[791,`${swf}.${ros}`,61,[[[29,56],[25,[0,793]]],[[29,57],[25,[0,794]]],[[],[25,[0,792]]]]],
[792,`${swf}.arithmeticMean.${ros}`,61,[[[18,52],[25,[0,378]]],[[],[151,[0,777],[0,378],[0,712]]]]],
[793,`${swf}.expectedValue.${ros}`,61,[[[18,52],[25,[0,378]]],[[],[152,[0,777],[0,378],[0,712]]]]],
[794,`${swf}.harmonicMean.${ros}`,61,[[[18,52],[25,[0,378]]],[[],[153,[0,777],[0,378],[0,712]]]]],
[795,`${sfe}.axis.eccentricity`,51,[[[],[154,[0,797]]]]],
[796,`${sfe}.axis.${ews}`,107,[[[13,58],[25,[0,778]]],[[],[25,[0,65]]]]],
[797,`${sfe}.axis.${lwr}`,51,[[[13,58],[25,[0,781]]],[[],[25,[0,71]]]]],
[798,`${sfe}.axis.major.${ros}`,61,[[[],[155,[0,832],[0,818]]]]],
[799,`${sfe}.axis.minor.${ros}`,61,[[[],[156,[0,798],[0,797]]]]],
[800,`${sfe}.axis.f.${ros}`,61,[[[],[157,[0,798]]]]],
[801,`${sfe}.axis.g.${ros}`,61,[[[],[158,[0,798],[0,818]]]]],
[802,`${sfe}.axis.h.${ros}`,61,[[[],[159,[0,799]]]]],
[803,`${sfe}.vector.fromHead`,37,[[[30,59],[25,[0,76]]],[[30,60],[18,[0,805],[0,859]]],[[30,61],[18,[0,804],[0,860]]],[[],[18,[0,804],[0,860]]]]],
[804,`${sfe}.vector.fromNorth`,37,[[[30,61],[25,[0,77]]],[[30,59],[19,[0,803],[0,860]]],[[30,60],[19,[0,805],[0,96]]],[[],[19,[0,805],[0,96]]]]],
[805,`${sfe}.vector.fromUpslope`,37,[[[30,60],[25,[0,78]]],[[30,59],[19,[0,803],[0,859]]],[[30,61],[18,[0,804],[0,96]]],[[],[18,[0,804],[0,96]]]]],
[806,`${sfe}.size.area`,44,[[[],[160,[0,807],[0,797]]]]],
[807,`${sfe}.size.length`,60,[[[],[161,[0,798],[0,75]]]]],
[808,`${sfe}.size.perimeter`,60,[[[],[162,[0,807],[0,809]]]]],
[809,`${sfe}.size.width`,60,[[[],[161,[0,799],[0,75]]]]],
[810,`${sfe}.map.area`,93,[[[],[163,[0,806],[0,79]]]]],
[811,`${sfe}.map.length`,95,[[[],[21,[0,807],[0,79]]]]],
[812,`${sfe}.map.perimeter`,95,[[[],[21,[0,808],[0,79]]]]],
[813,`${sfe}.map.width`,95,[[[],[21,[0,809],[0,79]]]]],
[814,`${sfe}.back.spreadDistance`,60,[[[],[161,[0,818],[0,75]]]]],
[815,`${sfe}.back.${fli}`,47,[[[],[164,[0,829],[0,832],[0,818]]]]],
[816,`${sfe}.back.${fl}`,49,[[[],[17,[0,815]]]]],
[817,`${sfe}.back.mapDistance`,95,[[[],[21,[0,814],[0,79]]]]],
[818,`${sfe}.back.${ros}`,61,[[[],[165,[0,832],[0,795]]]]],
[819,`${sfe}.back.${sh}`,58,[[[],[91,[0,815],[0,861],[0,99]]]]],
[820,`${sfe}.back.treeMortality`,98,[[[],[166,[0,59],[0,58],[0,45],[0,41],[0,819]]]]],
[821,`${sfe}.flank.spreadDistance`,60,[[[],[161,[0,825],[0,75]]]]],
[822,`${sfe}.flank.${fli}`,47,[[[],[164,[0,829],[0,832],[0,825]]]]],
[823,`${sfe}.flank.${fl}`,49,[[[],[17,[0,822]]]]],
[824,`${sfe}.flank.mapDistance`,95,[[[],[21,[0,821],[0,79]]]]],
[825,`${sfe}.flank.${ros}`,61,[[[],[167,[0,799]]]]],
[826,`${sfe}.flank.${sh}`,58,[[[],[91,[0,822],[0,861],[0,99]]]]],
[827,`${sfe}.flank.treeMortality`,98,[[[],[166,[0,59],[0,58],[0,45],[0,41],[0,826]]]]],
[828,`${sfe}.head.spreadDistance`,60,[[[],[161,[0,832],[0,75]]]]],
[829,`${sfe}.head.${fli}`,47,[[[13,58],[25,[0,784]]],[[],[25,[0,66]]]]],
[830,`${sfe}.head.${fl}`,49,[[[13,58],[25,[0,785]]],[[],[25,[0,67]]]]],
[831,`${sfe}.head.mapDistance`,95,[[[],[21,[0,828],[0,79]]]]],
[832,`${sfe}.head.${ros}`,61,[[[13,58],[25,[0,791]]],[[],[25,[0,72]]]]],
[833,`${sfe}.head.${sh}`,58,[[[],[91,[0,829],[0,861],[0,99]]]]],
[834,`${sfe}.head.treeMortality`,98,[[[],[166,[0,59],[0,58],[0,45],[0,41],[0,833]]]]],
[835,`${sfe}.psi.spreadDistance`,60,[[[],[161,[0,839],[0,75]]]]],
[836,`${sfe}.psi.${fli}`,47,[[[],[164,[0,829],[0,832],[0,839]]]]],
[837,`${sfe}.psi.${fl}`,49,[[[],[17,[0,836]]]]],
[838,`${sfe}.psi.mapDistance`,95,[[[],[21,[0,835],[0,79]]]]],
[839,`${sfe}.psi.${ros}`,61,[[[],[168,[0,803],[0,800],[0,801],[0,802]]]]],
[840,`${sfe}.psi.${sh}`,58,[[[],[91,[0,836],[0,861],[0,99]]]]],
[841,`${sfe}.psi.treeMortality`,98,[[[],[166,[0,59],[0,58],[0,45],[0,41],[0,840]]]]],
[842,`${sfe}.beta5.spreadDistance`,60,[[[],[161,[0,846],[0,75]]]]],
[843,`${sfe}.beta5.${fli}`,47,[[[],[164,[0,829],[0,832],[0,853]]]]],
[844,`${sfe}.beta5.${fl}`,49,[[[],[17,[0,843]]]]],
[845,`${sfe}.beta5.mapDistance`,95,[[[],[21,[0,842],[0,79]]]]],
[846,`${sfe}.beta5.${ros}`,61,[[[],[25,[0,853]]]]],
[847,`${sfe}.beta5.${sh}`,58,[[[],[91,[0,843],[0,861],[0,99]]]]],
[848,`${sfe}.beta5.treeMortality`,98,[[[],[166,[0,59],[0,58],[0,45],[0,41],[0,847]]]]],
[849,`${sfe}.beta.spreadDistance`,60,[[[],[161,[0,853],[0,75]]]]],
[850,`${sfe}.beta.${fli}`,47,[[[],[164,[0,829],[0,832],[0,858]]]]],
[851,`${sfe}.beta.${fl}`,49,[[[],[17,[0,850]]]]],
[852,`${sfe}.beta.mapDistance`,95,[[[],[21,[0,849],[0,79]]]]],
[853,`${sfe}.beta.${ros}`,61,[[[],[169,[0,803],[0,832],[0,795]]]]],
[854,`${sfe}.beta.${sh}`,58,[[[],[91,[0,850],[0,861],[0,99]]]]],
[855,`${sfe}.beta.treeMortality`,98,[[[],[166,[0,59],[0,58],[0,45],[0,41],[0,854]]]]],
[856,`${sfe}.beta.theta`,37,[[[],[170,[0,803],[0,800],[0,801],[0,802]]]]],
[857,`${sfe}.beta.psi`,37,[[[],[171,[0,856],[0,800],[0,802]]]]],
[858,`${sfe}.beta.psiSpreadRate`,61,[[[],[168,[0,857],[0,800],[0,801],[0,802]]]]],
[859,`${sfe}.heading.fromUpslope`,37,[[[13,58],[25,[0,779]]],[[],[25,[0,68]]]]],
[860,`${sfe}.heading.fromNorth`,37,[[[],[19,[0,96],[0,859]]]]],
[861,`${sfe}.wind.speed.atMidflame`,107,[[[13,58],[25,[0,782]]],[[],[25,[0,107]]]]],
[862,`site.terrain.spotSourceLocation`,25,[[[],[2]]]],
[863,`site.terrain.ridgeValleyDistance`,59,[[[],[2]]]],
[864,`site.terrain.ridgeValleyElevation`,60,[[[],[2]]]],
[865,`${spotb}.firebrand.criticalCoverHeight`,105,[[[],[172,[0,866],[0,56]]]]],
[866,`${spotb}.firebrand.height`,105,[[[],[173,[0,871]]]]],
[867,`${spotb}.firebrand.drift`,59,[[[],[9,[1,13]]]]],
[868,`${spotb}.spotDistance.flatTerrain`,59,[[[],[174,[0,866],[0,865],[0,106]]]]],
[869,`${spotb}.spotDistance.flatTerrainWithDrift`,59,[[[],[175,[0,868],[0,867]]]]],
[870,`${spotb}.spotDistance.mountainTerrain`,59,[[[],[176,[0,869],[0,862],[0,863],[0,864]]]]],
[871,`${spotb}.flameHeight`,49,[[[],[2]]]],
[872,`${spotc}.firebrand.criticalCoverHeight`,105,[[[],[9,[1,13]]]]],
[873,`${spotc}.firebrand.height`,105,[[[],[177,[0,879]]]]],
[874,`${spotc}.firebrand.drift`,59,[[[],[178,[0,879]]]]],
[875,`${spotc}.spotDistance.flatTerrain`,59,[[[],[179,[0,879]]]]],
[876,`${spotc}.spotDistance.flatTerrainWithDrift`,59,[[[],[180,[0,879]]]]],
[877,`${spotc}.spotDistance.mountainTerrain`,59,[[[],[176,[0,876],[0,862],[0,863],[0,864]]]]],
[878,`${spotc}.${fli}`,47,[[[11,62],[25,[0,1185]]],[[],[181,[0,74]]]]],
[879,`${spotc}.firebrandObject`,101,[[[],[182,[0,45],[0,106],[0,878]]]]],
[880,`${spots}.firebrand.criticalCoverHeight`,105,[[[],[172,[0,882],[0,56]]]]],
[881,`${spots}.${fli}`,47,[[[15,58],[25,[0,784]]],[[],[25,[0,66]]]]],
[882,`${spots}.firebrand.height`,105,[[[],[183,[0,881],[0,106]]]]],
[883,`${spots}.firebrand.drift`,59,[[[],[184,[0,882],[0,106]]]]],
[884,`${spots}.spotDistance.flatTerrain`,59,[[[],[174,[0,882],[0,880],[0,106]]]]],
[885,`${spots}.spotDistance.flatTerrainWithDrift`,59,[[[],[175,[0,884],[0,883]]]]],
[886,`${spots}.spotDistance.mountainTerrain`,59,[[[],[176,[0,885],[0,862],[0,863],[0,864]]]]],
[887,`${spott}.firebrand.criticalCoverHeight`,105,[[[],[172,[0,888],[0,56]]]]],
[888,`${spott}.firebrand.height`,105,[[[],[185,[0,894],[0,897],[0,898]]]]],
[889,`${spott}.firebrand.drift`,59,[[[],[9,[1,13]]]]],
[890,`${spott}.spotDistance.flatTerrain`,59,[[[],[174,[0,888],[0,887],[0,106]]]]],
[891,`${spott}.spotDistance.flatTerrainWithDrift`,59,[[[],[175,[0,890],[0,889]]]]],
[892,`${spott}.spotDistance.mountainTerrain`,59,[[[],[176,[0,891],[0,862],[0,863],[0,864]]]]],
[893,`${spott}.species`,26,[[[],[2]]]],
[894,`${spott}.height`,105,[[[],[2]]]],
[895,`${spott}.dbh`,104,[[[],[2]]]],
[896,`${spott}.count`,103,[[[],[2]]]],
[897,`${spott}.flameHeight`,49,[[[],[186,[0,893],[0,895],[0,896]]]]],
[898,`${spott}.flameDuration`,48,[[[],[187,[0,893],[0,895],[0,896]]]]],
[899,`scorch.height`,58,[[[14,63],[91,[0,66],[0,107],[0,99]]],[[],[25,[0,788]]]]],
[900,`mortality.${sh}`,58,[[[16,63],[25,[0,73]]],[[],[25,[0,899]]]]],
[901,`mortality.rate`,98,[[[],[166,[0,59],[0,58],[0,45],[0,41],[0,900]]]]],
[902,`mortality.crownLengthScorched`,98,[[[],[188,[0,45],[0,41],[0,900]]]]],
[903,`mortality.crownVolumeScorched`,98,[[[],[189,[0,45],[0,41],[0,900]]]]],
[904,`${ccfbdp}1.${dens}`,82,[[[],[9,[1,17]]]]],
[905,`${ccfbdp}1.${heat}`,74,[[[],[9,[1,0]]]]],
[906,`${ccfbdp}1.${load}`,81,[[[],[9,[1,64]]]]],
[907,`${ccfbdp}1.${mois}`,78,[[[],[25,[0,88]]]]],
[908,`${ccfbdp}1.${savr}`,85,[[[],[9,[1,34]]]]],
[909,`${ccfbdp}1.${emc}`,73,[[[],[9,[1,23]]]]],
[910,`${ccfbdp}1.${tmc}`,89,[[[],[9,[1,25]]]]],
[911,`${ccfbdp}2.${dens}`,82,[[[],[9,[1,17]]]]],
[912,`${ccfbdp}2.${heat}`,74,[[[],[9,[1,0]]]]],
[913,`${ccfbdp}2.${load}`,81,[[[],[9,[1,65]]]]],
[914,`${ccfbdp}2.${mois}`,78,[[[],[25,[0,89]]]]],
[915,`${ccfbdp}2.${savr}`,85,[[[],[9,[1,29]]]]],
[916,`${ccfbdp}2.${emc}`,73,[[[],[9,[1,23]]]]],
[917,`${ccfbdp}2.${tmc}`,89,[[[],[9,[1,25]]]]],
[918,`${ccfbdp}3.${dens}`,82,[[[],[9,[1,17]]]]],
[919,`${ccfbdp}3.${heat}`,74,[[[],[9,[1,0]]]]],
[920,`${ccfbdp}3.${load}`,81,[[[],[9,[1,66]]]]],
[921,`${ccfbdp}3.${mois}`,78,[[[],[25,[0,90]]]]],
[922,`${ccfbdp}3.${savr}`,85,[[[],[9,[1,19]]]]],
[923,`${ccfbdp}3.${emc}`,73,[[[],[9,[1,23]]]]],
[924,`${ccfbdp}3.${tmc}`,89,[[[],[9,[1,25]]]]],
[925,`${ccfbdp}4.${dens}`,82,[[[],[9,[1,17]]]]],
[926,`${ccfbdp}4.${heat}`,74,[[[],[9,[1,0]]]]],
[927,`${ccfbdp}4.${load}`,81,[[[],[9,[1,13]]]]],
[928,`${ccfbdp}4.${mois}`,78,[[[],[25,[0,88]]]]],
[929,`${ccfbdp}4.${savr}`,85,[[[],[9,[1,67]]]]],
[930,`${ccfbdp}4.${emc}`,73,[[[],[9,[1,23]]]]],
[931,`${ccfbdp}4.${tmc}`,89,[[[],[9,[1,25]]]]],
[932,`${ccfbdp}5.${dens}`,82,[[[],[9,[1,17]]]]],
[933,`${ccfbdp}5.${heat}`,74,[[[],[9,[1,0]]]]],
[934,`${ccfbdp}5.${load}`,81,[[[],[9,[1,13]]]]],
[935,`${ccfbdp}5.${mois}`,78,[[[],[9,[1,32]]]]],
[936,`${ccfbdp}5.${savr}`,85,[[[],[9,[1,8]]]]],
[937,`${ccfbdp}5.${emc}`,73,[[[],[9,[1,23]]]]],
[938,`${ccfbdp}5.${tmc}`,89,[[[],[9,[1,25]]]]],
[939,`${ccfblp}1.${dens}`,82,[[[],[9,[1,17]]]]],
[940,`${ccfblp}1.${heat}`,74,[[[],[9,[1,0]]]]],
[941,`${ccfblp}1.${load}`,81,[[[],[9,[1,13]]]]],
[942,`${ccfblp}1.${mois}`,78,[[[],[25,[0,92]]]]],
[943,`${ccfblp}1.${savr}`,85,[[[],[9,[1,67]]]]],
[944,`${ccfblp}1.${emc}`,73,[[[],[9,[1,23]]]]],
[945,`${ccfblp}1.${tmc}`,89,[[[],[9,[1,25]]]]],
[946,`${ccfblp}2.${dens}`,82,[[[],[9,[1,17]]]]],
[947,`${ccfblp}2.${heat}`,74,[[[],[9,[1,0]]]]],
[948,`${ccfblp}2.${load}`,81,[[[],[9,[1,65]]]]],
[949,`${ccfblp}2.${mois}`,78,[[[],[25,[0,93]]]]],
[950,`${ccfblp}2.${savr}`,85,[[[],[9,[1,67]]]]],
[951,`${ccfblp}2.${emc}`,73,[[[],[9,[1,23]]]]],
[952,`${ccfblp}2.${tmc}`,89,[[[],[9,[1,25]]]]],
[953,`${ccfblp}3.${dens}`,82,[[[],[9,[1,17]]]]],
[954,`${ccfblp}3.${heat}`,74,[[[],[9,[1,0]]]]],
[955,`${ccfblp}3.${load}`,81,[[[],[9,[1,13]]]]],
[956,`${ccfblp}3.${mois}`,78,[[[],[9,[1,32]]]]],
[957,`${ccfblp}3.${savr}`,85,[[[],[9,[1,8]]]]],
[958,`${ccfblp}3.${emc}`,73,[[[],[9,[1,23]]]]],
[959,`${ccfblp}3.${tmc}`,89,[[[],[9,[1,25]]]]],
[960,`${ccfblp}4.${dens}`,82,[[[],[9,[1,17]]]]],
[961,`${ccfblp}4.${heat}`,74,[[[],[9,[1,0]]]]],
[962,`${ccfblp}4.${load}`,81,[[[],[9,[1,13]]]]],
[963,`${ccfblp}4.${mois}`,78,[[[],[9,[1,32]]]]],
[964,`${ccfblp}4.${savr}`,85,[[[],[9,[1,8]]]]],
[965,`${ccfblp}4.${emc}`,73,[[[],[9,[1,23]]]]],
[966,`${ccfblp}4.${tmc}`,89,[[[],[9,[1,25]]]]],
[967,`${ccfblp}5.${dens}`,82,[[[],[9,[1,17]]]]],
[968,`${ccfblp}5.${heat}`,74,[[[],[9,[1,0]]]]],
[969,`${ccfblp}5.${load}`,81,[[[],[9,[1,13]]]]],
[970,`${ccfblp}5.${mois}`,78,[[[],[9,[1,32]]]]],
[971,`${ccfblp}5.${savr}`,85,[[[],[9,[1,8]]]]],
[972,`${ccfblp}5.${emc}`,73,[[[],[9,[1,23]]]]],
[973,`${ccfblp}5.${tmc}`,89,[[[],[9,[1,25]]]]],
[974,`${ccfbdp}1.${ef}.${ehn}`,72,[[[],[35,[0,908]]]]],
[975,`${ccfbdp}1.${ef}.${load}`,81,[[[],[36,[0,908],[0,906],[1,28]]]]],
[976,`${ccfbdp}1.${qig}`,75,[[[],[37,[0,907],[0,974]]]]],
[977,`${ccfbdp}1.net.${load}`,81,[[[],[38,[0,906],[0,910]]]]],
[978,`${ccfbdp}1.${sc}`,83,[[[],[39,[0,908]]]]],
[979,`${ccfbdp}1.${sc}.${wf}`,106,[[[],[40,[0,978],[0,1085]]]]],
[980,`${ccfbdp}1.${sa}`,84,[[[],[41,[0,906],[0,908],[0,904]]]]],
[981,`${ccfbdp}1.${sa}.${wf}`,106,[[[],[42,[0,980],[0,1069]]]]],
[982,`${ccfbdp}1.volume`,90,[[[],[43,[0,906],[0,904]]]]],
[983,`${ccfbdp}1.${ef}.waterLoad`,81,[[[],[44,[0,975],[0,907]]]]],
[984,`${ccfbdp}2.${ef}.${ehn}`,72,[[[],[35,[0,915]]]]],
[985,`${ccfbdp}2.${ef}.${load}`,81,[[[],[36,[0,915],[0,913],[1,28]]]]],
[986,`${ccfbdp}2.${qig}`,75,[[[],[37,[0,914],[0,984]]]]],
[987,`${ccfbdp}2.net.${load}`,81,[[[],[38,[0,913],[0,917]]]]],
[988,`${ccfbdp}2.${sc}`,83,[[[],[39,[0,915]]]]],
[989,`${ccfbdp}2.${sc}.${wf}`,106,[[[],[40,[0,988],[0,1085]]]]],
[990,`${ccfbdp}2.${sa}`,84,[[[],[41,[0,913],[0,915],[0,911]]]]],
[991,`${ccfbdp}2.${sa}.${wf}`,106,[[[],[42,[0,990],[0,1069]]]]],
[992,`${ccfbdp}2.volume`,90,[[[],[43,[0,913],[0,911]]]]],
[993,`${ccfbdp}2.${ef}.waterLoad`,81,[[[],[44,[0,985],[0,914]]]]],
[994,`${ccfbdp}3.${ef}.${ehn}`,72,[[[],[35,[0,922]]]]],
[995,`${ccfbdp}3.${ef}.${load}`,81,[[[],[36,[0,922],[0,920],[1,28]]]]],
[996,`${ccfbdp}3.${qig}`,75,[[[],[37,[0,921],[0,994]]]]],
[997,`${ccfbdp}3.net.${load}`,81,[[[],[38,[0,920],[0,924]]]]],
[998,`${ccfbdp}3.${sc}`,83,[[[],[39,[0,922]]]]],
[999,`${ccfbdp}3.${sc}.${wf}`,106,[[[],[40,[0,998],[0,1085]]]]],
[1000,`${ccfbdp}3.${sa}`,84,[[[],[41,[0,920],[0,922],[0,918]]]]],
[1001,`${ccfbdp}3.${sa}.${wf}`,106,[[[],[42,[0,1000],[0,1069]]]]],
[1002,`${ccfbdp}3.volume`,90,[[[],[43,[0,920],[0,918]]]]],
[1003,`${ccfbdp}3.${ef}.waterLoad`,81,[[[],[44,[0,995],[0,921]]]]],
[1004,`${ccfbdp}4.${ef}.${ehn}`,72,[[[],[35,[0,929]]]]],
[1005,`${ccfbdp}4.${ef}.${load}`,81,[[[],[36,[0,929],[0,927],[1,28]]]]],
[1006,`${ccfbdp}4.${qig}`,75,[[[],[37,[0,928],[0,1004]]]]],
[1007,`${ccfbdp}4.net.${load}`,81,[[[],[38,[0,927],[0,931]]]]],
[1008,`${ccfbdp}4.${sc}`,83,[[[],[39,[0,929]]]]],
[1009,`${ccfbdp}4.${sc}.${wf}`,106,[[[],[40,[0,1008],[0,1085]]]]],
[1010,`${ccfbdp}4.${sa}`,84,[[[],[41,[0,927],[0,929],[0,925]]]]],
[1011,`${ccfbdp}4.${sa}.${wf}`,106,[[[],[42,[0,1010],[0,1069]]]]],
[1012,`${ccfbdp}4.volume`,90,[[[],[43,[0,927],[0,925]]]]],
[1013,`${ccfbdp}4.${ef}.waterLoad`,81,[[[],[44,[0,1005],[0,928]]]]],
[1014,`${ccfbdp}5.${ef}.${ehn}`,72,[[[],[35,[0,936]]]]],
[1015,`${ccfbdp}5.${ef}.${load}`,81,[[[],[36,[0,936],[0,934],[1,28]]]]],
[1016,`${ccfbdp}5.${qig}`,75,[[[],[37,[0,935],[0,1014]]]]],
[1017,`${ccfbdp}5.net.${load}`,81,[[[],[38,[0,934],[0,938]]]]],
[1018,`${ccfbdp}5.${sc}`,83,[[[],[39,[0,936]]]]],
[1019,`${ccfbdp}5.${sc}.${wf}`,106,[[[],[40,[0,1018],[0,1085]]]]],
[1020,`${ccfbdp}5.${sa}`,84,[[[],[41,[0,934],[0,936],[0,932]]]]],
[1021,`${ccfbdp}5.${sa}.${wf}`,106,[[[],[42,[0,1020],[0,1069]]]]],
[1022,`${ccfbdp}5.volume`,90,[[[],[43,[0,934],[0,932]]]]],
[1023,`${ccfbdp}5.${ef}.waterLoad`,81,[[[],[44,[0,1015],[0,935]]]]],
[1024,`${ccfblp}1.${ef}.${ehn}`,72,[[[],[35,[0,943]]]]],
[1025,`${ccfblp}1.${ef}.${load}`,81,[[[],[36,[0,943],[0,941],[1,38]]]]],
[1026,`${ccfblp}1.${qig}`,75,[[[],[37,[0,942],[0,1024]]]]],
[1027,`${ccfblp}1.net.${load}`,81,[[[],[38,[0,941],[0,945]]]]],
[1028,`${ccfblp}1.${sc}`,83,[[[],[39,[0,943]]]]],
[1029,`${ccfblp}1.${sc}.${wf}`,106,[[[],[40,[0,1028],[0,1105]]]]],
[1030,`${ccfblp}1.${sa}`,84,[[[],[41,[0,941],[0,943],[0,939]]]]],
[1031,`${ccfblp}1.${sa}.${wf}`,106,[[[],[42,[0,1030],[0,1089]]]]],
[1032,`${ccfblp}1.volume`,90,[[[],[43,[0,941],[0,939]]]]],
[1033,`${ccfblp}2.${ef}.${ehn}`,72,[[[],[35,[0,950]]]]],
[1034,`${ccfblp}2.${ef}.${load}`,81,[[[],[36,[0,950],[0,948],[1,38]]]]],
[1035,`${ccfblp}2.${qig}`,75,[[[],[37,[0,949],[0,1033]]]]],
[1036,`${ccfblp}2.net.${load}`,81,[[[],[38,[0,948],[0,952]]]]],
[1037,`${ccfblp}2.${sc}`,83,[[[],[39,[0,950]]]]],
[1038,`${ccfblp}2.${sc}.${wf}`,106,[[[],[40,[0,1037],[0,1105]]]]],
[1039,`${ccfblp}2.${sa}`,84,[[[],[41,[0,948],[0,950],[0,946]]]]],
[1040,`${ccfblp}2.${sa}.${wf}`,106,[[[],[42,[0,1039],[0,1089]]]]],
[1041,`${ccfblp}2.volume`,90,[[[],[43,[0,948],[0,946]]]]],
[1042,`${ccfblp}3.${ef}.${ehn}`,72,[[[],[35,[0,957]]]]],
[1043,`${ccfblp}3.${ef}.${load}`,81,[[[],[36,[0,957],[0,955],[1,38]]]]],
[1044,`${ccfblp}3.${qig}`,75,[[[],[37,[0,956],[0,1042]]]]],
[1045,`${ccfblp}3.net.${load}`,81,[[[],[38,[0,955],[0,959]]]]],
[1046,`${ccfblp}3.${sc}`,83,[[[],[39,[0,957]]]]],
[1047,`${ccfblp}3.${sc}.${wf}`,106,[[[],[40,[0,1046],[0,1105]]]]],
[1048,`${ccfblp}3.${sa}`,84,[[[],[41,[0,955],[0,957],[0,953]]]]],
[1049,`${ccfblp}3.${sa}.${wf}`,106,[[[],[42,[0,1048],[0,1089]]]]],
[1050,`${ccfblp}3.volume`,90,[[[],[43,[0,955],[0,953]]]]],
[1051,`${ccfblp}4.${ef}.${ehn}`,72,[[[],[35,[0,964]]]]],
[1052,`${ccfblp}4.${ef}.${load}`,81,[[[],[36,[0,964],[0,962],[1,38]]]]],
[1053,`${ccfblp}4.${qig}`,75,[[[],[37,[0,963],[0,1051]]]]],
[1054,`${ccfblp}4.net.${load}`,81,[[[],[38,[0,962],[0,966]]]]],
[1055,`${ccfblp}4.${sc}`,83,[[[],[39,[0,964]]]]],
[1056,`${ccfblp}4.${sc}.${wf}`,106,[[[],[40,[0,1055],[0,1105]]]]],
[1057,`${ccfblp}4.${sa}`,84,[[[],[41,[0,962],[0,964],[0,960]]]]],
[1058,`${ccfblp}4.${sa}.${wf}`,106,[[[],[42,[0,1057],[0,1089]]]]],
[1059,`${ccfblp}4.volume`,90,[[[],[43,[0,962],[0,960]]]]],
[1060,`${ccfblp}5.${ef}.${ehn}`,72,[[[],[35,[0,971]]]]],
[1061,`${ccfblp}5.${ef}.${load}`,81,[[[],[36,[0,971],[0,969],[1,38]]]]],
[1062,`${ccfblp}5.${qig}`,75,[[[],[37,[0,970],[0,1060]]]]],
[1063,`${ccfblp}5.net.${load}`,81,[[[],[38,[0,969],[0,973]]]]],
[1064,`${ccfblp}5.${sc}`,83,[[[],[39,[0,971]]]]],
[1065,`${ccfblp}5.${sc}.${wf}`,106,[[[],[40,[0,1064],[0,1105]]]]],
[1066,`${ccfblp}5.${sa}`,84,[[[],[41,[0,969],[0,971],[0,967]]]]],
[1067,`${ccfblp}5.${sa}.${wf}`,106,[[[],[42,[0,1066],[0,1089]]]]],
[1068,`${ccfblp}5.volume`,90,[[[],[43,[0,969],[0,967]]]]],
[1069,`${ccfbd}.${sa}`,84,[[[],[45,[0,980],[0,990],[0,1000],[0,1010],[0,1020]]]]],
[1070,`${ccfbd}.${sa}.${wf}`,106,[[[],[21,[0,1069],[0,1124]]]]],
[1071,`${ccfbd}.mineralDamping`,45,[[[],[46,[0,1084]]]]],
[1072,`${ccfbd}.moistureDamping`,45,[[[],[47,[0,1078],[0,1076]]]]],
[1073,`${ccfbd}.${heat}`,74,[[[],[48,[0,981],[0,991],[0,1001],[0,1011],[0,1021],[0,905],[0,912],[0,919],[0,926],[0,933]]]]],
[1074,`${ccfbd}.${load}`,81,[[[],[45,[0,906],[0,913],[0,920],[0,927],[0,934]]]]],
[1075,`${ccfbd}.${ef}.${load}`,81,[[[],[45,[0,975],[0,985],[0,995],[0,1005],[0,1015]]]]],
[1076,`${ccfbd}.extinction.${mois}`,78,[[[],[9,[1,44]]]]],
[1077,`${ccfbd}.extinction.${mois}Factor`,34,[[[],[49,[0,1075],[0,1095]]]]],
[1078,`${ccfbd}.${mois}`,78,[[[],[48,[0,981],[0,991],[0,1001],[0,1011],[0,1021],[0,907],[0,914],[0,921],[0,928],[0,935]]]]],
[1079,`${ccfbd}.volume`,65,[[[],[45,[0,982],[0,992],[0,1002],[0,1012],[0,1022]]]]],
[1080,`${ccfbd}.${qig}`,75,[[[],[48,[0,981],[0,991],[0,1001],[0,1011],[0,1021],[0,976],[0,986],[0,996],[0,1006],[0,1016]]]]],
[1081,`${ccfbd}.${rxi}`,55,[[[],[22,[0,1082],[0,1072]]]]],
[1082,`${ccfbd}.${rxi}Dry`,55,[[[],[50,[0,1121],[0,1086],[0,1073],[0,1071]]]]],
[1083,`${ccfbd}.${savr}`,85,[[[],[48,[0,981],[0,991],[0,1001],[0,1011],[0,1021],[0,908],[0,915],[0,922],[0,929],[0,936]]]]],
[1084,`${ccfbd}.${emc}`,73,[[[],[48,[0,981],[0,991],[0,1001],[0,1011],[0,1021],[0,909],[0,916],[0,923],[0,930],[0,937]]]]],
[1085,`${ccfbd}.${sc}.${wf}`,106,[[[],[51,[0,980],[0,978],[0,990],[0,988],[0,1000],[0,998],[0,1010],[0,1008],[0,1020],[0,1018]]]]],
[1086,`${ccfbd}.net.${load}`,81,[[[],[48,[0,979],[0,989],[0,999],[0,1009],[0,1019],[0,977],[0,987],[0,997],[0,1007],[0,1017]]]]],
[1087,`${ccfbd}.${ef}.waterLoad`,81,[[[],[45,[0,983],[0,993],[0,1003],[0,1013],[0,1023]]]]],
[1088,`${ccfbd}.${ef}.${mois}`,78,[[[],[21,[0,1087],[0,1075]]]]],
[1089,`${ccfbl}.${sa}`,84,[[[],[45,[0,1030],[0,1039],[0,1048],[0,1057],[0,1066]]]]],
[1090,`${ccfbl}.${sa}.${wf}`,106,[[[],[21,[0,1089],[0,1124]]]]],
[1091,`${ccfbl}.mineralDamping`,45,[[[],[46,[0,1104]]]]],
[1092,`${ccfbl}.moistureDamping`,45,[[[],[47,[0,1098],[0,1096]]]]],
[1093,`${ccfbl}.${heat}`,74,[[[],[48,[0,1031],[0,1040],[0,1049],[0,1058],[0,1067],[0,940],[0,947],[0,954],[0,961],[0,968]]]]],
[1094,`${ccfbl}.${load}`,81,[[[],[45,[0,941],[0,948],[0,955],[0,962],[0,969]]]]],
[1095,`${ccfbl}.${ef}.${load}`,81,[[[],[45,[0,1025],[0,1034],[0,1043],[0,1052],[0,1061]]]]],
[1096,`${ccfbl}.extinction.${mois}`,78,[[[],[52,[0,1097],[0,1088],[0,1076]]]]],
[1097,`${ccfbl}.extinction.${mois}Factor`,34,[[[],[49,[0,1075],[0,1095]]]]],
[1098,`${ccfbl}.${mois}`,78,[[[],[48,[0,1031],[0,1040],[0,1049],[0,1058],[0,1067],[0,942],[0,949],[0,956],[0,963],[0,970]]]]],
[1099,`${ccfbl}.volume`,65,[[[],[45,[0,1032],[0,1041],[0,1050],[0,1059],[0,1068]]]]],
[1100,`${ccfbl}.${qig}`,75,[[[],[48,[0,1031],[0,1040],[0,1049],[0,1058],[0,1067],[0,1026],[0,1035],[0,1044],[0,1053],[0,1062]]]]],
[1101,`${ccfbl}.${rxi}`,55,[[[],[22,[0,1102],[0,1092]]]]],
[1102,`${ccfbl}.${rxi}Dry`,55,[[[],[50,[0,1121],[0,1106],[0,1093],[0,1091]]]]],
[1103,`${ccfbl}.${savr}`,85,[[[],[48,[0,1031],[0,1040],[0,1049],[0,1058],[0,1067],[0,943],[0,950],[0,957],[0,964],[0,971]]]]],
[1104,`${ccfbl}.${emc}`,73,[[[],[48,[0,1031],[0,1040],[0,1049],[0,1058],[0,1067],[0,944],[0,951],[0,958],[0,965],[0,972]]]]],
[1105,`${ccfbl}.${sc}.${wf}`,106,[[[],[51,[0,1030],[0,1028],[0,1039],[0,1037],[0,1048],[0,1046],[0,1057],[0,1055],[0,1066],[0,1064]]]]],
[1106,`${ccfbl}.net.${load}`,81,[[[],[48,[0,1029],[0,1038],[0,1047],[0,1056],[0,1065],[0,1027],[0,1036],[0,1045],[0,1054],[0,1063]]]]],
[1107,`${ccfb}.depth`,65,[[[],[9,[1,8]]]]],
[1108,`${ccfb}.bulkDensity`,64,[[[],[21,[0,1112],[0,1107]]]]],
[1109,`${ccfb}.${qig}`,66,[[[],[48,[0,1070],[0,1090],[0,1080],[0,1100]]]]],
[1110,`${ccfb}.heatSink`,76,[[[],[53,[0,1109],[0,1108]]]]],
[1111,`${ccfb}.noWindNoSlope.${ros}`,61,[[[],[54,[0,1118],[0,1117],[0,1110]]]]],
[1112,`${ccfb}.${load}`,81,[[[],[45,[0,1074],[0,1094]]]]],
[1113,`${ccfb}.open.${waf}`,108,[[[],[55,[0,1107]]]]],
[1114,`${ccfb}.packingRatio`,67,[[[],[56,[0,1079],[0,1099],[0,1107]]]]],
[1115,`${ccfb}.packingRatio.optimum`,67,[[[],[57,[0,1122]]]]],
[1116,`${ccfb}.packingRatio.ratio`,67,[[[],[21,[0,1114],[0,1115]]]]],
[1117,`${ccfb}.propagatingFluxRatio`,54,[[[],[58,[0,1122],[0,1114]]]]],
[1118,`${ccfb}.${rxi}`,55,[[[],[45,[0,1081],[0,1101]]]]],
[1119,`${ccfb}.reactionVelocityExponent`,34,[[[],[59,[0,1122]]]]],
[1120,`${ccfb}.reactionVelocityMaximum`,56,[[[],[60,[0,1123]]]]],
[1121,`${ccfb}.reactionVelocityOptimum`,56,[[[],[61,[0,1116],[0,1120],[0,1119]]]]],
[1122,`${ccfb}.${savr}`,85,[[[],[48,[0,1070],[0,1090],[0,1083],[0,1103]]]]],
[1123,`${ccfb}.savr15`,34,[[[],[62,[0,1122]]]]],
[1124,`${ccfb}.${sa}`,84,[[[],[45,[0,1069],[0,1089]]]]],
[1125,`${ccff}.maximumDirection.slope.${ros}`,61,[[[],[63,[0,1174],[0,1138]]]]],
[1126,`${ccff}.maximumDirection.wind.${ros}`,61,[[[],[64,[0,1174],[0,1161]]]]],
[1127,`${ccff}.wind.heading.fromUpslope`,37,[[[],[9,[1,13]]]]],
[1128,`${ccff}.maximumDirection.xComponent`,34,[[[],[65,[0,1126],[0,1125],[0,1127]]]]],
[1129,`${ccff}.maximumDirection.yComponent`,34,[[[],[66,[0,1126],[0,1127]]]]],
[1130,`${ccff}.maximumDirection.${ros}`,61,[[[],[67,[0,1128],[0,1129]]]]],
[1131,`${ccff}.limit.${ews}.exceeded`,31,[[[],[68,[0,1142],[0,1133]]]]],
[1132,`${ccff}.limit.${ros}.exceeded`,32,[[[],[68,[0,1144],[0,1150]]]]],
[1133,`${ccff}.limit.${ews}`,107,[[[],[69,[0,1171]]]]],
[1134,`${ccff}.limit.windSlopeSpreadRateCoefficient`,34,[[[],[70,[0,1133],[0,1156],[0,1159]]]]],
[1135,`${ccff}.limit.${ros}`,61,[[[],[71,[0,1174],[0,1134]]]]],
[1136,`${ccff}.slope.ratio`,100,[[[],[9,[1,13]]]]],
[1137,`${ccff}.slope.k`,34,[[[],[72,[0,1114]]]]],
[1138,`${ccff}.slope.phi`,34,[[[],[73,[0,1136],[0,1137]]]]],
[1139,`${ccff}.spread.step1.${ews}`,107,[[[],[74,[0,1140],[0,1156],[0,1160]]]]],
[1140,`${ccff}.spread.step1.${phiew}`,34,[[[],[75,[0,1161],[0,1138]]]]],
[1141,`${ccff}.spread.step1.${ros}`,61,[[[],[71,[0,1174],[0,1140]]]]],
[1142,`${ccff}.spread.step2.${ews}`,107,[[[],[74,[0,1143],[0,1156],[0,1160]]]]],
[1143,`${ccff}.spread.step2.${phiew}`,34,[[[],[76,[0,1174],[0,1144]]]]],
[1144,`${ccff}.spread.step2.${ros}`,61,[[[],[77,[0,1174],[0,1130]]]]],
[1145,`${ccff}.spread.step3a.${ews}`,107,[[[],[78,[0,1142],[0,1133]]]]],
[1146,`${ccff}.spread.step3a.${phiew}`,34,[[[],[78,[0,1143],[0,1134]]]]],
[1147,`${ccff}.spread.step3a.${ros}`,61,[[[],[78,[0,1144],[0,1135]]]]],
[1148,`${ccff}.spread.step3b.${ews}`,107,[[[],[74,[0,1149],[0,1156],[0,1160]]]]],
[1149,`${ccff}.spread.step3b.${phiew}`,34,[[[],[76,[0,1174],[0,1150]]]]],
[1150,`${ccff}.spread.step3b.${ros}`,61,[[[],[79,[0,1144],[0,1142]]]]],
[1151,`${ccff}.spread.step4.${ews}`,107,[[[],[74,[0,1152],[0,1156],[0,1160]]]]],
[1152,`${ccff}.spread.step4.${phiew}`,34,[[[],[76,[0,1174],[0,1153]]]]],
[1153,`${ccff}.spread.step4.${ros}`,61,[[[],[79,[0,1147],[0,1145]]]]],
[1154,`${ccff}.${waf}`,108,[[[],[9,[1,43]]]]],
[1155,`${ccff}.wind.speed.atMidflame`,107,[[[25,16],[25,[0,107]]],[[],[33,[0,106],[0,1154]]]]],
[1156,`${ccff}.wind.factor.b`,34,[[[],[81,[0,1122]]]]],
[1157,`${ccff}.wind.factor.c`,34,[[[],[82,[0,1122]]]]],
[1158,`${ccff}.wind.factor.e`,34,[[[],[83,[0,1122]]]]],
[1159,`${ccff}.wind.factor.k`,34,[[[],[84,[0,1116],[0,1158],[0,1157]]]]],
[1160,`${ccff}.wind.factor.i`,34,[[[],[85,[0,1116],[0,1158],[0,1157]]]]],
[1161,`${ccff}.wind.phi`,34,[[[],[86,[0,1155],[0,1156],[0,1159]]]]],
[1162,`${ccff}.${ews}`,107,[[[28,46],[25,[0,1151]]],[[],[25,[0,1148]]]]],
[1163,`${ccff}.${fli}`,47,[[[],[87,[0,1173],[0,1171],[0,1165]]]]],
[1164,`${ccff}.${fl}`,49,[[[],[17,[0,1163]]]]],
[1165,`${ccff}.${taur}`,57,[[[],[88,[0,1122]]]]],
[1166,`${ccff}.heading.fromUpslope`,37,[[[],[89,[0,1128],[0,1129],[0,1130]]]]],
[1167,`${ccff}.heading.fromNorth`,37,[[[],[19,[0,96],[0,1166]]]]],
[1168,`${ccff}.${hpua}`,50,[[[],[90,[0,1171],[0,1165]]]]],
[1169,`${ccff}.${lwr}`,51,[[[],[20,[0,1162]]]]],
[1170,`${ccff}.${phiew}`,34,[[[28,46],[25,[0,1152]]],[[],[25,[0,1149]]]]],
[1171,`${ccff}.${rxi}`,55,[[[],[25,[0,1118]]]]],
[1172,`${ccff}.${sh}`,58,[[[],[91,[0,1163],[0,1155],[0,99]]]]],
[1173,`${ccff}.${ros}`,61,[[[28,46],[25,[0,1153]]],[[],[25,[0,1150]]]]],
[1174,`${ccff}.noWindNoSlope.${ros}`,61,[[[],[25,[0,1111]]]]],
[1175,`${cfa}.size.area`,44,[[[],[190,[0,1176],[0,1183]]]]],
[1176,`${cfa}.size.length`,60,[[[],[161,[0,1184],[0,75]]]]],
[1177,`${cfa}.size.perimeter`,60,[[[],[191,[0,1176],[0,1183]]]]],
[1178,`${cfa}.size.width`,60,[[[],[21,[0,1176],[0,1183]]]]],
[1179,`${cfa}.map.area`,93,[[[],[163,[0,1175],[0,79]]]]],
[1180,`${cfa}.map.length`,95,[[[],[21,[0,1176],[0,79]]]]],
[1181,`${cfa}.map.perimeter`,95,[[[],[21,[0,1177],[0,79]]]]],
[1182,`${cfa}.map.width`,95,[[[],[21,[0,1178],[0,79]]]]],
[1183,`${cfa}.${lwr}`,51,[[[],[192,[0,106]]]]],
[1184,`${cfa}.${ros}`,61,[[[],[193,[0,1173]]]]],
[1185,`${cfa}.${fli}`,47,[[[],[194,[0,1187],[0,1184]]]]],
[1186,`${cfa}.${fl}`,49,[[[],[195,[0,1185]]]]],
[1187,`${cfa}.${hpua}`,50,[[[],[196,[0,46],[0,1223]]]]],
[1188,`${cfa}.powerOfTheFire`,52,[[[],[197,[0,1185]]]]],
[1189,`${cfa}.powerOfTheWind`,52,[[[],[198,[0,106],[0,1184]]]]],
[1190,`${cfa}.powerRatio`,53,[[[],[21,[0,1188],[0,1189]]]]],
[1191,`${cfa}.isPlumeDominated`,29,[[[],[199,[0,1190]]]]],
[1192,`${cfa}.isWindDriven`,29,[[[],[200,[0,1190]]]]],
[1193,`${cff}.size.area`,44,[[[],[190,[0,1194],[0,1183]]]]],
[1194,`${cff}.size.length`,60,[[[],[161,[0,1203],[0,75]]]]],
[1195,`${cff}.size.perimeter`,60,[[[],[191,[0,1194],[0,1183]]]]],
[1196,`${cff}.size.width`,60,[[[],[21,[0,1194],[0,1183]]]]],
[1197,`${cff}.map.area`,93,[[[],[163,[0,1193],[0,79]]]]],
[1198,`${cff}.map.length`,95,[[[],[21,[0,1194],[0,79]]]]],
[1199,`${cff}.map.perimeter`,95,[[[],[21,[0,1195],[0,79]]]]],
[1200,`${cff}.map.width`,95,[[[],[21,[0,1196],[0,79]]]]],
[1201,`${cff}.rSa`,61,[[[],[201,[0,1219],[0,316],[0,359],[0,361],[0,364],[0,343]]]]],
[1202,`${cff}.crownFractionBurned`,40,[[[],[202,[0,378],[0,1208],[0,1201]]]]],
[1203,`${cff}.${ros}`,61,[[[],[203,[0,378],[0,1184],[0,1202]]]]],
[1204,`${cff}.${fli}`,47,[[[],[204,[0,1203],[0,1202],[0,46],[0,1223]]]]],
[1205,`${cff}.${fl}`,47,[[[],[195,[0,1204]]]]],
[1206,`${cfi}.${fli}`,47,[[[],[205,[0,48],[0,41]]]]],
[1207,`${cfi}.${fl}`,49,[[[],[17,[0,1206]]]]],
[1208,`${cfi}.${ros}`,61,[[[],[206,[0,1206],[0,1223]]]]],
[1209,`${cfi}.rPrime`,61,[[[],[207,[0,47]]]]],
[1210,`${cfi}.transitionRatio`,42,[[[],[208,[0,1221],[0,1206]]]]],
[1211,`${cfi}.canTransition`,29,[[[],[209,[0,1210]]]]],
[1212,`${cfi}.activeRatio`,39,[[[],[210,[0,1184],[0,1209]]]]],
[1213,`${cfi}.type`,20,[[[],[211,[0,1210],[0,1212]]]]],
[1214,`${cfi}.isActiveCrownFire`,29,[[[],[212,[0,1210],[0,1212]]]]],
[1215,`${cfi}.isCrownFire`,29,[[[],[213,[0,1210],[0,1212]]]]],
[1216,`${cfi}.isPassiveCrownFire`,29,[[[],[214,[0,1210],[0,1212]]]]],
[1217,`${cfi}.isConditionalCrownFire`,29,[[[],[215,[0,1210],[0,1212]]]]],
[1218,`${cfi}.isSurfaceFire`,29,[[[],[216,[0,1210],[0,1212]]]]],
[1219,`${cfi}.oActive`,107,[[[],[217,[0,47],[0,1171],[0,1110],[0,1138]]]]],
[1220,`${cfi}.crowningIndex`,34,[[[],[218,[0,1219]]]]],
[1221,`crown.fire.surface.${fli}`,47,[[[10,58],[25,[0,784]]],[[],[25,[0,66]]]]],
[1222,`crown.fire.surface.${fl}`,49,[[[10,58],[25,[0,785]]],[[],[25,[0,67]]]]],
[1223,`crown.fire.surface.${hpua}`,50,[[[10,58],[25,[0,786]]],[[],[25,[0,70]]]]],
]
}
